### ISSUE TITLE
AdAway freezes on startup

### ISSUE THREAD

**Issue by B1naryKill3r** [AdAway/AdAway#1000]
Just installed latest AdAway app (from F-Droid)...
It stays on this screen forever:
![screenshot_20180227-121629](https://user-images.githubusercontent.com/31217117/36725954-502a8d08-1bb8-11e8-9104-50f3aa2a9009.png)

My Device: HTC Desire 820
OS: Stock Marshmallow
Root: Yes, via Magisk (v16)

**Comment by Sygmei** [comment]
How did you fixed it ? Same problem

**Comment by B1naryKill3r** [comment]
I've installed modified version by this guy:
https://github.com/pec0ra/AdAway/releases

And it worked, after two restarts... But it worked 👌

**Comment by Sygmei** [comment]
Ahah I did exactly the same thing without seeing this message, and it worked after the second restart too
