### ISSUE TITLE
Aapt2 build crash - :AdAway:processDebugResources FAILED

### ISSUE THREAD

**Issue by Joshndroid** [AdAway/AdAway#1003]
Since the recent update in gradle i have been seeing the above process crash on building.

current potential solution at the present as listed in the Google docs (https://developer.android.com/studio/build/gradle-plugin-3-0-0.html) is to disable it using the string

`android.enableAapt2=false`

within the gradle.properties file (this line also needs to be removed from the .gitignore)

unless you have a solution/fix/update not yet currently pushed to the master tree.

#1004

**Comment by PerfectSlayer** [comment]
Thanks! It is now fixed with you PR.
I guess it will help F-Droid to build the app! 😉

**Comment by ale5000-git** [comment]
@PerfectSlayer: F-Droid won't even try until there is a git tag (it won't look for milestones).

**Comment by PerfectSlayer** [comment]
@ale5000-git I know. But there is always [post about regression on XDA](https://forum.xda-developers.com/showpost.php?p=75824930&postcount=10656).
As I want a stable version on F-Droid, the build is delayed.

**Comment by ale5000-git** [comment]
Thanks for the reply, I wasn't following the thread on XDA so I didn't know before.
