### ISSUE TITLE
Adaway can't grant root access

### ISSUE THREAD

**Issue by mrvogiacu** [AdAway/AdAway#1005]
Adaway can't grant root access with magisk 16 and magisk manager 5.6.2. When I open app, it not responding and don't show any grant root permission popup

**Comment by Perflyst** [comment]
I have installed Magisk 16 and Magisk Manager 5.6.4 which works fine. So I installed Magisk Manager 5.6.2 and it works fine, too. No problems on Samsung Galaxy S6 (SM-G920F) with LineageOS 14.1-20180325-NIGHTLY (Android 7.1.2).

Which device do you have? The custom ROM and the Android version would also be important.

**Comment by mrvogiacu** [comment]
My device is HTC 10 KDDI, stock rom 7.0.
I using magisk 14, it work, but when i upgrade to version 10. It not work 😢

**Comment by mrvogiacu** [comment]
Edit: upgrade to version 16, not 10 😑

**Comment by idfxken** [comment]
Same issue, lineage OS 16 Android 8 with root addon( checked if it works) And it says it had updated the file
 But nothing changed.

**Comment by Olit2000** [comment]
Doesn't work with SuperSu either. Missing permission: android.ACCESS_SUPERUSER

**Comment by Olit2000** [comment]
@idfxken You may need to reboot the device.

**Comment by mrvogiacu** [comment]
I install same version with htc 10 au in htc u11, it still not working. But when i update to newest version, it work :D

**Comment by PerfectSlayer** [comment]
Nice! So I guess it is time to close the issue 😉
