### ISSUE TITLE
HTC 10, S-off, Android 8.0 (Magisk 16) - Unable to change hosts file 

### ISSUE THREAD

**Issue by galaktiker** [AdAway/AdAway#1006]
After flashing Android 8.0 I discovered that I now can't change host file. As well as other system files. So Adaway doesn't work. Please help

**Comment by Mhowser** [comment]
AdAway requires root permissions so it can change the hosts file located in /system, verify if you have root privileges after flashing. If not, you may have to re-flash to a rootable android version.

**Comment by PerfectSlayer** [comment]
No answer for 5 months. I close this issue.
