### ISSUE TITLE
Inserting Random Numbers? 

### ISSUE THREAD

**Issue by heresmathew** [AdAway/AdAway#1021]
Anybody have any clue why this is happening??   I'm using Samsung Galaxy S5,  rooted through CF Auto Root,  6.0.1.  

![screenshot_2018-04-27-18-47-01](https://user-images.githubusercontent.com/38799447/39389395-a61cfa8e-4a4d-11e8-9c2c-3dff71cbe3c4.png)
![screenshot_2018-04-27-19-06-06](https://user-images.githubusercontent.com/38799447/39389442-1be7e68e-4a4e-11e8-97aa-181a4de54b5e.png)

**Comment by JonnyTech** [comment]
Try with single hosts source to determine which is causing the issue

**Comment by diamondjohndroid** [comment]
open the file with no line breaks. The host will then look more believable. However, its a trick the advertisers will do to generate new unique hosts that are not being blocked.

ie these ARE possible valid advertising hosts used by the advertisers.
