### ISSUE TITLE
tcpdump does not work

### ISSUE THREAD

**Issue by 948171624** [AdAway/AdAway#1024]
When upgrading from 3.3 to 4.0.2 (40002), tcpdump stops working for the second time.
1.open adaway, grant root
2.click tcpdump. it works fine.
3.click again to close. it closes properly.
4.click agian tcpdump, nothing happened. it can't work agian.
5.force stop adaway and retry won't help.
6.back to 3.3 version is fine.

**Comment by PerfectSlayer** [comment]
Confirmed! Thanks for your report 👍 
I can reproduce the issue and my test device so I will see what I can do about it.

**Comment by PerfectSlayer** [comment]
It was fixed in the latest dev build.
Check [XDA related post](https://forum.xda-developers.com/showthread.php?t=2190753&page=1108#post76570243) for download. Thanks!
