### ISSUE TITLE
AdAway does not display systemless hosts as enabled when using Magisk

### ISSUE THREAD

**Issue by Xalaxis** [AdAway/AdAway#1029]
As per https://github.com/AdAway/AdAway/issues/876#issuecomment-296964207

AdAway does appear to use systemeless hosts with Magisk, but does not display it is doing so.  Perhaps there is some way we can address this?

**Comment by PerfectSlayer** [comment]
This behavior has been fixed in the latest development builds.
Thankso for your report!
