### ISSUE TITLE
Donations

### ISSUE THREAD

**Issue by tortugaverde98** [AdAway/AdAway#1030]
Thank you for adaway. You app has donate function but I don't use bitcoin on phone. Your F-droid page has flattr but no btc. Your adaway.org has paypal but no btc. Please put btc address on adaway readme and on F-droid.

**Comment by cyfrost** [comment]
+1

**Comment by PerfectSlayer** [comment]
Hi! 
It is very nice to you to help me 😊 
You could find BTC and Paypal link:
- on my personal website: https://blog.hardcoding.fr/
- on my XDA signature: https://forum.xda-developers.com/member.php?u=2822685

Remember to donate only if you can afford to!
Thanks all 🙏
