### ISSUE TITLE
Problem with Spotify Connect

### ISSUE THREAD

**Issue by adamnickster** [AdAway/AdAway#1031]
Hi, with last version of Spotify is problem with connecting to Speakers (Spotify Connect) when applied ads blocking.
Problem persist even when no host source is selected. and in Host file is only 127.0.0.1 IP.
Screens:
![spotify](https://user-images.githubusercontent.com/15010835/41081963-f55e5dc8-6a2c-11e8-83ca-9d1ed0f0c204.png)

**Comment by DaBozzz** [comment]
https://github.com/AdAway/AdAway/issues/1009

**Comment by DaBozzz** [comment]
#1009
