### ISSUE TITLE
Added AdAway Hosts Source, but showed not available both on Local and Online

### ISSUE THREAD

**Issue by koalox** [AdAway/AdAway#1034]
I added a Hosts Source https://hosts.nfz.moe/basic/hosts to AdAway, but after I applied this update, it is only showed Local: not available, Online: not available whatever how many times I applied. By the way, I can download this source manually, and added it to Your Lists. But, I need a automatic hosts update, can anybody resolves this question?

**Comment by PerfectSlayer** [comment]
If the server does not send the [Last-Modified](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Last-Modified) header, AdAway can't find the last update time.

**Comment by Gitoffthelawn** [comment]
I haven't tried it yet, but perhaps try [https://rawgit.com/](https://rawgit.com/)

If anyone tries it, please comment back whether or not it works for this purpose.

**Comment by patrickdrd** [comment]
I tried rawgit links on hostsman (windows) and it didn't work

**Comment by Gitoffthelawn** [comment]
@Vankog @patrickdrd Thanks for giving rawgit.com it a try.  It looks like it doesn't return a Last-Modified header either. :(

**Comment by PerfectSlayer** [comment]
I though about a workaround here: https://github.com/AdAway/AdAway/issues/700#issuecomment-422264994
So I guess they could!
