### ISSUE TITLE
Self imported hosts to source, not showing in built apk 'hosts sources'

### ISSUE THREAD

**Issue by Joshndroid** [AdAway/AdAway#1040]
I'm curious as to what needs to be added to import a host directly into the source?

I see that within - app/src/main/java/org/adaway/db/AppDatabase.java
```
        // https://hosts-file.net
        HostsSource source1 = new HostsSource();
        source1.setUrl("https://hosts-file.net/ad_servers.txt");
        source1.setEnabled(true);
hostsSourceDao.insert(source1);
```

and within - app/src/main/java/org/adaway/provider/AdAwayDatabase.java
```
         // AdAway's own mobile hosts
         insertHostsSource(insertStmt, "https://adaway.org/hosts.txt");
```

Adding fresh sources and lines within these and compiling after a clean in studio is not listing the new source within 'hosts sources.' A grep of key words such as 'adaway.org' and 'source' are not listing anything of value apart from those above. Is there a counter as to house the number of 'sources' there are such that by adding another host into the source i need to change a value from '3' to '4' ? Else what am i missing here? I might be an edge case but I build my own apk's to firstly assist in understanding of the process and to assist in pushing back where errors arise (as i have done in the past). Cheers.

**Comment by PerfectSlayer** [comment]
Hi @Joshndroid 

I understand you try to add a hosts source.
Could you confirm you try to add it when the user first install the application?

Because the code you quote only executed at the database creation. So If a database already exists, the hosts source wont be added.

For curiosity: what is the purpose of changing the default hosts inside in the build?

**Comment by PerfectSlayer** [comment]
Ok, so it should work.
Did you try it? (remember to wipe the application data before to trigger the database creation)

**Comment by Joshndroid** [comment]
Righteo... i think i can close this now... havn't really done much different but have run a clean build.... a fresh export. Force uninstall of old app, reboot and install it seems to work as expected with 4th source. clear app data and re-open the app i still see 4th source... so i can only put it down to some weirdness and probably my error. Thanks for the replies
