### ISSUE TITLE
TCPDump monitors strange DNS requests when calling some websites through chrome

### ISSUE THREAD

**Issue by towlie** [AdAway/AdAway#1056]
Device: Redmi Note 4 with stock miui 9
Adaway: 3.3

It seems to happen with any website. I tested https://www.mydealz.de/ and https://www.computerbase.de/
I had to restart chrome to reproduce this and somtetimes I had to call the website twice.

Can someone tell me what this is?
![adaway](https://user-images.githubusercontent.com/6986141/44656570-ac737a00-a9f9-11e8-828f-da2a2406367c.png)

**Comment by Vankog** [comment]
If I remember correctly, I recognized such strange host names as well on my Nvidia shield tablet on N. 
I could not find any correlation, though. Have you checked Chrome's own dns page in the net-internals?

**Comment by towlie** [comment]
I figured out that I don't need to open any website. You just have to clear chrome from cache and then open chrome.

net-internals doesn't show much:
![screenshot_2018-08-28-21-57-24-799_com android chrome](https://user-images.githubusercontent.com/6986141/44747650-f8174800-ab0d-11e8-8283-725f66b40dfb.png)

![screenshot_2018-08-28-21-57-11-227_com android chrome 1](https://user-images.githubusercontent.com/6986141/44747596-d4ec9880-ab0d-11e8-94ab-75e4d202df72.png)

**Comment by Vankog** [comment]
yeah, that's my state, too. Not sure what this could be. I was thinking about (internal) Chrome extensions. That may use such hosts.

**Comment by towlie** [comment]
I can only confirm that this is not an error on adaways side. Because my wifi router returns local/private domains for those requests. So after Chrome calls "djkwekjasijd" my Router returns "djkwekjasijd.fritz.box" because it assumes this might be the right domain. Wireshark also doesn't show resolved domains.

**Comment by jcfp** [comment]
Those dns lookups are done by chrome (and chrome-based browsers) to determine whether they are on some kind of restricted network, e.g. captive login portals. On such networks, dns requests for these obviously fake hostsnames will not return NXDOMAIN as they should but some other kind of response. Unfortunately, these crappy browser don't have a way of disabling their bullshit dns requests so they keep spamming the logs.

Don't think adaway can block these either as they are randomly generated while this app can only block exact matches (due to how the hosts file works).

**Comment by Vankog** [comment]
actually it is a bit more interesting than that:
https://unix.stackexchange.com/a/363513

It is a check if the ISP actually uses DNS hijacking (like for captive portals or for ISPs redirecting unknown hosts to a specific error website... I look at you, Telekom...) 

The browser must decide if an input in the address bar actually resolves a host or should be treated as a search term. Some ISPs use DNS hijacking to always resolve unknown hosts to the same site, so the browser needs to know if it is a valid DNS lookup result or just a redirect and decide accordingly.
