### ISSUE TITLE
Update Transifex configuration to include metadata

### ISSUE THREAD

**Issue by PerfectSlayer** [AdAway/AdAway#1057]
Hi @Vankog,

I just update the repository medata [according the F-Droid documentation](https://f-droid.org/en/docs/All_About_Descriptions_Graphics_and_Screenshots/) with this commit: 77afba21e73467ac5b997141601751b23fbe2726
Could you have a look to include these files in the Transifex configuration to get them translated? It could be nice.

Thanks!

**Comment by Vankog** [comment]
Hehe, just asked exactly this at the commit itself.
I'll have a look.

**Comment by Vankog** [comment]
What do you think about adding the changelogs?
Every file would be a new resource, which could be overkill in Transifex.

**Comment by Vankog** [comment]
I changed the source language from "en_US" to "en" to be compliant with the rest of the apps source language.

Transifex also created a directory for each locale we currently list, independently of whether there are already translations or not. It is the same behavior as with the HTML files: All untranslated phrases use English as fallback.

However, I am not sure about the locale codes. F-Droid lacks a proper documentation about what format the locale code must be. So I cannot say if, for example, "zh-rTW" should be used, like in Android, or "zh-TW" or something like that. As far as I could find out, it uses hyphenated codes, not codes with underscores ("zh_TW").

**Comment by PerfectSlayer** [comment]
About the locale codes, F-Droid seems to support some kind of hyphenated codes as they are proposed in AdAway store page: 
![image](https://user-images.githubusercontent.com/1766222/45893938-2f0b1180-bdcd-11e8-9135-4f7502cb54b2.png)

About [the F-Droid metadata documentation](https://f-droid.org/fr/docs/FAQ_-_App_Developers/#how-do-i-change-the-description-and-add-meta-information-like-screenshots), I use the only one example I could found: https://github.com/Triple-T/gradle-play-publisher#play-store-metadata

I propose we try as it is and adjust according how it behaves. What do you think about it?

**Comment by Vankog** [comment]
Agree 👍

**Comment by PerfectSlayer** [comment]
Everything looks to work fine. I'm closing the issue.
