### ISSUE TITLE
Adaway refuses to add long hostnames 

### ISSUE THREAD

**Issue by towlie** [AdAway/AdAway#1058]
Adaway 3.3

`fr-app-chat-global-xiaomi-net-1516654448.eu-central-1.elb.amazonaws.com`

I am trying to add this hostname but it returns it is in an invalid format.
I am sure it refuses to add this entry because of the length.
Because:
`fr-app-chat-global-xiaomi-net-1516654448.eu-central-1.elb`
will be accpeted.

**Comment by towlie** [comment]
It looks like adaway confuses the max label length (63 characters) with the entire hostname length (253 characters)
Source: https://en.wikipedia.org/wiki/Hostname#Restrictions_on_valid_hostnames

**Comment by towlie** [comment]
If I am not mistaken the issue is fixed by changing the value "61" in "{0,61}" from [RegexUtils.java; Line 32](https://github.com/AdAway/AdAway/blob/master/app/src/main/java/org/adaway/util/RegexUtils.java#L32)
to something like 251.

**Comment by Vankog** [comment]
Thanks for your fix suggestion. We will definitely consider this.

**Comment by PerfectSlayer** [comment]
Hi @towlie !
Thanks for the investigation 👍 
It will be fixed in the next beta release.

**Comment by PerfectSlayer** [comment]
Fixed it b1648b15375fb9d456849dee8f5974ccbcdf3aaf
