### ISSUE TITLE
Improve F-Droid listing

### ISSUE THREAD

**Issue by mueller-ma** [AdAway/AdAway#1063]
I've seen this app on F-Droid, but it lacks some screenshots there. It's pretty easy for you to add these information as you already provide metadata in your repo for F-Droid. Please have a look at [this example](https://github.com/Freeyourgadget/Gadgetbridge/tree/master/fastlane/metadata/android) or at the [F-Droid docs](https://f-droid.org/en/docs/All_About_Descriptions_Graphics_and_Screenshots/#in-the-apps-source-repository) or [fastlane docs](https://github.com/fastlane/fastlane/blob/2.28.7/supply/README.md#images-and-screenshots).

**Comment by Vankog** [comment]
F-Droid Metadata is already taken care of with (one of) the next release(s)! 
Thanks nonetheless for your suggestion.
