### ISSUE TITLE
Indonesian translation deprecated code

### ISSUE THREAD

**Issue by PerfectSlayer** [AdAway/AdAway#1065]
Hi @Vankog 

I looked at the linter report and it seems like Indonesian use a deprecated code `in` instead of `id` on Android:

![image](https://user-images.githubusercontent.com/1766222/46069723-6fc3ab80-c17c-11e8-8d60-b33be35f197c.png)

So I had to move the source code d56f3f4
Could you fix the Transifex config accordingly? Thanks!

**Comment by Vankog** [comment]
Yeah, was about to do, but was distracted in the process ^^
