### ISSUE TITLE
adaway not working, lineageos 15.1

### ISSUE THREAD

**Issue by 0lm** [AdAway/AdAway#1073]
hi there. unfortunately adaway isnt working for me. it says that it downloaded the hosts and they are active (yes i restarted phone, too), but i still get many ads. im using bromite browser. besides, my phone is encrypted, rooted and adaway has root rights via magisk. i also deactivated global captive portal mode (set it to 0 cause i had WLA exclaimation problem, so i couldnt download stuff from yalp store or google store).

so.. could of of the mentioned facts be a reason for adaway to not work? i have the feelings its the encryption. but idk.

greetings

**Comment by guest4711** [comment]
If it was solved then please close the issue...

**Comment by bushrang3r** [comment]
I'm having the same problem. I don't think this case is solved.
Has Adaway been optimized for Magisk 17.x ?

**Comment by PerfectSlayer** [comment]
Glad it works for you 😉

**Comment by bushrang3r** [comment]
Sorry, but I spoke too soon.

I'm still getting pop-up ads, full-screen and banner ads across the bottom. 

The ads are not app specific. They pop up at anytime, on the homescreen or while using apps. Occasionally my browser will just start on its own and open a bunch of random spammy websites in different tabs.
