### ISSUE TITLE
[4.0.10] Fatal exception crash. [Expected END_ARRAY but was BEGIN_OBJECT] 

### ISSUE THREAD

**Issue by DenyDarko** [AdAway/AdAway#1076]
Adding StevenBlack hosts (https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts) in list will crash AdAway immediately when checking for updates.

Logcat attached. 

[logcat_10-15-2018_10-06-03.txt](https://github.com/AdAway/AdAway/files/2477706/logcat_10-15-2018_10-06-03.txt)

**Comment by PerfectSlayer** [comment]
Hi @DenyDarko 

I fixed the issue and releases a new dev build (4.0.10 of the 15th of October).
I should fixed the issue but if you still have some troubles, feel free to re-open this issue.

Please note there is a known bug with timezone issue with GitHub date so the update date may appear in future. It will be fixed soon.

**Comment by DenyDarko** [comment]
@PerfectSlayer last build of 15 Oct confirmed to fix the problem.
