### ISSUE TITLE
Question: Is the Webserver compatible with systemless?

### ISSUE THREAD

**Issue by Vankog** [AdAway/AdAway#1079]
I am new to Magisk with my Pixel3 XL and I am still learning which root actions cause system changes, which won't and which are actually made systemless via Magisk or a module.

(I have the systemless option enabled in 4.11, 
running Android 9 with latest Magisk beta 17.3,
systemless host activated, 
root granted)

While I am quite certain that the host file is systemless I have no clue about the webserver (and maybe even other features?)

My goal is to try preserving my native OTA update...ability ;-)

(BTW: A bit off-topic, but do I still need SELinux to be permissive with Magisc systemless mode?
Haven't yet tried. Still working on setup.
EDIT. it seems SELinux is not needed to be permissive in this context )

**Comment by guest4711** [comment]
The webserver does not write any data to /system, so you should be able to use OTA as before...

On November 9, 2018 10:55:05 AM GMT+01:00, "Daniel Mönch" <notifications@github.com> wrote:
>I am new to Magisk with my Pixel3 XL and I am still learning which root
>actions cause system changes, which won't and which are actually made
>systemless via Magisk or a module.
>
>(I have the systemless option enabled in 4.11, 
>running Android 9 with latest Magisk beta 17.3,
>systemless host activated, 
>root granted)
>
>While I am quite certain that the host file is systemless I have no
>clue about the webserver (and maybe even other features?)
>
>My goal is to try preserving my native OTA update...ability ;-)
>
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/AdAway/AdAway/issues/1079

-- 
Von unterwegs gesendet. Deshalb evtl. etwas knapper und fehlerträchtiger...

**Comment by PerfectSlayer** [comment]
Agreed, the web server is just a running process which does not write anything to disk.

About SELinux, it depends. You might have trouble to run it on port 80.
Set SELinux to enforcing, enable the server and test http://localhost from you browser.
If it works, you won't need to set SELinux to permissive in order to run web server.
