### ISSUE TITLE
Whatsapp Youtube PIP

### ISSUE THREAD

**Issue by godoftech** [AdAway/AdAway#1081]
Youtube picture-in-picture mode in whatsapp doesn't work when adaway is enabled. It works fine when adaway is disabled.
I searched the hosts file and couldn't find what was causing it.

**Comment by godoftech** [comment]
How do I do that?

**Comment by Kronopt** [comment]
AdAway three dot menu -> Log DNS Requests
Activate that and see what gets blocked  when you try to use pip

**Comment by godoftech** [comment]
Nothing showed when I logged DNS requests. After many tries one or two links showed but they weren't blocked. I disabled adaway and logged DNS requests. Now, I got some links in the log.

After a long trial and error, I found out that these two links had to be added to whitelist.
**static.doubleclick.net
googleads.g.doubleclick.net**

**Comment by PerfectSlayer** [comment]
Good to see you found the solution.

Enjoy AdAway! 👍
