### ISSUE TITLE
Whitelist won't import

### ISSUE THREAD

**Issue by mr4ffe** [AdAway/AdAway#1083]
Please make the app accept whitelists! When saving whitelists from the internet as .txt files and attempting to import them to Adaway nothing happens.

**Comment by Vankog** [comment]
Could you elaborate, please?
Version, your settings, context?
Thank you!

**Comment by patrickdrd** [comment]
maybe it's a big one? it cannot import large whitelists

**Comment by PerfectSlayer** [comment]
Hi all,

Did you tried the latest dev versions? 4.0.11 and 4.0.12 include fix about list import and host parsing.
