### ISSUE TITLE
Question about DNS logger

### ISSUE THREAD

**Issue by towlie** [AdAway/AdAway#1085]
Scenario:
You have 10 entries in the DNS logger which only refreshes on a down-swipe or when you reenter the DNS log. So if one new DNS call is captured while looking at the log it will still only show 10 entries and 11 only on refresh.

My question is what happens when I press the clear button while you see 10 entries instead of 11? Will it also clear the 11th entry? Or does it only clear the 10 shown entries and will show you the 11th on next refresh?

**Comment by Vankog** [comment]
see https://github.com/AdAway/AdAway/search?q=clearLogFile&unscoped_q=clearLogFile
The log file itself gets cleared at the moment of the invocation.

**Comment by PerfectSlayer** [comment]
Agreed. It will clear the log file itself.
So you will loose the eleventh entry.

If any more question, you could close the issue 😉

**Comment by towlie** [comment]
Thanks for the answer. You might get why I asked this and what I will do now ;-)

https://github.com/AdAway/AdAway/issues/1086
