### ISSUE TITLE
f-droid build  failed for version 4.1.0

### ISSUE THREAD

**Issue by DaleBCooper** [AdAway/AdAway#1089]
The build for version 4.1.0 failed on f-droid with

"ERROR: Could not build app org.adaway: Missing subdir build/org.adaway/AdAway "

https://f-droid.org/wiki/page/org.adaway/lastbuild

**Comment by DaleBCooper** [comment]
Hi @PerfectSlayer,

I have to thank you for the quick fix and your development of this great app! I've never ran Android without it the last five years.

Regards!

**Comment by PerfectSlayer** [comment]
Any thanks appreciated! 🙇 

I hope the version 4 will finally hit the F-Droid store before the end of the year!
