### ISSUE TITLE
Block facebook?

### ISSUE THREAD

**Issue by kabo** [AdAway/AdAway#1093]
A lot of apps send data to facebook, even if you don't have a facebook account, according to a new report
https://www.privacyinternational.org/campaigns/investigating-apps-interactions-facebook-android

Would it be possible to have a block-list that blocks any communication with facebook please?

Cheers!

**Comment by JulianBerger** [comment]
Check this host list out, graph.facebook.com is on there: https://github.com/jerryn70/GoodbyeAds

**Comment by CaptainFrosty** [comment]
https://raw.githubusercontent.com/CHEF-KOCH/CKs-FilterList/master/HOSTS/Facebook.txt

**Comment by CaptainFrosty** [comment]
https://github.com/CHEF-KOCH/CKs-FilterList/blob/master/Anti-Corp/hosts/Facebook.txt

this is a full facebook breaking hosts file

**Comment by benji1000** [comment]
Hello, the repository linked by @CaptainFrosty was made unavailable by Github. So I searched for other lists updated recently and found the following ones, if that can help someone.

- From anudeepND (4000 domains): [facebook.txt](https://github.com/anudeepND/blacklist/blob/master/facebook.txt)
- From lightswitch05 (3622 domains): [facebook-extended.txt](https://github.com/lightswitch05/hosts/blob/master/facebook-extended.txt)
- From jmdugan (2037 domains): [corporations/facebook/all](https://github.com/jmdugan/blocklists/blob/master/corporations/facebook/all)

Cheers!

**Comment by taewookim** [comment]
I tried adding anudeepND and jmdugan  (404 on lightswitch05 ). Facebook app still showing ads.
