### ISSUE TITLE
[Feature Request] Option to set time-interval of updates

### ISSUE THREAD

**Issue by Tobias-B-Besemer** [AdAway/AdAway#1108]
I use the hosts files from Steven Black & hpHosts. AdAway seems to be not able to see if changes to this files happened until the files are downloaded (, again). Because changes don't happen daily, and it's just much traffic that is generated, it would be nice, if there is a option to set the time-interval an update/check happens. Maybe a text-box where the user can enter a value.

**Comment by Vankog** [comment]
Steven Black host lists are provided via Github, aren't they?
AdAway cannot check for changes if the server does not provide a last modified entry, like Github, unfortunately. 
However, it seems you are still using an old version of AdAway. Newer versions include a workaround for Github, by checking for changes via Github's API.

Currently you can only get the latest version from the development thread:
https://forum.xda-developers.com/showthread.php?t=2190753
F-Droid builds are still in preparation.

**Comment by Tobias-B-Besemer** [comment]
I'm using Steven Black's none-GitHub-Mirror because he provides at least a time-stamp...

I will check out the XDA-Version...

But hpHosts seems also to get downloaded every day... :-/

**Comment by mikhoul** [comment]
> However, it seems you are still using an old version of AdAway. Newer versions include a workaround for Github, by checking for changes via Github's API.
> 

I have the same problem here and I use the latest version **4.2.2**

![image](https://user-images.githubusercontent.com/5678673/52917439-86000e80-32b9-11e9-9a14-c9c7b3d4e033.png)


There is an option to "check each day update" but I don't know if it force to download the files ??? 

![image](https://user-images.githubusercontent.com/5678673/52917475-09216480-32ba-11e9-8562-17de8485e281.png)

But I have another problem in the pass to bypass this restriction with Steven Black Host files I was using his alternate hosting here: http://sbc.io/hosts/alternates/gambling/hosts but AdAway don't seem to no longer  allow non-https files :disappointed: 

![image](https://user-images.githubusercontent.com/5678673/52917556-ee032480-32ba-11e9-8e48-01887e86059d.png)


I've opened an issue for  this: https://github.com/AdAway/AdAway/issues/1112

**Comment by Tobias-B-Besemer** [comment]
> But hpHosts seems also to get downloaded every day... :-/

Seems to work with v4.2.2, now.

Also Steven Black's GitHub-Version seems to work...

(Screenshots follow...)

Anyway: An update (check) every week would be enough for me...

**Comment by soredake** [comment]
Any progress on this?

**Comment by soredake** [comment]
@PerfectSlayer

**Comment by PerfectSlayer** [comment]
@soredake Don't double post and quote at developer, especially twice

For GitHub hosted file, I added work-around to find the update time based on commit API.
For setting the host update delay, I just answered here: #3136
