### ISSUE TITLE
Can't install AA4.1 on LineageOS 15.1

### ISSUE THREAD

**Issue by Tobias-B-Besemer** [AdAway/AdAway#1109]
Can't install AA4.1 on LineageOS 15.1 (Android 8.1). AA3.3 worked.

![screenshot_20190216-114808_paket-installer](https://user-images.githubusercontent.com/11881073/52898819-f8ea8600-31e2-11e9-92c1-be2778613f7c.png)

**Comment by Tobias-B-Besemer** [comment]
SysLog capered after a install attempt.

[2019-02-16_12.57-AdAway.zip](https://github.com/AdAway/AdAway/files/2871874/2019-02-16_12.57-AdAway.zip)

**Comment by Tobias-B-Besemer** [comment]
Same situation with v4.2.2... :-/

**Comment by PerfectSlayer** [comment]
Hi @Tobias-B-Besemer 

Do you have any previous version installed?
If yes, which one is installed and which one are you trying to install?

Because the PackageManager complains about mismatching apk signature:

> 02-16 12:57:05.783 W/PackageManager( 3808): Package org.adaway signatures do not match the previously installed version; ignoring!

**Comment by Tobias-B-Besemer** [comment]
I have ATM v3.3 and tried to install version 4.1 & 4.2.2.

**Comment by Tobias-B-Besemer** [comment]
Upgraded now to v4.2.2 with F-Droid and it worked!

**Comment by PerfectSlayer** [comment]
It looks like a signature issue.
Glad it now works for you. 

I can close the issue :smile:
