### ISSUE TITLE
Log DNS Request doesn't work when Adaway is installed on external storage

### ISSUE THREAD

**Issue by zputnyq** [AdAway/AdAway#1114]
Hi Dev, I get a problem on Log DNS Request, it doesn't work when Adaway is installed on external storage (micro sd card). 

On logcat it says 

02-19 13:43:39.399 D/RootCommands(10579): ID: 4, Output: /system/bin/sh: <stdin>[14]: /mnt/asec/org.adaway-2/lib/arm64/libtcpdump_exec.so: can't execute: Permission denied 

Complete logcat's attached

Thanks, I really appreciate your hardwork

[logs-2019-02-19-13-44-31.zip](https://github.com/AdAway/AdAway/files/2878679/logs-2019-02-19-13-44-31.zip)

**Comment by PerfectSlayer** [comment]
Hi @zputnyq and thanks for the report!

I don't think the app could run a binary from an external storage.
Is it a regression or you always had this issue?

And I guess you will have the same issue if you try to run the web server?

**Comment by zputnyq** [comment]
I never touch that part untill v4.1.0 so I'm not really sure, it's always or a regression. 
For webserver, I don't know how to test it & I never use this too :D
Probably if it can't be fixed due to binary behaviour, it would be better if it gets a description like on auto update option.

**Comment by PerfectSlayer** [comment]
I don't think it's a regression from the app but a security improvement from Android (being blocked from running binary from external storage).

I think I could prevent the app to be installed on external storage. It should be easier than:
 
* checking where the app is installed
* disable tcpdump and webserver features
* show dialog to explain issue to the user

As the app doesn't require a lot of space, it should not be a problem to install it on the internal storage.

**Comment by zputnyq** [comment]
Ok, no problem.
Preventing installation on external storage is much better I believe.
Thanks I really appreciate it

**Comment by PerfectSlayer** [comment]
Ok. I just need to remove the following line as soon as I get back to my computer: 
https://github.com/AdAway/AdAway/blob/02f61307bd3d9b024e594691e230908872c73a8b/app/src/main/AndroidManifest.xml#L4
