### ISSUE TITLE
the "not enough space on partition" fix doesn't work

### ISSUE THREAD

**Issue by dragozo** [AdAway/AdAway#1124]
device: i9305
android version: RR-N-v5.8.5-20170928-i9305-Final
magisk version: v14.0
app version: 4.2.2 and 4.2.3 from F-Droid

I'm using F-Droid to get the app and I never had any issues until the update last month
3.3 runs fine, updates the hosts file, asks for a restart and works as intended
4.2.2 and 4.2.3 both tell me that there is not enough space on the partition but the suggested fixes don't work

Edit:
Updated to android version RR-N-v5.8.5-20190219-i9305-rodman01 running magisk 18.1 and I'm still having the same problem.
AdAway 3.3 still runs like a charm.

**Comment by jajuan60** [comment]
me ocurre el mismo problema.

como lo puedo solucionar

gracias

**Comment by Leny1996** [comment]
I have the same issue using Magisk 18.1, systemless hosts turned on.

**Comment by Dark-Cod3r** [comment]
Facing same issue. i think adaway developer should collaborate with Magisk developer and fix this issue once and for all .. :/

**Comment by jancm** [comment]
Switch to the beta channel in Magisk, update to v19+, make sure Systemless Hosts is correctly enabled in Magisk (i.e. does /data/adb/modules/hosts/system/etc/hosts exist) , and you should never see this error again.

**Comment by Leny1996** [comment]
Magisk 19 fixex issue, so this is not related to AdAway ;)

**Comment by ddgilad** [comment]
Thank you jancm! I hit the systemless host button in magisk setting and it solved the issue!

**Comment by PerfectSlayer** [comment]
Good! I'm closing the issue.
