### ISSUE TITLE
Doesn't work for live nettv

### ISSUE THREAD

**Issue by pedronz77** [AdAway/AdAway#1125]
Doesn't stop ads in live nettv

**Comment by AnXh3L0** [comment]
Hi @pedronz77,

From my limited knowledge, Live Nettv might load ads from the same domain where the content comes from, so a host-based adblocker won't work because it would block the content too instead of just the ads.

I haven't used this app so I can't help further.

**Comment by pedronz77** [comment]
Thanks for the reply, it was the hosts file in the end, I've since found others that block them 

 
 
  On Tue, 9 Jul 2019 at 9:03 pm, Anxhelo Lushka<notifications@github.com> wrote:   
Hi @pedronz77,

From my limited knowledge, Live Nettv might load ads from the same domain where the content comes from, so a host-based adblocker won't work because it would block the content too instead of just the ads.

I haven't used this app so I can't help further.

**Comment by AnXh3L0** [comment]
Oh ok then, that's good. This issue can be closed now.
