### ISSUE TITLE
ProblematicApps: Fietsknoop requires www.google-analytics.com in Whitelist

### ISSUE THREAD

**Issue by paarnoutse** [AdAway/AdAway#1129]
Suggested update for https://github.com/AdAway/AdAway/wiki/ProblematicApps info:

The 'Fietsknoop' app (nl.vv.fietsknoop) fails when www.google-analytics.com is blocked.
Can be resolved easily by adding www.google-analytics.com to your Whitelist.

**Comment by PerfectSlayer** [comment]
You could free edit the wiki if you want to 😉 
Thanks for the report.

**Comment by marcvangend** [comment]
@paarnoutse thanks for the tip, worked for me.

I'm curious: how did you find out? When I enabled DNS logging in AdAway because this app didn't work, www.google-analytics.com did not show up in the logs.

**Comment by paarnoutse** [comment]
Yes, it's always annoying to determine if an encountered app problem is caused by AdAway or not, and if it is then it's difficult to find out which URL may be the reason. This is because in AdAway DNS logging _only_ the entries are shown that were _not_ yet referred (by whatever app) before the AdAway logging was enabled. If an URL was already referred (and optionally blocked by AdAway) before the AdAway DNS logging was enabled, it will not be shown anymore in the DNS logging at the moment you re-open the app for trying to find out which URL is the reason of your problem.

For Fietsknoop I just found the problem URL by rebooting my phone, and immediately after reboot enable DNS logging in AdAway followed by starting the app. Not guaranteed that this will always show all DNS's referred via the app; the problem URL may still already be referred by another (eg. auto-started) app before the URL logging was enabled.

Would be much, much better when AdAway had an option to clear the info/IP-addresses of previously referred URLs at the moment the DNS logging is enabled, so any referred URL _after_ enabling the URL logging would be re-shown in the log. Unfortunately that's not possible (yet).

**Comment by marcvangend** [comment]
@paarnoutse thanks a lot for your detailed explanation!
