### ISSUE TITLE
Google Play Protect blocks v4.2.4 from installing

### ISSUE THREAD

**Issue by timkgh** [AdAway/AdAway#1134]
It started with this 4.2.4 version, did not have a problem before with previous versions. I checked the downloaded file md5sum and it matches what's posted in the xda forum.

If the file is fine, how do we bypass the Play Protect block without completely disabling it?

**Comment by p3yot3** [comment]
Google don't want you to block their own ads, so they block it. Just turn play protect off, it's useless anyway.

**Comment by PerfectSlayer** [comment]
It happens from time to time but it never lengths.
I don't know what part of the app does not please Play protect…
Thanks for the report anyway.

**Comment by reecuepatt-dot** [comment]
Fix thx
