### ISSUE TITLE
Root access denied

### ISSUE THREAD

**Issue by zybster** [AdAway/AdAway#1140]
Platform: Oneplus6T
Oxygen OS 9.0.12
Magisk 19
Magisk Manager 7.1.1 (203)

I tried several things, uninstalling, deleting app data, rebooting. Other apps like Titanium Backup are working just fine.

Adaway is not able to gain root access (no windows pops up asking for root access).
Adaway is the newest version from F-Droid (4.2.4)

**Comment by vatsalchandan** [comment]
facing same issue and same version

**Comment by vatsalchandan** [comment]
I found solution, magisk is culprit, downgraded to magisk 17.3 stable and it is working fine again

**Comment by Mte90** [comment]
I have the same problem but with lineage on oneplus 5t.
The systemless module for magisk is installed and enabled but it is not possible to aplly new changes.

**Comment by Dogora** [comment]
Same here. Sticking with v3.3 for now, which works fine.
Upgraded to 4.2.4, and now AdAway doesn't ask for root, but I get the Magisk popup about root is denied.

Axon 7 running Resurrection Remix (7.1.2, SDK25); Magisk 16.0 with Manager 5.8.3 (129).

**Comment by blablablup** [comment]
Here its constantly occuring that adaway suddenly not request root anymore, only.solution is to purge magisk completely and reinstall. Any way to force adaway reask for.root?its still listed as allowed in superuser settings.

**Comment by PerfectSlayer** [comment]
@blablablup It always ask for root.

The way it works is when you try to run `su` command, your root manager is handling the call and showing you some UI to accept or deny.

AdAway does not make specific call to request `su` permission, it only runs `su` command. I don't really see what I could do to fix this. Latest versions of Magisk seem to fix it. Could you all check on your device?

By the way, I change the library to use `su` command by the John Wu's one for the next major version. I don't think it will fix the issue but it is definitely more robust and maintain than the current one.

**Comment by Vstory** [comment]
facing same issue and same version

**Comment by Killfrra** [comment]
I figured out my problem. As I said, I changed the method of rooting and therefore I had several binaries in the system. RootCommands found su from kinguser and got an error "[-] Connection to ui timed out". While in $PATH the folders were placed in the correct order. Solved the problem of removing unnecessary su in the folders /system/bin and /system/xbin. Still believe, that patch need.

**Comment by grouvig** [comment]
Great job, AdAway never asked for root on my phone until release 4.3.0 came out.
Now AdAway simply works.

**Comment by dquintela** [comment]
Just a comment, whom who might came here from the same reason as I did - xiaomi with miui 11. Magisk was installed but adaway didn't trigger the root pop-up. After some seconds it got rejected. In the app settings, for magisk there is a tick to allow application pop-ups when the application doesn't have focus - it was disabled by default. I enabled it and auto startup and all started working normally again. Sorry for these 2 cents.

**Comment by PerfectSlayer** [comment]
@dquintela Thanks for sharing! I was not aware of this change from Magisk… I need to look more closely at this change.
A fix could be to request root at start in order to be granted when the app need it (like background update).

**Comment by dquintela** [comment]
> @dquintela Thanks for sharing! I was not aware of this change from Magisk… I need to look more closely at this change.
> A fix could be to request root at start in order to be granted when the app need it (like background update).

I don't know if this isn't more a MIUI issue... "In MIUI application settings, for Magisk, there is a tick to allow application..."

**Comment by pierro78** [comment]
thanks for the Magisk tip. I didn't find the "tick to allow application pop-ups when the application doesn't have focus" but I temporarily set the response from Magisk to "grant" instead of "Prompt" and it worked on my Nougat LG V20.

**Comment by newbie56** [comment]
Guys im on Miui 12, ive found a simple workaround. In magisk manager app, go to superuser tab (shield logo) , check the permission for adaway. At least it worked for me. Cheers.
