### ISSUE TITLE
WhatsApp: cannot send/receive images with default adaway blocklists

### ISSUE THREAD

**Issue by glowinthedark** [AdAway/AdAway#1165]
8AdAway with the default lists enabled is interfering with certain operations in WhatsApp while still maintaining general functionally.

Specifically, with AdAway enabled the following features work/don't work:

✔️ text messaging works (sending and receiving)

❎ sending/receiving attachments, documents, photos and videos not working.

❎ First time registration does not work (`Cannot connect to server`)

After disabling AdAway and rebooting the device full functionality is restored.

Seems to be related to this: https://github.com/StevenBlack/hosts/issues/955

So it is not directly an issue with AdAway but how about the following feature request:

#### _Filter block lists to exclude certain hosts by specific literal strings and/or regular expressions_

> *Update*

Oops, just saw that whitelisting is already implemented 🙌. So i added an entry `*whatsapp*` on the Whitelist tab, rebooted but attachments still don't work. So WhatsApp uses hosts that don't match the `*whatsapp*` pattern. **Enable whitelists** _is_ enabled in settings.

> *Update 2*
Two more patterns had to be added in order for media to start working:

* `*fbcdn*`
* `*facebook*`

**Comment by PerfectSlayer** [comment]
Thanks for the feedback! I hope it will help all WhatsApp user 😉
