### ISSUE TITLE
[Add to FAQ]  Difference between AdAway and GP adblocker appsapps

### ISSUE THREAD

**Issue by tarasyyyk** [AdAway/AdAway#1169]
Title on FAQ: What difference between AdAway app and Ad blockers from Google Play?

It's good to know how is Google Play adblockers working and will be good to write small explanation in FAQ why AdAway is better.

**Comment by PerfectSlayer** [comment]
Hello @tarasyyyk :)

First, let's start with what makes **you** think AdAwAy is better?
Then, I am surprised there is ad blocker on Google Play Store are the are forbidden.. Could you post some links?

**Comment by tarasyyyk** [comment]
Hi @PerfectSlayer .
Yeah, you right. There are browsers, not ad blockers...

**Comment by PerfectSlayer** [comment]
I think there might be some "network tools" or app to block some types of website (like gambling or pornography). They basically are ad blockers with no default rules to block ads.
I guess you can add them later after installing it =/
