### ISSUE TITLE
'::' instead '127.0.0.1' in hosts file

### ISSUE THREAD

**Issue by ropucyka** [AdAway/AdAway#1170]
Works faster, analog to '0.0.0.0'. Saving file space.
Instant feedback, not looping like '127.0.0.1'.
No need ipv6 to configure. 

Just my opinion.

**Comment by Kronopt** [comment]
Does that work for ipv4? I think that's ipv6 only.

I do agree with substituting 127.0.0.1 with 0.0.0.0. It might affect the webserver though

**Comment by ropucyka** [comment]
> Does that work for ipv4? I think that's ipv6 only.
I'm not sure. But this method works perfectly a years on Windows in this tool:
https://toolslib.net/downloads/viewdownload/175-skype-adblocker/

**Comment by PerfectSlayer** [comment]
Hello folk! 

As @Kronopt said, `::` is an IPv6. 
And about `0.0.0.0`, he/she well guessed: it won't work with web server.

About size reduction, there is other tricks (like several domains on one line).
But it is not clear what is supported on not and what side effects are.
