### ISSUE TITLE
I'm forced to disable https://adaway.org/hosts.txt to login

### ISSUE THREAD

**Issue by Sopor** [AdAway/AdAway#1171]
When i want to login to my phone provider (Telenor app) i have to disable the `https://adaway.org/hosts.txt` or else i get an error message. I have been trying to find the hostname, but so far i have failed.
Any tip on how i should find the hostname? I have tried the `Log DNS requests`, but maybe i do something wrong :(

**Comment by Kronopt** [comment]
It should show up if you log dns requests, just enabling monitoring should do it.
Try completely closing the app, try to login and then check the dns logs.

**Comment by Sopor** [comment]
Strange, but now i can login even if `hosts.txt` is enabled.
