### ISSUE TITLE
Can't check systemless host

### ISSUE THREAD

**Issue by Necrog** [AdAway/AdAway#1172]
Hello everyone,

Everytime I want to check the systemless host, either it will uncheck itself whenever I quit the app (if I reboot then), or it will not check at all, and I followed the same thing that I see everywhere since I have magisk, to install the systemless host on Magisk, but it don't work...
Also, whenever I try to get the original host, no matter if I reboot or not, it will stay with Adaway's host file
The thing is, when I was on Android O, everything worked fine but since I update to Android P, Adaway ceased to work.
If anyone could help me or at least tell me what's the problem I'll be glad to read ur responses.

Thank you.

**Comment by BlessDeix92** [comment]
I confirm that the "Enable systemless mode" checkbox is being automatically unchecked after each reboot.
I am on a Lineage OS 16 (9 / Pie) ROM.

My device will actually crash if you try to write to the /system partition after Linux has booted. This is a "special" feature from the OEM. It runs in TrustZone and is in the bootloader, so it can't be changed.

**Comment by PerfectSlayer** [comment]
The feature was updated in 4.3 version.
Please reopen the issue if the update does not fix it.
Regards
