### ISSUE TITLE
Moovit app not working

### ISSUE THREAD

**Issue by manusacco** [AdAway/AdAway#1180]
While using the tcpdump I discovered moovit needs some servers, like 4 or 5, all of the kind "*.moovit.com". Of course by whitelisting all of those with the * character moovit started working again. I read under the app that you want us to notify this kind of problem here when it happens so here I am. The Moovit app needs those server whitelisted to run properly. Without them it won't open and without some of them it will open and not show any proper result.

**Comment by PerfectSlayer** [comment]
Thanks @manusacco for the report.
I update the issue and tag it correctly.

Regards.
