### ISSUE TITLE
backup file format

### ISSUE THREAD

**Issue by xorcan** [AdAway/AdAway#1194]
I think better when app gives an option for backup file format.

adaway-backup.json or adaway-export file

example:

adaway > 
settings > 
backup file format > 
(two option here) "new type (json)" or "old type"

_OnePlus 5 cihazımdan [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github) kullanılarak iletildi._

**Comment by PerfectSlayer** [comment]
Hello @xorcan 

The old format is no more supported and won't be imported.
You can easily convert it if you want to the new format by wrapping it to some json structure.

I don't plan to support the old format as it doesn't offer all the features users need.
But I might offer a website or a script to convert it to the new version if some user struggle with json format (which I need to document in the wiki ...)

**Comment by xorcan** [comment]
@PerfectSlayer OK it would be nice :) 

_OnePlus 5 cihazımdan [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github) kullanılarak iletildi._

**Comment by PerfectSlayer** [comment]
Here it is: https://adaway.org/export
Thanks @AnXh3L0 for the website integration 😉

**Comment by RedWavve** [comment]
Thank you SO MUCH for that converter.
I wanted to clean up my black&white list, and reverting to legacy format, importing into excel, adding wildcards, using "highlight duplicates" and reverting back helped a lot.

Questions (when you got time, nothing urgent!):
- Does adding wildcards help with CPU or is it infinithesimal?
- Is some sort of "AI" planned? Like "You blacklisted 3 subdomains of this domain, add wildcard and regroup", etc?

Thank you so much, you're litterally one of the three (TB and Magisk) reasons I go through rooting every device I own for hours <3

**Comment by PerfectSlayer** [comment]
Thanks @RedWavve !

Wildcard is only available for white list domains. It is a limitation of the hosts file format itself.
White listing domains using willdcard will prevent the matching block rules to be saved in the hosts file. We can't put wildcard domain to block.

So in short, no AI plan or CPU impact ;)

But I might consider wildcard blocking rules in a future version of AdAway as it won't always use  hosts file blocking feature. But I won't promise too much until I got a stable release 😅

**Comment by vidmo91** [comment]
Website converter doesn't work. I tried Edge, Firefox, Chrome on PC and Chrome on Android. Clicking buttons does nothing.

**Comment by RedWavve** [comment]
There must have been something wrong in the way you copy/pasted.
white spotify.com
does convert without a problem

Remember:
- Always INPUT in MODERN the TOTAL FILE
- If you input in LEGACY one line, then INSERT the line in your JSON

**Comment by PerfectSlayer** [comment]
@vidmo91 I can confirm your example is working.
Could you check you refresh the page and do not have an old js in cache?
