### ISSUE TITLE
can't add disconnect hosts

### ISSUE THREAD

**Issue by xorcan** [AdAway/AdAway#1198]
https://s3.amazonaws.com/lists.disconnect.me/simple_malware.txt

adding host source not working. 

_OnePlus 5 cihazımdan [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github) kullanılarak iletildi._

**Comment by AnXh3L0** [comment]
Hi @xorcan,

I just tested that host source link and it worked on my device. The list was installed. Can you please try again or provide more information?

**Comment by xorcan** [comment]
I'll show you the issue.

**Comment by xorcan** [comment]
![Screenshot_20190714-225337__01](https://user-images.githubusercontent.com/25418042/61188613-73cca580-a68a-11e9-9479-dfc2df312223.jpg)
![Screenshot_20190714-225350__01](https://user-images.githubusercontent.com/25418042/61188614-73cca580-a68a-11e9-85db-35c1d6955d82.jpg)

**Comment by PerfectSlayer** [comment]
Hello  @xorcan 

This file is not an hosts file.
The parser does not recognized the format so it is not imported.

For example:
```
Malware list by Disconnect
# License: GPLv3
# Contact: support [at] disconnect.me

malware-check.disconnect.me
```
Should be something like "IP hostname", like:
```
Malware list by Disconnect
# License: GPLv3
# Contact: support [at] disconnect.me

127.0.0.1    malware-check.disconnect.me
```

If all is clear for you, I will let you close the issue.

**Comment by xorcan** [comment]
I understand but what can we do for this site?
personally I created a mirror of this disconnect.me-lists list. any other way you know?

**Comment by PerfectSlayer** [comment]
You will have to convert it to a host file in order to use it in AdAway (few line of bash, python or sed will do the trick). 
Then you can add it as a source file.

**Comment by xorcan** [comment]
thank you. i done a mirror. https://github.com/xorcan/disconnect.me-lists
