### ISSUE TITLE
Facebook Marketplace images being blocked

### ISSUE THREAD

**Issue by mica** [AdAway/AdAway#1212]
Images for posts on Facebook Marketplace seem to be getting blocked...

https://www.facebook.com/marketplace/

**Comment by Kronopt** [comment]
That is probably due to this, and not adaway:
https://www.independent.co.uk/life-style/gadgets-and-tech/news/facebook-down-site-app-not-working-pictures-photos-images-whatsapp-a8986426.html

**Comment by mica** [comment]
Ah, ok. That's probably it. Thanks for the info!
