### ISSUE TITLE
Does not work on Oneplus 6t

### ISSUE THREAD

**Issue by Alqaszar** [AdAway/AdAway#1214]
Problem: Adds are not blocked

1. Open AdAway version and try to activate host file
3. Get error message about no space on /system/etc/
4. Change host file location to "data/data/host"
5. AdAway shows "host active"
 
What should happen:
Adds should be blocked systemwide like before

What actually happens:
Adds are not blocked, even after several reboots

**Device**
 - AdAway version: 4.0.9-11d3f561
 - Device: Oneplus 6t
 - Android version: OPT_O2_BETA_14
 - Root version: magisk 19.3

**Additional context**
Behaviour started after system update.

**Comment by Kronopt** [comment]
Can you please specify how you're testing for systemwide adblocking?
Also, have you tried using the Systemless Hosts Magisk module?

**Comment by Alqaszar** [comment]
I'm working on it. Now, the hosts file is back at /system/etc/, but the file is empty. Obviously, Adaway can't write the file despite root access, despite saying "new hosts are ready". I'm using busybox NDK with solid explorer to acces the file system, and I can read  and delete files manually. Trying to show the hostfile from within AdAway, i get the message "Error: Failed to load host file content."

**Comment by Alqaszar** [comment]
I'm working on it. First, I put the hosts file is back at /system/etc/ via Adaway settings, but the file is empty (0 b). Obviously, Adaway can't write the file despite root access, despite saying "new hosts are ready". I'm using busybox NDK with solid explorer to acces the file system, and I can read and delete files manually. Trying to show the hostfile from within AdAway, i get the message "Error: Failed to load host file content." Then, I used the setting to place the hostfile in /data/data, and the symbolic link is created in /etc, but the system seems to ignore the hosts file. Manually copying the hosts file to system/etc was not possible, but I don't know what the issue is there -- Solid explorer claims to mount the system partition with rw.
