### ISSUE TITLE
Some menu items are missing when the system language is "Español (Uruguay)"

### ISSUE THREAD

**Issue by ajarov** [AdAway/AdAway#1220]
**Describe the bug**
Some menu items are missing when the system language is *Español (Uruguay)*. Also, tapping on menu items show the incorrect screen.

**To Reproduce**
1. Change the system language to *Español (Uruguay)*.
2. Open AdAway.
3. Open the menu.
4. Items *Home*, *Log DNS requests*, and *Scan for adware* are missing.
5. Open *Fuentes de hosts* (*Host sources*).
6. The Home screen is shown.
7. Go back and open *Tus listas* (*Your lists*).
8. The Host sources screen is shown.

**Screenshots**
Español (Uruguay):
![Spanish Uruguay](https://user-images.githubusercontent.com/1832140/64064094-e4486b00-cbd3-11e9-9875-f00b591a714d.png)

English (US):
![English US](https://user-images.githubusercontent.com/1832140/64064091-d4c92200-cbd3-11e9-9aea-e69b312f876f.png)

**Device**
 - AdAway version: 4.2.7
 - Device: Moto Z2 Force
 - Android version: 8.0 Oreo
 - Root version Magisk 19.3

**Comment by PerfectSlayer** [comment]
Hello @ajarov 
This is due to an incomplete translation. Be sure your locale is complete or improve it following #1050.
Once done, see with @Vankog to validate the PR and fix it for the next release.

Thanks for the report and enjoy improving the app!

**Comment by ajarov** [comment]
Hello @PerfectSlayer. I requested Spanish LatAm and Spanish Uruguay to be added in Transifex, but so far no news. In any case, I believe that if there is a missing string in the translation, then it should either show that string in English, or show the whole app in English. But being shown a screen that is not the one I selected is a bug.

**Comment by PerfectSlayer** [comment]
Hello @ajarov 

> if there is a missing string in the translation, then it should either show that string in English

It is handled by the Android framework. I can't control a fallback method or things like that.

> show the whole app in English

It is based on the system language and controlled by the framework.

But let's think a minute about what happened if the whole app revert back to English when a localized string is missing. As soon as I publish a new feature or an update, it will take weeks or months until translators update the locales and I publish them in an update. And moreover, this new update may also contains new string and the app will never be fully translated to users and always run in English to users 😞 

I had a look to the Mexico variant, and it's missing 32 strings. Once complete, I will have a PR to merge. Until then, I can't really fix the issue.

![image](https://user-images.githubusercontent.com/1766222/62003537-c3927e80-b118-11e9-9f2e-f30aded0ec7b.png)

**Comment by ajarov** [comment]
> But let's think a minute about what happened if the whole app revert back to English when a localized string is missing. As soon as I publish a new feature or an update, it will take weeks or months until translators update the locales and I publish them in an update. And moreover, this new update may also contains new string and the app will never be fully translated to users and always run in English to users disappointed

I understand it is not ideal. I personally think it's still better than the current situation of not being able to access some screens, and the menu items taking you to an incorrect screen. But I understand that this is a limitation of the framework and there's nothing to do.

> I had a look to the Mexico variant, and it's missing 32 strings. Once complete, I will have a PR to merge. Until then, I can't really fix the issue.

I find it odd that there exists a Mexico variant when the guidelines in issue #1050 state:
> Please refrain to request regional localizations (like sr_RS).
Then again, there's Portuguese and Portuguese Brazil, which makes sense, just as it makes sense to have Spanish Spain and Spanish Latin America.
I propose to remove the Mexico localization and either leave only Spanish (which I hope is neutral), or add a new Spanish Latin America localization, which I volunteer to translate. I already requested the language on Transifex a couple weeks ago, but so far it hasn't been accepted.

**Comment by Vankog** [comment]
Sorry for chiming in so late.
The regional languages were already part of the Transifex project when I took over.
I'm afraid I denied several requests for regional languages today. This was before I read this thread.

About the issue:
I can't really see why the menu items do not appear. 
The translation files only contain translated strings, while all non translated strings get a fallback automatically. 
The fallback strategy depends on the android version. On newer versions it behaves like:
Primary system language: Regional match? - > general language match? - > language match for other regions?
After that the cycle begins for secondary system languages. 
If nothing matches, the standard app language is used. 
(citing from memory, so it I might be wrong...) 

So at least English must be available in the end. 

There might be a bug in the language files. Sometimes translators mess up escaped characters or html encodings. This can break the whole app. 
Does this also happen in other languages and/or regions?

**Comment by PerfectSlayer** [comment]
@Vankog I guess the issue comes from the string arrays. Sometimes, they only translates few elements, not all. So the translated array is shipped, but incomplete.
When it happens on the menu drawer label array, not all entries will present be some must redirect to the wrong part of the app.

I post the list of all the translations with the string array issue here: https://forum.xda-developers.com/showthread.php?p=79846369#post79846369

**Comment by ajarov** [comment]
> The regional languages were already part of the Transifex project when I took over.
> I'm afraid I denied several requests for regional languages today. This was before I read this thread.

Does this mean that you disagree to have a Spanish Latin America variant? It's very common for multi-language software to have both Spanish Spain and Spanish Latin America, the same way they have both English US and English UK.
In any case, does it make sense to remove the Spanish Mexico variant, since it's incomplete and apparently not being maintained?
I see there's also Portuguese and Portuguese Brazil (perhaps it was so when you took over), but in that case they are both complete.

> The fallback strategy depends on the android version.

I'm using Android version 8.0.0 (Oreo).

**Comment by Vankog** [comment]
First, I really have to dig deeper for this decision to make.
Generally, it is not a big issue to add regional translations if there are good reasons and enough maintainers. We want to minimize the regional languages, though, because they are a hazzle to maintain on a technical level. 

But it won't fix our underlying problem at hand. As @PerfectSlayer pointed out it is a known issue with the string arrays in translation files. I agree, it does look like only the whole array gets translated, while untranslated parts are omitted. 
We really have to fix the string array issue in the first place.

@PerfectSlayer wouldn't it be a good general solution (or rather workaround) to remove all string arrays from the strings.xml and use single entries instead?

**Comment by PerfectSlayer** [comment]
Vankog: I just fixed the string-array issue with some place holders: 19ceaa01676cd1bbf072bf20b547bf15ac8c85e8 (I tried to restore the menu entries in english the best I could.) I hope it will motivate the translators to fix the English strings from their language file.

About not using this feature, I don't think it is a good idea. I won't bend the framework because translation platform is doing poorly. It will cause more troubles than it solves.

**Comment by Vankog** [comment]
I added the placeholders to all transifex languages as well. Thus, these changes won't be overwritten by the next pull.

I also added more context and announcements to Transifex. I hope this helps keeping the problem at bay.

**Comment by Madis0** [comment]
> I had a look to the Mexico variant, and it's missing 32 strings. Once complete, I will have a PR to merge. Until then, I can't really fix the issue.

How about importing all partially complete translations too, at least few times a year?

**Comment by Vankog** [comment]
We already do this from time to time.
If you do not see your translations, there might be a problem with the setup. 
All translated phrases are incorporated into the corresponding releases.

**Comment by PerfectSlayer** [comment]
> At least the drawer is fixed.

Ok, closing the issue. Thanks all!
