### ISSUE TITLE
play store copied app

### ISSUE THREAD

**Issue by ghost** [AdAway/AdAway#1221]
![](https://i.imgur.com/Q3e59LA.jpg)

**Comment by xorcan** [comment]
https://play.google.com/store/apps/details?id=com.spaceship.netprotect

**Comment by PerfectSlayer** [comment]
Oh f..k! At least it is not a paid app…
I will try a DMCA or a Google Play policy violation to remove it from the play store.

Whatever, thanks for the report! 👍

**Comment by xorcan** [comment]
everytime 👌

**Comment by Vankog** [comment]
just my thoughts on this:
# isn't this allowed by GNU GENERAL PUBLIC LICENSE?
# doesn't Google take care of it anyways in the long run, because of their ban on ad blockers?

**Comment by PerfectSlayer** [comment]
Hi @Vankog,

About GNU GPL, he/she should at least redistribute modifications, include original license and show from where the code comes. But I suspect license issue is not its main concern…

About ad blockers, it is against the play store rules but I found nowhere to notify the forbidden app behavior. If you found how to do it, please tell me. I also tried a DMCA but Google rejected it 😢

**Comment by Vankog** [comment]
Sorry, don't have any experience with this. I think xda is the better place to ask this question.

**Comment by Poussinou** [comment]
Hi @PerfectSlayer 

You can open a request to google [here](https://support.google.com/legal/contact/lr_dmca?product=googleplay) to remove this copy from the Store. It looks very easy.

**Comment by PerfectSlayer** [comment]
Is it me or the whole app changed?
It is still the same Play store link but the app seems different.
They are now capable of per app filter which is typically a VPN based blocker.

Does anyone tried the app recently to confirm?

P.S.: Non root VPN based blocker mode is coming in AdAway v5 but there is any chance they could make a copy of this version as this branch is not public yet :sweat_smile:
