### ISSUE TITLE
Feature Request: 0.0.0.0 or 127.0.0.1

### ISSUE THREAD

**Issue by Sadi58** [AdAway/AdAway#1228]
I would be very nice if you could also add a simple option to choose 0.0.0.0 instead of 127.0.0.1 which works equally well and results in a smaller file.

**Comment by DenyDarko** [comment]
It's already there.

Preferences -> redirection ipv4

**Comment by PerfectSlayer** [comment]
@DenyDarko is right. It is the right way 😉 
I don't think adding "a simple option" only for this worth it.

**Comment by Vankog** [comment]
I had never thought about this as a solution to this request. oO
Damn, so obvious!

**Comment by Sadi58** [comment]
Thanks for pointing this out! :-)
