### ISSUE TITLE
root not requested

### ISSUE THREAD

**Issue by JonnyTech** [AdAway/AdAway#1236]
Adaway 4.2.8 from fdroid on AOSP9 with Magisk 19.3 (manager 7.3.2) is not requesting root therefore cannot update hosts. Is this a known issue with a solution?

**Comment by PerfectSlayer** [comment]
Hi @JonnyTech 

It looks like you are not alone. See #1140 
I need to investigate this issue. Thanks for the report 👍

**Comment by JonnyTech** [comment]
Release 4.3.0 has fixed the issue. Thank you very much indeed.
