### ISSUE TITLE
Host file not recognized

### ISSUE THREAD

**Issue by coubi64** [AdAway/AdAway#1237]
Hi.

I try to use a personnalized host file from Seb Sauvage Wiki but it is not correctly recognized by Adaway.

The host file is: https://sebsauvage.net/hosts/raw

The Wiki for his dns block list: https://sebsauvage.net/wiki/doku.php?id=dns-blocklist-en

Thank you for having a look at his list and try to discover what is wrong to integrate in Adaway.

**Comment by guest4711** [comment]
The file https://sebsauvage.net/hosts/raw is not in host file format so
AdAway does not recognize it.

A host file consists of lines containig a ipp-address, a white space,
and a white space seperated lists of hostnames, e.h.

127.0.0.1 lb.usemaxserver.de
127.0.0.1 tracking.klickthru.com

while the mentioned file contains host names only;

lb.usemaxserver.de
tracking.klickthru.com

So you need to convert the file (e.g. by using a stream editor like sed)
to use it in AdAway (or look for another list format).
https://sebsauvage.net/hosts/hosts has the right format for AdAway.
