### ISSUE TITLE
Disabled

### ISSUE THREAD

**Issue by leeveng** [AdAway/AdAway#1238]
Cannot enable ad-blocking. It stays "Disabled" and on the right side of "Default hosts file installed" is an X. Need help to solve this problem. Thanks.

**Comment by DeadneM** [comment]
Adaway needs root. My guess is that you didn't accept root permissions for the app or your system isn't rooted

**Comment by leeveng** [comment]
True, my device is not rooted. Thank you for your response.
--
Mr. Vue Friday, 30 August 2019, 05:45AM -07:00 from DeadneM  notifications@github.com :
