### ISSUE TITLE
App Settings don't show up if your system language is Spanish (USA)/Español (Estados Unidos)

### ISSUE THREAD

**Issue by santimaster2000** [AdAway/AdAway#1241]
**Describe the bug**

App Settings don't show up if your system language is Spanish (USA)/Español (Estados Unidos)

**To Reproduce**

1. Change your system language to Spanish (USA)/Español (Estados Unidos)
2. Open AdAway
3. Settings are not there
4. Profit (?)

**Expected behavior**

Settings would be available for me to see/change them

**Screenshots**

Can't screenshot what's not actually there

**Device**
 - AdAway version: 4.2.8
 - Device: Razer Phone 2
 - Android version: 9.0
 - Root version: Magisk 19.3

**Comment by PerfectSlayer** [comment]
Hi @santimaster2000 
It is the same issue as #1220. Translation needs to be fixed in order to make the drawer working. See #1050 for more details.

I think I will try to make a patch to set some placeholders for missing menu items in the next version.
