### ISSUE TITLE
remount / not /system

### ISSUE THREAD

**Issue by orachas** [AdAway/AdAway#1245]
I am running Lineage on the Pixel XL (marlin).

AdAway fails on this device after advising links into data.

However, if I use root to "mount -o rw,remount /" then AdAway will work normally.

Perhaps the mounted filesystem's could be verified before attempts are made on /system?

**Comment by boggle247** [comment]
This works for me on my Pixel (sailfish) as well. As i've discussed here: https://github.com/AdAway/AdAway/issues/1226#issuecomment-527845575

**Comment by guest4711** [comment]
On Q this is a security feature - you cannot mount  /system or / r/w. Use a systemless solution like Magisk integrated systemless hosts instead (don't forget to reboot after enabling it and before calling AdAway)

**Comment by meiser79** [comment]
OK, but Android Pie not, right? I tried to remount / on a device running LineageOS 16.

**Comment by PerfectSlayer** [comment]
The issue should come from your setup.
AdAway already tries to remount all possible and related mount points.
See this post for details about the app behavior: https://github.com/AdAway/AdAway/issues/1226#issuecomment-522305734

**Comment by meiser79** [comment]
Do you own a device running LineageOS 16.0 and installed LOS su addon? If yes, is the above mentioned mount command successful on your device?

**Comment by PerfectSlayer** [comment]
I have a LineageOS 16 device but not with su addon installed (Magisk instead)
If none of the mount command works (on `/system/etc/hosts`, `/system/etc`, `/system` then `/`), AdAway can't work properly. It's a requirement for the app.

Try them from a shell and if it work from the shell and not the app, re-open or comment the issue.
