### ISSUE TITLE
Android 10: enabled but seeing ads in browser, but had no ads in Android 9

### ISSUE THREAD

**Issue by eturk1** [AdAway/AdAway#1247]
**Describe the bug**
Android 10 AdAway is enabled but still see ads in Chrome browser. Seems Google has beaten Adaway?

Was not seeing any ads in browser on Android 9

**To Reproduce**
Fresh Android 10 beta 5 install (now on full release)
install Magisk and set tap "systemless hosts" to install module
install AdAway, set enable systemless mode, enable ad-blocking (says enabled)
still see ads

**Expected behavior**
no ads

**Screenshots**
<img width="203" alt="Screenshot_20190909-134858" src="https://user-images.githubusercontent.com/525280/64635401-73b00400-d3b4-11e9-89e1-81b8a19771c4.png">

**Device**
 - AdAway version: 4.2.9
 - Device: Pixel 2 XL
 - Android version: 10
 - Root version Magisk 19.3 beta

P.S. didn't see any posts specifically about Android 10

**Comment by PerfectSlayer** [comment]
Hi @eturk1 

Thanks for your issue. Could you have a look to #1253 and more especially this comment: https://github.com/AdAway/AdAway/issues/1253#issuecomment-545435163 ?

**Comment by PerfectSlayer** [comment]
I'm closing the issue as the discussion continues on #1253.
