### ISSUE TITLE
Can't add source list starts w/ 'http'

### ISSUE THREAD

**Issue by sula7** [AdAway/AdAway#1250]
**Describe the bug**
Found some more hosts source list to block ad, but their URLs starts only w/ 'http'. So, I can't add them into the app. App accepts URLs only start w/ 'https'.

**To Reproduce**
1. Open AdAway
2. Open left-side menu
3. Open hosts source
4. Push button + in the right buttom corner
5. Copy past URL (start w/ http)
6. Button 'add' is gray colored and not clickable
7. If try to change http to https button 'add' is red colored and clickable

**Expected behavior**
Accept all http and https URLs as hosts source list

**Screenshots**
![Screenshot_20190912-103747_Chrome](https://user-images.githubusercontent.com/26718265/64754539-8d368480-d549-11e9-8328-2017cfc7a18e.png)
![Screenshot_20190912-103819_AdAway](https://user-images.githubusercontent.com/26718265/64754565-a3dcdb80-d549-11e9-86b0-10ba995b2cc5.png)
![Screenshot_20190912-103826_AdAway](https://user-images.githubusercontent.com/26718265/64754570-a8a18f80-d549-11e9-8a2d-947a29adf44f.png)

**Device**
 - AdAway v. 4.2.9
 - Device: LG G2 (D802)
 - Android version: 9 (AOSP extended)
 - Root version: Magisk 19.3

**Additional context**
Nothing to add

**Comment by tonia6970** [comment]
Me too 😒

**Comment by tonia6970** [comment]
I forgot to say that in your host list the 3th,4td,5rd & 6rd host work & if you make them as https.

**Comment by PerfectSlayer** [comment]
Hi all,

The question was already discussed in #1112 

Thanks!
