### ISSUE TITLE
domain adaway.org missing

### ISSUE THREAD

**Issue by ggzengel** [AdAway/AdAway#1261]
The domain does not exist anymore:

```
$ nslookup adaway.org 8.8.8.8
Server:		8.8.8.8
Address:	8.8.8.8#53

** server can't find adaway.org: SERVFAIL

**Comment by shoeper** [comment]
confirm

**Comment by BlohoJo** [comment]
Same here... gone for good?

**Comment by BlohoJo** [comment]
Seems to be back...

**Comment by Veldkornet** [comment]
See https://github.com/AdAway/adaway.github.io/issues/19

**Comment by PerfectSlayer** [comment]
I changed the domain from registrar last week.
It took time to update DNS settings.
All the details on the linked issue (the comment above mine).
