### ISSUE TITLE
Update stuck if big lists are used 

### ISSUE THREAD

**Issue by 35609902357** [AdAway/AdAway#1265]
In version 4 the update gets stuck and it never completes when several big lists are used (output hosts file around 30 MB). I let it run for much more than what it took with the same lists in version 3, but it stays stuck on building. On version 3 it could take minutes, but would complete all the time and predictably it used to use the same amount of time each time.

**Device**
 - AdAway version: [e.g. 4.2.9]
 - Device: [e.g. Android]
 - Android version: [7]
 - Root version [LineageOS]

**Comment by sula7** [comment]
I have the same problem with AdAway ver *4.3.1* & *4.3.2* and Android ver *9 AEX* (*AOSP Extended*). Let run AdAway for 1.5 hours, but it still hangs

**Comment by Rikj000** [comment]
Issue appears to be resolved now. 
But when using really big lists (30mb etc) it'll take my phone a good 10 minutes to build and apply the hosts file (Keeping AdAway on-screen the whole time and screen on)

Device:   
- AdAway version: v4.3.6   
- Device: OnePlus 3T   
- Android version: LineageOS v17.1 (Android 10) + MicroG   
-  Root version: Magisk v20.4
