### ISSUE TITLE
OnePlus One stuck in fastboot mode after install+reboot

### ISSUE THREAD

**Issue by janaxhell** [AdAway/AdAway#1471]
**Describe the bug**
Installed AdAway from F-Droid, launched it, updated, then rebooted as asked. The phone did not reboot into Android, but into Fastboot Mode, and I can't get out of it. Tried to reboot from CMD in Windows, but it simply returns to Fastboot. Same from TWRP. I always go back to Fastboot Mode screen.

**To Reproduce**
1. Go to F-Droid store
2. Install AdAway
3. Run it
4. Tap update
5. Tap Reboot when asked
6. Give permission to reboot

**Expected behavior**
I expected to reboot into Android.

**Screenshots**
none possible

**Device**
 - AdAway version: latest on F-Droid
 - Device: OnePlus One
 - Android version: LineageOS 16 - Android 9.0
 - Root version Magisk 20

**Additional context**
I don't know how to extract logcat from TWRP. My only suspect is a conflict with DN66 which tinkers with hosts file as well. I don't have a nandroid because I had just installed LineageOS and I was in the struggling process of configuring all my apps and system. I hope I don't have to wipe it.
I can access my phone from Windows if needed.

EDIT
Nevermind. In the rush of making a dirty flash, I swiped the wrong slide and factory reset my phone.

**Comment by PerfectSlayer** [comment]
Alright I can close the issue so.
For the record, was it the first time you applied hosts?
If yes, it could be an issue with system partition modified and AVB security.
About DNS66, it should not cause compatibility issue with AdAway.

**Comment by janaxhell** [comment]
Yes, it was the first time, I was just installing everything I had in my previous LineageOS version. I'm quite sure AdAway was working with no problem.
