### ISSUE TITLE
Cannot update hosts file (Pie, Magisk)

### ISSUE THREAD

**Issue by regulator-g** [AdAway/AdAway#1477]
**Describe the bug**
Using Android 9 Pie (LineageOS) and Magisk Manager (v20) AdAway gives the error "Copying of hosts file failed" when trying to enable AdAway. This can be resolved by enabling systemless hosts in Magisk, can the error message and FAQ be updated to help people combat this issue?

**To Reproduce**
1. Open AdAway
2. Click on update hosts file
3.  See error  "Copying of hosts file failed"

**Expected behavior**
hosts file updated successfully

**Screenshots**
can be added if required?

**Device**
 - AdAway version: 4.3.0
 - Device: OG Pixel
 - Android version: 9/ LOS 16
 - Root version . Stable Magisk Version: v20.1 / Magisk Manager Version: v7.4.0

**Additional context**
default settings, host file location:  /system/etc/hosts

**Comment by kinoegit** [comment]
Same with Android 8 (ShiftOS) and Magisk Manager (v20.1) AdAway gives the error "Copying of hosts file failed" when trying to enable AdAway as if rw access /system would not be given. It's possible to bypass this issue by enabling systemless hosts in Magisk.

**Comment by PerfectSlayer** [comment]
Thanks @regulator-g for the issue.

It is the intended behavior as AdAway requires to have a writable `/system` partition or at least a writable `hosts` file.

I don't think it is a good idea to ask user to enable Magisk module from the error dialog as the error could come from a lot other causes. Users might not be using Magisk at all, it could have an older Android version where Magisk is not required, it could have enabled the plugin but not reboot yet, etc…

I agree [the FAQ seems outdated](https://github.com/AdAway/AdAway/blob/master/app/src/main/res/raw/help_problems.html). A mention about latest Android versions requiring Magisk systemless hosts module could be nice.
The last update shipped some improvements about the module state to check if it is enabled and explains how to enable it. Maybe asking to users to enable it from FAQ will be enough.

I will add it to my task list but I could take some time to be released and translated in all other languages. Thanks for your advice.
