### ISSUE TITLE
Apply button covers the list

### ISSUE THREAD

**Issue by Benz99** [AdAway/AdAway#1485]
![Screenshot_2019-12-19_162945](https://user-images.githubusercontent.com/59047135/71157360-d0a53b00-227c-11ea-87d8-d92ea077ec19.jpg)

Apply button covers the list. 
Please add search in "your list" and 

BR

**Comment by sula7** [comment]
I just swipe to left or right **Apply button** if it covers

**Comment by Ghostbird** [comment]
> @Benz99 I just swipe to left or right **Apply button** if it covers

Thanks so much! I never realised that was possible!

**Comment by PerfectSlayer** [comment]
Hi @Benz99 

The search feature is already develop in the next version. So stay tune.
And about the notification, as @sula7 said you can swipe it if it bother you.

(I wasn't aware neither you can swipe it 😅)
