### ISSUE TITLE
Foursquare being completely blocked

### ISSUE THREAD

**Issue by m0yP** [AdAway/AdAway#1560]
**Describe the bug**
With today's hosts update Foursquare and Swarm apps become useless. Can't checkin (Swarm) or can't open history (Foursquare).

**To Reproduce**
Just open Foursquare / Swarm.

**Expected behavior**
Apps work as normal

**Device**
 - AdAway version: 4.3.2
 - Device: Jasmine_Sprout
 - Android version: 9
 - Root version Magisk 20.2

**Additional context**
Found this entry in https://adaway.org/hosts.txt

# [foursquare.com]
127.0.0.1 api.foursquare.com

For now I had to whitelist *foursquare.com to make them work. Dunno if it's indented to block certain parts of Foursquare's API but for now it blocks everything.

**Comment by Xx-Ness-xX** [comment]
I am having the same issue, took me a while to figure out my Swarm app malfunctioning was the cause of AdAway.

**Comment by gTamatea** [comment]
Same here, thanks for the whitelist

**Comment by mortonfox** [comment]
Just figured this out too by logging DNS requests from the Swarm app and checking the default blocklists. Is api.foursquare.com now an ad server?

**Comment by jawz101** [comment]
should be removed now.  please close if this is good.  thanks

**Comment by m0yP** [comment]
> should be removed now. please close if this is good. thanks

It is. Thanks a lot.
