### ISSUE TITLE
Add language option Please

### ISSUE THREAD

**Issue by NewUserHa** [AdAway/AdAway#1561]
**Describe the bug**
some translations are incomplete and fuzzy that is unable to make users know exactly what a function does and not beautiful. hope more awesome translater to help here.
but before that complete, could you add an option to allow users to change the ui language that they could understand and like?

Appreciate it!

**Device**
 - AdAway version: 4.3.2

**Comment by patrickdrd** [comment]
+1

every app should include such an option,
I don't like my native/phone's language in my apps, 
I want them all to run in english and only english,
I'm not interested in translations whatsoever, 
so please give us an option to change app's interface to english please,
thanks

**Comment by Vankog** [comment]
clean continue in 1054

**Comment by Sopor** [comment]
@patrickdrd and @NewUserHa If you want this feature, why did you not give the issue #1054 a thumbs up?

**Comment by patrickdrd** [comment]
I did now, even if it's a bit late?
for me at least because I'm on nougat
