### ISSUE TITLE
Remove locationiq.com

### ISSUE THREAD

**Issue by gopi-ar** [AdAway/AdAway#1573]
Hello,

We offer maps & geocoding (address) APIs to over 50k developers and do not have anything but Google Analytics & Intercom (chat) on our website. We woke up today to find our map tile servers and our US API endpoint listed on your list.

Could you please help us remove this?

```
maps.locationiq.com
us1.locationiq.com
```

Thanks,

**Comment by jawz101** [comment]
are we able to close this ticket now?  It's no longer on the host file
