### ISSUE TITLE
[News republic] compatibility report

### ISSUE THREAD

**Issue by javcarbe** [AdAway/AdAway#1574]
Is not loading if the adaway change the host
**Describe the third party app**
 - Name: [e.g. WhatsApp]
 - Version: [e.g. 1.12.3]

**Describe the compabitily issue**

**Workaround**
If applicable, describe the whitelist domains to add to fix the issue:
 - www.somedomain.com
 - *.server.org
Please add tag `workaround-available` if a work around is available.

**Comment by jawz101** [comment]
what is the issue?

**Comment by PerfectSlayer** [comment]
I guess "news republic" is not working? I close it until more details are provided.
