### ISSUE TITLE
Remove kuaidi100.com

### ISSUE THREAD

**Issue by Mosney** [AdAway/AdAway#1577]
`kuaidi100.com` is a comprehensive express inquiry website, it useful to Chinese customer check themselves express process, I recently notice it cannot work when I was under protect from AdGuardHome an I check log fount the issue is adaway add 3 items in the blacklist.

```
# [kuaidi100.com]
127.0.0.1 cache.kuaidi100.com
127.0.0.1 cdn.kuaidi100.com
127.0.0.1 p.kuaidi100.com
```
I think something must wrong here, even some pages include AD but block those 3 domains will let it whole not work.

**Comment by Sherman-Liu** [comment]
不是Adaway的锅，是数据源的问题，自己加下白名单吧，软件里有这个功能。

**Comment by Mosney** [comment]
> 不是Adaway的锅，是数据源的问题，自己加下白名单吧，软件里有这个功能。

你可能不知道，我列出的条目就是在AdAway的官方数据源里的
https://adaway.org/hosts.txt

**Comment by jawz101** [comment]
removed.  please close if it looks good.  thanks

**Comment by Mosney** [comment]
Yep, it looks good now.
