### ISSUE TITLE
Failed to install host file- StevenBlack

### ISSUE THREAD

**Issue by ioogithub** [AdAway/AdAway#1579]
**Describe the bug**
Can't add a Host source
error: "Installing hosts file... Failed to install host file."

**To Reproduce**
1. Tap Host Source
2. tap +
3. Add source: https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts, click Add

The message is displayed:
`Installing hosts file..`
then the result:
`Failed to install host file.`

After this the host file has a red check mark and it looks like it worked however I checked for a hosts that are only in this list and they were not added. 

**Expected behavior**
I expect it will add the list, it is a very popular and common list and it meets all the criteria for a host list.

**Device**
 - AdAway version: [e.g. 4.3.2.]
 - Device: [e.g. river]
 - Android version: [e.g. LineageOS nightly]
 - Root version [e.g. Magisk 20.3]

**Additional context**
The list that cannot be added:
https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts

**Comment by Kronopt** [comment]
I've been using Steven Black's hosts for a long time now.
I just installed the version you mentioned, just to check, and it works.

Did you give AdAway root permissions?
Have you enabled systemless hosts in Magisk?
Also, can you specify your device and LineageOS version?

###### note: 'e.g.' means 'example'. The device section is a bit confusing the way it is.

**Comment by jawz101** [comment]
can you try http://sbc.io/hosts/hosts and see if that works?  It's the StevenBlack's official mirror.  I use that sometimes instead of the github repo.  Easier to memorize too
