### ISSUE TITLE
[Immobilienscout24] compatibility report

### ISSUE THREAD

**Issue by carcinoma** [AdAway/AdAway#1581]
**Describe the third party app**
 - Name: [e.g. Immobilienscout24]
 - Version: [e.g. 14.3.1.872]

**Describe the compabitily issue**
The app is not able to connect to the API services.

**Workaround**
Whitelist:
 - api.finanzen.immobilienscout24.de
- api.mobile.immobilienscout24.de
- api.recommendation.immobilienscout24.de

**Comment by ustav** [comment]
This workaround may not be needed anymore soon as these domains were removed from blacklist 
https://github.com/AdAway/adaway.github.io/commit/fc4c7dcaccfaad47b76f6ace97824b418f6ecebb
