### ISSUE TITLE
[Kurio] can't open the app completely

### ISSUE THREAD

**Issue by ekapratama93** [AdAway/AdAway#1590]
**Describe the third party app**
 - Name: Kurio
 - Version: 3.x
 - Playstore: https://play.google.com/store/apps/details?id=com.merahputih.kurio&hl=en
 - APK Download: https://apkpure.com/kurio-–-baca-berita-terbaru/com.merahputih.kurio/download/92901-APK?from=versions%2Fversion

**Describe the compatibility issue**
I can't even open the app.

**Workaround**
If applicable, describe the whitelist domains to add to fix the issue:
 - *.kurioapps.com

**Comment by jawz101** [comment]
removed.  please close issue if it looks good.  thanks

**Comment by ekapratama93** [comment]
Thanks a lot.
