### ISSUE TITLE
Release Browser Extension for Maxthon

### ISSUE THREAD

**Issue by DrRazon** [AdAway/AdAway#1591]
**Describe the third party app**
 - Name: [e.g. WhatsApp]
 - Version: [e.g. 1.12.3]

**Describe the compabitily issue**

**Workaround**
If applicable, describe the whitelist domains to add to fix the issue:
 - www.somedomain.com
 - *.server.org
Please add tag `workaround-available` if a work around is available.

**Comment by jawz101** [comment]
This does not make sense.
