### ISSUE TITLE
Amazon Store Card getting blocked

### ISSUE THREAD

**Issue by KeetsScrimalittle1** [AdAway/AdAway#1596]
- Name: Amazon Store Card
 - Version: 2.1

Adaway hosts is blocking Amazon Store Card app from connecting.  Disabling https://adaway.org/hosts.txt in host sources allows it to connect.  Checked logs, it attempts to connect to mobile-collector.newrelic.com but fails.  Have whitelisted all the newrelic urls in adaway.org hosts.txt but it still fails to connect.  Cannot tell what other urls are getting blocked.

**Comment by jawz101** [comment]
it was that gpshopper.com one.  I couldn't see it either in NetGuard logs but I could in Blokada's logs

**Comment by KeetsScrimalittle1** [comment]
I'm not seeing gpshopper in the adaway hosts.txt but I'll try using the app you mentioned

**Comment by jawz101** [comment]
because I removed it

**Comment by KeetsScrimalittle1** [comment]
Ahh okay I thought you meant that one was causing issues for another app.  I see it loads now.  Thanks alot

**Comment by jawz101** [comment]
No problemo.  If things look good can you close the issue.  I would but I don't have permission on this repo.  Just the list.  Thanks

**Comment by KeetsScrimalittle1** [comment]
Sure thing

**Comment by KeetsScrimalittle1** [comment]
Thanks again
