### ISSUE TITLE
AdAway Breaking Several NetEase Games

### ISSUE THREAD

**Issue by Ninton564** [AdAway/AdAway#1599]
**Describe the bug**
AdAway's default filter lists breaks several NetEase games, not allowing you to automatically login.

**To Reproduce**
1. Disable Adblocking and restore default hosts file in AdAway. Reboot.
2. Download a NetEase game (Rules of Survival & Onmyoji Arena tested) 
https://play.google.com/store/apps/details?id=com.netease.chiji&hl=en_US
https://play.google.com/store/apps/details?id=com.netease.g78na.gb&hl=en_US
3. Open game to download additional game files, allow storage permission and choose an in-game username first. Game works perfectly.
4. Re-enable Adblocking in AdAway using the 3 default Hosts sources. Reboot.
5. Open game. Trying to proceed will prompt an impassable pop up saying "Slow connection. Please check your connection and try again", despite having full WiFi and Cell Data Connection.

**Expected behavior**
Upon opening the game, no "Slow connection" prompt should ever appear and you will able to enter the game normally.

**Device**
 - AdAway version: 4.3.2
 - Device: Xiaomi Mi 9T Pro
 - Android version: Android 10
 - Root version: Magisk 20.3

**Screenshots**
Screenshots of the erroneous prompt attached below. As well as the AdAway DNS request logs when attempting to enter the game Rules of Survival (potentially sensitive information redacted).

![Rules of Survival Error Prompt (1)](https://user-images.githubusercontent.com/61304168/75011070-55126680-5444-11ea-85cd-e36fbc5a47ae.png)
![Rules of Survival Error Prompt (2)](https://user-images.githubusercontent.com/61304168/75011087-5fccfb80-5444-11ea-932c-87b673d7b2ce.png)
![Rules of Survival Error Prompt (3)](https://user-images.githubusercontent.com/61304168/75011491-64de7a80-5445-11ea-8290-1b6bae92c0ef.png)
![DNS Request Log 1-1](https://user-images.githubusercontent.com/61304168/75011101-66f40980-5444-11ea-8442-819b99267d5c.png)
![DNS Request Log 2-2](https://user-images.githubusercontent.com/61304168/75011117-6fe4db00-5444-11ea-86e6-dac535335037.png)
![DNS Request Log 3-3](https://user-images.githubusercontent.com/61304168/75011131-71ae9e80-5444-11ea-85fe-92b5f3d8fef6.png)
![DNS Request Log 4-4](https://user-images.githubusercontent.com/61304168/75011139-73786200-5444-11ea-93e5-6eaf5024e182.png)

**Comment by jawz101** [comment]
removed easebar.com entries.  please let me know if this fixes it

**Comment by Ninton564** [comment]
> removed easebar.com entries. please let me know if this fixes it

Yes, this fixed the issue. I was able to enter and play both games without the "Slow Connection" prompt appearing.

**Comment by jawz101** [comment]
great.  if it looks good would you close the ticket out?  Thanks
