### ISSUE TITLE
Remove ns.exitgames.com

### ISSUE THREAD

**Issue by cmcooper123** [AdAway/AdAway#1603]
This domain is required for the game VRChat, without it login is denied.

**Comment by Techjar** [comment]
It's also required for Rec Room. The domain appears to be a critical component of the Photon Cloud multiplayer game service, so who knows what other games are broken by this. It should be removed from the list immediately.

**Comment by Techjar** [comment]
Yeah, it definitely shouldn't be in the list, breaks a bunch of games. Here's a link to the issue on the correct repo: https://github.com/AdAway/adaway.github.io/issues/58
