### ISSUE TITLE
About using SD Card

### ISSUE THREAD

**Issue by Combat1** [AdAway/AdAway#1604]
I 1st tried searching the web for an answer but could not find it. After updating hosts it gives a meesage about needing to reboot and warning about SD Card.
I could not find anything about using sd card on wiki either, So do we need to use a sd card Or is it best to have one in device?
Thanks

**Comment by PerfectSlayer** [comment]
The application does no more support SD Card. It is more a legacy warning.
You can forget about it (it is fixed in the next major version).
