### ISSUE TITLE
Copying of hosts file failed

### ISSUE THREAD

**Issue by nmayank** [AdAway/AdAway#1609]
I am using magisk latest version and also enabled Systemless hosts and rebooted then still not able to get Adaway working.
![Screenshot_20200314-202509](https://user-images.githubusercontent.com/18697936/76684469-47f72a80-6632-11ea-979b-3df709cea033.png)

**Comment by Kronopt** [comment]
Please don't ignore the issue template.

Provide the following information:
* Phone model
* Android version
* Rom
* Adaway version
* Magisk version

If you can, also provide a logcat

**Comment by nmayank** [comment]
Phone details : 
Model: Moto G (5S) Plus (XT1804)
Serial: ZY3227NR25
Hardware version: p4
Android version: 10
ROM build no.: QQ1B.200205.002
PixelExperience_sanders-10.0-20200228-0126-OFFICIAL
Adaway version: 4.3.2
Magisk version: 20.3(20300)

**Comment by nmayank** [comment]
[logcat.txt](https://github.com/AdAway/AdAway/files/4339446/logcat.txt)

**Comment by PerfectSlayer** [comment]
Hello @nmayank 

Can you enable verbose debug, restart the app, try to install hosts and post a new logcat here?
There is not enough details in the one you post.

Thanks!

**Comment by nmayank** [comment]
Enabled verbose debugging made the logcat again. Attaching the logcatfile
[logcat_03-18-2020_22-47-00.txt](https://github.com/AdAway/AdAway/files/4350375/logcat_03-18-2020_22-47-00.txt)

**Comment by PerfectSlayer** [comment]
Thanks. I had at look at the logcat.
Do you you enable systemless host from magisk manager settings?

**Comment by nmayank** [comment]
Added systemless hosts Module pops up as I tap on systemless hosts in Magisk Manager settings. So I am assuming that I have enabled it.

**Comment by PerfectSlayer** [comment]
And have you rebooted since?
Could you post the output of  `mount | grep hosts` from a root terminal? (from adb shell + su or any terminal app)

If the module is enabled and device was rebooted, you should have something like:
```
/sbin/.magisk/block/data on /system/etc/hosts type ext4 (rw, seclabel,relatime,noauto_da_alloc,resgid=1065,data=ordered)
```

**Comment by Chaotic-Entropy** [comment]
I briefly had this issue due to Magisk seemingly being a bit finicky about installing systemless host. Make sure that it appears in the Magisk modules section as after I had checked to make sure it was there, rebooted and Magisk agreed it was there AdAway worked fine. Either way seems more Magisk than AdAway related.

**Comment by PerfectSlayer** [comment]
Thanks @Chaotic-Entropy for the feedback 👍 
I'm closing the issue, feel free to comment if you still have trouble with systemless module.

**Comment by nmayank** [comment]
I don't have any idea as to when, why amd how I had enabled Magisk core only mode because of that my copying of hosts file failed, now the issue has been resolved
