### ISSUE TITLE
[Bug] Last entry in host sources hidden behind "apply" text box

### ISSUE THREAD

**Issue by opusforlife2** [AdAway/AdAway#1613]
**Describe the bug**
When you modify a source on the Host Sources screen, the white text box with the apply button takes up the entire bottom of the screen. If you scroll to the bottom of the list, you can't see the last entry. You can barely make it out with the slight gap between the text box and the edge of the display.

**Expected behaviour**
I suppose the list should be scrollable a little beyond the existing limit, to accommodate the white text box underneath it. That seems like the most straightforward solution.

**Comment by PerfectSlayer** [comment]
Hello @opusforlife2 

The list and apply wigets come from Google Material Design components.
They behave as Google expect it... It's not optimal but it's the intended behavior.

If you want to access the last row, you can dismiss the apply box by swiping it to left or right.

Regards
