### ISSUE TITLE
Does not update

### ISSUE THREAD

**Issue by gallegonovato** [AdAway/AdAway#1619]
Good afternoon:

I'm contacting you since Adaway doesn't update me:

https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts

Puts unknown update status

A hug and thanks for your help and time

**Comment by PerfectSlayer** [comment]
Hi @gallegonovato 

The _unknown_ status does mean it does not update but the app is not able to retrieve the last update date of the file. So it applies it everytime.

On which app version are you? Because GitHub source should be supported.

Regards

**Comment by gallegonovato** [comment]
Good morning @PerfectSlayer:

First of all thank you very much for your help, attention and time.

Adaway is on version 4.3.2 which is the last one to be released on fdroid.

Then I have lineages in a Nexus 6p with its last official update. Magisk same

Thank you very much for your help.

A hug.

**Comment by PerfectSlayer** [comment]
I ran the unit test about the GitHub workaround to extract the date of the latest commit and it worked fine.

I also have the same behavior when I try it on my device. Then I wait or restart the app and it displays the right information: _up-to-date for 1 day_.

I need to investigate with my ide and a test device... Thanks for the report!

**Comment by PerfectSlayer** [comment]
So here is the new behavior when there is no last online update known date (ie the app can't find the last time the hosts source was updated):
![Screenshot_20200331-154619](https://user-images.githubusercontent.com/1766222/78034003-70d42b00-7367-11ea-88ca-8d090e09d78f.png)

Then, if this time is found, it goes back to the usual status:
![Screenshot_20200331-154638](https://user-images.githubusercontent.com/1766222/78034071-847f9180-7367-11ea-9891-6328e9d685e6.png)

I hope it's fine to you! 👍

**Comment by gallegonovato** [comment]
Good afternoon @PerfectSlayer:


First of all I apologize for taking so long to respond and thank you for your help.

Yes, the host was always installed. Except for that host's website. But for example I tried it a few minutes ago, and Adaway put me the arrows in blue that there were new hosts. I gave him to install and restart the phone as he always does when there are new host updates. And that link kept putting me the same, and in the meantime I got another link with the same message.

What I did was run the Lte cleanner and reboot the phone. And I gave it to Adaway again to check for updates. And she's already putting me right underneath the time. More specifically, that link puts me down for one day.

So I think that's solved the problem. I'll keep investigating and if it comes back to it I'll tell you.

But now it seems to be going well. The only thing I can think of is that the websites had saturation or something. But when I clicked on the link, I wondered if the website would be OK. So I can't tell you exactly what was going on.

If you remember, previously (in a previous version) they didn't load or failed the links of that type. And you confirmed that it was a failure of Adaway. And you released an update. 

But now the bug seems to have been fixed.

Thank you very much for your help and your time.

Please receive a warm hug

**Comment by gallegonovato** [comment]
Good afternoon @PerfectSlayer



I'm having trouble with Adaway again.



Now the one that's not going is:



https://hosts-file.net/ad_servers.txt (this site in the browser does not load) and when it loads it puts error 404.



Y



https://pgl.yoyo.org/adservers/serverlist.php?hostformat=hosts&showintro=0&mimetype=plaintext puts me Need update for -37 minutes



On the first website it seems to me that now malwarebyte gave that host without being service.  To offer their own application apparently in https://forums.malwarebytes.com/topic/256701-what-happened-to-hphosts-website/?tab=comments#comment-1370003 and even the problem also in ublock that is giving https://www.reddit.com/r/uBlockOrigin/comments/fsgy4b/hphosts_ad_and_tracking_servers_link_down/ or what they say in the topic of github ublock https://www.reddit.com/r/uBlockOrigin/comments/fsgy4b/hphosts_ad_and_tracking_servers_link_down/



Attached are screenshots for you to see:





https://ibb.co/YfBhDrS



https://ibb.co/NSh1NL3



https://ibb.co/R25bJjb



I don't know if you can help me with this problem.



Since you're always looking for and installing hosts for these websites



Receive a warm hug

**Comment by PerfectSlayer** [comment]
Hello again @gallegonovato 

There is two different issues:
1. https://hosts-file.net/ad_servers.txt is down. @jawz101 are you aware of this? Is it an issue for the future?
2. The negative time (`-37 minutes`) should be a timezone error. I will check about it ;)

Thanks!

**Comment by gallegonovato** [comment]
Good afternoon @PerfectSlayer



Thank you for your help and time.



In an attempt now in the afternoon I managed to update those two host links.  Attached is a screenshot for you to see:



https://ibb.co/p2JjwFv



Take away adaway's options to check for updates automatically.  Because of the downed host that you comment on so that you don't give an error.  Until you tell me.



What I don't understand is what you say if it's a mistake for the future.  I don't understand this question.



I have the time on my mobile phone at 20:25, gmt +2 Central European Summer Time.  Since I live in Spain.  And the date 1 April 2020



I don't know if you can influence that there are more access permissions to the servers.  Because people are at home, with teleworking and so on.  Because of this pandemic that affects us.  And because of that there can be problems depending on the creator of the host (the link of that host) has it hosted.  Thus affecting Adaway?.



Any other error, I'll point out and help this great app.  As far as I can help, here I am.



If you agree and it's not a problem. 

 

Receive a warm hug.

**Comment by jawz101** [comment]
>     1. jawz101

@PerfectSlayer I don't know why it would matter for me about hphosts being down?

**Comment by PerfectSlayer** [comment]
Hi @jawz101 I hope you're going well on your side.

hphosts being down means one of the default hosts file of the app is no more.
Does it decrease the efficiency of the app or do the hostnames of this file are already covered in yours?

I just ask about your thoughts on this 😉

**Comment by jawz101** [comment]
Oh.  IMO no it doesn't.  It's a great list but most lists are for desktop browsing.

I run pfBlocker on my firewall at home and tested maybe 75 or so lists out there and whittled my favs  Steven Black and hphosts ads.  Pfb let's me see list overlap, set list order, and view hits per list.  With mine, StevenBlack, and HPHosts in that order, the MobileAdTrackers got hit the most, then StevenBlack picked up the stragglers that were more from non-mobile traffic, and maybe none or just a few would hit from hph.

If it's online I'd keep it in the defaults but if it isn't I would think StevenBlack's list really does well.  And if it ever comes back up I would keep hph just because I think they are more responsive to list changes so it likely catches more new stuff than some others

**Comment by gallegonovato** [comment]
Good afternoon @PerfectSlayer:



Today without realizing it my wife updated the Adaway lists. 

 

And the website that is down puts me status of the update unknown.  And that yesterday I got it to load (in the image I attached yesterday you could see)



But there's no way now.



Does this mean that those files are integrated in the host or that I lost the ones on that website?



I don't know if he knows of another one to put in his place and be more protected.



Receive a warm hug and thank you for your time and help

**Comment by gallegonovato** [comment]
Good afternoon @PerfectSlayer @jawz101



First of all, thank you for your help and time.  And I hope you are well in these times we are living.



Lea wanted to ask a question if I may, about host to replace the one that doesn't work



I've been looking and I don't know if they would recommend me to replace the link that these don't go:



https://raw.githubusercontent.com/jawz101/MobileAdTrackers/master/hosts 

 

https://raw.githubusercontent.com/EnergizedProtection/block/master/unified/formats/hosts



https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts



Then the ones Steven Black has at https://github.com/StevenBlack/hosts/blob/master/readme.md (here I don't know if they could all be)



https://raw.githubusercontent.com/Maji78/Antigoogle/master/Hosts



https://gitlab.com/Jorgu81/hosts/raw/master/Mozilla



https://raw.githubusercontent.com/Maji78/Antigoogle/master/Tor



https://raw.githubusercontent.com/CHEF-KOCH/FFCK/master/docs/HOSTS/Mozilla-HOSTS.txt



I don't know how you feel about those hosts...



Receive a warm hug and thank you for your time and help

**Comment by jawz101** [comment]
@gallegonovato

My MobileAdTrackers list _is_ now Adaway's list.  If anything, it's a little less up-to-date because I don't copy the changes from Adaway to MATS that often.

Energized Protections tiniest list is basically StevenBlack Unified + MobileAdTrackers.

Now that MobileAdTrackers is Adaway, and Adaway is in StevenBlack's Unified, Just use StevenBlack's Unified List (it's the basic one that just says ads + malware)

Ergo, the only list that's worth using, IMO, is StevenBlack's.

**Comment by PerfectSlayer** [comment]
Thanks for your heads up @jawz101 

> The only list that's worth using, IMO, is StevenBlack's. If you just want to target Mobile ads and you have an ad blocker for your mobile browser, the Adaway list is the tiniest.

Would you recommend to replace hphosts by StevenBlack's one?
If so, I will update the default hosts of the app.
Otherwise, should I just remove it (with no replacement)?

**Comment by jawz101** [comment]
I guess I would replace HPHosts with StevenBlack.

While the Adaway list by itself is mobile specific, StevenBlack will catch more of your web-based domains.

**Comment by gallegonovato** [comment]
Good afternoon @jawz101



Thank you very much for your time and response.



What I don't see is where is your MobileAdTrackers list on adaway?



And forgive my ignorance but I don't understand when you say IMO?.



After the one on the StevenBlack website https://github.com/StevenBlack/hosts/blob/master/readme.md at the bottom where it says Sources of hosts data unified in this variant would you put one?



Then talking about Energized Protection's would you put one, the most complete one for example?



I don't know if you could recommend me some host addresses and then I have seen that there are anti NSA lists, would you put some?  If so, could you tell me which one?



Also, if you could tell us which host lists you and @PerfectSlayer are using, it would be a problem.



I'm sorry for any inconvenience caused.  And I thank you for all your time and help.



Thank you very much for everything and receive a warm hug

**Comment by PerfectSlayer** [comment]
A quick follow up: StevenBlack host is going to replace hpHost 

See https://github.com/StevenBlack/hosts/pull/1218

**Comment by jawz101** [comment]
@gallegonovato The message about the Adaway change is on the readme: https://github.com/jawz101/MobileAdTrackers

IMO is short for "in my opinion". Sorry for the confusion.

This one is the Steven Black list I'm talking about:
https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts

on the readme it is called "Unified hosts = (adware + malware)"

**Comment by gallegonovato** [comment]
Good afternoon @PerfectSlayer and @jawz101

Thank you very much for your help and for being there.  And for your help and time.

I have added to my Adaway https://raw.githubusercontent.com/jawz101/MobileAdTrackers/master/hosts and Steven's I will add it either automatically or in an upcoming update?

Ah... sorry I didn't know what imo was.  Like they say where I'm from, you never go to bed without knowing something new.

So, speaking of Energy Protection, would you put one in your adaway?  I mean, would you recommend that I put one?

  Then I've seen that there are anti-NSA lists, like this one from Chef-kok: https://raw.githubusercontent.com/CHEF-KOCH/NSABlocklist/master/HOSTS/HOSTS .    I don't know if you know of any better or more complete ones.

Also, if you could tell us what host lists you are using in your adaway and @PerfectSlayer in your adaway, it would be very useful for users and would be appreciated.  Or if you could recommend us some to put in our adaway, I would be very grateful. 

Sorry for the inconvenience.    And I appreciate all your time and help.

Thank you very much for everything and receive a warm hug

**Comment by b0gdanw** [comment]
https://hosts-file.net/ad_servers.txt returns Not Found The requested URL was not found on this server.

**Comment by jawz101** [comment]
>So, speaking of Energy Protection, would you put one in your adaway? I mean, would you recommend that I put one?

Not necessary.

Steven Black contains Adaway(formerly MobileAdTrackers)

Energized Spark = Steven Black + MobileAdTrackers 

Therefore Energized Spark is now = to Steven Black

Since Energized Spark is now = Steven Black, it's really not necessary

**Comment by gallegonovato** [comment]
Good afternoon @jawz101 and @PerfectSlayer 

Thank you very much for your help and time.

I've seen anti-NSA lists, like this one from Chef-kok: https://raw.githubusercontent.com/CHEF-KOCH/NSABlocklist/master/HOSTS/HOSTS .    I don't know if you know of any better or more complete ones and if I would recommend putting them on my adaway.

Also, if you could tell me what host lists you are using on your adaway, it would be very useful for users and would be greatly appreciated.    Or if you could recommend us some to put in our adaway, I would be very grateful.

Sorry for the inconvenience.    And I appreciate all your time and help.

Thank you very much for everything and get a hug

**Comment by jawz101** [comment]
@gallegonovato this issue is closed but I have to say that some idea to block the NSA with a list of domains to block is silly.  Just looking over that list, it's a bunch of webpages.  My state's website is listed.  Universities are listed.  The sites to get Social Security, health insurance, or Medicare are listed.  I have no idea what you would use that list unless you wanted to prevent someone from living in America.
