### ISSUE TITLE
hosts-file.net/ad_servers.txt no longer available

### ISSUE THREAD

**Issue by monzta** [AdAway/AdAway#1620]
It seems https://hosts-file.net/ad_servers.txt is gone. I am being redirected to https://www.malwarebytes.com/browserguardad_servers.txt and getting a `404 - Page Not Found` message.

**Comment by Ubimo** [comment]
Can confirm.
hosts-file.net isn't offering this service any more.

**Comment by Dabombber** [comment]
There's some info on the [malwarebytes forums](https://forums.malwarebytes.com/topic/256701-what-happened-to-hphosts-website/):

> We are currently restructuring hpHosts and it will no longer be updated. You could however check out our browser extension product.

and

> Yes, we can understand but unfortunately we're no longer able to support that service

**Comment by PerfectSlayer** [comment]
Hello @monzta aml @Dabombber and thanks for your report.

We are currently discussing the issue here: #1619 
I'm closing this one and you are welcome to join the discussion.
