### ISSUE TITLE
Audio ads

### ISSUE THREAD

**Issue by ghost** [AdAway/AdAway#1625]
Audio ads in apps like Spotify, online radio box are not being blocked by your app.
Similar issue raised here.
https://github.com/uBlockOrigin/uAssets/issues/6423

**Comment by jawz101** [comment]
That isn't something a DNS ad blocker can block if someone is saying an add in the middle of a stream of music or if it's triggered by a snippet of code.

You can use a browser that supports ad block addons which can pick apart actual code on a webpage to carve out a specific thing like that or use an ad blocker such as Adguard which might be able to accomplish this with a more sophisticated rule engine.

Adaway uses plain old DNS blocklists.  It's like a shotgun for swatting flies.  They are effective as a first layer but then an adblocker that supports Adblock Plus syntax'd rulesets can carve out more specific content.

**Comment by Kronodile** [comment]
Hi, did you get to block spotify ads with adaway or any other adblocker for android? My device is rooted btw
