### ISSUE TITLE
Dont block any ad in Puffin Tv

### ISSUE THREAD

**Issue by 9acca9** [AdAway/AdAway#1626]
HI all.
I use puffin tv and i noticed that adaway dont block nothing when i use this web browser. And this is the browser i use most.
(i dont speak english)
Thanks to all.

**Comment by jawz101** [comment]
You may have to disable any Data Savings feature in your browser settings that describes its mechanism as "we will compress your traffic" for DNS blocklisting to work.

Compressed ads vs. blocked ads?  I think I would rather block them in the first place.
