### ISSUE TITLE
Updates are disabled but it will still check for new hosts files

### ISSUE THREAD

**Issue by Sopor** [AdAway/AdAway#1800]
**Describe the bug**
I have disabled all updates but still i get notification about new hosts files. I can also see in AdAway that there are hosts files that need to be updated.

**Expected behavior**
All updates should be made manually as i did in version 4.x

**Screenshots**
![image](https://user-images.githubusercontent.com/5789283/79511907-853f4580-8040-11ea-8973-a2dc40090834.png)

**Device**
 - AdAway version: 5.0.1
 - Device: Samsung S9+
 - Android version: 8.0
 - Root version Magisk

**Comment by PerfectSlayer** [comment]
Hello @Sopor 

Thanks for your report!

There is at least a bug with the periodical updates that does not trigger if you don't re-enable them manually at first install. It tooks me few days to properly test it so now I will have a look to this use case: how to disable them 😛

**Comment by PerfectSlayer** [comment]
The last beta version should be better.
Try to enable and disable it again to be sure.

**Comment by Sopor** [comment]
Sorry to say it, but it will still search for updated hosts file and show a notification:
![image](https://user-images.githubusercontent.com/5789283/80320573-7c582c00-8817-11ea-9d57-5d2d6c4b2722.png)

**Comment by PerfectSlayer** [comment]
😭 

Is the app checking for update the first time you launch it? Kill it and restart it, you should not see "Check for update..." in the home UI.

Can you provide the result of the following command: `adb shell dumpsys jobscheduler`
It is used to [debug workmanager tasks](https://developer.android.com/topic/libraries/architecture/workmanager/how-to/debugging) so I can check if there is periodic task declared and their statuses.

**Comment by Sopor** [comment]
I have the wifi/data disable and when i enable it it seems to do a check.

Now it will update even if i already have updated it. Check the update status in the picture below:

![image](https://user-images.githubusercontent.com/5789283/80400199-c0503d00-88ba-11ea-88d2-c2921b8e6eaf.png)

**Comment by Sopor** [comment]
> Can you provide the result of the following command: `adb shell dumpsys jobscheduler`
> It is used to [debug workmanager tasks](https://developer.android.com/topic/libraries/architecture/workmanager/how-to/debugging) so I can check if there is periodic task declared and their statuses.

I have no idea how to use this debug workmanager. Any step by step guide?

**Comment by PerfectSlayer** [comment]
About the negative time, I am working on it for several days now.

If you are not a developer, it might be tricky. It requires to enable developer settings from your device, authorize adb connections, install adb drivers on your computer and run an adb shell to connect to your device in order to type the command.
It's not worth it the trouble. I will keep investigating the issue on my side :wink:

**Comment by PerfectSlayer** [comment]
About negative time, could you try this test build? [app-release.zip](https://github.com/AdAway/AdAway/files/4562780/app-release.zip)
Just be sure to refresh source to update internal database time.

**Comment by Sopor** [comment]
> Just be sure to refresh source to update internal database time.

I'm not sure i understand what you mean but i downloaded all my sources again and now it is even more:

![image](https://user-images.githubusercontent.com/5789283/80888120-959d2480-8cbe-11ea-8e6a-257597faf38b.png)

**Comment by PerfectSlayer** [comment]
Thanks for the capture! This issue comes from millisecond to second conversion. 
I will have a look at it! 😅

**Comment by PerfectSlayer** [comment]
It's surprising you got an « installed » status for 2nd source because it does no more exist.
Do you have similar issue with active sources?

**Comment by Sopor** [comment]
This was the first time i noticed it but most of the times i never check the status of the hosts files. I press update and when it find one i update :)

**Comment by Sopor** [comment]
When i enabled the Wifi this morning:
![image](https://user-images.githubusercontent.com/5789283/81099442-37b14c80-8f0b-11ea-8c0d-30ccab3aafc7.png)

![image](https://user-images.githubusercontent.com/5789283/81099466-40a21e00-8f0b-11ea-83bf-2a599919e4cb.png)

**Comment by Sopor** [comment]
I'm now running 5.0.3 and i still get those update notifications for hosts files.

**Comment by PerfectSlayer** [comment]
Could you try from a clean install?

1. Remove hosts.file.net source,
2. Export a backup,
3. Delete application data,
4. Uninstall application,
5. Install last beta
6. Restore backup
7. Disable update
8. Wait and report ?

**Comment by DjDiabolik** [comment]
Hi... i have installed 5.0.3. For do this i have previous "Force STOP" 5.0.2.
Uninstalled and remove all files like cache from android and reinstall 5.0.3.....

You suggest to export a backup and restore for what ?

**Comment by Sopor** [comment]
Done! Now i have to wait and see what happens :)

**Comment by Sopor** [comment]
Sorry, but it will still check for updates :(

**Comment by Sopor** [comment]
I have a question about restoring my HOSTS file. In version 4.x there was a button to do that (if i remember it right) so i could install my original HOSTS file, but i can't find that in 5.x.

**Comment by DjDiabolik** [comment]
Exactly........ i have also made it. I continue to see the notification say to me ever "Upgrade Avaiable".

**Comment by PerfectSlayer** [comment]
Thanks all for the report. I will have a look at it.

**Comment by PerfectSlayer** [comment]
I think I find the issue. The next beta will ship this fix. It should be apply at next app startup.
Don't hesitate to comment the issue if it does not work so I can reopen it and keep investigating.

**Comment by DjDiabolik** [comment]
Ok thanks in advance.
Please advice our if we can install over the currently 5.0.3 or it's also better to do a clean installation....

Little OT:
I have a little question.. on main screen there's a button. If i click on it appears a symbol like "Pause".  
If i re-click over the "Pause" button it's appears the icon of Adaway inside a red button.
What's the difference ? When i see the "Pause" button there's stop using the host files ?
When i see the the "Pause" button also the color of background change to grey to red.... how it's works ?

**Comment by Sopor** [comment]
Yeah, i'm a bit confused about that too as i wrote in my hidden comment [above](https://github.com/AdAway/AdAway/issues/1800#issuecomment-628340858)
