### ISSUE TITLE
Follow system default theme

### ISSUE THREAD

**Issue by ghost** [AdAway/AdAway#1892]
I would like to suggest following the system default theme that is available from Android 10 (API level 29):
https://developer.android.com/guide/topics/ui/look-and-feel/darktheme

**Comment by PerfectSlayer** [comment]
Hi "ghost",

It's already using the System API. There is only always on / off because it's a toggle.
I guess I can make a combo list like that:
![image](https://user-images.githubusercontent.com/1766222/79900242-39a8e500-840e-11ea-8cc1-4e07c55a0c86.png)
