### ISSUE TITLE
No indicator that will show when the web server is running

### ISSUE THREAD

**Issue by Sopor** [AdAway/AdAway#1916]
In this new 5.x version there is nowhere to see if the web server is running. Could you add that again?

**Comment by PerfectSlayer** [comment]
Hello @Sopor

If the `Enable web server` checkbox is checked in your settings, it's running.
I already had this feedback but I don't know how to implement it / let the user know from the settings.
Any idea? 🤷

**Comment by PerfectSlayer** [comment]
A quick update of what's coming: https://twitter.com/HardCoding/status/1258816228400992256

**Comment by PerfectSlayer** [comment]
I release the new beta. Have a look to the new preferences screen.

Regards
