### ISSUE TITLE
Whitelist ignored when updating

### ISSUE THREAD

**Issue by m0yP** [AdAway/AdAway#1917]
**Describe the bug**
I have a couple of hosts in whitelist. When updates are found and host file is rebuilt one of my whitelisted hosts is removed and I have to add it again.

Besides the default lists I also added GoodbyeAds

**To Reproduce**
1. New update is found.
2. Click on update.
3. New files are parsed.
4. After updating I have to re add "graph.facebook.com".

**Expected behavior**
Whitelisted items are left untouched.

**Screenshots**
N/A

**Device**
 - AdAway version: 5.0.2
 - Device: Android
 - Android version: Q
 - Root version: Magisk 20.4

**Comment by PerfectSlayer** [comment]
Hello @m0yP 

Thanks for the report. I fixed it recently but not ship it yet! 7682ca3b3dfee5056d6f98f9f3e306aaa72cae21
Allowed hosts presents in blocked hosts from source are deleted on source update.

Stay tuned for the next beta update :wink:
