### ISSUE TITLE
Create ability to enable / disable all entities in whitelist / blacklist at once 

### ISSUE THREAD

**Issue by mickrussom** [AdAway/AdAway#1943]
**Describe the bug**
Create ability to enable / disable all entities in whitelist / blacklist at once 

**To Reproduce**
NA

**Expected behavior**
Have an in application control to enable and disable all entries in white/black/redirects at once. 

**Screenshots**
NA

**Device**
 - AdAway version: [4.3.4]
 - Device: [Pixel 3xl]
 - Android version: [10]
 - Root version [Magisk 20.4]

**Additional context**
NA

**Comment by PerfectSlayer** [comment]
Hello @mickrussom 

This can be easily achieve by creating a host source file on your device and add it as source.
Then you can enable / disable this source easily.

Adding a such feature will clutter the UI and I don't think a lot of users will use it.
If a lot of users are interested in and the workaround is not enough, please comment this issue.

Regards
