### ISSUE TITLE
AdAway 5.x Allowed (white) list entries are being removed with hosts download.

### ISSUE THREAD

**Issue by ipdev99** [AdAway/AdAway#1965]
**Describe the bug**
Stumbled across this a little earlier while trying to get an app to work while AdAway was running.

Issue:

Using the DNS requests option to add a blocked url to the whitelist (Allowed) is removed after you download(update) hosts sources if the URL is included in the hosts source.

Steps to reproduce:
Disable blocking.
Run dns logging.
Find an URL that will be blocked by a hosts source.
Click on the checkmark to add it to Allowed (whitelist).
Check Allowed list and make sure it was added.
Enable blocking and update/download hosts sources.

The URL will be removed from the Allowed list.
Under DNS requests it will show as being blocked (blacklist).

If the URL was not in the hosts source, it would stay in the Allowed (white) list.

Tested on:

Pixel 3aXL abc ROM (Android 10 May 2020 Security)
Magisk canary (debug)
AdAway 5.0.2 (The test version from xda thread)

Nexus 7 (2013) AEX [AospExtended unofficial] (Android 10 APR 2020 Security.)
Magisk canary (debug)
AdAway 5.0.2 (Beta release, updated from 5.0.1 using the built-in updater.)

App:
CNN Breaking News [_PlayStore_](https://play.google.com/store/apps/details?id=com.cnn.mobile.android.phone&hl=en_US)

Allowed (whitelist) URL:
geolocation.onetrust.com

Blocked by hosts source:
[_AdAway_](https://adaway.org//hosts.txt)

I never rule out user error so, might just be me.

**Comment by PerfectSlayer** [comment]
Hello @ipdev99 

Thanks for the report! I hope you're doing fine.
I fixed this bug few days ago (7682ca3b & e29715c3). I will make a beta release this week with the patch. fo

**Comment by ipdev99** [comment]
> Thanks for the report! I hope you're doing fine.
I'm okay, thank you for asking.
>
By your activity I assume you are fine. (?)

> I fixed this bug few days ago ([7682ca3](https://github.com/AdAway/AdAway/commit/7682ca3b3dfee5056d6f98f9f3e306aaa72cae21) & [e29715c](https://github.com/AdAway/AdAway/commit/e29715c3a6f9c25d7c585f6d2534f3f77f7095e3)). I will make a beta release this week with the patch.
> 
> If you want more details about the issue, I set a card to store some notes about it https://github.com/AdAway/AdAway/projects/2#card-37335029
>
Missed that.
Skimmed the issues and did not realize they were symptoms of the same cause.

Looking forward to the next (beta) update.

In the meantime, using the 5.x builds an easy work-a-round is to make a backup and then restoring it after a hosts update/download.

_(Side note: For those who may read this, restore currently works as append not replace.)_

**Comment by PerfectSlayer** [comment]
> By your activity I assume you are fine. (?)

I am fine thanks. I avoid to go outside the most I can. Until now, I can work remotely but I will have to go back to the office soon... As I have no more commute, sport nor conference organization, I can work more on the app 😅 

> (Side note: For those who may read this, restore currently works as append not replace.)

Good catch! I will fix this. The import will update host entry if it's already present. That will prevent duplicate entry in the database.

**Comment by PerfectSlayer** [comment]
The new beta is out!
