### ISSUE TITLE
duplicate entries of same blocked domain

### ISSUE THREAD

**Issue by holysnipz** [AdAway/AdAway#1997]
**Describe the bug**
Seems like AdAway is not checking for duplicate entries when building hosts file. making the final file bigger than what it should be

**To Reproduce**
1. Add multiple 'Hosts sources', in my case:
```
https://gitlab.com/CHEF-KOCH/cks-filterlist/raw/master/hosts/Ads-tracker.txt
https://gitlab.com/CHEF-KOCH/cks-filterlist/raw/master/hosts/coinminer.txt
https://raw.githubusercontent.com/EnergizedProtection/block/master/blu/formats/hosts
https://raw.githubusercontent.com/deathbybandaid/piholeparser/master/Subscribable-Lists/CountryCodesLists/Thailand.txt
https://raw.githubusercontent.com/deathbybandaid/piholeparser/master/Subscribable-Lists/ParsedBlacklists/EasyList-Thailand.txt
https://raw.githubusercontent.com/hoshsadiq/adblock-nocoin-list/master/hosts.txt
https://raw.githubusercontent.com/jawz101/MobileAdTrackers/master/hosts
https://raw.githubusercontent.com/kowith337/ThaiAntiTokenSites/master/AntiPumpSites_hosts.txt
https://raw.githubusercontent.com/kowith337/ThaiConsentHosts/master/ThaiConsentHosts.txt
https://raw.githubusercontent.com/notracking/hosts-blocklists/master/hostnames.txt
https://raw.githubusercontent.com/r-a-y/mobile-hosts/master/AdguardMobileAds.txt
```
2. Let AdAway build the *hosts* file
3. Go to preferences -> Open hosts file
4. make a copy of that hosts file then open it in PC
5. search for entries, ` ads.yahoo.com` for example *(space before domain is must)*

**Expected behavior**
find 2 results, one for ipv4 and another for ipv6. not too many like screenshot below

**Screenshots**
the top one is final result from AdAway 5.0.3, while the below is from 4.3.4
![image](https://user-images.githubusercontent.com/9103583/81500811-cd2f5080-92fe-11ea-908e-fb2a9cb3b4aa.png)

**Device**
 - AdAway version: 5.0.3
 - Device: Xiaomi A1
 - Android version: 9.0 
 - Root version Magisk 20.4

**Additional**
or maybe this is cause by "direct upgrade" from stable version? 🤔

**Comment by PerfectSlayer** [comment]
Hello @holysnipz 

Thanks for you report! It's nice of you to find the bug so quickly after the release.
I will take time to write unit tests to test the new database backend because there is too many related bugs...

Dont' worry, the issue does not come from you (direct upgrade or anything). It's due to this bug fix 7682ca3b3dfee5056d6f98f9f3e306aaa72cae21 for the latest beta. I will take time to address those issues first before working of any new feature.

I'll keep you posted in this issue.
