### ISSUE TITLE
It is possible to open hosts sources when update is running

### ISSUE THREAD

**Issue by Sopor** [AdAway/AdAway#2001]
**Describe the bug**
It is possible to open the hosts source even if the hosts files get updated (press the spinning icon at update). If i do that it will also show a message that i need to apply it.

**To Reproduce**
1. Update hosts files
2. When the icon spinns press it
3. Sometimes you need to do it a couple of times

**Expected behavior**
Does it really need to be necessary to open the hosts sources? I believe it could be blocked while it updates the hosts files ...

**Screenshots**
![image](https://user-images.githubusercontent.com/5789283/81514168-d4218780-932d-11ea-80f6-7430fd4936f2.png)

**Device**
 - AdAway version: 5.0.3
 - Device: Samsung S9+
 - Android version: 8.0
 - Root version: Magisk (DevBase)

**Additional context**

**Comment by zgfg** [comment]
It was also reported on XDA (I've attached a video there)
Problem is that when it asks to Apply changes, if you click Ok, it will endlessly ask again to Apply changes, and updating will never finish
