### ISSUE TITLE
Adaway for unrooted mobiles

### ISSUE THREAD

**Issue by Imparium** [AdAway/AdAway#2005]
So I really like AdAway, however, I use Xiaomi mobiles that are a pain in the ass to root. Last time I tried to root my phone I hard bricked it and had to purchase a new one.
I thought about having a AdAway app to [edit hosts file of the Android using a PC](https://www.modmy.com/how-modify-hosts-file-your-android-device) , so no root is required.
It could use an application as Steve Black's. So it automatically update the hosts file and push to Android using ADB.

**Comment by PerfectSlayer** [comment]
Hello @Imparium 

The article is 3 years old. You can no more edit hosts file using adb and persist it.
Even if you can edit it using adb, your hosts file will be restore at each reboot.

If you want to use AdAway without root, have a look to the latest beta 5.x version.
It's a built-in feature :wink;
