### ISSUE TITLE
Wrong amount of hosts files in update status

### ISSUE THREAD

**Issue by Sopor** [AdAway/AdAway#2039]
I now have 4 sources but only three are selected,
![image](https://user-images.githubusercontent.com/5789283/82103507-92b91f80-9713-11ea-8cea-df8226cf1be5.png)

but as you can see here i should only have 2 sources
![image](https://user-images.githubusercontent.com/5789283/82103541-b2e8de80-9713-11ea-8324-70eedf69d80a.png)

I then pressed the update button (the other one was done automatically by AdAway even if it is disabled) and now it suddenly show the correct sources

![image](https://user-images.githubusercontent.com/5789283/82103635-0eb36780-9714-11ea-92a1-0894d7c0249e.png)

I did an update but it got stuck here or
![image](https://user-images.githubusercontent.com/5789283/82103664-2c80cc80-9714-11ea-85b4-434c04059ec9.png)

it took about two minutes for it to finished. The file is only 1.68 MB, so i don't know why it took so long time and why does it show only two sources when i have three?

I'm still at AdAway 5.0.3

**Comment by Sopor** [comment]
In AdAway 4.x it took a few seconds to update three hosts files but in 5.x it takes 1:40 as you can see in this [video](https://gofile.io/d/RzmP1d). Sometimes it takes even longer.

**Comment by Sopor** [comment]
@PerfectSlayer If you want to watch the above vide you need to do it soon or else it will be deleted from the server.

**Comment by Sopor** [comment]
Installed 5.0.4 but it is still very very slow to update the hosts files :(

**Comment by Sopor** [comment]
It seems to be stuck at this hosts file but if i paste it in my web browser it will open it in less than a second. So why will it take AdAway 1:40 to get it?
```
https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts
```

**Comment by PerfectSlayer** [comment]
Your browser is only downloading hosts file.
The app must download it, validate format, parse each ip and host, check everything is fine related to security (no injection or stuff like that) then record it to database.

Browser and app timings can't be compared as they don't do the same thing.

**Comment by Sopor** [comment]
But it is stuck at that file and the whole process take about 1:40. It shouldn't take that long time. When it is downloaded the rest of the process is done in 1-2 seconds when it merge the hosts files.

As i already have told you, the old AdAway did everything in a few seconds.

**Comment by PerfectSlayer** [comment]
Stable and Beta does not have anything in common. You can't compare them.

I never watched it because I have my own life! You open [more than a dozen of issues](https://github.com/AdAway/AdAway/issues?q=author%3Asopor). Each issue takes between 2 and 10h to fix. Maybe I would rather spend time with my family than arguing with you why I don't have time to fix all your report and comment all issues.

Do you have any idea how much time it takes to learn how to develop an app, develop it, help a community, taking care of UI design, translations, builds, releases... So no, I didn't have the time to watch your video and I won't apologize for it.

**Comment by Sopor** [comment]
Do you think that write reports only takes a few minutes? I'm testing the app, if i find something that i thing is odd i have to try to reproduce it. Then i need to take screenshots and sometimes even make videos to try to explain and show what i believe is wrong. I need remember all steps and write a step by step instruction to make it easy for the devs to understand. I translate their apps and that also will take much of my free time. If you don't have time for this you can always stop doing what you do or make the app only for yourself. Then you don't have to spend time you don't have on this.

There are several ways to let me know that you don't want to improve your app. You can tell me that you don't want my reports anymore or you can block me from creating reports or you can keep your project private.
