### ISSUE TITLE
Make the hosts sources on two or more rows

### ISSUE THREAD

**Issue by Sopor** [AdAway/AdAway#2040]
Make the hosts sources on two or more rows.
![image](https://user-images.githubusercontent.com/5789283/82104050-a5ccef00-9715-11ea-931f-214fe351394d.png)

Then you maybe tell me to turn the phone horizontally but that is not enough as you can see here
![image](https://user-images.githubusercontent.com/5789283/82104110-d9a81480-9715-11ea-98c1-6f38d8bb974d.png)

**Comment by zgfg** [comment]
Yes, that would be valuable.

Otherwise, one must click on Edit to see the whole URL or to make a Json backup to see the URL there
