### ISSUE TITLE
Is there any way to completely block a domain? (with subdomains)

### ISSUE THREAD

**Issue by vishalnandagopal** [AdAway/AdAway#2053]
Firstly, thank you. You have made my life online so much better, with such a great app.

Version - 5.0.3
Phone - Android 10 / whyred

Is there any way to completely block a domain with AdAway?
For example, I noticed that blocking facebook.com , doesn't block m.facebook.com or pixel.facebook.com. Is there any way to add facebook.com, such that all sub domains are also blocked.

On another note, what do you think should be the max size of the host file for a good experience?

**Comment by ipdev99** [comment]
You should be able to use an asterisk as a wildcard.
> *.facebook.com

**Comment by vishalnandagopal** [comment]
@ipdev99 it blurs out the 'add' when I use anything other then letters and dots.

**Comment by PerfectSlayer** [comment]
Hello @vishalnandagopal 

Wildcard blocked hosts is not allowed. It's due to hosts file limitation.
Technically, it could be done in the non-root ad-blocking method but nothing planned yet.

Regards

**Comment by ipdev99** [comment]
@vishalnandagopal
Hi.
I have been jumping around a bit and misread your issue.

As pointed out, wild cards do not work when adding to blocking list.
_You can use them in the allowed list._

I would be willing to test wild cards in blocking if, ever possible but, it seems it's a dead end.

Sorry for the bad comment.
Cheers.
