### ISSUE TITLE
YouTube vanced features not working  

### ISSUE THREAD

**Issue by shamrat05** [AdAway/AdAway#2055]
Some cool features of YouTube vanced is not working for s.youtube.com blocking.thousands of people is using adaway and vanced together.. So, we hope you just put s.youtube.com on whitelist or totally remove it from host file or whatever. Thanks sir.stay home

**Comment by PerfectSlayer** [comment]
Hello @shamrat05 !

`s.youtube.com` is not blocked by default AdAway hosts.
You should have a look to the source you use and allow it if needed.

Regards
