### ISSUE TITLE
Very high RAM usage on run

### ISSUE THREAD

**Issue by Danbest82** [AdAway/AdAway#2057]
**Describe the bug**
Version 5.0.3 has very high RAM usage when opened. This also happens on boot. I have a 4gb phone and it was using about 1.7gb when I checked. Even with my LMK settings set to not aggressive at all, it kills off important apps. 

**To Reproduce**
1. Open AdAway 
2. Start list updates 

**Expected behavior**
AdAway 4.3.4 works perfectly. 

**Device**
 - AdAway version: 5.0.3
 - Device: LG V30 VS996 
 - Android version: 8.0
 - Root version: Magisk 20.4

**Additional context**
Currently using version 4.3.4 but can install version 5.0.3 and run logcat if needed.

**Comment by PerfectSlayer** [comment]
Hello @Danbest82 

There was some issue with database. Could you have a look to the 5.0.4 version? It should be way better.

**Comment by Danbest82** [comment]
Looks like it's fixed. Thank you! I'll rest it out a couple days under normal conditions and see how it goes.

**Comment by Danbest82** [comment]
Running a couple days and all good on my end! Thanks!
