### ISSUE TITLE
AdAway is not working on my OP after Android 10

### ISSUE THREAD

**Issue by tinaag** [AdAway/AdAway#2061]
It says
"Symlink missing

Symlink from your target to /system/etc/hosts is not existing or incorrect! AdAway will not work if it is not pointing to the right file.
Do you want to creating a symlink?
no     yes"
I click yes, reboot the phone, and still same message appears, can anyone help me with this?

**Comment by pilsnerbeer** [comment]
If you have Magisk, go to preferences and enable systemless hosts & reboot.

**Comment by tinaag** [comment]
I did and didn't work.

I was trying to use the latest version. Then I decided to use the version 3
something and is working like a charm. Thanks anyway.

**Comment by jadball** [comment]
@pilsnerbeer This worked for me, thank you.
