### ISSUE TITLE
Charlotte Business Journal  menu not working

### ISSUE THREAD

**Issue by stolo17** [AdAway/AdAway#2062]
The Charlotte business journal sidebar/menu no longer works with adaway enabled

**Comment by stolo17** [comment]
![Screenshot_20200529-080824](https://user-images.githubusercontent.com/9360563/83262149-780e8e00-a18a-11ea-81ec-92dd39870dd1.png)

**Comment by jawz101** [comment]
Geez that site did not want to work.
cookielaw, onetrust, and something on the homepage had to be allowed before uBlock Origin would work.

**Comment by jawz101** [comment]
The site is bizjournals.com

**Comment by jawz101** [comment]
just in uBlock Origin I had to allow
```
@@||geolocation.onetrust.com/cookieconsentpub/v1/geo/location/dnsfeed$script
* https://cdn.cookielaw.org/consent/ xmlhttprequest allow
* https://cdn.cookielaw.org/opt-out/ script allow
* https://cdn.cookielaw.org/scripttemplates/ script allow
* https://cdn.cookielaw.org/scripttemplates/ xmlhttprequest allow
* https://geolocation.onetrust.com/cookieconsentpub/v1/geo/location script allow
```

to get around AdGuard Annoyances list, MVPS, and maybe other blocklists.  I guess I'll remove them from the Adaway list but I guess others try to block it and I don't see those domains on VirusTotal as being in mobile apps

**Comment by stolo17** [comment]
Thanks! I was able to get them all white listed and it is working now. So many requests in that app!

**Comment by jawz101** [comment]
yeah.  Some sites are turds.  You may want to give Firefox for Android a try.  It has some built-in tracking protection and you can install add-ons such as uBlock Origin to filter ads out even further.  Makes web pages snappier and sites don't connect to millions of things.

Check out how ad blocking works in this test I did.

This is me just browsing 25 sites and seeing what domains were on each site, then it puts lines in between domains that were observed occurring on multiple sites.

https://github.com/jawz101/TrackersVsFirefox
