### ISSUE TITLE
Can't deactivate host-sources lists

### ISSUE THREAD

**Issue by Cris--** [AdAway/AdAway#2067]
**Describe the bug**
If i deactive one or two of my three hosts lists and apply this all 3 lists gets activated. 

**To Reproduce**
1. Got to Host sources
2. Deactivate one or two lists
3. Apply
4. Lists gets activated. 

Is this a normal behavior?
Don't think so or!?

Fresh AdAway install. 

**Device**
 - AdAway version: 5.0.4
 - Device: OnePlus 5T 
 - Android version: 10, crDroid 6.6 (LOS) 
 - Root version Magisk 20.4

**Comment by zgfg** [comment]
See also:
https://forum.xda-developers.com/showpost.php?p=82712989&postcount=14916

and the second part of:
https://forum.xda-developers.com/showpost.php?p=82653871&postcount=14869
