### ISSUE TITLE
Parsing all Hosts sources although only few were Outdated

### ISSUE THREAD

**Issue by zgfg** [AdAway/AdAway#2068]
**Describe the bug**
I have 9 up-to-date hosts sources and 2 outdated.
Opening the list, it shows which 2 are outdated.
But when I click to the icon next to the outdated hosts sources, it starts downloading and parsing all my 11 hosts sources

**To Reproduce**
Wait when it shows that 1 or 2 hosts sources are outdated, click to the icon next to (second row on the main screen)

**Expected behavior**
It must download and parse only the outdated hosts sources.
There is a line above, with the other icon, to trigger updating of all hosts sources

**Screenshots**
![Screenshot_20200601_123130](https://user-images.githubusercontent.com/51943147/83400986-2ec97300-a404-11ea-8e94-158888c81c1e.jpg)
![Screenshot_20200601_123223](https://user-images.githubusercontent.com/51943147/83401004-3852db00-a404-11ea-919e-f324583c3f8d.jpg)
![Screenshot_20200601_123300](https://user-images.githubusercontent.com/51943147/83401024-44d73380-a404-11ea-81e5-8bd41102ba25.jpg)

**Device**
 - AdAway version: 5.0.4
 - Device: Xoaomi Mi 9T, Huawei Mate 9
 - Android version: 10 (Xiaomi), 9 (Huawei)
 - Root version 20415 Canary (Xiaomi), no root - VPN (Huawei)

**Additional context**
Copy of my Json backup (11 hosts sources, every day almost one needs update):
{
    "sources": [
        {
            "url": "https:\/\/adaway.org\/hosts.txt",
            "enabled": true
        },
        {
            "url": "https:\/\/block.energized.pro\/blu\/formats\/hosts.txt\"",
            "enabled": true
        },
        {
            "url": "https:\/\/mirror.cedia.org.ec\/malwaredomains\/immortal_domains.txt",
            "enabled": true
        },
        {
            "url": "https:\/\/mirror.cedia.org.ec\/malwaredomains\/justdomains",
            "enabled": true
        },
        {
            "url": "https:\/\/pgl.yoyo.org\/adservers\/serverlist.php?hostformat=hosts&showintro=0&mimetype=plaintext",
            "enabled": true
        },
        {
            "url": "https:\/\/raw.githubusercontent.com\/StevenBlack\/hosts\/master\/hosts",
            "enabled": true
        },
        {
            "url": "https:\/\/raw.githubusercontent.com\/jawz101\/MobileAdTrackers\/master\/hosts",
            "enabled": true
        },
        {
            "url": "https:\/\/raw.githubusercontent.com\/jerryn70\/GoodbyeAds\/master\/Extension\/GoodbyeAds-Xiaomi-Extension.txt",
            "enabled": false
        },
        {
            "url": "https:\/\/raw.githubusercontent.com\/jerryn70\/GoodbyeAds\/master\/Hosts\/GoodbyeAds.txt",
            "enabled": true
        },
        {
            "url": "https:\/\/someonewhocares.org\/hosts\/hosts",
            "enabled": true
        },
        {
            "url": "https:\/\/www.hostsfile.org\/Downloads\/hosts.txt",
            "enabled": true
        },
        {
            "url": "https:\/\/www.malwaredomainlist.com\/hostslist\/hosts.txt",
            "enabled": true
        }
    ],
    "blocked": [],
    "allowed": [],
    "redirected": []
}

**Comment by zgfg** [comment]
Originally reported on XDA, the frst part of
https://forum.xda-developers.com/showpost.php?p=82673863&postcount=14890

**Comment by PerfectSlayer** [comment]
Hello @zgfg 

Thanks for the bug report. It's something I thought previously but it didn't worth the cost at the time.
Since I hardened the hosts file parsing, it now takes more time to parse them. I just fix it in 48b10c2f.

**Comment by zgfg** [comment]
Thanks
