### ISSUE TITLE
"Ad-blocker VPN starting" forever

### ISSUE THREAD

**Issue by zgfg** [AdAway/AdAway#2069]
**Describe the bug**
From time to time I find the notification VPN Starting instead of VPN Active, although AdAway, VPN method works fine.
Eg, now, just few minutes after updating the hosts sources.

If I click to Pause and later Resume, notification changes properly to Active, but few hours later it will be likely Starting again

**To Reproduce**
Intermittently

**Expected behavior**
If VPN started successfully, it should show "Ad-blocker VPN active" 

**Screenshots**
![Screenshot_20200601_125540](https://user-images.githubusercontent.com/51943147/83403090-4dca0400-a408-11ea-8e35-b6938e6be199.jpg)
![Screenshot_20200601_125350_org adaway](https://user-images.githubusercontent.com/51943147/83403104-56223f00-a408-11ea-93f8-c67a831db490.jpg)

**Device**
 - AdAway version: 5.0.4
 - Device: Huawei Mate 9
 - Android version: 9
 - Root version: VPN mode, not rooted

**Comment by zgfg** [comment]
Intermittently, I even had two notifications:
Ad-blocker VPN starting
or
Ad-blocker VPN active
but also
Ad-blocker VPN reconnecting error

However, in that case VPN did not work - ads were leaking everywhere.

But opening AdAway main page, all looked normal.

To get it working I had to Pause and Resume. Once it came back Reconnecting error and I had to reboot the phone

Link to the report on XDA with the screenrecord:
https://forum.xda-developers.com/showpost.php?p=82671537&postcount=14886

**Comment by PerfectSlayer** [comment]
Hi @zgfg 

Can the fact it goes back to "starting" be linked to some network changes? (like data drop, switching to wifi?)
I will have a look at the "infinite starting state" but I could be nice if I found what triggers it first.

Regards

**Comment by zgfg** [comment]
With the latest 5.0.6 and 5.0.7 I usually have VPN Starting notification all day, but it works and I really don't pay attention (wrong notification but no problem).

Maybe only once or something during the last weeks I saw Reconnecting notification and AdAway did not work, I rebooted the phone and it was ok

All together, it's not critical

**Comment by PerfectSlayer** [comment]
No but it need some polish before the stale release 😉

**Comment by PerfectSlayer** [comment]
It might be related to #2154. I'm investigating the issue...
