### ISSUE TITLE
YouTube history not working

### ISSUE THREAD

**Issue by David46433** [AdAway/AdAway#2071]
Dear adaway team i have using YouTube vanced and adaway. YouTube vanced working normally without adaway when I enable adaway YouTube vanced not working properly eg..No view history and ads too. Please fix it thank you

**Comment by zgfg** [comment]
You need to white-list some URLs - they are blocked by the hosts sources you use, not by AdAway

Find the details what to white-list in XDA AdAway thread (search for YouTube)

**Comment by PerfectSlayer** [comment]
Hi @David46433 

It comes from the StevenBlack hosts source, one of the three default source of the AdAway.
You can whitelist `s.youtube.com` in order to get the history feature working.

Regards
