### ISSUE TITLE
Search in blocked domains will leave it empty

### ISSUE THREAD

**Issue by Sopor** [AdAway/AdAway#2072]
**Describe the bug**
After using search the list is totally empty

**To Reproduce**
1. Open Blocked
2. Press the magnification icon
3. Search (it should be a instant search but it isn't) and press enter
4. Press X to close search

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/5789283/83451958-171bda00-a458-11ea-964a-fc5a1f0dcfcf.png)

**Device**
 - AdAway version: 5.0.4
 - Device: Samsung S9+
 - Android version: 8.0
 - Root version: Magisk

**Additional context**
Add any other context like logcat about the problem here. Use adb logcat if you have developer settings enabled on your device or use any application like [MatLog](https://play.google.com/store/apps/details?id=com.pluscubed.matlog) to save logs. Include the crash report in the issue in a code block, a file attachment, or put it in a gist and provide link to that gist.

**Comment by zgfg** [comment]
Searching through Blocked list works for me just fine (also 5.0.4, rooted mode)
![Screenshot_2020-06-01-22-53-35-873_org adaway](https://user-images.githubusercontent.com/51943147/83453698-3cf6ae00-a45b-11ea-98c9-15be138a6ca9.jpg)

**Comment by Sopor** [comment]
Not for me. When i type there is no instant search and i need to press enter as i wrote above. So if i type something that won't get any match i get this empty list when i close search. To get it back i need to leave and re-enter the Blocked list.

@zgfg Do you have any domains you have added by yourself from the DNS logs?

**Comment by zgfg** [comment]
For the test I added www.cnn.com to the Blacklist - 1st screenshoot.
Search in Blacklist (all) - 2nd screenshoot.
Search in Blacklist (my manually blacklisted domains) - 3rd screenshot.
All screenshots ok.

Make sure you don't test while AdAway is updating (downloading and parsing) hosts sources - then the whole app is irresponsive, and sometimes I cannot even open Blacklist (shows empty) or cannot open my own Blacklist part, etc - but that is another, general issue with the app while updating hosts sources

![cnn1](https://user-images.githubusercontent.com/51943147/83485706-e6fc2780-a4a7-11ea-8275-2d37d0dfbed9.jpg)
![cnn2](https://user-images.githubusercontent.com/51943147/83485718-ee233580-a4a7-11ea-9e5e-73a66e19a7b4.jpg)
![cnn3](https://user-images.githubusercontent.com/51943147/83485739-f7140700-a4a7-11ea-85be-58ab191e9215.jpg)

**Comment by Sopor** [comment]
In that case that wasn't the reason for the issue.

**Comment by Sopor** [comment]
Here is a [video](https://gofile.io/d/3tj8gK) when i type in a word that doesn't exists and as you can see there is no instant search. I have to press the magnification glass on the keyboard and when i then empties the search the list is empty.
