### ISSUE TITLE
Menu only closes when using the back button

### ISSUE THREAD

**Issue by Sopor** [AdAway/AdAway#2073]
**Describe the bug**
When open the settings by pressing the hamburger menu i need to use the back button to close it. It should be closed when i press outside the menu.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Device**
 - AdAway version: 5.0.4
 - Device: Samsung S9+
 - Android version: 8.0
 - Root version: Magisk

**Additional context**
Add any other context like logcat about the problem here. Use adb logcat if you have developer settings enabled on your device or use any application like [MatLog](https://play.google.com/store/apps/details?id=com.pluscubed.matlog) to save logs. Include the crash report in the issue in a code block, a file attachment, or put it in a gist and provide link to that gist.

**Comment by PerfectSlayer** [comment]
Which menu are you talking about? There is no more hamburger menu in 5.x version.

**Comment by Sopor** [comment]
It looks like a hamburger menu but maybe that was wrong?

![image](https://user-images.githubusercontent.com/5789283/83878901-2000fa00-a73d-11ea-9b4b-1854e922b70b.png)

**Comment by PerfectSlayer** [comment]
This design comes from Google. It behaves as expected.
Not sure it will survive the beta though.
