### ISSUE TITLE
Fastlane metadata missing en-US directory

### ISSUE THREAD

**Issue by linsui** [AdAway/AdAway#2076]
**Describe the bug**
F-Droid use en-US as fallback which is missing. See https://gitlab.com/fdroid/fdroiddata/-/issues/1894#note_354171513 . Could you please rename or copy the en directory to en-US? Thanks!

**Comment by IzzySoft** [comment]
A symlink `en-US` pointing to `en` might suffice.

**Comment by PerfectSlayer** [comment]
Hello @linsui @IzzySoft 

Thanks for bringing the issue here to get my attention.

I made a PR which should fix the issue. I want Vankog to have a look at it before merging it. He's the one in charge of the Transifex thing and I don't want to mess up with it 😉

**Comment by Vankog** [comment]
Thanks for reaching out.

Unfortunately, just moving en to en_US (in general) does more harm than good.
The Android Localization fallback works better with a basic language in place, especially for Android <7 
(see https://developer.android.com/guide/topics/resources/multilingual-support )

It is better to add en-US as a variant.

**Comment by IzzySoft** [comment]
@Vankog that'd solve it as well of course. Though as I wrote, a simple symlink might do the job (and would meet both, as nothing would be "moved"). Whichever approach: as long as there's an `en-US`… :wink:

**Comment by Vankog** [comment]
en_US was added in Transifex and the pseudo-translations were pulled into the code.
The images and change log were moved to en_us exclusively, though. We don't have a process to translate these files (yet).

**Comment by Vankog** [comment]
@IzzySoft @linsui @PerfectSlayer 
What about the 4.3.4?

**Comment by IzzySoft** [comment]
If you could give some context, I might know what to answer. Is it an update that wasn't yet pulled by F-Droid? Have you checked the "[usual suspects](https://gitlab.com/snippets/1896503)"? According to metadata, 4.3.4 is the latest and recommended version, so it cannot be that (unless it was just updated and only the index is not yet published).

**Comment by Vankog** [comment]
4.3.4 is the current version of the stable version.
The changes were made in v. 5 though.
I have no clue from which branch/version/source F-Droid pulls the metadata from.

**Comment by linsui** [comment]
A new tag is needed.

**Comment by IzzySoft** [comment]
> I have no clue from which branch/version/source F-Droid pulls the metadata from.

That's easy to answer: from the one you put the tag on.

```yaml
AutoUpdateMode: Version v%v
UpdateCheckMode: Tags .*[0-9]$
CurrentVersion: 4.3.4
CurrentVersionCode: 40304
```

So it's the tags named `v<versionName>`, with `versionName` being pure numeric. Your v5 tags have a trailing `b` and are hence ignored. Apart from that, being marked pre-release, I guess you wouldn't want them declared "stable" for the average user, right?

**Comment by Vankog** [comment]
Thanks for the info.
One last question (I think):
Our latest stable version on F-Droid is 4.3.4, marked with an according tag in this repo.
Is there a way to create a new tag for F-Droid for the same app version 4.3.4 - and it's F-Droid entry - without having to build a new release? 

I mean, I aim to only adjust the metadata for the F-Droid entry of 4.3.4 (and above). This does not affect the app per se. I'd like to just change the information for the current app version there without having to build or supply a whole new release, creating an unnecessary entry on F-Droid. 
Is this possible?

**Comment by PerfectSlayer** [comment]
Okay, thanks to you all. I guess I will have to make a new stable version that bundles the metadata changes.

I would like to check the stable version includes all negative time bug fixes (another bug) before releasing it and my next two weekends are already full... I will see what I can do to make it happen faster.

**Comment by PerfectSlayer** [comment]
The [new stable version is up](https://github.com/AdAway/AdAway/releases/tag/v4.3.5). I will update XDA thread accordingly.
There was no more patch to include so it is just an update for the store.

Thanks again for your help 👍
