### ISSUE TITLE
Adaway can't start

### ISSUE THREAD

**Issue by zarathustra19** [AdAway/AdAway#2077]
i installed it and tried to enable but it wasn't able to start.

maybe it's unsuitable besides to Adguard ?

**Comment by zgfg** [comment]
How do you think it can be debugged and fixed if you don't dare to probide any information (as required when reporting a bug here)
- Which AdAway version
- Which phone
-Which Android version
- Which Magisk or other root version (in case of AdAway 5.0.x and if using VPN, not root, declare also)
- Do you mean it doesn't start after the phone reboot or it doesn't block ads (in which app or browser or what)

**Comment by PerfectSlayer** [comment]
Hello,

I'm closing the issue until we get more details.
Thanks for your help @zgfg 

Regards
