### ISSUE TITLE
Enlarged UI elements causing clipping and misalignment

### ISSUE THREAD

**Issue by djdelarosa25** [AdAway/AdAway#2078]
**Describe the bug**
UI elements are enlarged and do not fit properly on my device's screen (16:9, 1080p) causing text and icons to clip and be misaligned.

**Screenshots**
<img src="https://user-images.githubusercontent.com/34760155/83647141-28472100-a5e7-11ea-9cab-3202a384c335.png" width="480">
<img src="https://user-images.githubusercontent.com/34760155/83647386-693f3580-a5e7-11ea-9e6e-3a4f2c43034f.png" width="480">

**Device**
 - AdAway version: 5.0.4
 - Device: Motorola Moto Z Play
 - Android version: Android 8.0.0
 - Root version Magisk 20.4

**Comment by PerfectSlayer** [comment]
Hello @djdelarosa25 

The first screen is well a design issue. The second seems right 😅  (it's a design choice).
I got several reports abort this so I guess it doesn't not feel natural.

I am waiting for some help with the design for this version. I hope it will improve things.

**Comment by PerfectSlayer** [comment]
I did not receive help with design for now so I start fixing the issue by myself and there is some progress coming for the first screen.
