### ISSUE TITLE
AdAway randomly extends the list of User apps excluded for VPN

### ISSUE THREAD

**Issue by zgfg** [AdAway/AdAway#2079]
**Describe the bug**
AdAway 5.0.4, VPN mode (not root)

- exclude one User app
- close and reopen AdAway
- in addition to the app you have excluded, there will be one or two more apps excluded (selected by AdAway at random)
- deselect some of those
- close and reopen AdAway
- deselected apps will be selected/excluded again

To get rid of the mess, you must take Deselect all option

**Expected behavior**
AdAway must remember and exclude only and exactly those apps that were selected/excluded by user

**Device**
 - AdAway version: 5.0.4
 - Huawei Mate 9
 - Android version: 9
 - Root version: VPN mode, no root

**Comment by zgfg** [comment]
Reported also by another user:
https://forum.xda-developers.com/showpost.php?p=82746551&postcount=14943

**Comment by PerfectSlayer** [comment]
Hi @zgfg 

Thanks for the report. I fixed it with d300c28a6afe745a5d8ef7c437fb591ad3ef77c6

Regards
