### ISSUE TITLE
assembleDebug build error

### ISSUE THREAD

**Issue by gspeiliu** [AdAway/AdAway#2082]
I want to build a debug version to do some experiments. However, when I use the build command: ./gradlew assembleDebug to build, the build error occurs.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':tcpdump:generateJsonModelDebug'.
> Build command failed.
  Error while executing process /home/xxxxxx/Android/Sdk/ndk/21.0.6113669/ndk-build with arguments {NDK_PROJECT_PATH=
null APP_BUILD_SCRIPT=/home/xxxxxx/Downloads/BuildSystem/Repos/AdAway#AdAway/tcpdump/jni/Android.mk APP_ABI=armeabi-v
7a NDK_ALL_ABIS=armeabi-v7a NDK_DEBUG=1 APP_PLATFORM=android-26 NDK_OUT=/home/xxxxxx/Downloads/BuildSystem/Repos/AdAw
ay#AdAway/tcpdump/build/intermediates/ndkBuild/debug/obj NDK_LIBS_OUT=/home/xxxxxx/Downloads/BuildSystem/Repos/AdAway
#AdAway/tcpdump/build/intermediates/ndkBuild/debug/lib APP_SHORT_COMMANDS=false LOCAL_SHORT_COMMANDS=false -B -n}
/home/xxxxxx/Android/Sdk/ndk/21.0.6113669/build/core/gdb.mk:33: *** missing separator.  Stop.

OS: Ubuntu 18.04.4 LTS with the latest Android Studio Linux.

**Comment by PerfectSlayer** [comment]
Hello @gspeiliu 

There is something surprising in your log. You seem to use NDK 21.0.x version where the build script requires 21.2.6472646 version. It might be an issue.

https://github.com/AdAway/AdAway/blob/b22f9e60adc1306c90d34fdb398890f8d639d7d4/tcpdump/build.gradle#L12
