### ISSUE TITLE
Adaway automatically disabled

### ISSUE THREAD

**Issue by sircode** [AdAway/AdAway#2083]
**Describe the bug**
On my new ZTE V10, Android 9, Adaway 4, latest, enabling is already a problem.
Everytime I want to enable, it says "Symbolic link missing". Responding with "Yes"  and enabling again, it shows "enabled".

But after a while, just while using my phone, it will automatically be disabled again.

Other way to reproduce the issue: if I click "show hosts file" I see the correct generated list, when I click back on my phone keys, I see "Symbolic link missing" again and have to follow the above process again.

Similar with Adaway 5. After a while it is automatically disabled.

Info: although my phone is rooted, it seems that it won't allow write access to all system files like hosts.

So this may cause the problem, since Adaway works perfectly on my other phones like Xiaomi A1.

**Comment by PerfectSlayer** [comment]
Hello @sircode 

Quick question, are you using Magisk?
If yes, did you enable the systemless hosts mod? It should allow you to write the hosts file.

If it's enabled and you already rebooted, there might be an issue with the app settings (like the target of the hosts file).

**Comment by sircode** [comment]
Thx!
 I thought I had enabled it. I also had a custom target hosts file, since
 /system/etc/hosts seem not writable.

Now, I made sure seemless hosts is enabled, rebooted, changed preferences hosts location to /system/etc/hosts.

And now adaway seems to work! No more "missing" message. It also seems to block properly for the first time. Great!
Thx again!

**Comment by PerfectSlayer** [comment]
You're welcome!
