### ISSUE TITLE
[YouTube] compatibility report

### ISSUE THREAD

**Issue by SahilLangoo** [AdAway/AdAway#2104]
**Describe the third party app**
 - Name: [YouTube / YouTube Vanced]
 - Version: [15.24]

**Describe the compabitily issue**
(Adaway On) While watching YouTube Watch history isn't recorded ; resume from last position is also broken and still shows advertisements (on official app) after disabling adaway it works fine.
Please tell or add domains to wishlist ?

**Workaround**
If applicable, describe the whitelist domains to add to fix the issue:

**Comment by PerfectSlayer** [comment]
Hello @SahilLangoo 

It's due to one of your source that include `s.youtube.com`. See #665

Regards

**Comment by PerfectSlayer** [comment]
Hello @SahilLangoo 

It's due to one of your source that include `s.youtube.com`. See #665

Regards

**Comment by SahilLangoo** [comment]
Fixed after v5.0.5 is released 
Now working fine !
