### ISSUE TITLE
Ignoring source selection

### ISSUE THREAD

**Issue by shack-32** [AdAway/AdAway#2105]
The latest version (5.0.4) on the release page seems to not allow you to control which sources are enabled or not.

When you toggle to disable, it asks you to apply, after clicking that the source gets enabled again. The previous version 5.0.3 works correctly.

**Comment by PerfectSlayer** [comment]
Hello @shack-32 

Yes, it's a known bug that I fixed here: 2dee2418e5db250efc2cb31fbc691020d7562a8f
You can download the latest beta to get the fix 😉 

Regards
