### ISSUE TITLE
Doubt version 5 and suggestion of new host

### ISSUE THREAD

**Issue by gallegonovato** [AdAway/AdAway#2106]
Good afternoon folks @PerfectSlayer @jawz101:

I wanted to ask you a question.  Do you know what version of adaway 5 will be compatible with?

And then I don't know if you can help me change a host I have.  The link is https://www.malwaredomainlist.com/hostslist/hosts.txt I don't know if you can advise me a different and good one to put in its place?

I take this opportunity to ask you how you can collaborate with the project.  Either with translations, or what can help?  Also I do not know if there is a way to make an economic collaboration.  But instead of being every month once.  Since I would like to promote the project.

A hug and thanks for your help and time.

**Comment by Vankog** [comment]
Hi,

1. What do you mean with version? Android version?
1. For hosts file recommendations: 
You could use our own, that comes with AdAway (see https://github.com/AdAway/adaway.github.io) 
and check the XDA forum thread: https://forum.xda-developers.com/showthread.php?t=2190753
1. Collaboration is easy ([the contributing guide](CONTRIBUTING.md)):
   1. Either provide changes to the code of this repository via Pull Requests. 
Maybe creating something proactively, or fixing an issue or request etc. (See Issues tab)
   1. Or by helping out in the community. 
Commenting or moderating Issues and Pull Requests or helping in the forum etc.
   1. Or by translating the app. For information about that, please see [the translating guide](TRANSLATING.md)
1. one-time donations are also possible. see [the readme](README.md) for details. (Paypal, Bitcoin)

**Comment by gallegonovato** [comment]
Good afternoon.



First of all thank you very much for your help and time.



I will look at the links you mention.



I was referring to version 5. The final version when released will ask for the minimum to work.  I currently have lineageos 15.1 (I think it would be 8.1.0 android) with root and latest version of Magisk.



I take this opportunity to ask a last question, if you allow me.  Yesterday I downloaded version 4.3.5 and when I installed it from scratch, before loading my backup of Adaway.  I noticed that there are now these hosts at the source:



https://adaway.org/hosts.txt



https://pgl.yoyo.org/adservers/serverlist.php?hostformat=hosts&showintro=0&mimetype=plaintext



https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts



The old Adaway fonts that I brought in earlier versions.  Will they still work in the other new versions?  Mostly:



https://hosts-file.net/ad_servers.txt



Because this host source.  Is the only one that comes out right below me, instead of coming out in Spanish updated for x time.  It says in english installed x hours ago.



That's why I don't know if you can tell me what will be left of the host or if I can leave the old ones I have in my backup?



A hug

**Comment by Vankog** [comment]
I, personally, am not sure about the version. So I cannot answer you for sure.

You can definitely use the new host files, provided by AdAway.

Unfortunately, https://hosts-file.net/ad_servers.txt is not online any more and thus, AdAway won't be able to load it.

**Comment by gallegonovato** [comment]
Good afternoon @Vankog 



First of all, thank you very much for your help and time.



So that old host I was telling you about, I can erase it.  I understand that it won't work for Adaway version 5 when it comes out either.



And any other old host on Adaway that had the old versions and no longer works.  I apologize for this question but I have everything in the backup and now I don't remember which one had the previous versions of Adaway and which one I put.



Thank you very much for all your help and time.  And sorry for the inconvenience.

**Comment by gallegonovato** [comment]
Good afternoon @Vankog @PerfectSlayer 



I would also like to ask if:



https://someonewhocares.org/hosts/hosts and https://someonewhocares.org/hosts/zero/hosts are the same except that the first is 127.0.0.1 and the second is 0.0.0.0. Can I remove the first and leave the first?.  These that came in adaway



A hug
