### ISSUE TITLE
Missing Storage permission for local Hosts source files

### ISSUE THREAD

**Issue by zgfg** [AdAway/AdAway#2131]
**Describe the bug**
In v5.0.3 Storage Permission was supported:
![400027400120_233783](https://user-images.githubusercontent.com/51943147/87670294-c80fd700-c76f-11ea-96fd-828d37b49b32.jpg)
With that, user was able to add his local hosts source file from Internal memory, e.g. /Download/mysource.txt to the Hosts sources list as file:///sdcard/Download/mysource.txt:
![Screenshot_20200716_142435_org adaway](https://user-images.githubusercontent.com/51943147/87671079-05c12f80-c771-11ea-946d-96da0b55e3bb.jpg)

However, in v5.0.5, Storage permission is removed:
![Screenshot_20200716_134108_com google android packageinstaller](https://user-images.githubusercontent.com/51943147/87669857-fd67f500-c76e-11ea-9139-edab45805fba.jpg)
and if you add your local file to the List, it fails to Apply the new configuration:
![Screenshot_20200716_134300_org adaway](https://user-images.githubusercontent.com/51943147/87669669-b11cb500-c76e-11ea-90c8-ff5b0dba0548.jpg)

**Expected behavior**
User should be able to add his local hosts source file to the List.
Popup says that file:// URL type is supported

**Device**
 - AdAway version: v5.0.5
 - Xiaomi Mi 9T, Huawei Mate 9
 - Android version: 9, 10
 - Magisk Canary, VPN

**Comment by PerfectSlayer** [comment]
Hi @zgfg !

I just read the XDA thread... I will need to have a deeper look about the whole storage documentation to find a way to fix it.
May be it's time to improve the UI to select host file and create a dedicated folder for the app on external storage.
I will try to avoid to ask for the whole storage read permission if I can.


Thanks for the issue anyway! 😉

**Comment by zgfg** [comment]
> Hi @zgfg !
> 
> I just read the XDA thread... I will need to have a deeper look about the whole storage documentation to find a way to fix it.
> May be it's time to improve the UI to select host file and create a dedicated folder for the app on external storage.
> I will try to avoid to ask for the whole storage read permission if I can.
> 
> Thanks for the issue anyway!

You can check how DNS66 does - it takes Storage permission but uses contemt:// type.

Then user can navigate with file explorer to the file.
But in XDA I have commented an issue with that approach:
I have stock Files and MiXPlorer.
DNS66 gives me an option to select file explorer, if I take MiXPlorer, DNS66 would not be able to open its URL (URL is different than if I navigate with stock Files)

**Comment by PerfectSlayer** [comment]
Hum.. Will try an implementation based on [SAF](https://developer.android.com/training/data-storage/shared/documents-files) as[ it's the recommended way to do it](https://developer.android.com/training/data-storage).

_Note for myself:_ Here is [how to persist the permission](https://developer.android.com/training/data-storage/shared/documents-files#persist-permissions). Need to find when call it (I guess in the `onActivityResult`).

**Comment by PerfectSlayer** [comment]
I started to rewrote the UI to add and edit source. No more long press action the source list. A simple click will open the UI.

It looks like this for now:

![image](https://user-images.githubusercontent.com/1766222/87876855-14128400-c9db-11ea-9caa-c835f1ca6452.png)
![image](https://user-images.githubusercontent.com/1766222/87876860-1ffe4600-c9db-11ea-8dba-70b2bea76b05.png)

The source list will also receive an update to display label and entry size.

**Comment by zgfg** [comment]
Nice, thanks, pls post also screenstot for File when ready

**Comment by PerfectSlayer** [comment]
Nothing fancy here:

![image](https://user-images.githubusercontent.com/1766222/87978754-38e92300-cad1-11ea-86f6-ebe33191f441.png)

Typing the "File" button or the content URL open the document picker to select a custom host file from any Document provider (maybe it could work with GDrive 😏 )

**Comment by zgfg** [comment]
Please test how the content provider works if you have more than one File manager (e.g., stock Files and MiXYPlorer)

Then try to navigate to the file by one or another File manager and check if upon reboot, AdAway still correctly reads the local hosts file

**Comment by PerfectSlayer** [comment]
Don't worry @zgfg You can test it as soon as it gets ready 😉 
I setup automatic builds on github commit so you can grab an apk and test it when you want.

(sadly not right now as I'm waiting for the weekly GitHub update to get the latest Android build tool version to fix the build...)

**Comment by PerfectSlayer** [comment]
A WIP screenshot of the new source screen

![image](https://user-images.githubusercontent.com/1766222/89096687-c2092f80-d3d8-11ea-8379-84bf843975fd.png)

Sources now have a title (easier to understand who's who) and URL is display on two lines to read them easily.
I am not really satisfied with the whole result but it's a WIP after all...

**Comment by PerfectSlayer** [comment]
The features is now complete and merge to master branch.
It will be shipped in the next beta.

And good news, it also works fine with other content providers like Google drive. So you can store, backup and share some hosts file in gdrive and use them in AdAway 👍
