### ISSUE TITLE
NordVPN compatibility report

### ISSUE THREAD

**Issue by lohmobius** [AdAway/AdAway#2135]
**Describe the third party app**
 - Name: NordVPN
 - Version: 4.13.2

**Describe the compabitily issue**
NordVPN App gets stuck on initial splash screen.  Does not proceed after any length of time.
Using Sesame Shortcuts, am able to connect via quick connect long press.  This skips splash screen and loads main app.  Does not work if not already logged into app.

**Workaround**
None Known, except as descried above.  Not intended workaround though.

**Comment by Frencisis** [comment]
Maybe I've found a solution:
Go to adaway LOG DNS and enable the V (turned to red) to this voices:
launchers.appsflyer.com

This is worked to me with adaway 4.3.5 and NordVPN 4.13.2

**Comment by lohmobius** [comment]
I have found a workaround:
Install the NordVPN app (v4.13.2+sideload) from their website rather than the play store.  It works with no other issues/configuration.



> Maybe I've found a solution:
> Go to adaway LOG DNS and enable the V (turned to red) to this voices:
> launchers.appsflyer.com
> 
> This is worked to me with adaway 4.3.5 and NordVPN 4.13.2

Cannot seem to test as even when reusing play store version (4.13.2).  Works with no workaround required and nothing whitelisted.
