### ISSUE TITLE
Previously used sources will not download if they are still up-to-date

### ISSUE THREAD

**Issue by ipdev99** [AdAway/AdAway#2137]
AdAway will not download a hosts source if it was used previously and still current.
I know this is intended so selected hosts sources are not downloaded and parsed each and every time.
If you deselect a source it should clear the cached info also?

If you deselect a hosts source, the entries will be removed when the blocking list is regenerated.
If you then select the same source and generate a blocking list, AdAway will add the source info to the header of the hosts file but no entries since the source is not downloaded.

Same results on Root mode (hosts file) and VPN mode.

Steps to reproduce.
- Select a hosts source and generate a blocking list.
- Deselect the hosts source and generate a blocking list.
- Select the hosts source and generate a blocking list.

Work-a-round to be able to use the source again.
- Wait until the hosts source is updated.
- Clear app data for AdAway and run though the setup and configuration.
- Delete and add the hosts source to the list.

AdAway version 5.0.5
Android 10 (SDK29)
VPN mode on Pixel 3aXL
Root mode on Nexus 7 (2013) WiFi

Attached files.
Starting from a clean reset of AdAway and deselecting all the hosts sources results with 1-hosts.
Then just selecting adaway.org source results with 2-hosts.
Deleting the adaway.org source and adding it back results with 3-hosts.
[1-hosts.txt](https://github.com/AdAway/AdAway/files/4976096/1-hosts.txt)
[2-hosts.txt](https://github.com/AdAway/AdAway/files/4976097/2-hosts.txt)
[3-hosts.txt](https://github.com/AdAway/AdAway/files/4976098/3-hosts.txt)

**Comment by PerfectSlayer** [comment]
Hello @ipdev99 !

I will have a look at it. I think it's the same issue you talked here: https://forum.xda-developers.com/showpost.php?p=83134171&postcount=15135

**Comment by PerfectSlayer** [comment]
Thanks for the detailed bug report.
I can easily spot the bug and fix it.

It should be fixed in the next release 😉 
Regards

**Comment by ipdev99** [comment]
Hi.
Yes it was the same issue I mentioned on xda.
Sorry it took a few dayss before I had time to test and reproduce it so I could actually open an issue.

Happy to see it was a easy fix.

Cheers.
