### ISSUE TITLE
Crash on check-button to enable/disable an Allowed URL

### ISSUE THREAD

**Issue by zgfg** [AdAway/AdAway#2140]
**Describe the bug**
AdAway v5.0.5 (hosts/root) keeps crashing every time I change the check-button enable/disable state for a domain in my Allow list

**Screenshots**
![IMG_20200729_131415](https://user-images.githubusercontent.com/51943147/88793849-c85f9780-d19d-11ea-8a4b-3f77e0fb1c18.jpg)
![Screenshot_2020-07-29-13-14-42-928_org adaway](https://user-images.githubusercontent.com/51943147/88793865-cdbce200-d19d-11ea-930f-928b43fa8936.jpg)

**Device**
 - AdAway version: 5.0.5
 - Device: Xiaomi Mi 9T
 - Android version: MIUI 11/Android 10
 - Root version: Magisk Canary 20419

**Comment by PerfectSlayer** [comment]
Hi @zgfg 

I will have a look at it.
I just past your comment from XDA to remember the steps:

 - add an item like www.googleadservices.com, Allow to change configuration
- disable check-button for that domain, AdAway immediately crashes for me
- reopen AdAway and its Allow list, domain is now properly disabled, enable it and AdAway will crash again
- and so on

**Comment by PerfectSlayer** [comment]
Thanks for the report. I just fix it.
Too bad I didn't see it earlier 😞 

It should be shipped in the next version.
Regards

**Comment by zgfg** [comment]
Thanks, v5.0.5 was long out but we didn't see it yet  I was trying something else and as side-effect observed crashes, finding they are reproducible
