### ISSUE TITLE
Symlink creation failed

### ISSUE THREAD

**Issue by ralphSQ** [AdAway/AdAway#2180]
**Describe the bug**
I get "Symlink creation failed" when trying to enable ad blocking.

Did the instructions on the help > S-ON/S-OFF section, and got this error:
`OnePlus8:/ # ln -s /data/data/hosts /system/etc/hosts
ln -s /data/data/hosts /system/etc/hosts
ln: cannot create symbolic link from '/data/data/hosts' to '/system/etc/hosts': File exists`

**To Reproduce**
1. Go to 'Home'
2. Click on 'Enable Ad-Blocking'
3. Symlink Missing will pop up, asking Do you want to try creating a symlink?
4. Click 'Yes'

**Expected behavior**
The ad blocking should be enabled

**Screenshots**

**Device**
 - AdAway version: 4.3.6
 - Device: Oneplus 8 IN2013
 - Android version: 10.5.9
 - Root version Magisk 20.4

**Comment by PerfectSlayer** [comment]
Hello @ralphSQ 

If you are using Magisk, enable the systemless hosts module then restart.
You should not need anything else (no need to create a symlink).

Regads

**Comment by ralphSQ** [comment]
Hi @PerfectSlayer 

That did the trick.

Thanks
