### ISSUE TITLE
Youtube history 

### ISSUE THREAD

**Issue by Pikachuu1122** [AdAway/AdAway#2197]
On this latest adaway update 5.0.8 YouTube history not updating. Is there anyway i can block youtube from adaway??

**Comment by Sego1234** [comment]
Hello, I will try to reproduce this issue and tell you how to fix it.

**Comment by Sego1234** [comment]
Hello, it is me again. I have found a fix for your issue.

1. Open AdAway
2. Open the burger menu in the top left.
3. Tap Hosts Sources.
4. Uncheck https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts
5. Tap on the + button on the bottom right corner.
6. Add https://raw.githubusercontent.com/Sego1234/Modified-StevenBlack-host/master/hosts.txt
7. Done!

**Comment by Pikachuu1122** [comment]
Wow thanks its working fine now 👍
