### ISSUE TITLE
[Suggestion] Enable / Disable hosts block with Quick Setting Tile

### ISSUE THREAD

**Issue by gwolf2u** [AdAway/AdAway#2198]
Just an idea (suggestion)
Used AdGuard for a while and got used to enabling/disabling block of ads with help of QS tile
Would be nice to see this also implemented here

Feel free to close this if no interest in developing this as this is not actually an issue, and I do understand that GitHub is not intended as a feedback platform

**Comment by hackbot1337** [comment]
i was going to suggest this . i use amazon often and am just annoyed at having to toggle adaway off so that i can use the amazon app. please add a pause tile.

**Comment by PerfectSlayer** [comment]
Hi all,

It feels like a good idea since the V5 is able to quickly pause / resume adblocking.
I don't have any idea how to do it yet and I need to do some research first.

If anyone have API or related documentation, feel free to post links here :wink:

**Comment by DorCoMaNdO** [comment]
I'd like to suggest an Android 11 power tile too, since A11 reduced the amount of QS tiles displayed due to media controls, so now only two rows of 3 tiles display rather than 3, my 2 pages of tiles became 3 and it's pretty cumbersome to use now for something that is meant to be quick.

**Comment by PerfectSlayer** [comment]
QS Tile was implemented. I'm closing the issue :)
