### ISSUE TITLE
Upgrade from 4.xx to 5.xx breaks all lists

### ISSUE THREAD

**Issue by auanasgheps** [AdAway/AdAway#2203]
**Describe the bug**
Hello,
The other day I manually upgraded from 4.3.6 (not 100% sure) to 5.0.8.
At first glance seemed that lists have been migrated, but they are just broken place holders as you can see from screenshots below.
In fact this ultimately breaks ad-blocking.

Are you aware of this issue?

**To Reproduce**
1. Run version 4.3.x 
2. Manually install 5.0.8
3. Open lists and observe they are broken

**Expected behavior**
Lists should exists and be functional.

**Screenshots**
![Screenshot_20200907-153531_AdAway](https://user-images.githubusercontent.com/20586878/92393652-7d338f80-f120-11ea-9400-1308361ada88.jpg)
![Screenshot_20200907-153540_AdAway](https://user-images.githubusercontent.com/20586878/92393654-7e64bc80-f120-11ea-8246-210344a69da0.jpg)
![Screenshot_20200907-153844_AdAway](https://user-images.githubusercontent.com/20586878/92393655-7e64bc80-f120-11ea-8ba9-979d323f09fd.jpg)

**Device**
 - AdAway version: 5.0.8
 - Device: Galaxy S9+
 - Android version: 10
 - Root version Magisk 20.4

**Comment by PerfectSlayer** [comment]
Hi @auanasgheps 

Thanks for your report! 
It seems there is obviously an issue. I will have a look at it to reproduce it and look how to fix it.

**Comment by PerfectSlayer** [comment]
I had a quick look at it. It doesn't seems it's related to the migration itself but it is rather a bug with the new UI.
The source type is wrong and it causes some issues if you validate the edit UI.

Could you confirm the _only_ issue you had was the source type was wrong, leading to corrupted sources and maybe no more ad-blocking?

**Comment by PerfectSlayer** [comment]
Oh, there might have an issue with dates too?
I can't translate date / duration in from your language but I guess they are wrong after migration?

**Comment by auanasgheps** [comment]
> Could you confirm the only issue you had was the source type was wrong, leading to corrupted sources and maybe no more ad-blocking?

The source type is wrong, leading to not load the source because it does not think is a link but a file, which does not exist. No ad-blocking at all since all sources are in this situation and the host file is empty. 

> Oh, there might have an issue with dates too?
I can't translate date / duration in from your language but I guess they are wrong after migration?

I am using the app in Italian (which I have partially translated too) and the date format is the European standard DD-MM-YYYY, but I can't see the date you are referring to

**Comment by PerfectSlayer** [comment]
Actually, the empty hosts file is another issue I also solved.
The source type is _just_ a visual bug.

All fixes will be shipped in the next beta 😉 
Thanks for your report!
