### ISSUE TITLE
Virust Total detects virus in apks from F-Droid and Github

### ISSUE THREAD

**Issue by cb474** [AdAway/AdAway#2209]
I downloaded the most recent release from Adaway's Github site, 5.0.8, ran it through Virustotal, and one virus scanner, Tencent, detects a virus it calls "A.gray.andrsca.f."

https://www.virustotal.com/gui/file/26144826ea2700d592540614159bf4ab4e824689a77bc27b0f0b6d063937edd1/detection

Then I tried the latest apk on F-Droid, and Tencent also detected a virus engine, it labeled, "A.gray.adaway."

https://www.virustotal.com/gui/file/0912cf9be553658559e7a624f4897b148829d5f94fc4e1f98d46306598379910/detection

What's going on here?

I see that someone posted a similar issue in 2017 and it was closed without explanation.

https://github.com/AdAway/AdAway/issues/865

**Comment by PerfectSlayer** [comment]
Got no idea. I guess it is a wrong positive due to the adware signature the app bundle.

You have the source code, the changelog and the build procedure. Build the app from yourself or grab one of the automatic build if you don't trust the release.

But what happens to the APK name? _AdAway-v5.0.8-208030[Premium-Final].apk_ seems shady... And 5.0.8 is not released on F-Droid...

**Comment by cb474** [comment]
I tested 4.3.6 from F-droid. You can see that in the second Virustotal link.

I don't know why Virustotal changed the name of the 5.0.8 apk. It did something similar with the 4.3.6 apk label also. I just downloaded the apks from github and F-Droid and tested them on Virustotal. The files I downloaded have the names as they are shown on github and F-Droid. Perhaps the label change has something to do with the how the apk was packaged.

I found this dicussion of what sounds like a similar issue, where the software being used to build the apk may have been creating the issue:

https://groups.google.com/forum/#!topic/mitappinventortest/GcVB5DfDLx0

I don't really have the skills to review the source code myself. I'm not a developer. I would assume Adaway would prefer to solve the issue and not have Virustotal saying Adaway has malware in it. It does seem like it could be an issue with how the apk is built.

I tried some other apk's from F-Droid (Blokada, AdGuard, DNS66) and they don't have this issue. Also Virustotal does not see the name of the apk as different from how the file is labeled. 

So both things, the malware detection and the name difference, do seem to be something about the Adaway apk and how it's built.

**Comment by PerfectSlayer** [comment]
There is nothing I can do to please Virus Total and its underlying antiviruses. It's not the first time (see [this XDA post](https://forum.xda-developers.com/showthread.php?p=71136023#post71136023)) and AV is labeling AdAway as grey app (it creates a dedicated category: _A.grey.adaway_).

I can't do more than: 
- Disclosing the whole source code,
- Using trusted build server to provide hosting and binary

For the record, the GitHub apk is built and signed by myself on my personal computer. The F-Droid apk is built and signed by F-Droid build servers.

**Comment by cb474** [comment]
Thanks for your replies.

I guess I'm still wondering why AdAway is detected as having malware in it and not the other apks I mentioned, which were also downloaded from F-Droid (and which I assume were also build by F-Droid's servers). As an experiment, I also randomly downloaded a few other apps from F-Droid and none of them are detected by Virustotal as containing malware. So it seems like something about AdAway is triggering this.

**Comment by eebssk1** [comment]
The app(ver 5.0.9) even failed to install in the Tencent Habo™ generic safety analyze system.Which means we can't know what exactly they are checking.
useless result: https://habo.qq.com/file/showdetail?md5=70e81a88ff32e9970e14368f9e37e499&pk=ADcGYl1rB24IP1s5U2o%3D
It shows yellow 'no dangers found' just because failed to install,should be green 'safe' if no issues.

**Comment by PerfectSlayer** [comment]
Agreed, antivirus results are not helping to understand the issue...
