### ISSUE TITLE
Suggest:Always use magisk if available

### ISSUE THREAD

**Issue by eebssk1** [AdAway/AdAway#2211]
Since the host install path is now auto determind, Users can't set a static path to install the host file.I suggest always install host to magisk host module whether the module is active or not.Add a choice for users to chose what path is preferred is also a good way.
The reason(for me) is I want my system to be clean and avoid any direct mod from any application.When the module is disabled,adaway will install host to system directly and my system is RW-able and then system is 'polluted'.
This may also solve some issues when system is  writable but any direct mod will let the system unable to boot for some reason.

_Sorry for my trash english,just ask if you can not understand_

**Comment by PerfectSlayer** [comment]
Hi @eebssk1,

First, rooting Android device does not always imply Magisk. Some ROM have built-in root, some have eng variant, etc... Moreover, I am not sure all Magisk installations support modules.

I agree that modifying system partition could cause issues on some devices (few won't even boot) but setting a path to install hosts file (as the 4.x version does) always cause issues as most of users don't read docs/understand the consequence.

So for the V5, I end up with a simpler solution: always write in /system/etc/hosts and let root users handle their custom setup or use Magisk and its built-in systemless hosts module.

I have few users requesting for a "light Adaway": a simple app to download hosts files and merge them somewhere in the device file system. I think this is more the kind of feature you are looking for than a system ad-blocker 😅 

Regards

**Comment by eebssk1** [comment]
Well I think the feature you just say should suitable for such situation.But that's no need to separate to  two apps,you can just hide such feature in Adaway somewhere and only some special action can unhide them.
Or you can add it as alternative function in app that tell user it won't modify system and users need to care the rest things.
Also there's nothing powerful than a forced 5sec full screen warning that tell user how it do and if user can't understand then just quit.

(Fun fact,I'm quietly shocked when i find that v5 doesn't have custom install path at first.Which end up to search github and this issue)

_My english is worse for long paragrah_

**Comment by PerfectSlayer** [comment]
Making a « configurable » UI is even harder than making a successful UI. And I'm not that good at making good UI. Make a new UI, plug it to the current engine and remove anything else (web server, vpn, tcpdump) is definitely simpler!

> Also there's nothing powerful than a forced 5sec full screen warning that tell user how it do and if user can't understand then just quit.
That is not why people call a good UI. You can be sure I will get complains about it! From "power" users who don't care about warnings for "noobs" and "noobs" users who just want something that work and don't want to read too much text.

**Comment by eebssk1** [comment]
Closed due to inactivity (historitic issues cleanup).

//Current design is suitable for me at least.
