### ISSUE TITLE
[Amazon app] compatibility report

### ISSUE THREAD

**Issue by yazeed0o0** [AdAway/AdAway#2212]
**I need to have a way to make this app not block from Amazon because the app doesn't work if enabled**
 - Name: [e.g. WhatsApp]
 - Version: [Latest]

**Describe the compabitily issue**

**Workaround**
If applicable, describe the whitelist domains to add to fix the issue:
 - www.somedomain.com
 - *.server.org
Please add tag `workaround-available` if a work around is available.

**Comment by PerfectSlayer** [comment]
See #2066
