### ISSUE TITLE
If you have a hosts source link to just https:// adaway will crash when trying to download hosts sources.

### ISSUE THREAD

**Issue by ipdev99** [AdAway/AdAway#2238]
With a bad, dead or invalid hosts source.
AdAway will generally ignore the source and still download sources.

If you have a link to just content:// adaway will give a pop-up message when trying to download hosts sources.
"Failed to download hosts source"

If you have a link to just https:// adaway will crash when trying to download hosts sources.

This is not a big issue but, someone could accidentally create a https:// link when adding or editing a hosts source.

When you add or edit a hosts source, it requires a label and URL entered to save it.
The label is blank so you need to enter something there.
The URL is preset with https:// and that is enough to save the source.

Someone new to adding hosts source links might not notice and add the URL to the label field and save.
Someone updating from an older version that allowed http links.
- When you open (edit) a hosts source, the http:// link (or any invalid link) will be replaced by just https:// 

To reproduce crash:
Open AdAway

Choose hosts list
Add a hosts source and just enter something in the label field and save.
Apply change. (or download sources)

To reproduce pop-up message:
Open AdAway
Choose hosts list
Add a hosts source and enter something in the name field
Replace https:// with content:// in the URL field and save.
Replace https:// with https://a in the URL field and save.
Apply change. (or download sources)

First idea was to remove the preset https:// from the URL field but, that would only fix part of it.
The user could still enter https:// or content:// and then save it.

There only has to be one character after the https:// to make it an invalid link and ignored when downloading sources.
Could the validation check be updated to make sure there is at least one character after https://

Manually adding a content:// link will still fail regardless unless it points to an actual file.
This would still pass the verification check but, a bad content link fails with an error pop-up and does not crash the app.
[logcat.log](https://github.com/AdAway/AdAway/files/5296138/logcat.log)
![Screenshot_20200928-213018_AdAway](https://user-images.githubusercontent.com/18606268/94508499-b8812580-01d7-11eb-9230-3d36a084a01b.png)
![Screenshot_20200928-213030_AdAway](https://user-images.githubusercontent.com/18606268/94508500-b8812580-01d7-11eb-9b24-1f7c0a165b12.png)
![Screenshot_20200928-213043_AdAway](https://user-images.githubusercontent.com/18606268/94508501-b919bc00-01d7-11eb-96de-0c0dd6f1ce24.png)
![Screenshot_20200928-213157_AdAway](https://user-images.githubusercontent.com/18606268/94508502-b919bc00-01d7-11eb-92fb-c57e9f99c391.png)
![Screenshot_20200928-213229_AdAway](https://user-images.githubusercontent.com/18606268/94508503-b919bc00-01d7-11eb-982e-9f3ca6e730bd.png)
![Screenshot_20200928-213257_AdAway](https://user-images.githubusercontent.com/18606268/94508506-b9b25280-01d7-11eb-8ea3-c10574ff9b84.png)

**Comment by zgfg** [comment]
IMO, app should use the same/unified function for hosts source link validation if imported by json or entered through UI (then, there will be no differences/surprises, yet undetected cases)

**Comment by PerfectSlayer** [comment]
Hi @zgfg 

I had a quick look to the multiple issues. I agree new users can confuse label and url so better fix this issue.

First, I was surprise you could create a source with only an `https://` url. I run some tests in the debugger then I found the culprit:
![image](https://user-images.githubusercontent.com/1766222/94985128-0ab5a400-0554-11eb-878e-ebb8751f38ba.png)
I will add a dedicated check for this value to not be allowed.

Then, I will also validate the source URL while importing backup.
I will keep you posted 😉

**Comment by PerfectSlayer** [comment]
That should be fixed and import was improved.

Thanks!

**Comment by zgfg** [comment]
PerfectSlayer - perfect👍
