### ISSUE TITLE
[Request] Add pulldown bar quick toggle to quickly switch adaway on and off

### ISSUE THREAD

**Issue by oathzed** [AdAway/AdAway#2241]
Can you please add a quick toggle, adguard has one and its super handy for when you need to quickly turn it off for a page that's not handling adaway well. Thanks!

![Screenshot_20201007-122444~2](https://user-images.githubusercontent.com/52545913/95378855-5f7d5580-0899-11eb-829c-5be52a0a803b.png)

**Comment by PerfectSlayer** [comment]
Hi @oathzed 

Thanks for the idea. Let's track it here #2198 

Regards
