### ISSUE TITLE
Amazon app sign-in

### ISSUE THREAD

**Issue by TheOnlyYandere** [AdAway/AdAway#2242]
It doesn't allow me to sign in on the Amazon app. If you are signed in, you'll just have an error page.
Version 5.0.9

**Comment by Matakor** [comment]
Having the same problem in 5.0.10.

Didn't have this issue with the 4.x versions, so not sure what changed.

**Comment by Matakor** [comment]
Should also note that with the latest 4.x version, it's not blocking ads in the Amazon store app (not appstore).

**Comment by PerfectSlayer** [comment]
Could you check the solution here if it works for you? #2066
