### ISSUE TITLE
android 11 certificate issue

### ISSUE THREAD

**Issue by mradzkii** [AdAway/AdAway#2246]
unable to get the webserver certificate to install on android 11. adaway 5.0.9.

![Screenshot_20201010-230600](https://user-images.githubusercontent.com/38789311/95666000-5ddbb800-0b4d-11eb-931b-319f8dc9f2dc.jpg)

no option to manually install or export the certificate

**Comment by PerfectSlayer** [comment]
Hello @mradzkii 

I just release a new beta to fix this issue. Have a look here: https://github.com/AdAway/AdAway/releases/tag/v5.0.10b :wink: 

Regards
