### ISSUE TITLE
Exclude User Apps for VPN does not populate with Android 11

### ISSUE THREAD

**Issue by drothenberger** [AdAway/AdAway#2259]
Clicking on Preferences / VPN based add blocker / Exclude user applications results in an empty list, so there is no way to exclude applications.

I'm running Pixel 2 XL with latest Android 11, fully stock (locked bootloader).

![Screenshot_20201015-221312](https://user-images.githubusercontent.com/5431111/96215784-c0f59200-0f33-11eb-8ac9-56bdaab902d4.png)

**Comment by PerfectSlayer** [comment]
Hi @drothenberger 

Thanks for the bug report. 
It looks like Android 11 requires a new permission to list all installed applications: https://developer.android.com/training/basics/intents/package-visibility

I will upgrade my test device first and test the new permission.
I might need to document it to explain the users why the AdAway requires it too.
