### ISSUE TITLE
Device Not working

### ISSUE THREAD

**Issue by Amr-Samy** [AdAway/AdAway#2265]
**Describe the bug**
After the installation and giving root permission the app asked to reboot and i accepted then the device didnot open again.

**Expected behavior**
How to get the device back to normal and work again..

**Device**
 - AdAway version: [e.g. 4.3.6] from apkmirror
 - Device: [Lenovo tablet a3500]
 - Android version: [4.4]
 - Root version [don't know]

**Additional context**
please help me to fix this.

**Comment by Amr-Samy** [comment]
Any Suggestions @dschuermann @Vankog @AnXh3L0

**Comment by PerfectSlayer** [comment]
Hi @Amr-Samy 

It seems your device won't boot if you modify the root or system partition.
I would recommend restoring the hosts file by flashing the system (without wipe to not clear your data).

You should ask for help[ in the XDA forum](https://forum.xda-developers.com/showthread.php?t=2190753). You will find a lot of knowledgeable people here about this kind of issue.
Next time, have a look to "systemless root" solution to prevent this issue.
