### ISSUE TITLE
Samsung S7 + linageos17.1 + magisk20.4: unable to copy hosts file

### ISSUE THREAD

**Issue by mrechte** [AdAway/AdAway#2267]
Hello,

When trying to activate adaway, I get an error, just after the app is granted root privilege "Fail copy hosts  file. read help for more information".

**Screenshots**
![Screenshot_20201025-151945_AdAway](https://user-images.githubusercontent.com/5902317/97110001-ed00d800-16d6-11eb-8aab-c84185831983.png)

**Device**
 - AdAway version: 4.3.6
 - Device: Galaxy S7
 - Android version: 10
 - Root version Magisk 20.4

Thanks

**Comment by rechtem** [comment]
I rebooted the phone and tried again: it worked !

This issue may be closed.

Thanks a lot for this great tools !

**Comment by PerfectSlayer** [comment]
Thanks! Glad you fixed it yourself.

For the record, did you reboot after enabling systemless magisk module?

**Comment by mrechte** [comment]
Hello,

I was faced again with the problem after resetting my smartphone. Yes 
one has to activate "hosts file outside system partition" in Magisk 
configuration, then reboot. Then in AdAway activate systemless mode.

May be this should be stated on install instructions (if it is not 
already the case).

Thanks

Le 01/11/2020 à 07:34, Bruce BUJON a écrit :

**Comment by PerfectSlayer** [comment]
The main issue is Magisk systemless module usage changed a lot those last years. I can't assume which Magisk version the user have.
AdAway only checks if systemless is enabled but has no control over it.

But thanks for the info.
Have a good day
