### ISSUE TITLE
root based adblock disabled after update

### ISSUE THREAD

**Issue by tomasmueller** [AdAway/AdAway#2345]
**Describe the bug**
Root based adblocker is disabled after the last update. Only VPN is working.

**Expected behavior**
Usw adblock without VPN.

**Device**
 - AdAway version: 5.1
 - Device: moto g6
 - Android version: lineageos 17.1
 - Root version magisk 20.4 magisk manager 7.5.1

**Comment by PerfectSlayer** [comment]
Hello @tomasmueller 

Can you check in magisk manager AdAdaway is well allowed?
If yes, could you clear the ApAdaway app data and restart the app if the root ad-blocking method is proposed at first launch?

Don't forget to go to settings to export your configuration first 😉

**Comment by tomasmueller** [comment]
Works now. 

Before i switched back to the last 4.x version for some days because of the annoying symbol in the status bar.

**Comment by PerfectSlayer** [comment]
The status bar is required by Android. You can't run a background service without it.

Glad it works.
