### ISSUE TITLE
Critical! Nothing works after last update

### ISSUE THREAD

**Issue by jjgh** [AdAway/AdAway#2352]
After last update from F-Droid AdAway doesn't work anymore at all on Android 10. Nothing is blocked, all traffic goes through, app doesn't report anything wrong.
However it is in a critical status! Please fix ASAP!

**Comment by PerfectSlayer** [comment]
_I will answer you with as much greetings as your issue..._

Fill the issue bug report template. I don't understand the context at all.
Please fill template ASAP!

**Comment by jjgh** [comment]
@PerfectSlayer what kind of greetings did you expect exactly in an issue report? Also, there's no need for too much context here, as AdAway is simply not working (i.e. not blocking ads) anymore after last update. 
On Android 10. 
That's all. 

There are no steps to be described and to be followed to reproduce anything. 
It just doesn't work. 
One more thing to report is that the UI is all messed up (oversized container rectangles covering each other all over the place... don't know what they are called, but something equivalent to divs in HTML).

Anyway man, it seems you're taking it too personally, perhaps you're working on this too much? If so please don't project your frustration over random people trying to help. Not everyone has the time to fill a template, but it doesn't mean their short feedback is completely worthless.

If anything, you could say my tone was a bit alarmist (but not rude) as I just wanted to quickly stress that the app is in a critical stage where it's totally failing to work and I just wanted to convey this message to you **ASAP!** 
Now tell me I'm the one guilty...

**Comment by PerfectSlayer** [comment]
Let's say hello for example? You are expecting to be read by a human to whom you are requesting help. You can at least say hi.

No need for context? It look to be working for dozen of thousands of users, you came here claiming it does not work for you and you don't think it could be nice to add some context to understand your problem? No device, no android version, no logcat, nothing.

Sure I am frustrated. I spent dozen of hours of my free time to maintain the project and you don't have 5 min to fill a template to request help? How could I not be frustrated? How did you expect to be welcome when you are using imperative form (to give order?), exclamation mark, "ASAP"?

You're not rude but let's be clear, this kind of feedback is not welcome here and not helping at all.

**Comment by jjgh** [comment]
Well I'm sorry you took it bad because I did not say hello... but that's the first time it happens to me on GitHub that someone takes it bad because someone else did not say hi. People just give it for granted...

Anyway please tell me, where did I use imperative form exactly? In which part did I give you any orders? My last sentence was literally "**Please** fix it As Soon As Possible!".
Not sure why you're trying so hard to see evil here, when there's none of it.

Also it's not just for me that AdAway is not working anymore... I've seen already similar reports, and same goes for the UI being corrupted. 
But yeah, keep up selecting only what you like to hear...

**Comment by PerfectSlayer** [comment]
> I've seen already similar reports

Don't you think it could be helpful to include them? 

> same goes for the UI being corrupted

The issue is being address. Already spend a dozen of hours on it. How could you tell I am not listening to people issues?

> But yeah, keep up selecting only what you like to hear...

See? That's the behavior I don't want to see on this project. I'm locking the issue because I spend enough time on it and it brings nothing to the project or the users.
