### ISSUE TITLE
[ING Home'Bank 6.16] compatibility report

### ISSUE THREAD

**Issue by gumball3000ro** [AdAway/AdAway#2369]
**Describe the third party app**
 - Name: ING Home'Bank (Romania)
 - Version: 6.16
 - AdAway version 5.1.0

**Describe the compabitily issue**
The app doesn't load anymore with adaway enabled.
Message displayed by the app: "Connection error Unable to contact server at this time. Please try again"

**Workaround**
Whitelisting domains *.homebank.ro, *.ing.ro and
*.akamaitechnologies.com didn't solve the problem

The single workaround found is to keep enabled only  the AdAway official hosts list, the other two (Pete Lowe and StevenBlack) seems to block the connection.

**Comment by PerfectSlayer** [comment]
If you use the root ad-blocking method, did you disable ad blocking before logging requests?
Because blocked requests can't be logged when using root ad-blocking...

**Comment by dhaern** [comment]
It's related to amazon app error and local web server:

[https://github.com/AdAway/AdAway/issues/2266](https://github.com/AdAway/AdAway/issues/2266)

Just disable local web server and apps will work again.

**Comment by ednancosta** [comment]
Has the same problem with brasilian bank Bradesco. 
And fix disabling local web server.
