### ISSUE TITLE
https://github.com/AdAway/AdAway/wiki/BlockNewAds this page not exist

### ISSUE THREAD

**Issue by droople** [AdAway/AdAway#2371]
Hi there
https://github.com/AdAway/AdAway/wiki/BlockNewAds this page not exist
cheers,

**Comment by PerfectSlayer** [comment]
Hello!

Where do you find this link?

Cheers

**Comment by PerfectSlayer** [comment]
Thanks, I will make a PR to the site to link to https://github.com/AdAway/AdAway/wiki/LogDNS instead.

Agreed. The content was not maintained. There is too much on my plate with the app development itself, its backend and finding contributors to keep the project alive... (for hosts file maintenance for example). I'm actually spending my day off to provide support and answer to GitHub issue 😢 

You can update the Wiki about Fitibt for sure. It should be editable for anyone with a GitHub account. Any contribution is more than welcome 🙏
