### ISSUE TITLE
UI issue: where is the update button?

### ISSUE THREAD

**Issue by Code7R** [AdAway/AdAway#2372]
**Describe the bug**
The tray notification button calls for update the screen opened by it does not offer one

**To Reproduce**
Wait a day until some update appears on remote server, and a notification appears in the notification area.

1. Go to notification (which says something like ... tap to update)
2. Click on notification
3. The screen from #2343 appears (although it says "one new source" )
4. Look around how to start the update

**Expected behavior**
There should be some button which starts the update. Pushing the "Down array" button in the middle (on the right) which looks like a typical download icon has no effect! UI is not intuitive, I opened the menu (botton left corner) but even there is nothing called "Update" or "Download" or similar element.

**Device**
 - AdAway version: 5.1
 - Device: Samsung Galaxy A3
 - Android version: LineageOS (latest)
 - Root version: latest Magisk

**Comment by PerfectSlayer** [comment]
Hello,

This is indeed the "download" button you are looking for. What do you mean by "has no effect"?
By the way, I would recommend to let the app update its content itself instead than displaying a notification then manually update.

**Comment by Code7R** [comment]
I am closing this, I cannot reproduce it anymore. I was sure I have clicked this download thing a few times and there was no feedback - no klick sound, no changed reaction. But now it works.

Anyway, this new UI is utterly confusing. It's not clear which parts are information, and which are actions to trigger, maybe somebody should rethink this with user's perspective in mind.

**Comment by PerfectSlayer** [comment]
I asked for help for months (years maybe) and nobody answers.
I did the best I could, it can't please everybody.

Regards
