### ISSUE TITLE
Youtube ad

### ISSUE THREAD

**Issue by dschuermann** [AdAway/AdAway#240]
_Original author: mgamm...@gmail.com (May 10, 2012 10:29:27)_

<b>What steps will reproduce the problem?</b>
1.Opening the youtube app.
2.Trying to watch a video of a user who has a youtube partnership.
3.Then you have to watch the ad before the actual video starts.

I'm using a rooted Lg 2x on the standard Android  2.3.3 on.

<b>Please enable Debug Logging in preferences of AdAway, install aLogcat and</b>
<b>save a logfile while reproducing the problem. The logfile can be attached</b>
<b>to this issue.</b>

<b>What version of AdAway are you using? What Android version? What custom</b>
<b>rom?</b>

<b>Please provide any additional information below.</b>

_Original issue: http://code.google.com/p/ad-away/issues/detail?id=239_

**Comment by Vankog** [comment]
AdAway cannot block most of YouTube’s video ads.
AdAway is a host based blocking system. You could only block YouTube ads by basically blocking YouTube itself...
