### ISSUE TITLE
Does not find: libtcpdump_exec.so

### ISSUE THREAD

**Issue by DavidMaza** [AdAway/AdAway#2401]
**Describe the bug**
When trying to record DNS events, no items appear. Logcat shows the message: "Does not find: libtcpdump_exec.so: listening on any, link-type LINUX_SLL (Linux cooked), capture size 512 bytes" 

**To Reproduce**
1. Start Adaway 
2. Open DNS Requests screen 
3. Press record 
4. Check logcat

**Expected behavior**
DNS Requests appear in the DNS Requests screen

**Device**
 - AdAway version: 5.1.0
 - Device: Oneplus 7
 - Android version: 10
 - Root version: Magisk 21.1

**Additional context**
Attached are the Logcat logs

**Comment by DavidMaza** [comment]
Logs: 
[logcat_12-09-2020_08-26-32.txt](https://github.com/AdAway/AdAway/files/5662810/logcat_12-09-2020_08-26-32.txt)

**Comment by PerfectSlayer** [comment]
Hi,

Thanks for the detailed bug report!

Could you upload your `dns_log.txt` file too? 
At least the first lines where you should see some text about `libtcpdump`.

Regards

**Comment by DavidMaza** [comment]
Hello,

Below is the dns_log.txt file:

[dns_log.txt](https://github.com/AdAway/AdAway/files/5663987/dns_log.txt)

**Comment by PerfectSlayer** [comment]
Thanks, that was fast!

Ok, as far as I can tell, there is nothing wrong with the app or your setup.

But it seems your are getting nothing logged?
Are you only testing blocked domains? If so, did you disable ad-blocking before? tcpdump can't log blocked connections.

**Comment by DavidMaza** [comment]
Ah ok. I tested it without any blocking at all.

I tested it by visiting several websites in Chrome that I hadn't visited before, but nothing came up in the DNS log.

**Comment by PerfectSlayer** [comment]
Ok, that is surprising...

Did the dns_log.txt file you attached here is whole or did you just extract the first lines?
If you attached the whole file, it means tcpdump does not catch any request.

**Comment by DavidMaza** [comment]
The dns_logs.txt was the whole file.

I've tried playing around with it for the past few days such as leaving it recording for a few hours, disabling battery optimisation, etc without much luck. 

Yesterday I opened the DNS Logs page for the first time that day and there were several entries in there, surprisingly. But I haven't been able to get any entries since.

**Comment by PerfectSlayer** [comment]
According the log file and if you get some logs at some point, it means tcpdump could work and everything it needs is here (the right binary, related libs, the right arch, etc...).

It is well listening to any interface so it is not the issue...

The two main reasons why you get no logs are:

1. Adblocking is enabled so blocked requests are not logged (but you should see some requests as all your traffic is not blocked)
2. You are using a private / secure DNS (so it does not use the basic DNS protocol and tcpdump has nothing to catch)

Could you check your device settings: `Settings` > `Network and Internet` > `Private DNS`. Try to set it to off (and maybe reboot?)
You can also check the Google Chrome DNS settings: `Settings` > `Privacy and Security` > `Use secure DNS` > `Use secure DNS`. Try to disable it.

The idea is to check if it can make the tcpdump log work. I would recommend to re-enable the secure DNS settings if it won't disable adblocking (at some point, these settings override the device hosts configuration and AdAway can no more block ads).

In the meantime, have a merry chistmas 🎅🎄
