### ISSUE TITLE
[5.1] cannot restore backup

### ISSUE THREAD

**Issue by bege10** [AdAway/AdAway#2411]
**Describe the bug**
If I try to restore my backed up settings I cannot choose the file in the file manager: all files are grayed out.

**To Reproduce**
Steps to reproduce the behavior: (Terms translated from German locale)
1. Go to 'Settings'
2. Click on 'Backup/Restore' -> Restore
3. Search backup file in file manager
4. One can click folders, files are grayed out

**Expected behavior**
Files should be clickable to choose for restore

(I can backup to any location on the phone but not restore from these files.)

**Device**
 - AdAway version: 5.1
 - Device: Samsung Galaxy S5 Plus (SM-G901F)
 - Android version: LineageOS for microG 16 (Android 9)
 - Root version: addon-su

**Comment by PerfectSlayer** [comment]
Hello @bege10 

From which version the backup is coming from?
Which name is it (especially the extension) and where is it located?

Regards 🎅🎄

**Comment by bege10** [comment]
It doesn't matter from which version (4 or 5.1) and where it is located (internal, external SD), all files in the file manager are grayed out (not, if I do the same procedure from another app that backs up and restores settings via the Android file manager).
The Adaway backup file name is "adaway-backup.json".
A fresh install of Adaway did not help.

**Comment by bege10** [comment]
This issue persists in v5.2
I restored v4.3.6 - everything OK
Restored v5.2 - issue is back

**Comment by PerfectSlayer** [comment]
Hum, which file explorer are you using?

I just start my weekend by doing some tests:
1. I remove all existing backups
2. I create a new backup
3. I check the created file using my file explorer: a `adaway-backup.json` exists in Download folder
4. I tap Restore in the app: the file explorer opens in the Download folder and the `adaway-backup.json` file is shown.

It seems file to me. May be there is an issue with your file manager?

_Step 2: Backup creation_
![Screenshot_1610173140](https://user-images.githubusercontent.com/1766222/104084878-83ab5280-524b-11eb-9ece-1d7950c64848.png)
_Step 3: Checking creation file_
![Screenshot_1610173161](https://user-images.githubusercontent.com/1766222/104084880-84dc7f80-524b-11eb-871a-4ec17e0cf40f.png)
_Step 4: Restore in the app_
![Screenshot_1610173171](https://user-images.githubusercontent.com/1766222/104084882-860dac80-524b-11eb-9d51-bee9cb7d3796.png)

Regards

**Comment by bege10** [comment]
Thank you, that helped to narrow the issue down.

AdAway opens the standard file explorer and I use that, looks the same as on your screenshots.

When the file explorer opens to backup you can chose the folder (both internal and external SD) and AdAway stores the backup file in this folder. In the Download folder in internal SD I can choose that file to restore, indeed. But in all other folders incl. Download in external SD the file is greyed out. In v4.3.6 you can restore from any folder.

**Comment by PerfectSlayer** [comment]
It might be a restriction from the recent Android versions.
The version 5 of AdAway target recent a version of Android that does no more require permission access to storage. It is based on Storage Access Framework (the new recommended way for app to access storage).

What it is surprising is the app can export (write) everywhere but import (read) on limited locations... I can't tell if it comes from AdAway, your file explorer or some system restrictions. Have you tried another file explorer like the Google one: https://play.google.com/store/apps/details?id=com.google.android.apps.nbu.files

**Comment by bege10** [comment]
I read that in Android 11 apps can only access their own folders and public folders as Download on internal storage. But this phone's system is still Android 9 and AdAway 4 can read all folders.
Can you change anything in AdAway 5 that it can access all folders? It is rather inconvenient to move the backup files around to enable AdAway to read them.
I have several other file managers but AdAway does not ask which one to use, it just uses the one that comes with the system (com.android.documentsui).

**Comment by PerfectSlayer** [comment]
No, I can't really change where the app has access. It's a framework feature and I am just using it.

I run Android 10 and I did a test moving my backup to /sdcard/Movies for example and I can successfully import them (they are not greyed out). I also did the same test on Android 11 using an emulator and it is also working fine.

**Comment by bege10** [comment]
Here on Android 9 it is greyed out.

**Comment by PerfectSlayer** [comment]
There is nothing more I can do. It's controlled by Android framework.
The fact you didn't get the standard behavior may come from a vendor specific implementation.

AdAway 5 won't behave as AdAway 4 as it targets the latest version of Android and the recommended file access way.
I am closing the issue as wontfix for now.

**Comment by PerfectSlayer** [comment]
As stated in the linked issue, I made some discovery and improve the app. 
I hope it will fix the issue for you in the next release 😉

**Comment by bege10** [comment]
In v5.6.0 the issue is fixed. Thank you very much.
