### ISSUE TITLE
[BUG] No root - unable to use Adaway 

### ISSUE THREAD

**Issue by And96** [AdAway/AdAway#2425]
**Describe the bug**
Unable to use AdAway. I cannot pass the first start screen.

**To Reproduce**
1. Install APK.
2. Open AdAway.
3. I cannot do anything.
4. Unable to tap o swipe.

**Expected behavior**
Set AdAway as VPN.

**Device**
 - AdAway version: 5.0.10
 - Device: Xiaomi Mi 9
 - Android version: 10
 - No root. 100% stock

**Additional context**
I can use others Adblockers without any problem. E.g Blokada which is VPN based too.

**Comment by skx7** [comment]
You should disable Blokada first, before using AdAway. If Blokada is active with always VPN enabled, you will indeed not be able to use AdAway. Disable Blokada and it will work! This is not a bug, not a feature as well, but technical limitation not being able to run 2 VPN services at the same time. AdAway blocks as you do not have root enabled to use root enabled adaway, and you have VPN active which blocks AdAway's VPN mode. Hope it helps...

**Comment by And96** [comment]
Yes. You're right. I had to disable Blokada from "Always On" VPN in settings. Blokada however was off and VPN not connected.

The strange things is that Adways seems freezed.

I think, at least, an information message should be added.
