### ISSUE TITLE
Installation error for v5.2.0

### ISSUE THREAD

**Issue by TheLonelyGhost** [AdAway/AdAway#2428]
**Describe the bug**
 
Update from 5.1.0 to 5.2.0 fails in the install phase

**To Reproduce**

1. Go to Adaway home screen
2. Click on "Update Available" in upper right corner
3. Let it download (may need to authorize installs initiated by Adaway)
4. See error "not installed"

Additionally, this can be replicated when downloading the APK attached to the v5.2.0 release on GitHub and installing that.

**Expected behavior**

Adaway v5.2.0 to install

**Screenshots**

![Screen just prior to error](https://user-images.githubusercontent.com/1276113/103504036-40547c80-4e24-11eb-9f5e-93cc0369e4a4.png)

![Error Screenshot](https://user-images.githubusercontent.com/1276113/103504034-3fbbe600-4e24-11eb-9d8e-23b3e8f5ecc6.png)

**Device**

 - AdAway version: 5.1.0 (via F-droid)
 - Device: Motorola One Action
 - Android version: 10
 - Root version: Magisk 21.0

**Additional context**

_N/a_

**Comment by PerfectSlayer** [comment]
The backend seems fine. So it looks like it comes from the app.
I have some trouble to spy request using mitm to check what request is done to the backend and I did not set log in this part of the app. I will try to setup frida on an emulator and some scripts to dump okhttp requests...

**Comment by PerfectSlayer** [comment]
I keep spending hours on this issue and I can't spy what happens in the F-Droid build...
I successfully setup a frida environment but I failed to trace the part I need. It seems it happens before the script being injected.
I guess I will need 5 to 10h more on the subject that I won't have anytime soon. In the meantime, bug reports and XDA posts about the issue keeps coming 😭

**Comment by PerfectSlayer** [comment]
I finally found the issue... I am mad at me to have to use so much complicated tools to find a so silly error...

The application reads its apk signature, compute the sha256 sum and match it to its record to check if it is me who built the app, f-droid or an unknown builder (which happens to anyone who fork the app or use a builtin version in some ROM).

https://github.com/AdAway/AdAway/blob/9bdff23f320f1930e635262391e63b668ce5c88b/app/src/main/java/org/adaway/model/update/UpdateStore.java#L24-L35

But when I compute the sha256 sum, I convert the hash byte array to a string representation:
https://github.com/AdAway/AdAway/blob/9bdff23f320f1930e635262391e63b668ce5c88b/app/src/main/java/org/adaway/model/update/UpdateStore.java#L97-L108

You might have guess the issue here. The string representation uses uppercase A-F letters where the sign hash declare in the code uses lower case letters a-f... And the string comparison does not ignore the case so the application does not detect the F-Droid store and tries to server a GitHub release to all users.
https://github.com/AdAway/AdAway/blob/9bdff23f320f1930e635262391e63b668ce5c88b/app/src/main/java/org/adaway/model/update/UpdateStore.java#L86

I will release a 5.2.1 version soon™️ to fix this issue.

**Comment by Mathnerd314** [comment]
So I see that 5.2.1 has a GitHub tag / release, and that shows up in the app, but the installation of this version still fails from the F-Droid version (5.1.0). So I guess you still need to release 5.2.1 on F-Droid to fix this?

**Comment by TheLonelyGhost** [comment]
I just uninstalled from F-Droid and reinstalled based on the package uploaded to the GitHub release, given there's a built-in update checker and installer. It's not the same third-party verification of source code == application, but it gets updates a bit faster and I trust the maintainer enough to go with their release channel.

Looking forward to the F-Droid release though. 😄 

Thanks so much @PerfectSlayer !

**Comment by PerfectSlayer** [comment]
@Mathnerd314 Yes. Sadly the 5.1will stay bogus. You will need to install 5.2.1 from F-Droid (or let the F-Droid store update it for you) to stop getting this error.

The F-Droid build configuration was fixed today. So I hope it should not be long before the 5.2.1 version appears on F-Droid store. (the 5.2.0 version will never be on the F-Droid store though... I don't know why they remove it from the build list)

**Comment by derN3rd** [comment]
@PerfectSlayer I don't know if you noticed (or get notifications) but it seems that 5.2.1 failed to build on fdroid https://f-droid.org/wiki/page/org.adaway/lastbuild_50201

**Comment by PerfectSlayer** [comment]
Thanks @derN3rd !
No, I don't get any notification from F-Droid... So thanks for the heads up!

But I am really tired of the build failure on the store. The F-Droid configuration is right: https://gitlab.com/fdroid/fdroiddata/-/blob/7d1544223edbea82fc7617f1320754e307763d68/metadata/org.adaway.yml#L559 and matches the `tcpdump` requirements: https://github.com/AdAway/AdAway/blob/v5.2.1/tcpdump/build.gradle#L12
So there is nothing I can do to fix it.

About the 5.2.0 version, it is not the main reason: it was removed by a maintainer: https://gitlab.com/fdroid/fdroiddata/-/commit/8668461c70470e2816154deb89cf3207eb05c7a7 Can't tell why 🤷

**Comment by Mathnerd314** [comment]
it looks like there is a build running: https://monitor.f-droid.org/builds/running. But I don't see it there yet.

**Comment by Mathnerd314** [comment]
failed again, "CRITICAL: Android NDK version 'r22' could not be found!". https://monitor.f-droid.org/builds/log/org.adaway/50201

**Comment by derN3rd** [comment]
> failed again, "CRITICAL: Android NDK version 'r22' could not be found!". https://monitor.f-droid.org/builds/log/org.adaway/50201
> 
> I guess they have to update the build farm images to include r22... 😫

The link now shows a successful build, but it's still not available on fdroid...

**Comment by Mathnerd314** [comment]
Copying a comment from https://gitlab.com/fdroid/fdroiddata/-/issues/2268:
> As your link shows, it was build, but not yet published. Wait a bit more ;)

I love release engineering...

**Comment by PerfectSlayer** [comment]
Finally! 🎉 

Please keep in mind you will need to install it manually as my broken 5.1.0 will keep downloading the GH release. (it was fixed in 5.2.1).

**Comment by derN3rd** [comment]
Just got the update notification from fdroid. Seems like it's all fixed now 👌🏼

**Comment by dtrunk90** [comment]
Issue still persists with 5.4.0

**Comment by PerfectSlayer** [comment]
https://github.com/AdAway/AdAway/issues/2428#issuecomment-756996483

**Comment by dtrunk90** [comment]
I don't even used F-Droid. I've used NikGApps. So to fix this error permanently I just need to install the GitHub release (do I need to install it as a data app over the currently installed one or do I need to replace the system app?)?
