### ISSUE TITLE
Adaway says there is a new version, without having automatic updates enabled

### ISSUE THREAD

**Issue by gallegonovato** [AdAway/AdAway#2432]
**Describe the bug**

First of all, WISH YOU A VERY MERRY CHRISTMAS, A HAPPY NEW YEAR AND MAY THE THREE KINGS BRING YOU ALL THE BEST AND MORE.

I have Adaway 5.1 with 17.1 lineageos and magisk in its latest stable version. Adaway is downloaded from fdroid. What is my surprise, when I look at the top of Adaway. That puts me that there is a new version available. I look at fdroid and there is no. I look at github and indeed there is. I have disabled all automatic update options. So I don't understand why Adaway shows that there is a new version available. Without the intention of offending anyone and without taking this doubt the wrong way. This would not be some kind of telemetry or automatic connection with github ?. I don't know if there is a way in future versions to remove this option? Because this in other versions and for example in version 4.3.6 did not happen either. And of course if you install the github version then it would not be valid with fdroid. I don't know if I'm wrong?

A hug and thanks for your help and time.

**To Reproduce**
1. Go to  Open adaway
4. See error shows at the top that there is a new version

**Expected behavior**

I have Adaway 5.1 with 17.1 lineageos and magisk in its latest stable version. Adaway is downloaded from fdroid. What is my surprise, when I look at the top of Adaway. That puts me that there is a new version available. I look at fdroid and there is no. I look at github and indeed there is. I have disabled all automatic update options. So I don't understand why Adaway shows that there is a new version available. Without the intention of offending anyone and without taking this doubt the wrong way. This would not be some kind of telemetry or automatic connection with github ?. I don't know if there is a way in future versions to remove this option? Because this in other versions and for example in version 4.3.6 did not happen either. And of course if you install the github version then it would not be valid with fdroid. I don't know if I'm wrong?

A hug and thanks for your help and time.

** Screens

https://ibb.co/bPnMjzD
https://ibb.co/V2h4FSc

As you can see, I have nothing active in updates. And it shouldn't show that there is another new version

**Device**
 - AdAway version: 5.1
 - Device: Nexus 5, Nexus 6p , Htc, Oneplus 7
 - Android version: 17.1
 - Root version Magisk in its latest version

**Additional context**
Add any other context like logcat about the problem here. Use adb logcat if you have developer settings enabled on your device or use any application like [MatLog](https://play.google.com/store/apps/details?id=com.pluscubed.matlog) to save logs. Include the crash report in the issue in a code block, a file attachment, or put it in a gist and provide link to that gist.

**Comment by Nathan-Nesbitt** [comment]
This is reproducable on One Plus 3T with version 5.1.0.

**Comment by faraz-b** [comment]
Getting the same issue here.

AdAway version: 5.1.0
Device: OnePlus 5
Android version: 10 (Oxygen OS 10.0.0)
Root version: Magisk 20.4

**Comment by bege10** [comment]
See here https://github.com/AdAway/AdAway/issues/2428

**Comment by PerfectSlayer** [comment]
Hi and happy new year to you all 🎉

There is a built-in updater in order to easily update the app for all users.
If you don't have the F-Droid store or install the app from GitHub, it allows you to stay up-to-date.
If you don't want the app to check for update (it only ping the app.adaway.org domain once a week), you can disable it from the Settings > Update > Application update > Periodically check for update.

And the 5.2.0 version has issue to detect the F-Droid store and falls back to the GitHub store to distribute its release.
As mentioned, the bug was handled here #2428 and will be fixed in the coming 5.2.1 version.

Have a good day,
Regards
