### ISSUE TITLE
Updating sources crashes app if SAF access was revoked

### ISSUE THREAD

**Issue by sr1canskhsia** [AdAway/AdAway#2434]
**Describe the bug**
After adding a local file hosts source, if the user revoked the access to that file, then app would crash when trying to update sources.

**To Reproduce**
1. Add a local file hosts source
2. Go to Settings -> Apps -> AdAway -> Storage & cache -> Clear Access
3. Go back to the AdAway app and tap on update button. Now the app should crash
4. Things get worse if the user enabled "Check for updates at startup" option. The app would always crash on startup and the only way to recover is to clean reinstall the app.

**Device**
 - AdAway version: 5.2.1
 - Device: OnePlus 7T Pro
 - Android version: 10
 - Root version: Magisk 21.2

**Additional context**
Link to the crash report: https://del.dog/icyrothock.txt

**Comment by PerfectSlayer** [comment]
Awesome! I totally forgot to handle this case...
Moreover, it becomes a nightmare with update check at startup 😅 

Thanks, I will have a look at it for the next releases.

**Comment by PerfectSlayer** [comment]
Turns out it was pretty easy to fix it.
Thanks for the report 👍
