### ISSUE TITLE
Updates Won't Install 

### ISSUE THREAD

**Issue by sadonn** [AdAway/AdAway#2438]
When attempting to install updates, the update downloads but then gives the error "App not installed." As shown in the screenshot. 

[Screenshot_20210109-070325_Package installer](https://user-images.githubusercontent.com/77197487/104092592-878aa500-524a-11eb-9eab-dac35e6d998a.jpg)

 - AdAway version: 5.1.0
 - Device: Samsung Note 9
 - Android version: 10

**Comment by AngusNB** [comment]
I had the same issue.
Nexus 9 tablet
LineageOS 15.1 (Android 8.1)

I worked around it this way;
I found the downloaded 5.2.1 .apk, uninstalled 5.1.0 then installed the downloaded .apk.
Search for _AdAway 5.2.1_

**Comment by PerfectSlayer** [comment]
Hello,

The issue was address on #2428 and it should be fixed in the coming 5.2.1 release.
You will find all the explanation here.

Regards

P.S. : If you are looking for official APK, you can find all of them on GitHub: https://github.com/AdAway/AdAway/releases

**Comment by AngusNB** [comment]
Thanks. Found the official APK after the fact. 
That would have been easier. :)
