### ISSUE TITLE
Automatic updates checkmark not taking effect

### ISSUE THREAD

**Issue by fusionneur** [AdAway/AdAway#2441]
Version 5.1.0

After opening the app, several connection attempts towards app.adaway.org is made even if automatic updates (periodically check for update) is unchecked under preferences

**Comment by PerfectSlayer** [comment]
Hello,

Thanks for the report! It is clearly a bug. The app should not request this domain if the automatic update are disable.
I will have a look at it as soon as find some free time 😉 

Regards

**Comment by PerfectSlayer** [comment]
Hum, I just check and in fact it is not that simple.
Disabling the option will disable the automatic background check but not the check at start up.
For hosts sources, there is an option for that: _Check for update at startup_ but it does not exist for app update itself.

So it's more an addition to make in the coming releases.

**Comment by fusionneur** [comment]
When is this going to be released? Ty
