### ISSUE TITLE
[Feature Request] allow domains for a chosen app only

### ISSUE THREAD

**Issue by dhammel** [AdAway/AdAway#2442]
Hello,

I would like to request the ability to allow domains only for a chosen app.

One reason is facebook messenger. A host file I prefer using blocks graph.facebook.com which I like having blocked system wide as many apps use it for ads.

This way i can allow messenger to connect to graph.facebook.com while everything else other than messemger is still blocked from it.

Messenger at its core function works with it blocked, but certain features like facebook pay just error with a connection error, while allowing graph.facebook.com fixes it.

Would this feature be considered?

Thank you

**Comment by Ivar418** [comment]
Also usefull for games that have the option to press in an add ti receive something. A "dont block this app" funtion is verry usefull (adblocker reborn from xposed hasbsuch a feature, u could look at it)

**Comment by dhammel** [comment]
@Ivar418 Thanks for the tip, however Ive been out of the xposed community for sometime, as i've been updating to the very latest versions of android, and xposed is always one or 2 android versions behind on support. I'm not sure if the magisk version of it works, I saw it in repo list but never researched it yet.

**Comment by Ivar418** [comment]
> @Ivar418 Thanks for the tip, however Ive been out of the xposed community for sometime, as i've been updating to the very latest versions of android, and xposed is always one or 2 android versions behind on support. I'm not sure if the magisk version of it works, I saw it in repo list but never researched it yet.

Well personally id rather staywith xposedles adaway.but if u want to try it out, use EDxposed its the recontinued cersion of xposed since xposed is no longer (active) being developed

**Comment by PerfectSlayer** [comment]
Hello,

There is sadly nothing I can do. The closest solution will be to use the VPN ad-blocking and allow Facebook Messenger to bypass it.
There is no SDK API for me to know which application is making which request so I can't apply application based filters.

But I would definitely like to have a such feature to be more aggressive on ad-blocking for a lot of app and more loose for the rest of my system 😅 

Regards
