### ISSUE TITLE
Nolonger working since Magisk 21.2 with Systemless Hosts

### ISSUE THREAD

**Issue by mrechte** [AdAway/AdAway#2457]
Hello,

Since a recent Magisk update, AdAway no longer works.

The AdAway DNS log is empty

Last point: AdAway keeps proposing an update (Fix F-Droid store detection), which, after validating the message "AdAway Do you want to update your application ? Your data will not be lost", ends-up with "AdAway Application not installed".

**Device**
 - AdAway version: ?
 - Device: [Samsung S7]
 - Android version: 10 LineageOS 17.1
 - Root version Magisk 21.2

**Comment by Snorchy** [comment]
I also can't update my existing AdAway version with the .apk downloaded from Releases (v5.2.1). I have a Oneplus 7 with Magisk 21.2.

**Comment by Snorchy** [comment]
I uninstalled AdAway and now I could install v5.2.1 I guess my previous F-Droid version was incompatible with the GitHub one?

**Comment by albotroz** [comment]
I had same problem with Update of AdAway 5.2.1
Two Honor 5X - KIW-L21 devices with LineageOS 16.0, both rooted, Magisk 21.4

I uninstalled old AdAway Version and installed with success AdAway 5.2.1 apk from official AdAway Homepage.

**Comment by PerfectSlayer** [comment]
Hello,

For the app update issue, please check here: https://github.com/AdAway/AdAway/issues/2428
For the Magisk issue, John Wu acknowledge the problem on twitter: https://twitter.com/topjohnwu/status/1350019555150553088. There is already a patch. If it is not enough, I would recommend to revert to previous Magisk version or ask for Magisk support!
And about DNS log empty, please keep in mind it can't log blocked request. Don't forget to disable adblocking before logging.

Regards
