### ISSUE TITLE
VPN reconnecting error when always on VPN is enabled in VPN settings

### ISSUE THREAD

**Issue by patkarmandar** [AdAway/AdAway#2466]
**Describe the bug**
VPN always show reconnecting when always on VPN is enabled in VPN settings. I don't know if it was there on previous version, i noticed it now. Then i have to reinstall app for getting adaway work again.

**To Reproduce**
1. Go to VPN setting
2. Select adaway VPN and enable always on VPN
3. Then turn off VPN and on it again.
4. it will show VPN reconnecting
5. It will not get connected until reinstall adaway app

**Expected behavior**
It should get connected after turning on adaway VPN. even i try with pause and resume in app, but not work.

**Device**
 - AdAway version: 5.3.0
 - Device: Redmi Note 4 (custom rom)
 - Android version: 10
 - Root version: No root - VPN mode

**Logcat**
```
Network exception in vpn thread, reconnecting
java.lang.NullPointerException: Attempt to invoke virtual method 'java.io.FileDescriptor android.os.ParcelFileDescriptor.getFileDescriptor()' on a null object reference
	at org.adaway.vpn.VpnWorker.runVpn(VpnWorker.java:206)
	at org.adaway.vpn.VpnWorker.work(VpnWorker.java:155)
	at org.adaway.vpn.VpnWorker.lambda$Q_er0Ccc81appYA5vyHMnQZ5U4o(Unknown Source:0)
	at org.adaway.vpn.-$$Lambda$VpnWorker$Q_er0Ccc81appYA5vyHMnQZ5U4o.run(Unknown Source:2)
	at java.lang.Thread.run(Thread.java:919)
```

**Comment by PerfectSlayer** [comment]
Hello,

Thanks for the complete bug report. This kind of error is due when the VPN permission is removed but the app is still running.

Do you still have the error if you restart the app? It should ask you to enable VPN permission (ie _prepare the application_ according the developer documentation term).
If there anything that could prevent the VPN from starting? Like another VPN application or any ad-blocking VPN application?

I tried to reproduce on my Android 10 Pixel 2 and it is working as expected so we will need to find what is preventing the VPN service to start on your device.

Regards

**Comment by patkarmandar** [comment]
It did not giving me option to enable vpn again. And if i remove adaway VPN (ie forgot vpn from vpn settings), Even though it did not gave option to set vpn permission again. And after i need to reinstall app for removing always on vpn notification.
Sometimes it crashes app, here is logcat https://del.dog/samagnapof.txt

And i don't have any other app using VPN. If i toggle always on vpn sometimes it works as expected.

As its not critical issue i really don't have any problem using adaway. Just keep always on vpn disabled.

Thanks for awesome app!

**Comment by PerfectSlayer** [comment]
You should not have to reinstall the app to get the VPN prepare dialog.
I test it on my device and I can confirm there is a bug. I quickly fixed it and make a build for you.

Could you have a look if this build fix your issue? [AdAway-5.3.0-vpnprepare.zip](https://github.com/AdAway/AdAway/files/5869379/AdAway-5.3.0-vpnprepare.zip)
It is signed with the GitHub release key (so you can't install it over a F-Droid release) but it should work as any GitHub build (including be updated as soon as the 5.4.0 is shipped).

As I can't reproduce the always on VPN reconnection issue, please report if you see any progress with this build :wink: Thanks!

**Comment by patkarmandar** [comment]
This test build not give me any issue and also it give option to allow vpn permission again. Thanks for quick fix.

And i think that always on VPN is my device/android's fault. Bcoz while always on vpn is on and disable vpn directly, i have to toggle always on vpn to make it work. here is video :
https://easyupload.io/is30vk

**Comment by PerfectSlayer** [comment]
Thanks for the feedback and the video!
The fix will be shipped in the next version. But for the always on vpn issue, yeah, it seems to be related to your device... Not sure I can do about it 🤷 

If it's okay for you, you can close the issue!

**Comment by patkarmandar** [comment]
As i said earlier, i don't have any issue using adaway :)
Thanks for all !

**Comment by DB9-max** [comment]
Did you have rooted systemless adblock magisk module on?

Now with 6.1.3 I root method I cannot start other VPN
