### ISSUE TITLE
Amazon Kindle app sign in

### ISSUE THREAD

**Issue by Kreuger** [AdAway/AdAway#2541]
Hey guys Ive been unable to sign into the Amazon Kindle app and I have a suspicion that it has to do with ad away because it works fine on my other devices that dont have adaway. Is there anything specific related to Amazon being blocked?

**Comment by mind-overflow** [comment]
Have you tried what was suggested in #2488?

**Comment by Kreuger** [comment]
No I did not see that. I will have to figure out the URL for NA.

**Comment by Kreuger** [comment]
fls-na.amazon.com is the one for me, and it worked so thank you!
