### ISSUE TITLE
Scenario with Third Party Host Source

### ISSUE THREAD

**Issue by Djtrip83** [AdAway/AdAway#2566]
Trying to add this source but it never downloads and merges with the host file. 

https://zerodot1.gitlab.io/CoinBlockerLists/list.txt

I know it is not an approved one but it should still install. Instead it is ignored by the updates and the number of hosts added never shown.

![Screenshot_20210217-194035.png](https://user-images.githubusercontent.com/48355907/108258653-2d89d300-7158-11eb-9772-974e36264043.png)

![Screenshot_20210217-194105.png](https://user-images.githubusercontent.com/48355907/108258659-2f539680-7158-11eb-8ac4-cbe98eae0674.png)

**Comment by gallegonovato** [comment]
Good afternoon:

I think I can help you with this problem.

You only have to change the link of the source you have for this one: https://gitlab.com/ZeroDot1/CoinBlockerLists/raw/master/hosts_browser and check the first box below where you put the addresses in all the sources.

That is, change the one you have ( https://zerodot1.gitlab.io/CoinBlockerLists/list.txt ) to https://gitlab.com/ZeroDot1/CoinBlockerLists/raw/master/hosts_browser . Then check the first box. And in the top right hand corner click on v. Lego will tell you to apply changes, say yes. Wait and it should be done.

Then if you want the optional zerodot1 is https://gitlab.com/ZeroDot1/CoinBlockerLists/raw/master/hosts_optional

A hug

**Comment by Djtrip83** [comment]
It works! Thanks!

Hug to you too!! 😁
