### ISSUE TITLE
[Amazon Shopping] compatibility report

### ISSUE THREAD

**Issue by nahcos** [AdAway/AdAway#2586]
- Amazon Shopping (Android application)
 - Android 10
 - Samsung SM-G980F

As soon as AdAware is enabled, Amazon app shows the message "UH-OH Something went wrong on our end". 

I tried enabling/disabling some sources as well as adding the domain suggested in the help section (and finally, the entire *amazon.com) to "allowed" list but as long as the app is enabled, Amazon app remains blocked. If I disable/uninstall AdAware and reboot, everything turns back to normal.

**Comment by jaydenrre** [comment]
- Android 10
- Oneplus 7 pro gm1910
Same issue.
Just updated to 5.4.0 and the problem persists.

**Comment by omgfrost** [comment]
> * Android 10
> * Oneplus 7 pro gm1910
>   Same issue.
>   Just updated to 5.4.0 and the problem persists.

Same here after 5.4.0

**Comment by nahcos** [comment]
> > * Android 10
> > * Oneplus 7 pro gm1910
> >   Same issue.
> >   Just updated to 5.4.0 and the problem persists.
> 
> Same here after 5.4.0
> Suggesting the OP to tag in the title [workaround-available] as if you pause adaway ad it defaults hosts file the app works as intended

Pausing the app does resolve the issue, BUT the phone needs to be rebooted (already mentioned in my first post)! I had to freeze the app, though! For no apparent resons it enables itself after a while.

**Comment by omgfrost** [comment]
> > > * Android 10
> > > * Oneplus 7 pro gm1910
> > >   Same issue.
> > >   Just updated to 5.4.0 and the problem persists.
> > 
> > 
> > Same here after 5.4.0
> > Suggesting the OP to tag in the title [workaround-available] as if you pause adaway ad it defaults hosts file the app works as intended
> 
> Pausing the app does resolve the issue, BUT the phone needs to be rebooted (already mentioned in my first post)! I had to freeze the app, though! For no apparent resons it enables itself after a while.

My galaxy s6 with android 10, when i pause adaway, the app works as intended,attaching the proof:

**Comment by mooms06** [comment]
Same issue here
G930F on Android 8.0

**Comment by nahcos** [comment]
The problem persists after updating to the last version (5.4.0 - 210228)

**Comment by FrostbiterTy** [comment]
Are you using root mode? Do you have the webserver enabled? If so, disable it and Amazon should work again. I had this issue before and that fixed it for me. Fixed a few other apps that were having issues too.

**Comment by nahcos** [comment]
> 
> 
> Are you using root mode? Do you have the webserver enabled? If so, disable it and Amazon should work again. I had this issue before and that fixed it for me. Fixed a few other apps that were having issues too.

**Comment by nahcos** [comment]
> 
> 
> Are you using root mode? Do you have the webserver enabled? If so, disable it and Amazon should work again. I had this issue before and that fixed it for me. Fixed a few other apps that were having issues too.

That was it! Problem solved, thank you!
