### ISSUE TITLE
Web Server Not Running

### ISSUE THREAD

**Issue by Master0ne** [AdAway/AdAway#2588]
**Describe the bug**
`Test web server` shows `Not running`.

**To Reproduce**
1. A fresh installation of AdAway.
2. Self-signed certificate installed.
3. `Test web server` shows `Not running`.

**Expected behavior**
`Test web server` should show `Running and certificate installed`.

**Screenshots**
![Screenshot_20210303-154355](https://user-images.githubusercontent.com/8912853/109822665-743afb00-7c37-11eb-957a-60f78afc54ef.jpg)

**Device**
 - AdAway version: 5.4.0
 - Device: POCO X3 NFC
 - Android version: 11 (ArrowOS 11)
 - Root version: Magisk v22.0

**Additional context**
Clicking on `Test web server` opens the page `https://localhost/internal-test`. I have two web browsers installed:

- In DuckDuck Go Privacy Browser it is just an empty white page.
- In Bromite Browser an error page is shown with first `ERR_SOCKET_NOT_CONNECTED` and then `ERR_BAD_SSL_CLIENT_AUTH_CERT` although the self-signed certificate has been installed correctly as per app instructions.

I am using the Surfshark VPN client and have disabled the VPN and the VPN Kill Switch for this test, because I was not sure if this has any influence. The VPN client has a Whitelister where I can add websites to bypass the VPN, but the URL `https://localhost/internal-test` can not be entered ("Wrong website format").

**Comment by Master0ne** [comment]
**Device**
 - AdAway version: 5.4.0
 - Device: OnePlus 6
 - Android version: 9 (LineageOS for microG)
 - Root version: Magisk Canary (22001)

`Test web server` shows `Running and certificate installed`, so the reported issue must have something to do with AdAway 5.4.0 not running properly on Android 11.

**Comment by Master0ne** [comment]
I've done a new installation of v5.4.0 on another POCO X3 NFC with ArrowOS 11 and Magisk v22.0 and I've seen it first tell something like `Running but self-signed certificate not installed`, which changed to `Not running` after installing the certificate.

**Comment by Master0ne** [comment]
Not sure if there is a connection to the certificate installation in the used custom ROM, so [here](https://gitlab.com/arrowos-support/issues/android/-/issues/94) is the reference to the issue that I have just opened on their GitLab issue tracker.

**Comment by dexdie** [comment]
Device

AdAway version: 5.4.0
Device: OnePlus 7
Android version: 10
Root version: Magisk Canary (22001)

I have enabled web server but the Test web server shows Not Running (I have installed certificate but no effects)

On version 5.3.0 everything works fine.

**Comment by KyleKolander** [comment]
Same experience for me. Fresh install of v5.4.0 w/ cert installed on Pixel 5.  Root w/ Magisk Canary 22001.  It's always worked on earlier versions.

**Comment by Master0ne** [comment]
Good to know that it's reproducible by others, which means I can close that issue on the ArrowOS GitLab tracker.

**Comment by giokou** [comment]
AdAway version: 5.4.0
Device: OnePlus 8 Pro
Android version: 11 official OOS 11.0.4.4
Root version: Magisk 21.4

Same issue here. Fresh install, cert installed, reboot but no luck. Also after reboot i keep getting that annoying system notification about the cert installed. See attached please.
![Screenshot_20210305-220813](https://user-images.githubusercontent.com/80127400/110168609-1b6a8e80-7e00-11eb-921c-4954fd460208.jpg)
![Screenshot_20210305-220825](https://user-images.githubusercontent.com/80127400/110168614-1c9bbb80-7e00-11eb-97d2-f605a1e359ae.jpg)
![Screenshot_20210305-220936](https://user-images.githubusercontent.com/80127400/110168617-1d345200-7e00-11eb-87a5-4888624d64b9.jpg)
![Screenshot_20210305-220947](https://user-images.githubusercontent.com/80127400/110168624-1e657f00-7e00-11eb-8c5a-3ec68018989b.jpg)
![Screenshot_20210305-221003](https://user-images.githubusercontent.com/80127400/110168629-1efe1580-7e00-11eb-94d2-50edd8d161b1.jpg)
![Screenshot_20210305-221008](https://user-images.githubusercontent.com/80127400/110168631-1f96ac00-7e00-11eb-902e-b3c0243270f1.jpg)

**Comment by Holguitar** [comment]
Bug is also true for:
Device: Moto G5+
Android version : Stock Oreo (Android 8)
Root version: Magisk 21.4
AdAway 5.40

**Comment by PerfectSlayer** [comment]
Hello everyone,

I can confirm I have the same issue on my device.
On my side, the server is running but there is an issue with TLS or the certificate.
Could you test to reach http://localhost ? (without TLS) and confirm the process is running?

I think the issue comes from the upgrade to mongoose from 7.0 to 7.1 as it's working fine on AdAway 5.3.0.
I will see what I can find about it but the mongoose release changelog is scarce...

**Comment by PerfectSlayer** [comment]
Another question:

It is very brief but I can see a popup when I try to load the a page from the webserver:
![image](https://user-images.githubusercontent.com/1766222/110234504-28d06780-7f2b-11eb-9aa9-5b20b57771a8.png)

I had to record my screen and go frame by frame in order to capture the dialog. The only thing I notice was a quick fade / shade of the screen. Am I only to have this?

**Comment by PerfectSlayer** [comment]
So, I can confirm:

* There is an issue with the web server
* It starts from AdAway 5.4.0 when I upgrade mongoose to 7.1
* The issue comes from mongoose: it always request a certificate from the client (it explains the dialog from the screenshot above)

I will fix it when a new version of mongoose is released (the maintainer is aware of the issue and fix it in the main branch).

**Comment by Dark-Yox** [comment]
I have 3 phones with the same issue all of them are on Android 11, Magisk 22.0 and AdAway 5.4.0

**Comment by PerfectSlayer** [comment]
The new Mongoose version is released so I update it in AdAway and it fixes the issue 👍

**Comment by DRayX** [comment]
Any chance of a 5.4.1 or 5.5.0 release in the nearish future?  Had to go back to 5.3.0 for now (this bug seemed to be causing a few apps to crash for me).

**Comment by Master0ne** [comment]
@PerfectSlayer, I have just updated to v5.5.0 but the app is still telling `Test web server: Not running`.

**Comment by giokou** [comment]
I updated to 5.5.0, rebooted and voila!!
1st scr is from OnePlus 8 Pro android 11 and 2nd scr from Chuwi Hipad X android 10.
Thanks!

![Screenshot_20210317-204140](https://user-images.githubusercontent.com/80127400/111523003-7a66c680-8763-11eb-9ef0-a1a22edd6544.jpg) ![Screenshot_20210317-204419](https://user-images.githubusercontent.com/80127400/111523009-7aff5d00-8763-11eb-9f1f-fe92952e421d.jpg)

**Comment by PerfectSlayer** [comment]
@Master0ne You need to stop then start the server to kill the old version and start the new one.

Or you could just reboot 😉

**Comment by Master0ne** [comment]
@PerfectSlayer, thanks, it's indeed working now.

**Comment by pufcio** [comment]
I've got the same issue on my Mi 9 Lite and no amount of restarts helps in any way. I've even installed a mod that moves the user certificate to the main store, but it doesn't help in any way. On 5.4 I got that the cert is not installed, no matter where it was or if it was installed, on 5.5 if it's not installed then it properly states that it's not and once I install it, it says that web server is not running. That's it.

**Comment by asheroto** [comment]
I noticed a problem related to this.

Steps to reproduce:
1. Enable web server
2. Uninstall AdAway
3. Install AdAway
4. "Enable web server" is still enabled, but "Test web server" says "Not running"
5. Disabling and re-enabling works for me
