### ISSUE TITLE
[Podcasts] compatibility report

### ISSUE THREAD

**Issue by jacobmar1ey** [AdAway/AdAway#2590]
- Name: I use AntennaPod but imagine it would effect other podcast apps, too
 - Version: 2.1.3

Starting Monday Mar 1st I’ve been unable to download two podcasts, The Daily from the NYT and Pod Save America from Crooked Media.

Other downloads, like On the Media (from WNYC) and Stay Tuned with Preet (from Cafe) still were able to.

When I look at the download log the error is 

```
java.security.cert.CertPathValidatorException: Trust anchor for certification path not found. 

File URL:
https://dts.podtrac.com/redirect.mp3/chtbl.com/track/8DB4DB/pdst.fm/e/nyt.simplecastaudio.com/03d8b493-87fc-4bd1-931f-8a8e9b945d8a/episodes/47d5453e-ac24-44b5-aa1d-5d77503ec4af/audio/128/default.mp3?aid=rss_feed&awCollectionId=03d8b493-87fc-4bd1-931f-8a8e9b945d8a&awEpisodeId=47d5453e-ac24-44b5-aa1d-5d77503ec4af&feed=54nAGcIl

```
**Workaround**
I just disabled the AdAway official hosts and then downloaded the podcasts and re-enabled.
I haven't tried to white list any particular domain yet.

I am opening this after a thread on AntennaPod's forum:
https://forum.antennapod.org/t/cannot-download-some-podcasts-for-24h/740

**Comment by wh0isit** [comment]
Mine started working again after white listing chtbl.com

Apparently it's used to measure the podcast numbers.

**Comment by smithilberry** [comment]
> Mine started working again after white listing chtbl.com
> 
> Apparently it's used to measure the podcast numbers.

Yes!!! Thank you! I was having the same issue with a couple of podcasts (the daily and skimmthis) and whitelisting this worked.

**Comment by lcoll** [comment]
Any podcast from the podcastone network is showing the same issue. I believe it should be whitelisted on the "main" hosts file, I was having the same problem on two different cell phones and I was going crazy thinking it had something to do with the LineageOS certificate credentials.

**Comment by jacobmar1ey** [comment]
Yes, I have two of those whitelisted now (dts.podtrac.com and chtbl.com)and have not had issues since. I'll close this issue so other people can find it but it won't bog down the devs.
