### ISSUE TITLE
AdAway stuck in downloading lists causes huge lags

### ISSUE THREAD

**Issue by auanasgheps** [AdAway/AdAway#2598]
**Describe the bug**
Hi, I have experienced a very strange behaviour with AdAway.

I am long time AdAway (root) user and some days ago I cleared my old lists switching to [Energized Protection - Blu ](https://github.com/EnergizedProtection/block)version.
Old lists were about 68k hosts, whilst Energized is 358k.
I have a OnePlus 8T, so not exactly a low end device.
I cleared previous lists, installed Energized Blu and everything went fine.

After a couple of days I started noticing huge lags. I mean: huge. I could barely answer phone calls, the whole system would hang for 10 seconds pretty frequently every time using different apps, every hour or so.

After a lot of troubleshooting which didn't help (reboots, clear app caches, kill apps that could slow down the device, etc), I accidentally opened AdAway and found out it was stuck updating the list.
I configured AdAway to automatically update lists every day in background, and this usually works fine.

Unfortunately I did not take a screenshot, but the number of Blocked hosts on the left was painfully growing by one host every second or so. So I disabled the new host list and re-enabled old ones, but the app was stuck, with blocked hosts still growing by one every second and a loading bar with some progress just below the number of sources.
I am aware the Energized Blu host list is pretty big, but I was not on a slow connection and the app was likely in this state since hours if not a day.

Only after I killed it, I was able to finally disable all lists, go back to zero and rebuild the host file list. Now I'm temporarily back to my previous lists, because this issue was causing a lot of issues to me.

Once I did this, the phone immediately came back to life, snappy and responsive as has always been.

I am aware this information is not a lot and did not collect logs, but maybe could help other people. Maybe OnePlus background restrictions are too aggressive for a larger lists which obviously takes more time to be processed? Even if that's the case, a high end smartphone should not behave like it happened to mine.

Maybe a sort of timeout/cutoff could be implemented if the whole process takes too much time and notify the user of such failure?

**To Reproduce**
N/A

**Device**
 - AdAway version: 5.4.0
 - Device: OnePlus 8T
 - Android version: 11
 - Root version: Magisk 22

**Comment by gallegonovato** [comment]
Good afternoon:

I don't know if it can help you to solve the problem. 

Energized lists are usually updated very very often. And think that if you have in automatic updates Adaway is always downloading, processing the changes, updating and creating the new hosts.

I don't know how it is now but I used to use those lists and it was updating either every hour or every few minutes. And of course you have to check for updates and so on...

I would almost say to try without automatic updates. Doing your updates manually. And then look under the energized list to see how long it says updated for.

And after a few minutes go back to check for updates to see if I'm right and that's it.

If you can try to download the Energized updates with Wi-Fi. When I had them I noticed the change to the mobile data network.

And stop AdAway from doing all the processes. And remember to enable systemless hosts in magisk.

Best regards

**Comment by auanasgheps** [comment]
Hello!
I have an update to this issue.

The problem is not Auto update in the background, but the list itself.

If I use AdAway's default lists, everything runs fine.
However, if I use Energized Blue List (link) the phone will constantly lag. 

I don't know yet if the list does not behave correctly or it's my phone that doesn't like it, but at least I've found the problem. I'll use default lists until there's a solution.

**Comment by auanasgheps** [comment]
Hi, a final update to the issue: the mistake is on me.
I used the wrong format of the Energized Blue List. By checking out their GitHub page, they recommend to use the RAW list for AdAway, not the .txt version. 
Using the RAW list I don't have performance issues!
