### ISSUE TITLE
Cannot install Adaway on LineageOS 14

### ISSUE THREAD

**Issue by peter099** [AdAway/AdAway#2601]
I am trying to install Adaway on my phone with LineageOS 14 from fdroid app but getting 'install failed'. Why is that?

**Comment by gallegonovato** [comment]
Good afternoon @peter099

I do not know if it will be the version of lineageos you use and that in you try to download AdAway in some version 5.x . I mean that according to https://github.com/AdAway/AdAway says Android 8 Oreo or above (version 5) and For devices older than Android 8 Oreo, use the version 4 of AdAway.

I would almost say that if you can you should upgrade to a higher version of lineageos. Or try activating the fdroid archive repo of the fdroid app and try to see if you get some adaway 4.x version. 

But I can't be sure that the 4.x version will work yet, I don't know about that.

Best regards

**Comment by peter099** [comment]
LineageOS 14 is based on android 7.1. Will older version of Adaway work without issues?

**Comment by gallegonovato** [comment]
Good afternoon 

In principle version 4.x should work. But I can't guarantee it since there is version 5.x because I have no way to tell you for sure. 

But in terms of security and others, as long as your phone can. It would be better to put a higher lineageos. Because there may be security problems in the system itself, or some application is covered in its latest versions. 

A hug

**Comment by PerfectSlayer** [comment]
Hi,

Here is a quote from the [V5 FAQ](https://forum.xda-developers.com/t/app-root-nonroot-official-adaway-v5-5-0.2190753/page-726#post-82281687):

_Why does this version targets Android 8+ Oreo only?_
Like the v4, v5 is expected to offer support for latest devices.
Android 8 and above represent more than 60% of device distribution and will grew through time.
If you use an older device, root solutions work very well and v4 is here for you (like v2 and v3 stayed for legacy devices).

So you can use the last 4.x version without issue.
There might be some minor issues (like legacy UI things) but nothing that will prevent you to block ads 😉 

Regards
