### ISSUE TITLE
For your hosts sources from Github, use a redirected githubusercontent.com URL, not the github.com raw address

### ISSUE THREAD

**Issue by zgfg** [AdAway/AdAway#2605]
First, let me explain how to add your own hosts source to your Github 'project' and to use it for blocking the sites by AdAway.

The corresponding issue in AdAway on updating that source file will be explained in the subsequent comment.

For the beginning, create a test-hosts.txt source file like:
```
# Test hosts file
0.0.0.0 aaa.bbb1.ccc
0.0.0.0 aaa.bbb2.ccc
0.0.0.0 aaa.bbb3.ccc
0.0.0.0 aaa.bbb4.ccc
0.0.0.0 aaa.bbb5.ccc
```

Upload the file to your Github project:
![upload](https://user-images.githubusercontent.com/51943147/111077802-ca8b2200-84f2-11eb-8aed-f5e6fe85333e.jpg)

![choose](https://user-images.githubusercontent.com/51943147/111076463-a75d7400-84ec-11eb-8c3c-cc63bc0289ea.jpg)

And don't forget to Commit:
![commit](https://user-images.githubusercontent.com/51943147/111076444-94e33a80-84ec-11eb-9842-2d40815f248e.jpg)

Go to and open the uploaded file:
![goto](https://user-images.githubusercontent.com/51943147/111077242-2011ff80-84f0-11eb-93cb-4becc3296905.jpg)

![open](https://user-images.githubusercontent.com/51943147/111077244-27d1a400-84f0-11eb-9f25-f448569881b7.jpg)

To use this hosts source in AdAway, we need to obtain its raw addres - long press to Raw:
![raw](https://user-images.githubusercontent.com/51943147/111077530-7af82680-84f1-11eb-8f79-ad17b28550fb.jpg)
and take Copy link address:
![copy-link](https://user-images.githubusercontent.com/51943147/111076479-b3e1cc80-84ec-11eb-9aa2-aa662846dc14.jpg)

If the file is too big, Github will not open and display the content but we can still obtain its raw address by long pressing to View raw:
![codeberg](https://user-images.githubusercontent.com/51943147/111076942-c2c97e80-84ee-11eb-8a47-c7c92e8278a4.jpg)

E.g., in my case the obtained raw address (URL) was:
https://github.com/zgfg/Etc/raw/main/test-hosts.txt

We can test now if the uploaded test-hosts.txt file is properly available on Internet by pasting its URL to opening from browser:
![browser](https://user-images.githubusercontent.com/51943147/111076426-88f77880-84ec-11eb-855e-da3445d57c48.jpg)

Finally, we can add our test-hosts.txt source file to AdAway (and don't forget to Apply):
![add-github](https://user-images.githubusercontent.com/51943147/111074307-b2130b80-84e2-11eb-804f-1a80b1d5f715.jpg)

That way we have successfully added 5 sites for blocking:
![applied](https://user-images.githubusercontent.com/51943147/111075695-89dadb00-84e9-11eb-8b35-1ab5612c163d.jpg)

And if this was the only hosts source currently enabled in AdAway, we will see on its first screen:
Up-to-date sources 0
Outdated sources 0
Blocked sites 5
![adaway](https://user-images.githubusercontent.com/51943147/111075706-92cbac80-84e9-11eb-9815-76b2ef7b4297.jpg)
![blocked](https://user-images.githubusercontent.com/51943147/111075714-9a8b5100-84e9-11eb-8fb5-225118d64a6a.jpg)

So far, everything looks good (but there are some hidden issues - follow up below)

**Comment by zgfg** [comment]
Now, some issues begin when you press on the icon next to Up-to-date sources:
+up-to-date
![up-to-date](https://user-images.githubusercontent.com/51943147/111072875-c522dd00-84dc-11eb-91e3-cbaee1d73229.jpg)

AdAway will pop-up the error, contamplaining about lost Internet connection:
+pop-up.jpg
![pop-up](https://user-images.githubusercontent.com/51943147/111072906-e5eb3280-84dc-11eb-80ef-9311c1eff5e3.jpg)

Upon this, AdAway displays:
Up-to-date sources 0
Outdated sources 0

Here, 0+0 is not equal to 1, our total number of enabled hosts sources, but our sites are still correctly blocked:
Blocked sites 5
+zero.jpg
![zero](https://user-images.githubusercontent.com/51943147/111072930-fb605c80-84dc-11eb-8348-897a02fd8338.jpg)

However, there was not really any Internet disconnection since if you now press the icon next to Outdated sources:
+outdate.jpg

The AdAway then successfully updates and it will again correctly display:
Up-to-date sources 1
Outdated sources 0

But if you press again to the icon next to Op-to-date sources, AdAway will again pop-up the (Internet disconnection) error, and so on

**Comment by zgfg** [comment]
If you now enable at least one additional 'regular' hosts source in AdAway, e.g. its default adaway.org hosts..txt file, then our statistics will look like:
Up-to-date sources 2
Outdated sources 0

In this case, pressing on the icon next to Up-to-date sources will not pop-up the error, but AdAway will also loose our Github test-hosts.txt fron the counter - we will have:
Up-to-date sources 1
Outdated sources 0
(1+0 is not equal to 2, our total number of enabled hosts sources)

And the same issues (loosing your hosts source file you put to Github) from Adaway's counting will also happen every time when AdAway goes to automatically update the hosts sources

That issue was already discussed in #2570

**Comment by zgfg** [comment]
The problem is actually easy to workaround, although it's not obvious.

If you use curl (have the BusyBox NDK Magisk module installed) from Terminal app, you will see that the raw address we previously obtained by Github is not really the 'correct' one - when getting our file fron that address the Github server actually redirects to:
https://raw.githubusercontent.com/zgfg/Etc/main/test-hosts.txt
```
curl https://github.com/zgfg/Etc/raw/main/test-hosts.txt

<html><body>You are being <a href="https://raw.githubusercontent.com/zgfg/Etc/main/test-hosts.txt">redirected</a>.</body></html>
```
+redirect.jpg
![redirect](https://user-images.githubusercontent.com/51943147/111073348-9e65a600-84de-11eb-880c-83679b7e8d57.jpg)

If you now use that redirected  githubusercontent.com URL, curl will successfully get the test-hosts.txt file from Github:
```
curl https://raw.githubusercontent.com/zgfg/Etc/main/test-hosts.txt

# Test hosts file
0.0.0.0 aaa.bbb1.ccc
0.0.0.0 aaa.bbb2.ccc
0.0.0.0 aaa.bbb3.ccc
0.0.0.0 aaa.bbb4.ccc
0.0.0.0 aaa.bbb5.ccc
```
+redirected.jpg
![redirected](https://user-images.githubusercontent.com/51943147/111073420-dd93f700-84de-11eb-921a-b40eb2b00944.jpg)

And if we finally use that redirected  githubusercontent.com URL in AdAway (instead of the original raw github.com address):
+add-githubusercontent.jpg

Then AdAway will have no troubles with:
- will not loose our file from the Up-to-date  counter upon manual or automatic hosts sources  update
- will not pop-up Failed to download /Internet disconnection errors

**Comment by zgfg** [comment]
![add-githubusercontent](https://user-images.githubusercontent.com/51943147/111073747-27311180-84e0-11eb-9adc-07987fc508db.jpg)

**Comment by zgfg** [comment]
![add-local](https://user-images.githubusercontent.com/51943147/111073889-dff75080-84e0-11eb-9dfe-9c5606c12565.jpg)

**Comment by zgfg** [comment]
Nevertheless, the observed issue with updating the hosts source file from Github when using its original raw address as obtained directly by Github, is a small bug in AdAway and hopefully it could be fixed 🤓

**Comment by zgfg** [comment]
![add-github](https://user-images.githubusercontent.com/51943147/111074307-b2130b80-84e2-11eb-804f-1a80b1d5f715.jpg)

![add-githubusercontent](https://user-images.githubusercontent.com/51943147/111074312-b8a18300-84e2-11eb-9331-416b54e2cbdc.jpg)

![add-local](https://user-images.githubusercontent.com/51943147/111074330-c3f4ae80-84e2-11eb-8336-a4ae8aeb06b5.jpg)

**Comment by zgfg** [comment]
![redirect](https://user-images.githubusercontent.com/51943147/111074756-db349b80-84e4-11eb-816f-0ba5a281ac33.jpg)

![redirected](https://user-images.githubusercontent.com/51943147/111074759-e25ba980-84e4-11eb-977e-a84ad9cdfcfb.jpg)

**Comment by zgfg** [comment]
![up-to-date](https://user-images.githubusercontent.com/51943147/111075053-6a8e7e80-84e6-11eb-8d92-b6244e9bb6fd.jpg)

![pop-up](https://user-images.githubusercontent.com/51943147/111075057-724e2300-84e6-11eb-81cb-06b7783c52f8.jpg)

![zero](https://user-images.githubusercontent.com/51943147/111075066-7aa65e00-84e6-11eb-8748-b3b654f3fa7e.jpg)

**Comment by zgfg** [comment]
![applied](https://user-images.githubusercontent.com/51943147/111075695-89dadb00-84e9-11eb-8b35-1ab5612c163d.jpg)

![adaway](https://user-images.githubusercontent.com/51943147/111075706-92cbac80-84e9-11eb-9815-76b2ef7b4297.jpg)

![blocked](https://user-images.githubusercontent.com/51943147/111075714-9a8b5100-84e9-11eb-8fb5-225118d64a6a.jpg)

**Comment by zgfg** [comment]
![browser](https://user-images.githubusercontent.com/51943147/111076426-88f77880-84ec-11eb-855e-da3445d57c48.jpg)

![commit](https://user-images.githubusercontent.com/51943147/111076444-94e33a80-84ec-11eb-9842-2d40815f248e.jpg)

![codeberg](https://user-images.githubusercontent.com/51943147/111076454-9f053900-84ec-11eb-9372-0ac9cd1e27aa.jpg)

![choose](https://user-images.githubusercontent.com/51943147/111076463-a75d7400-84ec-11eb-8c3c-cc63bc0289ea.jpg)

![copy-link](https://user-images.githubusercontent.com/51943147/111076479-b3e1cc80-84ec-11eb-9aa2-aa662846dc14.jpg)

**Comment by zgfg** [comment]
![codeberg](https://user-images.githubusercontent.com/51943147/111076942-c2c97e80-84ee-11eb-8a47-c7c92e8278a4.jpg)

**Comment by zgfg** [comment]
![goto](https://user-images.githubusercontent.com/51943147/111077242-2011ff80-84f0-11eb-93cb-4becc3296905.jpg)

![open](https://user-images.githubusercontent.com/51943147/111077244-27d1a400-84f0-11eb-9f25-f448569881b7.jpg)

**Comment by zgfg** [comment]
![raw](https://user-images.githubusercontent.com/51943147/111077530-7af82680-84f1-11eb-8f79-ad17b28550fb.jpg)

![upload](https://user-images.githubusercontent.com/51943147/111077534-82b7cb00-84f1-11eb-9264-0bc224cd551b.jpg)

**Comment by zgfg** [comment]
![upload](https://user-images.githubusercontent.com/51943147/111077802-ca8b2200-84f2-11eb-8aed-f5e6fe85333e.jpg)

**Comment by gallegonovato** [comment]
Good afternoon:

Thank you very much for the explanation and help

I wanted to ask you if you check the box:

Apply allowed hosts

Apply redirected hosts

In case the hosts has some redirection or something to allow?

Best regards

**Comment by zgfg** [comment]
Applied Allowed box is for Allowed list, not for Blocked list (but not sure does it work, there are other issues - seems there will be a fix in the new release soon

I use IPv4 redirection from general Preferences (not per particular hosts source), redirecting to 0.0.0.0 (some hosts sources block by resolving to 127.0.0.1 but acoording to discussions in XDA AdAway thread it is better to use 0.0.0.0 - 0.0.0.0 and 127.0.0.1 have different meaning for IPv4 routing).
That way AdAway when creating the resulting hosts file, put 0.0.0.0 for all the blocked sites

**Comment by zgfg** [comment]
@gallegonovato - regarded to Apply redirected hosts option, I'm not sure how it works (seems not working), see #2612

**Comment by gallegonovato** [comment]
Good afternoon @zgfg 

Thank you very much for your time and help. I really appreciate all the time you dedicate to solve doubts and problems and improve Adaway.

About checking the boxes. I would like to say that I check the boxes in all the hosts (or better said) in all the sources or host lists. I have checked the first option. And in the Adaway settings I enable ipv6 support. And if I go to root based adblocker and then to ipv4 redirection I get 127.0.0.1 and in ipv6 ::1

I use the ipv6 thing as many host sources have that option within the lists. Or marked to block also by ipv6. And because ipv6 is the improvement of ipv4 that they use in many places. And I don't know exactly when I connect via WiFi or mobile network which one I use. Although I also read in some felt that it is better to remove ipv6 if it is not used.

At the moment I tell you I did not notice anything strange. And Adaway blocks the things I have on the host. Because if I go to Adaway register dns I do not get. I get other things that if any seems weird or so. I put it to the black list.

I also tell you that I use fennec from fdroid. With ublock origin. And I navigate in advanced user. With the things there blocked. Or the same in my filters or my rules.

I take this opportunity to tell you about a strange thing I noticed. The developer of the codeberg hosts gave me permission to use them in my github (upload and so on) after asking him for permission. So I removed the codeberg sources. Everything loaded fine and so on. But I notice something strange. And it is that when I delete the adaway cache, and pass sd maid (downloaded from github) and lte cleanner (from fdroid) . And then I activate the permission to use the network in Afwall+. As usual. Adaway then updating the hosts is like choking. Or it will not update well. First it takes a while to load the numbers of the total of blocked things (it seems normal to me when clearing the cache), but sometimes when I give it to update some sources I get updated for a few minutes. Having to restart the phone, or give it back to download. 

And this did not do it before. 

Say that I have the latest stable version of fdroid adaway. And magick updated and the version of systemless host that this brings activated.

A warm hug and sorry for being so heavy.

**Comment by zgfg** [comment]
@gallegonovato, I didn't day that there is anything wrong to enable IPv6 Redirection.
I said that AdAway should not allow a user to (by mistake or by his ignorance) to enter any meaningless garbage string (or empty string)  - AdAway should force user to enter a valid IPv4/IPv6 addresses.

Btw, if you disable Web browser option in AdAway, then it is better to redirect IPv4 to 0.0.0.0 than to 127.0.0.1.
127.0.0.1 is an existing address, it stays for localhost which means that apps will try to send packets to the phone itself (although, nothing will happen, packets will not go out to WiFi or Mob Internet).
With the redirection to 0.0.0.0, packets will go nowhere (it is valid but not routable address) and you may save some milluseconds (you will never observe, but still)

**Comment by PerfectSlayer** [comment]
![image](https://user-images.githubusercontent.com/1766222/111356485-b4af6580-8688-11eb-9df5-5847bc941a58.png)
From this picture, you can just click the `raw` link. Once the hosts file content is displayed in your browser, copy the URL from your browser and use it as source URL.

It will work as expected in AdAway 😉

**Comment by zgfg** [comment]
> ![image](https://user-images.githubusercontent.com/1766222/111356485-b4af6580-8688-11eb-9df5-5847bc941a58.png)
> From this picture, you can just click the `raw` link. Once the hosts file content is displayed in your browser, copy the URL from your browser and use it as source URL.
> 
> It will work as expected in AdAway 😉

So please do the experiment exactly as I described:

Copy that URL to AdAway but it must be the SINGLE  hosts source you have enabled in AdAway

Apply and go to the main AdAway window and press the icon next to Up- to-date sources

When I do it, I get that pop-up Update failed, about Internet connection problem - everything as described above

**Comment by zgfg** [comment]
@PerfectSlayer, the screenrecording:
https://mega.nz/file/c5VmVTSL#HbDXRgu8r2eU9G0t8typMnjmVr56HG62DQ9SjErFN7c

**Comment by zgfg** [comment]
Full video - Getting link address from Raw, pasting to AdAway, Applying and obtaining Failed to download from Up-to-date sources:
https://mega.nz/file/ct0ilYbI#yfuBth33dhhZIakUcqNbjIR6r9uoBwCf0U5wDukAe5Q

**Comment by gallegonovato** [comment]
Good afternoon @PerfectSlayer @zgfg 

Thank you very much for your help and tremendous clarification and assistance. And for the tremendous tutorial :)

You guys are the best ;)

I already have the permission from the creator of several codeberg hosts. I am uploading them to github with everything you taught me.

I have only one doubt left. Adaway has a limit on the number of host lists, or on the number of blocked lists.

I found a lot of them interesting :)

By the way @zgfg I was looking and you have a systemless module for magisk. Which is better than the one that comes with magisk. And I don't know if I can put in adaway the lists of hosts that you have?. Not in my github but use them in Adaway?

And if you allow me I wanted to ask you another question. Do you know if there is any host list to block online gambling sites, like casinos and so on. It is that here they do not do but to leave and to leave new tidbits of those. And I would like to block them if possible.

A hug and thanks for your help and time.

**Comment by zgfg** [comment]
@gallegonovato - my SystemlessDebloater is only for 'debloating' system installed apps (e.g. stock apps), it's all described in the OP posts.
It is based on the same Magisk dynamical mounting, but it is not for the hosts file

**Comment by gallegonovato** [comment]
Good afternoon:

Thank you very much for the explanation and clarification 

Best regards
