### ISSUE TITLE
IPv4/IPv6 Redirection options

### ISSUE THREAD

**Issue by zgfg** [AdAway/AdAway#2612]
This issue was maybe already sumbitted - sorry, didn't search for😌

With AdAway 5.4.0 (using root/hosts mode) user can enter any string, or even leave it empty, to IPv4 Redirection and IPv6 Redirection.

E g., I have enabled IPv6 and then edited:
IPv4 Redirection: BLAH
IPv6 Redirection: blah
![ipv4](https://user-images.githubusercontent.com/51943147/111115854-766d5580-8565-11eb-97ed-0a6de246f46a.jpg)
![ipv6](https://user-images.githubusercontent.com/51943147/111115876-7b320980-8565-11eb-8d63-0476aca11cfd.jpg)

As a result, hosts file looks like:
```
BLAH a.stat.xiaomi.com
blah a.stat.xiaomi.com
BLAH a.union.mi.com
blah a.union.mi.com
BLAH abtest.mistat.intl.xiaomi.com
blah abtest.mistat.intl.xiaomi.com
BLAH abtest.mistat.xiaomi.com
blah abtest.mistat.xiaomi.com
```
![blah](https://user-images.githubusercontent.com/51943147/111115816-69e8fd00-8565-11eb-911f-6544871b6d1e.jpg)

Similarly, with:
IPv4 Redirection: (empty)
IPv6 Redirection: (empty)

As a result, hosts file looks like:
```
a.stat.xiaomi.com
a.stat.xiaomi.com
a.union.mi.com
a.union.mi.com
abtest.mistat.intl.xiaomi.com
abtest.mistat.intl.xiaomi.com
abtest.mistat.xiaomi.com
abtest.mistat.xiaomi.com
```
![empty](https://user-images.githubusercontent.com/51943147/111115671-41f99980-8565-11eb-8470-d155c9524755.jpg)

AFAIK, in both cases these are invalid entries in the hosts file.

IMO, app should only allow user to enter valid IPv4/IPv6 addresses

**Comment by zgfg** [comment]
Additionally, I don't see how Add/Edit Source, Apply redirected hosts works - or is supposed to work.
![apply](https://user-images.githubusercontent.com/51943147/111116355-32c71b80-8566-11eb-8b83-041d10988a9d.jpg)

No matter if I enable or leave it disabled (per default), entries in the hosts file are always created according to the IPv4/IPv6 Redirection values (as above)

**Comment by PerfectSlayer** [comment]
> IMO, app should only allow user to enter valid IPv4/IPv6 addresses

Agreed, that is an issue!
I need to improve the validation dialog.

**Comment by PerfectSlayer** [comment]
Unlike the redirection addition dialog, the validation will be done when you validate the dialog.
I can't validate it when typing as it comes from the Android Preferences SDK.

But at least, user input will be validated 👍
