### ISSUE TITLE
Switching orientation allows multiple updates at same time

### ISSUE THREAD

**Issue by SapphireExile** [AdAway/AdAway#2613]
Bug: Updater attempts to download the same update twice

Reproduction:
Start in portrait, open updater, click update. 
Rotate to landscape.
Rotate back to portrait, and the update button will reappear, allowing you to click it.
Clicking it again causes it to download the same update while first one downloads, causing the progress bar to glitch and show the progress of both updates.

**Comment by gallegonovato** [comment]
Good afternoon:

Yes this is a bug that Adaway had in version 4.x. That I already commented at the time to @PerfectSlayer 


But I didn't know that it was reproduced again in the latest version. Since now I have the mobile always activated horizontal position. 

Instead of it rotating by itself.

Thanks for the warning 

A hug

**Comment by PerfectSlayer** [comment]
Hi,

Which version are you using?
It looks like a V4 issue.

**Comment by SapphireExile** [comment]
5.3.0, issue is still present.

**Comment by SapphireExile** [comment]
@PerfectSlayer I could probably do a screen record if that would help narrow it down. This is also a very high DPI device, which could mess with things.

**Comment by PerfectSlayer** [comment]
Oh! The _application_ update screen, not the _source_ update screen! 💡

Okay, I will have a look at it on my side.
Don't bother with more capture, it will be easier to reproduce on my side (I can fake available update easily).

**Comment by SapphireExile** [comment]
That's my bad. I should have specified app update screen. At least updates work now, in the previous versions, it would always download then claim the package is corrupted. That went away in 5.0.x though.
