### ISSUE TITLE
unable to update past 4.3.6

### ISSUE THREAD

**Issue by lemmy04** [AdAway/AdAway#2614]
**Describe the bug**
I'm running adaway on an older Samsung Tab S2 which still runs Android 7, and I can't update adaway from f-droid anymore, I assume this is because in release 5.0.5 the NDK versions got raised?

4.3.6 is the last version that works on this old beast. Any chance to get around this? Or am I good with that old version?

**Comment by gallegonovato** [comment]
Good afternoon:

The latest version asks for more requirements. 

As you can see in https://github.com/AdAway/AdAway . It asks for Android 8 Oreo or above the only thing I can think of is if you could put a lineageos 17.1 for example. Or some other room.

Otherwise I think you can not use the 5.x version of AdAway. 

I do not know if I'm fooled @PerfectSlayer 

A hug

**Comment by lemmy04** [comment]
There is no LineageOS 17 for my tablet... the best that exists for the Samsung Tab S2 is a LineageOS 16 image that has no support for the LTE part, so basically the phone part of the tablet would be dead. I guess I have to simply stick with Adaway 4.x...

**Comment by PerfectSlayer** [comment]
Hi,

Here is a quote from the [V5 FAQ](https://forum.xda-developers.com/t/app-root-nonroot-official-adaway-v5-5-0.2190753/page-726#post-82281687):

_Why does this version targets Android 8+ Oreo only?_
Like the v4, v5 is expected to offer support for latest devices.
Android 8 and above represent more than 60% of device distribution and will grew through time.
If you use an older device, root solutions work very well and v4 is here for you (like v2 and v3 stayed for legacy devices).

As you have an older OS version, there is no need for you to update AdAway.
The V4 will keep working as expected. And if any major issue is found, I will keep pushing updates for it.
Developing V5 for older devices requires too much time time and energy for a single developer on its free time.

Regards

**Comment by lemmy04** [comment]
I can live with this - was just wondering if there was somethign wrong with my tablet...
