### ISSUE TITLE
Handle jcenter shutdown

### ISSUE THREAD

**Issue by PerfectSlayer** [AdAway/AdAway#2615]
There might be issue in the build process as JCenter is shuting down...

See https://blog.gradle.org/jcenter-shutdown

**Comment by gallegonovato** [comment]
Good afternoon:

What a bummer. They want to leave us without Adaway and without free software :(

A hug

**Comment by PerfectSlayer** [comment]
It seems there is still some issues...
See commit message 46838aa630f73723e0f0b599451b432b133bcf0c
