### ISSUE TITLE
Failed to download host source

### ISSUE THREAD

**Issue by iSpaghetti** [AdAway/AdAway#2621]
Hello,

I added [energized pro's whitelist](https://github.com/EnergizedProtection/unblock) and gives me a **failed to download hosts source** error

Ive seen some issues regarding/related to this but i cant seem to know where to start. Can i ask some guidance if there is some workaround or not

Thanks in advance

 - AdAway version: 5.4.0 F-Droid
 - Device: SM-J730G
 - Android version: One UI Android Pie
 - Root version Magisk 22

**Comment by zgfg** [comment]
5.5.0 is the last AdAway version - and in that version the bug with Allowed list was fixed.

If you cannot update to 5.5.0 over FDroid- get rid of and install 5.5.0 directly from Github here

Of the Energized Pro formats, you will need to use:
https://github.com/EnergizedProtection/unblock/raw/master/basic/formats/domains.txt

I just tested, it works, see the screenshots:
![IMG_20210321_223718](https://user-images.githubusercontent.com/51943147/111922128-76ef7a00-8a98-11eb-8ade-64dbc2192426.jpg)
![IMG_20210321_224017](https://user-images.githubusercontent.com/51943147/111922135-7fe04b80-8a98-11eb-8cad-b5a789e437da.jpg)
![IMG_20210321_223847](https://user-images.githubusercontent.com/51943147/111922148-8a9ae080-8a98-11eb-9ea1-64607f86ed2f.jpg)

**Comment by zgfg** [comment]
![IMG_20210321_230429](https://user-images.githubusercontent.com/51943147/111922504-71932f00-8a9a-11eb-9ccb-c9c6271c383d.jpg)

**Comment by iSpaghetti** [comment]
Oh my, i just literally clicked releases and read the changelog for 5.5.0 an hour or so before i opened this. I feel so freaking dumb it didnt even struck me to update it lol

Thank you very much and sorry for the inconvenience
