### ISSUE TITLE
AdAway 5 incompatible with Android 6 and 7

### ISSUE THREAD

**Issue by indig0F10w** [AdAway/AdAway#2673]
Hi, I got the update notification on both devices, tried updating and now I cannot even install again because of incompatibility.

I have two devices, one is a smartphone with Android 6, the other is a virtual Android Lineage OS 7 running in VmWare Workstation. Both devices have root access, on smartphone it was working flawlessly until AdAway version 5x. On Virtual machine I cannot even install AdAway v5.

How can I install on Android 6 and 7?

Thanks.

**Comment by Chilace** [comment]
> How can I install on Android 6 and 7?
https://github.com/AdAway/AdAway/releases/tag/v4.3.6

**Comment by zgfg** [comment]
It is mentioned on GitHub, etc which AdAway versions are for which Android versions. AdAway 5.x requires Android 8 or higher

**Comment by salamvid** [comment]
v4.3.6 It does not blocke in YouTube ads. Is it possible to update the version for Android 6 ?

**Comment by zgfg** [comment]
> v4.3.6 It does not blocke in YouTube ads. Is it possible to update the version for Android 6 ?

AdAway is not for blocking ads in YouTube. Doesn't matter if you use the old v4.3.6 or the latest v5 12

**Comment by salamvid** [comment]
> > v4.3.6 It does not blocke in YouTube ads. Is it possible to update the version for Android 6 ?
> 
> AdAway is not for blocking ads in YouTube. Doesn't matter if you use the old v4.3.6 or the latest v5 12

frinds i want to block ads on youtube .. the adaway working with me only for apps like apps
