### ISSUE TITLE
Regression: downloaded entries mixed into custom block list

### ISSUE THREAD

**Issue by blaueente** [AdAway/AdAway#2679]
**Describe the bug**
I had a small custom block list, which was shown as an extra list, and which I could activate/deactivate. Since a recent update, all entries from the downloaded host lists are integrated with my custom entries into one list, and I cannot distinguish anymore.

**Expected behavior**
Have a separate list for "custom" blocked hosts.
Or maybe even have the possibility of filtering the list entries by the source url/file the entry is coming from, thus allowing again to have something like "custom"

**Comment by zgfg** [comment]
Btw, I'm interested about the 'custom' block list

With which version of AdAway it worked (did it really work with any 5.x)?

How does your hosts source look like - do you have it somewhere on the server that you can provide its URL, or zip and upload it here.
And how is it marked the beginning and end of the 'custom' block?
Is that format with 'custom' block documented somewhere?

**Comment by blaueente** [comment]
Is didn't really follow version, it was before the redesign. I just manually added about 10 rule items in the phone with the "+" button, which I then could individually activate and deactivate. Exactly the same as now, just that it didn't contain thousands of other entries. The allow list, for example still works like this, as it has no predefined entries

**Comment by zgfg** [comment]
Simply create your local file(s) on the phone, like blocked.txt and allow.txt

Enter your blocked and allowed domains, and those you don't want to activate yet prepend with ampersand # (standard commenr sign), not with plus +

Add the blocked.txt to your hosts sources list, by using File type, not URL type

When you want tp enable those commented blocked/allowed rule(s), remove the ampersand in your blocked.txt file # and force AdAway to update the hosts sources 
![IMG_20210404_160717](https://user-images.githubusercontent.com/51943147/113511475-43185800-9560-11eb-9ede-973dae5f8ced.jpg)
![IMG_20210404_160628](https://user-images.githubusercontent.com/51943147/113511488-4dd2ed00-9560-11eb-8618-e6e872b53b8b.jpg)
![IMG_20210404_160535](https://user-images.githubusercontent.com/51943147/113511490-5a574580-9560-11eb-8362-3d6329bc9db6.jpg)

**Comment by zgfg** [comment]
![IMG_20210404_162955](https://user-images.githubusercontent.com/51943147/113512050-2fbabc00-9563-11eb-9638-8f18a680c796.jpg)

**Comment by zgfg** [comment]
![IMG_20210404_163300](https://user-images.githubusercontent.com/51943147/113512128-858f6400-9563-11eb-8d8e-43007b2798de.jpg)

**Comment by armordecai** [comment]
> Simply create your local file(s) on the phone, like blocked.txt and allowed.txt

It was a lot easier to manage custom lists in the AdAway UI in the 4.x versions. There, you could quickly add hostnames just by tapping them in the in-app DNS log, and toggle them on and off just by checking a box. Having to open a file in another app, manually type the hostnames, save the file, switch back to AdAway, and update everything, is a lot more complicated.

I'm actually still using 4.2.9, but accidentally updated to 5.5.0 in F-Droid today and gave it another try, then came here to open a similar issue. This is the last (and biggest) reason I'm still using the older version.

**Comment by blaueente** [comment]
I now found an option that helps: the toggle sources icon on the top right. It is a bit hidden and hard to discover, but it does what I want.

**Comment by TheShanMan** [comment]
I just updated from 3.3 and found this to be extremely frustrating. I've actually updated a few times, tried to get this figured out, gotten frustrated, and went back to 3.3.

Adding separate sources is bad in a couple of ways. 1, they're mixed with downloaded sources when you look at the lists. This could be addressed by adding a way to filter by source. 2, I'm assuming that by using externally created files, the personal lists won't be backed up along with the app by titanium backup.

Or am I just totally misunderstanding how this stuff works?

Love adaway and appreciate that it probably takes a ton of time to maintain, but I'm so tempted to (again) go back to 3.3. :(

Could you please add a "filter by source" option? And could you also add a way to create the personal allow and block list files in a way that they would be "owned" by the app and therefore backed up with it?
