### ISSUE TITLE
AdAway not updating 

### ISSUE THREAD

**Issue by jay-1704** [AdAway/AdAway#2698]
Hi everytime I try to update the app it won't work.
 
![Screenshot_20210405-154718_AdAway](https://user-images.githubusercontent.com/81991531/113619072-850bd180-9626-11eb-8ef9-fc55ae722110.jpg)
![Screenshot_20210405-154658_Package installer](https://user-images.githubusercontent.com/81991531/113619111-905efd00-9626-11eb-81d3-de3dff48e014.jpg)
![Screenshot_20210405-154702_Package installer](https://user-images.githubusercontent.com/81991531/113619132-981ea180-9626-11eb-8ba8-e7dacc91384c.jpg)
![Screenshot_20210405-154708_Package installer](https://user-images.githubusercontent.com/81991531/113619150-9f45af80-9626-11eb-9d7d-19811e657dce.jpg)

**Comment by zgfg** [comment]
Uninstall f-droid version, install from SdAway site, Guthub or XDA, it will update every time with no issue

**Comment by PerfectSlayer** [comment]
I don't know your question but there was an issue in 5.2.0.
It can't detect the store you came from to download the right update so the downloaded version can't always be installed.

A fresh install should do the trick.
You can export your settings before and re-import them after.

Feel free to reopen the issue if it didn't work.
