### ISSUE TITLE
Add app excluding feature on root version.

### ISSUE THREAD

**Issue by lucaslira95** [AdAway/AdAway#2701]
Currently, we can only whitelist apps on vpn adblocking.
I would love to see this feature on root adblocking because root version is lightweight and discrete, and to have a option to choose what apps would have it's ads redirected or not would be even more practical.

**Comment by zgfg** [comment]
It will be nice to have, but if you understand how DNS resolving works by use of hosts file, you will see that it's not possible

Any app that wants to resolve DNS name asks system, and the system reads if that DNS name is blocked (resolved to 0.0.0.0 or 127.0.0.1) in the hosts file.
AdAway does not know and has no control for which app(s) the system uses  entries from hosts file - therefore, AdAway can not exclude a particular app from resolving through the hosts file

**Comment by PerfectSlayer** [comment]
Hi,

@zgfg sums it up very well. App filtering is not possible with the root ad-blocking method.
Root ad-blocking and VPN ad-blocking are a trade-off question 😉
