### ISSUE TITLE
Configuration changed toast in Your Lists covers bottom list item

### ISSUE THREAD

**Issue by MaxPelly** [AdAway/AdAway#2728]
**Describe the bug**
When enabling or disabling multiple items in the Your Lists section a toast is generated saying "Your Configuration changed. You need to apply it". This can not be dismissed without applying the change, but covers the bottom item in the list preventing it from being (un)ticked. The only way around is to either (un)thick the bottom item first (annoying as I tend to start from the top) or do everything but the bottom item, apply, do the bottom one then apply again. 

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'Your Lists'
2. If the list doesn't fill the page add more domains
3. Click on '(un)check any item'
4. Scroll down to 'the bottom'
5. Attempt to (un)check the bottom item

**Expected behaviour**
Either the toast can be swiped aside to dismiss it or the list scrolls further to bring the bottom item above it

**Screenshots**
![Screenshot_20210419-154511_AdAway](https://user-images.githubusercontent.com/17359435/115257480-09327e80-a128-11eb-84c8-6999c8cf5fad.jpg)
![Screenshot_20210419-155315_AdAway](https://user-images.githubusercontent.com/17359435/115257490-0a63ab80-a128-11eb-8d60-bde7fe5165f9.jpg)
![Screenshot_20210419-155315_AdAway](https://user-images.githubusercontent.com/17359435/115257752-4d258380-a128-11eb-9f5a-531b7b0e2b68.png)

**Device**
 - AdAway version: 5.5.1
 - Device: OnePlus 3t
 - Android version:  11 (Lineage OS 18.1)
 - Root version: Magisk 22.1

**Additional context**
Add any other context like logcat about the problem here. Use adb logcat if you have developer settings enabled on your device or use any application like [MatLog](https://play.google.com/store/apps/details?id=com.pluscubed.matlog) to save logs. Include the crash report in the issue in a code block, a file attachment, or put it in a gist and provide link to that gist.

**Comment by zgfg** [comment]
Yes, it's little annoying. To avoid, I press the back button to go to AdAway main screen, then I enter again Hosts sources screen (Apply config disappears) and check/uncheck/edit that last item, then Apply pops again and I accept

**Comment by PerfectSlayer** [comment]
Hello @MaxPelly 

I agree the toast is not optimal but it comes as is from the Google material design library.
Moreover, nearly nobody know but you can simply swipe it to make it disappear. (for me the real issue is there is no affordance for this interaction).

This issue was already reported but I can't find a better way to integrate the _apply_ feature.
