### ISSUE TITLE
Zgfg promotion

### ISSUE THREAD

**Issue by PerfectSlayer** [AdAway/AdAway#2734]
Hi @zgfg

I see you particularly active on the project issues.
I wonder if you would like to be part of the team and have rights on the repository?

If you are interested, I can give [the `triage` GitHub permission](https://docs.github.com/en/organizations/managing-access-to-your-organizations-repositories/repository-permission-levels-for-an-organization#repository-access-for-each-permission-level) on the repository so you can freely close issue, manage labels, mark them as duplicate, etc... I saw you in action the past weeks and I trust you to make a good use of it.

I wasn't sure how to reach you but feel free to answer to this issue or reach me by XDA, Twitter DM or even avian carrier if it suits you 😉 
Regards

**Comment by zgfg** [comment]
Cheers. I cannot take officially since of the overload at work. If/when I have a time I comment/answer something (to relax myself) BR

⁣Get BlueMail for Android ​

**Comment by PerfectSlayer** [comment]
I wasn't asking you to do commit to the project or do more!  
It is more a recognition of what you already did 😅 

Anyway, don't hesitate if you ever interested. But take care of yourself first 😉
