### ISSUE TITLE
Amazon App doesn't load pages when AdAway enabled

### ISSUE THREAD

**Issue by sleblang** [AdAway/AdAway#2767]
Amazon content will not load in the Amazon App when AdAway is enabled. The page initially loads and then I get their custom error screen.  Pausing restores functionality. 

![Screenshot_20210430-073927](https://user-images.githubusercontent.com/2072042/116711152-6e3b6f00-a987-11eb-90ec-8c8116f2725d.jpg)

**Comment by slimline33** [comment]
Same problem here.

**Comment by guest4711** [comment]
Disable integrated webserver of AdAway.

**Comment by sleblang** [comment]
> Disable integrated webserver of AdAway.
> […](#)

How is that done? I don’t see an option for it?

**Comment by slimline33** [comment]
@guest4711 thanks. this solve my problem.
@sleblang in the settings disable the integrated webserver!

**Comment by sleblang** [comment]
> @guest4711 thanks. this solve my problem.
> @sleblang in the settings disable the integrated webserver!
@slimline33 I don't have settings. Only preferences and it's not there.

**Comment by reclaimist** [comment]
> > @guest4711 thanks. this solve my problem.
> > @sleblang in the settings disable the integrated webserver!
> 
> @slimline33 I don't have settings. Only preferences and it's not there.

Same issue, Amazon crashing, no option for disable webserver. Preferences are sparse. 
![Screenshot_20210519-000428](https://user-images.githubusercontent.com/84438172/118770937-c2bf6500-b836-11eb-9405-5ad24da5163d.png)

**Comment by sleblang** [comment]
> Edit: The option is under "root based ad blocker". Unchecking webserver does fix Amazon.

That fixed it. Thank you.
