### ISSUE TITLE
Fastlane directory uses invalid names for some locales

### ISSUE THREAD

**Issue by linsui** [AdAway/AdAway#2776]
**Describe the bug**

[Fastlane](https://github.com/fastlane/fastlane/blob/633860a5aae0fa9c0b936797560efb24181b1bf7/fastlane_core/lib/fastlane_core/languages.rb#L14) uses [BCP47](https://www.w3.org/International/articles/bcp47/) locale tags without `r`. Please rename those dirs. Thanks!

**Additional context**

For reference: F-Droid downstream [issue](https://gitlab.com/fdroid/fdroiddata/-/issues/2323).

**Comment by PerfectSlayer** [comment]
Hello @linsui 

Thanks for the heads up! I will see the impact for transifex first then update the locale tags.

**Comment by PerfectSlayer** [comment]
I fixed it.
I hope everything is fine for you @Vankog 👍

**Comment by linsui** [comment]
Thanks!
