### ISSUE TITLE
Pause does not work in VPN mode

### ISSUE THREAD

**Issue by Martin-Maat** [AdAway/AdAway#2788]
When using root mode I can temporarily pause blocking. It restores the default host file and I get ads again. I can tell this works when I am playing a game (Idle Miner). With blocking enabled the game will tell me "no video available" when I choose to double my points in exchange for watching a video. After I paused I do get videos.

However... when I install AdAway and choose VPN blocking, pausing seems to have no effect whatsoever. The game will keep telling me "no video available".

I get this behavior with LineageOS 16 on my tablet (Samsung Galaxy Tab S2). The AdAway version is 5.6.0.

**Comment by PerfectSlayer** [comment]
Hi,

I just tried myself and everything seem to work fine.
I tried to pause using the home screen button and the notification and both worked.

You can reproduce the test by:
- Pick a site / domain to test (ex. github.com),
- Add it to blocked list,
- Navigate to the site using your browser: it should be blocked,
- Pause the ad blocking,
- Refresh the page in your browser, it should load,
- Resume the ad blocking,
- Refresh the page in your browser, it should be blocked again.

If this test works, it means your game must cache domain resolution or ads resources somewhere and does not retry to fetch it after pausing the ad blocking.

**Comment by Martin-Maat** [comment]
Thank you for looking into it. Fortunately it is not a problem for me, I
only picked VPN to try it after I had to reinstall anyway to successfully
update to 5.6.0.

Your suggestion that the game caches domain information does not make sense
to me. This would explain that it shows ads despite of AdAware being on,
not the other way around.

Anyway, if I am the only one experiencing this it may be something in my
tablet after all.

Regards, Martin.

**Comment by PerfectSlayer** [comment]
Alright. We will see if anyone face the issue later.

Regards
