### ISSUE TITLE
YouTube Watch History Bug

### ISSUE THREAD

**Issue by denzhaummer** [AdAway/AdAway#2789]
**Describe the bug**
My YouTube watch history does not work when the "Steven Black Hosts" filter is active in the Adaway app.

**Device**
 - AdAway version: [e.g. 5.6.0]
 - Device: [e.g. Samsung Galaxy J7 Pro (2017)]
 - Android version: [e.g. 9 (Pie)]
 - Root version: [e.g. i don't know]

**Comment by Sourav2005** [comment]
I was just about to post this bug, and yes the solution appears to  be steven hosts.

**Comment by PerfectSlayer** [comment]
See #2071

**Comment by denzhaummer** [comment]
@PerfectSlayer Thank you so much
