### ISSUE TITLE
The backup file cannot be imported using the Document App

### ISSUE THREAD

**Issue by Vstory** [AdAway/AdAway#2809]
**Describe the bug**
The backup file cannot be imported using the Document App(com.android.documentsui).

**To Reproduce**
1. Open settings
2. Choose to restore backup
3. adaway invokes the file selector, and selects the document application(com.android.documentsui) at this time.
4. The backup file cannot be selected, it is grayed out.

**Expected behavior**
Use the document application(com.android.documentsui) to restore the backup.

**Screenshots**
![Screenshot_2021-05-29-13-51-14-325_com android documentsui](https://user-images.githubusercontent.com/20795557/120059587-19257280-c085-11eb-925f-3a1f438c7dbb.jpg)

**Device**
 - AdAway version: 5.6.0(50600)
 - Device: Xiaomi Note 3
 - Android version: 9.0
 - Root version: Magisk 23.1

**Additional context**
Other programs that use the document application can select the file correctly.
For example, [KeePassDX](https://github.com/Kunzisoft/KeePassDX)

Do not use the document application, use [ZArchiver](https://play.google.com/store/apps/details?id=ru.zdevs.zarchiver.pro), adaway can select the file and restore it.

**Comment by Vstory** [comment]
#2411

**Comment by zgfg** [comment]
For me it works flawlessly.
AdAway 5.6.0, Magisk 23001, Xiaomi Mi 9T, A11, MIUI 12.6

![IMG_20210531_065800](https://user-images.githubusercontent.com/51943147/120142084-f22e8400-c1dd-11eb-8b6b-235e0b20cc93.jpg)

**Comment by PerfectSlayer** [comment]
Hello, 

I am sad to see this issue back... There must really be something strange.

So I run some tests again. I spawn an Android 9 emulator and Android platform does not describe json files with `application/json` but `application/octect-stream`, which is wrong according [the MDN documentation](https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/MIME_types/Common_types).

I can make a work-around to allowing both mime types but it will allow a lot of file AdAway can't import (all the binary files...).
I want to find the bogus platforms first. It seems to be Android 9 / SDK 28 (Android 10 and 11 are fine) but I will need to test Android 8 and 7...

Stay tuned!

**Comment by PerfectSlayer** [comment]
As you can see in the commit attached below, Android behavior is not consistent across all versions...
I had to setup different types of filter for different Android versions. I hope it will fix your issue in the next release 😉 

Regards

**Comment by Vstory** [comment]
Thank you!
