### ISSUE TITLE
Ordergroove compatibility report

### ISSUE THREAD

**Issue by remitaffin** [AdAway/AdAway#2815]
**Describe the third party app**
 - Name: Ordergroove
 - Version: (web SaaS)

**Describe the compatibility issue**
[Ordergroove](https://www.ordergroove.com/) is a SaaS company with the goal of providing convenience to their customers' life by enabling Relationships Commerce via Subscriptions, custom SDKs and sms reordering experiences.
Ordergroove integrates with big brands such as GNC, L'oréal, Pepsi, Home Depot as well small SMBs in order to provide the best customer experience and also enable the best deals for the brands' customers.
While Ordergroove injects dynamic content to load the subscriptions modal inside the product page (via static.ordergroove.com), Ordergroove is fully integrated as a white label SaaS and is in no way providing ads or irrelevant content to the customers (see screenshot below).
For that reason, I believe that static.ordergroove.com should not be part of the [current AdAway block list](https://adaway.org/hosts.txt). For reference, it is not part of any other block list on the market.
I would be happy to answer any questions you may have about the value we provide the customers and why static.ordergroove.com shouldn't be part of the block list.
Thanks a lot!

**Workaround**
The following domain needs to be removed from the block list for the subscription modal to load successfully:
 - static.ordergroove.com

<img width="1391" alt="Screen Shot 2021-06-02 at 1 13 23 PM" src="https://user-images.githubusercontent.com/9221626/120524666-4df73980-c3a5-11eb-892f-323a89f8256d.png">

**Comment by remitaffin** [comment]
Good morning! Do you have any update on the above?

**Comment by remitaffin** [comment]
@jawz101 Any update on the above?
Would it be possible to remove static.ordergroove.com from the list?

Thanks and have a great day!

**Comment by jawz101** [comment]
removed.  thanks

**Comment by remitaffin** [comment]
Thanks a lot! I'll close this issue then.
