### ISSUE TITLE
Blocking YouTube ads?

### ISSUE THREAD

**Issue by ItzSwapnil** [AdAway/AdAway#2829]
I am certain that adaway should be able to block YouTube ads but idk I did something wrong or what I still see YouTube ads 

'''Yes,My phone is rooted
And all of the sources are updated'''
Thanks

**Comment by zgfg** [comment]
Not a 'bug'

Please read and learn elswhere how YT uses different technology: not pushing its ads from some additional servers (ad-blockers like AdAway, DNS66, Blokada block those servers, just like if you block those servers by a firewall or Private DNS), but YT pushes its ads as ENCODED INSIDE the AUDIO-VIDEO STREAM - hence those ads can only be blocked by a special application that acts like a YT player but filters out the adds from a received and decoded stream

Google to find such apps (like YT Vanced) that do just that - they replace the official YT player, and they remove ads from the stream before displaying the video

**Comment by zgfg** [comment]
Btw, such 'bugs' for YT have also been reported here (and closed)

Before submitting a 'bug', research through the previously reported ones

**Comment by prorounak2005** [comment]
Bro download youtube vanced manager from here - https://github.com/YTVanced/VancedManager
Tutorial - https://youtu.be/TQ2DAfTWIkI?t=105
