### ISSUE TITLE
Failed to install new hosts file 

### ISSUE THREAD

**Issue by Khang5687** [AdAway/AdAway#2846]
I can't get adaway to work, it just says failed to install new hosts file. My device is system as root, I also installed systemless host module on magisk and restarted multiple times but still cannot get it to work

1. Go to the app
2. Click on AdAway button at the bottom
3. See error

**Expected behavior**
The color turning from grey to red

**Screenshots**
![image](https://user-images.githubusercontent.com/22163416/124372088-497ab500-dcb2-11eb-9659-1b3eaac5d4d4.png)

**Device**
 - AdAway version: 5.7.0
 - Device: Oneplus 8T
 - Android version: 11
 - Root version: Magisk 23.0 (23000)

**Additional context**
![image](https://user-images.githubusercontent.com/22163416/124372205-564bd880-dcb3-11eb-819b-87759c15dbb8.png)

**Comment by guest4711** [comment]
Did you grant root privs to AdAway (see Magisk Manager -> SuperUser)?

**Comment by Khang5687** [comment]
Yes I did and I also tried to revoke and give it access again but still no luck
![Screenshot_20210704-171503](https://user-images.githubusercontent.com/22163416/124381226-78f9e380-dceb-11eb-95b0-cadf5277b1be.jpg)

**Comment by Khang5687** [comment]
It seems like whenever an app does an action that reauires root pernission, magisk will show a notification saying "xxx was granted superuser rights"
But when I click on the button to activate adaway, it doesn't show such notification

**Comment by Khang5687** [comment]
Solved, it's funny that adaway was enabled in magisk hide for some reason

**Comment by idanny76** [comment]
I have the same issue, but the app is not in the hide list. Any suggestions?

**Comment by TheRealIndru** [comment]
I am having the same issue. Any ideas?

**Comment by Zero-Ace5** [comment]
same issue. Using Kernel SU.
