### ISSUE TITLE
NikGApps-like flashable AdAway package?

### ISSUE THREAD

**Issue by justkamiii** [AdAway/AdAway#2847]
Heya! I was wondering if there is a chance of getting the latest version of AdAway in something like a flashable .zip that can be installed via a recovery like TWRP. I'm currently using Magisk to use AdAway, the only problem is that I'm gonna be uninstalling Magisk soon due to MagiskHide not working properly. I know I can use the VPN choice, but I use VPNs in my phone from time to time, and also from what I saw, it's slower. I've checked the NikGApps website, and it does indeed have a flashable package for AdAway, but the only issue is that it is an outdated version

**Comment by soorajsprakash** [comment]
Hey, try this for magisk issue:
Flash magisk canary instead of magisk stable, and hide apps using magisk hide. If needed repackage magisk app (hide app) from magisk settings. 

I couldn't even pass basic integrity, but after doing this most banking apps works.

**Comment by justkamiii** [comment]
Hey @soorajsprakash , what I ended up doing is just figuring out that SafetyNet wouldn't disappear even by removing Magisk because of my unlocked bootloader, and I found out how to use the MagiskHide Props Config module. It worked like a charm to bypass SafetyNet, and this issue is irrelevant now. If you have telegram, DM me as @justkamiii and I can tell you how to do it.
