### ISSUE TITLE
No internet after swichig from mobile data to Wifi or back 

### ISSUE THREAD

**Issue by Marcopolox13** [AdAway/AdAway#2854]
Hey

since I use the app in VPN and not in root mode I have problems with my internet when I go out of wifi in mobile data or back or in general when my puplic IP is chnaging.

I can't connect to anything then, first after I pause and resume AdAway my internet works again.

I use the app on my Google pixel 3a with latest Android 11, stock firmware and unrooted.

**Comment by nanawel** [comment]
I think this is a duplicate of #2154.
