### ISSUE TITLE
Not triggering File Storage Permission

### ISSUE THREAD

**Issue by sillypoint69** [AdAway/AdAway#2855]
**Describe the bug**
Cannot Add source {Type: File} as user is not able to give access to File Storage Permission to the app.

**Expected behavior**
App should ask for File Storage Permission of the device in order to access host file in order to add to the source.

**Screenshots**

![Screenshot_20210719-230842_Settings](https://user-images.githubusercontent.com/54402828/126202998-761768a8-8d78-4676-8bc1-bcbbbe8d38d6.png)

**Device**
 - AdAway version: [5.7.0{latest} ]
 - Device: [Redmi Note 5 pro {Evolution X custom ROM}]
 - Android version: [11]
 - Root version: [ Magisk 23.0]

**Comment by mcfisch** [comment]
I have the same issue on the CherishOS ROM from 2021-07-20 for the OnePlus 6T. It happens with AdAway 5.6.0 as well as 5.7.0. However, it was working on the previous release of the ROM with the same app versions, so I'm not sure if this is actually an app problem, and not something wrong with the ROM.

**Comment by mcfisch** [comment]
I was able to get around the issue by installing AdAway 5.5.1 from F-Droid first, which for whatever reason allowed the hosts file to be created even though the app still didn't ask for storage permissions (though I don't remember if it ever did before). And update to 5.7 didn't break anything, even after a reboot it still works.

I still don't know who's at fault here - the app or the ROM... 🧐

**Comment by sillypoint69** [comment]
> I was able to get around the issue by installing AdAway 5.5.1 from F-Droid first, which for whatever reason allowed the hosts file to be created even though the app still didn't ask for storage permissions (though I don't remember if it ever did before). And update to 5.7 didn't break anything, even after a reboot it still works.
> 
> I still don't know who's at fault here - the app or the ROM... 🧐

Thanks for the suggestion and I too tried installing v5.1 but still the same problem exists in my phone. The app keeps crashing upon clicking file button.

**Comment by sillypoint69** [comment]
The fault of app crashing was that I had uninstalled default system File manager. 
Dirty Flashing or installing the default file manager apk and moving it into system app solved the problem.
Thankyou. This issue is closed.
