### ISSUE TITLE
Web server certificate has too long a validity period

### ISSUE THREAD

**Issue by rany2** [AdAway/AdAway#2875]
The minimum validation period for most devices is 2 years and 3 months. It seems like AdAway uses ~10 years for the validity of its MITM certificate which means that web browsers, apps, etc. would reject it. Chromium for example rejects it with the error: `ERR_CERT_VALIDITY_TOO_LONG`.

For instance for Apple https://support.apple.com/en-us/HT210176 : 

> TLS server certificates must have a validity period of 825 days or fewer (as expressed in the NotBefore and NotAfter fields of the certificate).

Edit:

According to [Servertastic](https://support.servertastic.com/knowledgebase/article/neterr_cert_validity_too_long-the-server-certificate-has-a-validity-period-that-is-too-long), Chromium returns this error for certificates with a validity period greater than 39 months which I guess is more forgiving than Apple's limit. However, I guess I would go with Apple's limit because its lower.

**Comment by PerfectSlayer** [comment]
Thanks for the head up.
I will have a look for the next release.
