### ISSUE TITLE
[Amazon] compatibility report

### ISSUE THREAD

**Issue by jojos38** [AdAway/AdAway#2880]
**Describe the third party app**
 - Name: Amazon
 - Version: 22.14.0.100

**Describe the compabitily issue**
All pages doesn't load on the application (Oops, an issue went out) 

**Workaround**
Disabling the web server fixes the issue but I want to keep it, it's very useful

**Comment by milindgoel15** [comment]
Whitelist `*amazon*` and `*aws*`

**Comment by jojos38** [comment]
Imma try thank you

**Comment by jojos38** [comment]
It worked, thank you very much!
