### ISSUE TITLE
[Idea] Ability to whitelist apps

### ISSUE THREAD

**Issue by milindgoel15** [AdAway/AdAway#2881]
As the title says, we would appreciate an option/feature which lets us whitelist apps directly in adaway as to make apps work which rely/doesn't work without whitelisting URLs. 

A perfect example would be Amazon app when used with default sources(I suspect Stevenblack host) which makes it unusable causing unexpected error (referencing various Amazon issues such as #2436).
Another example is YouTube app using this same host, breaks watch history.

We know that whitelisting URLs can make those apps work but when we whitelist a URL, it affects every other app as well which displays ads by showing us ads of Amazon. Hence, whitelisting an app would be better that way instead of whitelisting URL.

Sorry, if this idea was already created by someone. I did searched using the keyword "whitelist" but didn't found any.

**Comment by phineas-pta** [comment]
there is that feature: preferences > vpn based as blocker > exclude user app

**Comment by milindgoel15** [comment]
u are forgetting that not everyone uses VPN based blocker. but thanks for reply

**Comment by PerfectSlayer** [comment]
Hi,

It already was discussed in other issues. It is not doable in root mode using `hosts` file because there is no context of the app when resolving the domains to block.

Only VPN mode can achieve this because it provides API to select which app can bypass the VPN proxy.

Regards

**Comment by milindgoel15** [comment]
Ah, is there a way that I could use while using root mode? Some app or thing?

**Comment by phineas-pta** [comment]
nope, in root mode it's system-wide
