### ISSUE TITLE
Cannot download AdAway Stable Build or Beta Build anyway

### ISSUE THREAD

**Issue by Duy-Thanh** [AdAway/AdAway#2924]
Cannot download AdAway Stable Build or Beta Build on AdAway Website anyway

When I visit in AdAway Beta website located in: https://app.adaway.org/adaway.apk?channel=beta, I can't download AdAway APK file and get this error:

Fatal error: Uncaught PDOException: SQLSTATE[HY000] [1045] ProxySQL Error: Access denied for user 'hardcodiblog'@'10.20.103.233' (using password: YES) in /home/hardcodi/adaway/public/index.php:11 Stack trace: #0 /home/hardcodi/adaway/public/index.php(11): PDO->__construct('mysql:host=mysq...', 'hardcodiblog', 'dbHard42') #1 {main} thrown in /home/hardcodi/adaway/public/index.php on line 11

I have factory reset and re-rooted my phone and I want to download Beta application to use lastest features. Please help me.

**Comment by adlainewson** [comment]
I have the same problem, temporarily you can get AdAway from here https://f-droid.org/packages/org.adaway/

**Comment by Duy-Thanh** [comment]
> I have the same problem, temporarily you can get AdAway from here https://f-droid.org/packages/org.adaway/

Thanks for your feedback @adlainewson, this method of using the F-Droid store worked for me. However, this is still an inconvenience for beta users like me, so I hope they fix this soon. But for now, we should use F-Droid as an alternative while we wait for them to fix it.

Once again, thank you very much.
