### ISSUE TITLE
Support for Shizuku/Sui

### ISSUE THREAD

**Issue by TriStaRvOiD** [AdAway/AdAway#2932]
Support for Shizuku/Sui apart from su could help increase AdAway's performance by some extent. With Shizuku support, AdAway may be able to modify the hosts file even on those devices which aren't rooted.

(Shizuku : https://github.com/RikkaApps/Shizuku
Sui : https://github.com/RikkaApps/Sui)

**Comment by PerfectSlayer** [comment]
Are you sure adb access is enough to write the `hosts` file? Have you tried it?

About the performance part, Magisk is only use to copy a file. I don't think the impact will be significant.

**Comment by TriStaRvOiD** [comment]
> Are you sure adb access is enough to write the `hosts` file? Have you tried it?
> 

I had come across these sites with guides saying how to edit the hosts file using adb.

I personally haven't tested it on my phone yet, I'll try it out and update this comment

> About the performance part, Magisk is only use to copy a file. I don't think the impact will be significant.

I in general have always found Shizuku fast in most cases, so I assumed that it would speed up things. But regardless of whether or not there is a performance boost, AdAway being able to do it's thing without root would be great.

**Comment by TriStaRvOiD** [comment]
> > I had come across some sites with guides saying how to edit the hosts file using adb.
> 
> Could you send me one? I only found guides that use "su" commands.
> 
> Moreover, is Shizuku providing something similar to Magisk overlay FS? Because most of system partition are read-only now.

Tested it, yeah.. it doesn't work. My bad, I should've done this before creating this feature request.

Apparently the guide I came across is from 2017. I guess some things have changed since then.

This one:-
https://www.howtogeek.com/140576/how-to-edit-the-hosts-file-on-android-and-block-web-sites/

Closing this now

**Comment by giathinhk52005** [comment]
> AdAway being able to do it's thing without root would be great.

Can you somehow elaborate on how adAway works with shizuku?

**Comment by lucasdaweb95** [comment]
> > AdAway being able to do it's thing without root would be great.
> 
> Can you somehow elaborate on how adAway works with shizuku?

essentially, it runs a local vpn that males all network traffic to go thru the app, instead of directly going to the router
