### ISSUE TITLE
[Youtube Vanced don't record the history 

### ISSUE THREAD

**Issue by HakanDOGAN1981** [AdAway/AdAway#2937]
Hello,
I have a root permission.
I have already open record the history on YouTube Vanced. 
But Youtube Vanced don't record the history.
When i stop the Adaway, Vanced record the history fine. 
Can u fix it? 

**Describe the third party app**
 - Name: [e.g. WhatsApp]
 - Version: [e.g. 1.12.3]

**Describe the compabitily issue**

**Workaround**
If applicable, describe the whitelist domains to add to fix the issue:
 - www.somedomain.com
 - *.server.org

Please add tag `workaround-available` if a work around is available.

**Comment by NayamAmarshe** [comment]
Add `s.youtube.com` in your Allowed list.

**Comment by HakanDOGAN1981** [comment]
Thanks. İt is working.

16 Eki 2021 Cmt 04:55 tarihinde NayamAmarshe ***@***.***>
şunu yazdı:

**Comment by PerfectSlayer** [comment]
Duplicate #665
