### ISSUE TITLE
The option Block Connections without VPN does not work

### ISSUE THREAD

**Issue by ianmazurek** [AdAway/AdAway#2957]
**Describe the bug**

¡Hello @PerfectSlayer! , when I use the option of VPN Always Active and Block Connections without VPN, The Application leaves me without internet, that is, it stops working but keeps me connected to the VPN.

**To Reproduce**
1. Go to 'Settings VPN'
2. Active 'Block Connections without VPN' 
3. I lose my internet connection.

**Screenshots**
![Screenshot_20211028-231705~2](https://user-images.githubusercontent.com/78317379/139363349-bbb10f62-12df-4431-9b3d-93df30c30046.png)
![Screenshot_20211028-232425~2](https://user-images.githubusercontent.com/78317379/139363672-8968229d-6d8b-4bb5-b0c7-a1148278e915.png)

**Device**
 - AdAway version: 5.8.0
 - Device:  Moto E6S
 - Android version: 9.0
 - Root version: No Root

**Comment by PerfectSlayer** [comment]
Hello @ianmazurek 

Thanks for your comment. I think the main reason is how AdAway uses the VPN API.
In fact, it only captures the DNS traffic through the VPN to intercept requests then allow or block them according your blocking list (or answer itself in case of a redirection).

If you send all your traffic to the VPN, AdAway will drop packets that are not DNS related (including the usual HTTP requests to browse website) as it has nothing to do with them. So you won't "have internet" (except DNS) if you enable this option.

```
┌──────────────────┐   ALL INTERNET TRAFFIC EXCEPT DNS                   ┌───────────────────┐
│                  ├────────────────────────────────────────────────────►│                   │
│                  │                                                     │                   │
│                  │                                                     │                   │
│     DEVICE       │   DNS REQUEST  ┌───────────────┐ ALLOWED DNS REQ    │     INTERNET      │
│                  ├───────────────►│               ├───────────────────►│                   │
│                  │                │   DNS API     │                    │                   │
│                  │◄───────────────┤               │◄───────────────────┤                   │
└──────────────────┘   DNS ANSWER   │               │ ALLOWED DNS ANSWER └───────────────────┘
                                    └───┬──────┬──┬─┘
                                        │      │  │
                                        │      │  │
                              ┌─────────┴──┐   │  │  BLOCKED DNS REQ
                              │            │   │  └──────────────────►xxx
                              │   USER     │   │     NOT DNS PACKET   xxx
                              │   DOMAIN   │   └─────────────────────►xxx
                              │   LISTS    │
                              │            │
                              └────────────┘
```

The main reason AdAway does not handle all the packets is performance.
So it is not a bug but a design choice. I hope the drawing make it clear for you.

Regards
