### ISSUE TITLE
Can't install version 5.9.0

### ISSUE THREAD

**Issue by Neutronoid** [AdAway/AdAway#3001]
I get "App not installed" everytime.

**Comment by Kiina** [comment]
Have you tried uninstalling the old version, downloading the apk and installing it? I can't install via the included updater either but removing the app and installing the apk for 5.9 works

**Comment by mangkoran** [comment]
The issue title should be revised to better reflect the issue described. I also encounter this issue when updating through in-app updater.

**Comment by Neutronoid** [comment]
My problem is not just with the in-app updater, I tried install with apk file but it also fail. The issue was only solved after I uninstalled the old version.
