### ISSUE TITLE
[Feature Request]Add IP blocklist support in AdAway?

### ISSUE THREAD

**Issue by Rexadev** [AdAway/AdAway#3007]
I tried CIDR, json,plain-list in .txt nothing worked.

**Comment by BigmenPixel0** [comment]
It's unreal in root mode.

**Comment by Rexadev** [comment]
> It's unreal in root mode.

What I don't understand. I tested is on root method

**Comment by BigmenPixel0** [comment]
> > It's unreal in root mode.
> 
> What I don't understand. I tested it on root method

AdAway uses the "hosts" file. In it, you can only set a different IP address for the domain.

**Comment by NSTAdventure** [comment]
> I tried CIDR, json,plain-list in .txt nothing worked.

if you want block host and ip

you can use RethinkDNS is FOSS and free
support for non root mode with VPN idk with root
