### ISSUE TITLE
AdAway blocks downloads from the Google Drive app

### ISSUE THREAD

**Issue by Bouboulov** [AdAway/AdAway#3008]
Obviously i can't download files stored on my Google Drive. 

It's not so important, it just needs to put AdAway on pause but what causes this ?

Thanks.

**Comment by CaptainFrosty** [comment]
You need to run a DNS test in the app and figure out what google hostnames you need to whitelist. Or just use less restrictive blocklists that don't block google services unrelated to advertisement and tracking.

**Comment by Bouboulov** [comment]
Thanks !

**Comment by CaptainFrosty** [comment]
@Bouboulov Hope it was successful. I don't recall exactly what URLs Drive uses, but I imagine probably drive.google.com, googleapis, gstatic, googleusercontent. Probably will need some asterisks in the whitelist rules to get it all.

**Comment by CaptainFrosty** [comment]
Oh and I take back what I said about less restrictive blocklists...these days the overkill is necessary it seems. But some disagree. Many just don't have the patience to weather the hit to their "quality of life." It's not a burden to me though. Making exception rules fairly often keeps me on my toes. I get antsy with a quiet firewall.
