### ISSUE TITLE
App gets killed in background in Android 12

### ISSUE THREAD

**Issue by the-Alpha18** [AdAway/AdAway#3015]

**Comment by the-Alpha18** [comment]
It happens only on the root-based ad blocker.

**Comment by immanuelgracious** [comment]
Try turning off Battery optimistisation

**Comment by the-Alpha18** [comment]
I think it's an issue with the android version itself. Android 12 has more severe background restrictions even when not optimised. Any notification showing background service like the one Greenify has would definitely help.

**Comment by PerfectSlayer** [comment]
Hi,

How do you notice the app gets killed?
Because using root-based ad-blocking, you should need to have it running in the background.
Only source update is running from times to times using Google work-manager library.

Regards
