### ISSUE TITLE
Can't change the target hosts file

### ISSUE THREAD

**Issue by rna98mod** [AdAway/AdAway#3070]
There is no option for change the target hosts file in preferences menu. I wanted to change the target hosts file to /data/hosts/ because my system partition is not enough for the hosts file.

AdAway 5.10.0

![Screenshot_2021-12-10-03-24-24-0147390348](https://user-images.githubusercontent.com/72114467/145470319-f53a287f-a462-4a6e-a549-3b26b90be1ff.png)

My Device :
Lenovo K520
ZUI 3.7.208
Android 8.0

Thank you in Advance.

**Comment by HuskyDG** [comment]
If you are using Magisk, enable the Systemless hosts

**Comment by rna98mod** [comment]
I have enable the systemless hosts module, but still can't find the option.
