### ISSUE TITLE
Fast.com not working due to blocked Netflix subdomain

### ISSUE THREAD

**Issue by hcuk94** [AdAway/AdAway#3073]
Fast.com loads but fails to initiate a speed test. 
Upon investigation this is due to ichnaea-web.netflix.com being blocked.
Please could this subdomain be reviewed to potentially be removed from the block list?

**Comment by maxreuben** [comment]
On AdAway 5.11.0, fast.com works(loads and initiates speedtest) even with ichnaea-web.netflix.com blocked.

**Comment by hcuk94** [comment]
Looks good to me now - maybe it was a red herring. Thanks.
