### ISSUE TITLE
[Feature Request] Copy button for selected items in blocked list and Allowed list

### ISSUE THREAD

**Issue by Mark-Joy** [AdAway/AdAway#3095]
1. Please add copy button for selected items in Blocked list and Allowed list.
Example: I have Blocked list as: 
```
abc.com
xyz.org
```

I want to be able to select item `abc.com` and copy its text. Could also select and copy multiple items if possible.

2. If Blocked list is a hyperlink, its item can't be selected. Please make it selectable, so that its text can be easily copied.

**Comment by omarhuseyni0** [comment]
I agree

**Comment by PerfectSlayer** [comment]
It has been implemented for the next version.

You will be able to copy a hosts by long pressing it from the blocked/allowed/redirected list and the dns log as well.

Regards
