### ISSUE TITLE
Network connection stops working while crossing wifi->mobile data->wifi

### ISSUE THREAD

**Issue by waclaw66** [AdAway/AdAway#3125]
**Describe the bug**
Crossing among wifi and mobile data networks causes network connection unavailability.

**To Reproduce**
1. Being on a first wifi (ok)
2. Then moving outside using mobile data (ok)
3. Finally comming to another wifi (ko)
4. Network connection doesn't work. Even ping to gateway IP is not possible. It helps to toggle AdAway blocking. It doesn't matter whether network monitoring is enabled in settings. When it's enabled then there is old (grey) notification and new one (red) shown, so it detects network change, but it still not working.

**Expected behavior**
If a new network is detected blocking should be restarted to work again.

**Device**
 - AdAway version: 5.11.0
 - Device: Samsung Galaxy S20 FE
 - Android version: 11
 - Root version: no root

**Additional context**
Anyway what's the cause of this? Does it matter on what network am I? AdAway just creates local VPN, right?

**Comment by Simon-List** [comment]
Looks like a duplicate of [#2154](https://github.com/AdAway/AdAway/issues/2154).

**Comment by waclaw66** [comment]
@Simon-List seems so, closing in favour of #2154.
