### ISSUE TITLE
White list application in adaway

### ISSUE THREAD

**Issue by marveldj** [AdAway/AdAway#3127]
How to add application in white list

**Comment by GitHub-Updates** [comment]
If adding apps to a white list is a possible option, I would also like to see.

**Comment by PerfectSlayer** [comment]
It is only doable using the VPN ad-blocking variant.
You can set it up using settings > VPN based ad blocker > excluded applications.

The recorder can't distinguish the source app when it receives a request.
But you can exclude all system app and all user app except the one you want to record.
