### ISSUE TITLE
Parse error when parsing manifest. 

### ISSUE THREAD

**Issue by Petomai** [AdAway/AdAway#3128]
I am trying to install Adaway 5.11.0 but it is saying "There was a problem parsing the package" I checked log cat and it just says "Parse error when parsing manifest. There isn't a whole lot of details on why it is failing. I tried a few previous version since I used to have Adaway before resetting my phone. but none of the previous versions on the website worked either. I don't know what to do. 

Moto E4 Sperry
Android 7.1.1
rooted with Magisk (no plugins) 
installation method was f-droid and apk off website. neither work.

**Comment by nickfraser** [comment]
I have the same issue on my Nexus 10 with LineageOS 14.1 (Android 7.1.2). It appears to happen with all v5.x.x releases. Installing v4.3.6 worked for me. Maybe Android 7.x.x is no longer supported?

**Comment by PerfectSlayer** [comment]
[As stated in the readme](https://github.com/AdAway/AdAway#stable-builds), the v5 version requires Android 8.
v4 is still supported for older devices.
