### ISSUE TITLE
failed to show dns log 

### ISSUE THREAD

**Issue by Tanzin01** [AdAway/AdAway#3131]
**Describe the bug**
I was using telegram foss. I opened away to see it's log, however there weren't any log of telegram. Apparently telegram is using IP, if my deduction is correct instead of domain/sub domain.(I used a VPN app called trackercontrol and in there I can see telegram using IP instead of domain)

**To Reproduce**
1. Open telegram and send a message
2. Now open adaway to see it's dns log.
4. See error- you won't find any log of telegram.

**Expected behavior**
I want to see dns log of telegram.
**Screenshots**
In adaway-
![Screenshot_20220129-001248](https://user-images.githubusercontent.com/41266558/151599755-8d8f1d0b-9ca1-4452-9068-55c4bf1707f8.png)

In Tc-
![Screenshot_20220129-001302](https://user-images.githubusercontent.com/41266558/151599799-ab14122e-e51d-4847-aad8-cd43deaac1d3.png)

**Device**
 - AdAway version: [5.11.0]
 - Android version: [10]

**Comment by PerfectSlayer** [comment]
Hello @Tanzin01 

I think it comes from the fact Telegram is not using DNS. So it won't appear in _DNS logs_.
As you could see the second screenshot, it is connected directly to an IP, not a domain, so it doesn't use DNS.

Regards

**Comment by Tanzin01** [comment]
Okyy
