### ISSUE TITLE
Does adaway support wildcard rules?

### ISSUE THREAD

**Issue by biange200** [AdAway/AdAway#3135]
Does adaway support wildcard rules?

**Comment by biange200** [comment]
> It won't let me add a wildcard rule to the redirects but I've added a wildcard rule to my allow list and it works. I assume they work in the block list too.

![Screenshot_2022-02-19-08-10-16-69_0d8cecce28558e4d0a8cf6af1b99c74e.jpg](https://user-images.githubusercontent.com/37582806/154777013-75b57c7c-0311-4d9c-bb2a-307f97c4dfb6.jpg)![Screenshot_2022-02-19-08-11-37-89_0d8cecce28558e4d0a8cf6af1b99c74e.jpg](https://user-images.githubusercontent.com/37582806/154777023-a3a70938-5d62-4e90-a3d8-5f54ad1bb830.jpg)

https://dblw.oisd.nl/
Wildcards are not supported

**Comment by PerfectSlayer** [comment]
Only in the allowed list to remove elements from block lists.
It is a limitation from the `hosts` file format.
