### ISSUE TITLE
Schedule update

### ISSUE THREAD

**Issue by fusionneur** [AdAway/AdAway#3136]
Ability to schedule hosts lists update at a certain time and/or period (eg once per day/ once per week)

**Comment by soredake** [comment]
Any progress on this?

**Comment by soredake** [comment]
@PerfectSlayer

**Comment by PerfectSlayer** [comment]
AdAway checks for hosts update every 6h, when it is convenient for the device.
Hosts update only requires few bytes and use multiple cache.

It is on purpose this settings is not exposed as it will be worst for the battery and data consumption to ensure the updates happen when the user required it.
