### ISSUE TITLE
Untranslatable string

### ISSUE THREAD

**Issue by kubalav** [AdAway/AdAway#3144]
DNS request screen contain untranslatable string:

![adaway_dns_request](https://user-images.githubusercontent.com/37414585/156130272-f89064ea-aeec-4006-8c2b-72ceca869074.png)
 
Check it out, please.

**Comment by PerfectSlayer** [comment]
Hi,

The text is well translatable as there is no `translatable="false"` attribute:
https://github.com/AdAway/AdAway/blob/35887f0bc639351368df629daf703b7ea2a346e2/app/src/main/res/values/string_log.xml#L4

But the translations is missing from your language:
https://github.com/AdAway/AdAway/blob/bc45dd6bfeeae58ca14c022e01071e1582a81d82/app/src/main/res/values-sk/string_log.xml#L2-L8

Translations can be done on the related Transifex project. See #1050

**Comment by kubalav** [comment]
I'm sorry, but I can't find mentioned string in Transifex project.
As you can see all languages are missing this string. I'm afraid something is wrong.

**Comment by PerfectSlayer** [comment]
My bad. I found several issues related to this translation file.
First, the filename miss an "s" to "strings".
Then, the transifex configuration and GitHub integration mapping is missing for this file.

I am on it. Thanks for bringing the issue to my attention 🙏

**Comment by PerfectSlayer** [comment]
I just pushed the code update and an update to the Transifex GitHub integration.
You should be able to see the resource file in the translation list in the coming minutes.
