### ISSUE TITLE
[LOS][Magisk] Undetected root

### ISSUE THREAD

**Issue by Megver83** [AdAway/AdAway#3156]
**Describe the bug**
When I open the app and choose the root method, there's a message saying that root was undetected

**To Reproduce**
1. Open the app
2. Select adblocking based on root
3. See the message

**Expected behavior**
Magisk should ask me if I want to allow root access to AdAway, like with all other apps

**Device**
 - AdAway version: 5.12.0 (F-Droid)
 - Device: Xiami Redmi Note 8
 - Android version: LineageOS 17.1 (Android 10)
 - Root version: Magisk 24.3

**Comment by PerfectSlayer** [comment]
Hello @Megver83 

Did you get a request from Magisk to allow AdAway?
Do you have AdAway listed in the superuser tab of Magisk? If so, it is allowed to access root?

**Comment by PerfectSlayer** [comment]
Could you enable debug logging in AdAway and Magisk and provide a logcat?

I tried to reproduce with the same version of Magisk without success.

**Comment by Rhymekinggtc** [comment]
y
