### ISSUE TITLE
经常发生连接错误

### ISSUE THREAD

**Issue by biange200** [AdAway/AdAway#3159]
网络连接发生切换 或是关闭 打开网络 都会有连接错误的问题
5.12.0版本 VPN模式不稳定

**Comment by PerfectSlayer** [comment]
Duplicate of #2154

**Comment by biange200** [comment]
VPN模式 vpn过滤经常自动关闭
手机状态栏右上角🗝图标
[cid:eu.faircode.email.105]

[cid:eu.faircode.email.106]

**Comment by biange200** [comment]
VPN模式下 vpn过滤会一天内经常自动关闭
在同个网络连接下
有时候又不会 不过adaway6的稳定性要比5好 5是每天都会断 6是VPN钥匙🗝图标没了 也无法过滤了


现在6还有一个新的问题 就是在有VPN图标的情况下
也会出现无法过滤广告的问题 关闭重启adaway才能重新过滤广告

**Comment by biange200** [comment]
我之前用过clash 关闭clash后 adaway无法自动恢复VPN模式

获取Outlook for Android<https://aka.ms/AAb9ysg>
