### ISSUE TITLE
Enable rebooting

### ISSUE THREAD

**Issue by Sayori1576** [AdAway/AdAway#3160]
Enable ad-blocking causes reboot.

**To Reproduce**
1. Adaway paused
2. push the button to restart
3. system rebooted

**Expected behavior**
Adaway enabled

**Device**
 - AdAway version: 5.12.0
 - Device: Galaxy S9
 - Android version: 10
 - Root version: Magisk 3dc7d77e

**Comment by PerfectSlayer** [comment]
Hello @Sayori1576 

Did you device reboot properly (showing a fade to black animation with a loader and a _rebooting_ label) or it just crashed?
Did it reboot everything you resume ad-blocking?
Did it happen only after updating rom/magisk/app?

AdAway used to provide a feature to reboot after applying but it is no more required so it was removed.
Could you:
1. enable verbose logging,
2. restart the app, 
3. pause and resume the ad-blocking (leading to reboot)
4. capture and send a logcat

Regards

**Comment by Sayori1576** [comment]
it was magisk's problem. thank you.

**Comment by Sayori1576** [comment]
Oh, It isn't magisk's fault. error occured now. how to view log?

**Comment by PerfectSlayer** [comment]
Using logcat application (ex MatLog) or using adb logcat if you already have set up adb and developer mode on your device.

**Comment by Sayori1576** [comment]
but **the os** rebooted, So I can't log.

**Comment by PerfectSlayer** [comment]
I think hooking your device with an adb shell logcat can still provide some clues.
You are the first one to report this kind of issue and I can't reproduce it.

And what about:
>Did you device reboot properly (showing a fade to black animation with a loader and a rebooting label) or it just crashed?
Did it reboot everything you resume ad-blocking?
Did it happen only after updating rom/magisk/app?

**Comment by Sayori1576** [comment]
Reboot properly.

**Comment by Sayori1576** [comment]
Oh, I don't why, The systemless hosts module is disabled, so the error was occured, haha.
