### ISSUE TITLE
OnePlus 8T lags with AdAway

### ISSUE THREAD

**Issue by auanasgheps** [AdAway/AdAway#3168]
**Describe the bug**
Hello, a long time ago I opened #2598 but in the end I though the custom list I was using was the culprit. 
I was wrong.

The other day I made a full, fresh OS reinstall on my OnePlus 8T and I can now confirm that **AdAway in root mode** makes the OnePlus 8T lag like a 100$ phone.

I am using stock sources, no added ones. By simply running the modified hostfile, the phone lags a lot, a lot. Everyhing hangs multiple times a day.

Since I am using the stock OnePlus ROM, I am thinking that this ROM simply doesn't work well with a modded hostfile, since doesn't expect one at all.

However, I have one straight question: is the Magisk systemless host module still required? I am currently using it, if is not needed I could try disabling it.

Other than this, I have no idea how to troubleshoot this problem. I could grab ADB logs but might be tough to analyze them.

**To Reproduce**
1. Use AdAway in root mode on a OnePlus 8T as described here
2. Lags will regularly occur when AdAway has applied hosts.
3. If host file is restored to empty, no problem at all.

**Expected behavior**
System not to lag like hell

**Screenshots**

**Device**
 - AdAway version: 5.12
 - Device: OnePlus 8T
 - Android version: Android 11, February 2022 patches, Oxygen OS 11.0.13.13
 - Root version: Magisk 24.3, Magisk systemless host integrated module

**Additional context**
To be honest I always had these lags, so it's not caused by recent changes.

**Comment by PerfectSlayer** [comment]
Hello @auanasgheps 

Thanks for the report. When you talk about lag, are you talking about SystemUI lag (screen responsiveness overall) or page loading?

These are several things to test that come to my mind:

- Is the lag coming from customizing the hosts file or from blocking some connection?
  You can restore the hosts file first, setup AdAway in VPN mode (clear app data to do so) and test if you still have lag.
  If your phone still lag, it doesn't come from editing hosts file but from blocking the system to reach some server.

- Do you enabled web server? 
  Answering to blocked request can help some app to stay responsive.

> However, I have one straight question: is the Magisk systemless host module still required? I am currently using it, if is not needed I could try disabling it.

Yes, modern android version does not allow the `/system` partition to be modified.

**Comment by auanasgheps** [comment]
Hello @PerfectSlayer!

Yes, I am talking about SystemUI lag + the app in foreground.
The lag is pretty substantial and severe, usually for 5 seconds the whole UI hangs. 
Then I get a warning that the app I'm using is not responding, then SystemUI. Sometimes only one of the two, but you get the point.

When doesn't hang like this, I can "feel" the UI is very slow and unresponsive (my phone has a 120hz display, it's really easy to see when misses frames or animations).

I always though was a bad behaving app on my phone, but as soon as I restore the empty hostfile, it goes back to smooth as butter (it's a fast phone!)

1- VPN Mode. Ok, I don't like it (hostfile are one of the 3 top reasons why I root) but will try that!
2- Web server is enabled yes, but the cert is not installed. I will try that as well (first, before VPN).

I also read trough the FAQs, and I found what I expected: AdAway doesn't really use resources after the hostfile has changed, so the problem is not really AdAway... but hey, you know how things go.

In case we "confirm" the phone doesn't like a modified hostfile, can we do something or I have to go for a custom ROM? Maybe there's a system connection or similar that doesn't really _like_ to be cut. I tried to find a pattern, but hangs/lags occur with any app. I tried looking for other similar issues, but I could not find any! It's weird since my phone is pretty popular for rooting... and everybody with root uses Adaway.

**Comment by PerfectSlayer** [comment]
> 1- VPN Mode. Ok, I don't like it (hostfile are one of the 3 top reasons why I root) but will try that!

Yes, the goal is only to identify the issue. You can revert it after the way you like.

>  2- Web server is enabled yes, but the cert is not installed. I will try that as well (first, before VPN).

It is also something you can revert. Just go to settings to remove the installed certificate (the same UI to install it).

> I also read trough the FAQs, and I found what I expected: AdAway doesn't really use resources after the hostfile has changed, so the problem is not really AdAway... but hey, you know how things go.

That is right. Once hosts file installed, you can kill the app or even remove it if you want to be sure it does not come from AdAway running. The hosts file will be kept.

> In case we "confirm" the phone doesn't like a modified hostfile, can we do something or I have to go for a custom ROM? Maybe there's a system connection or similar that doesn't really like to be cut. I tried to find a pattern, but hangs/lags occur with any app. I tried looking for other similar issues, but I could not find any! It's weird since my phone is pretty popular for rooting... and everybody with root uses Adaway.

Too early to think about it but a solution might to identify the host your phone needs to connect to if the root cause of the lag, mainly using DNS log feature of AdAway, and add it to you allowed list.

> Allright, I though AdAway had native support for this, because I remember it was originally developed before AdAway really supported Magisk (longtime Android/root/AdAway user here!)

It has. But it become a so common feature it was integrated natively to Magisk. If you are not using Magisk, you will have to find your own solution to make the hosts file writable. It could be challenging as it could possibly bricks the phone. AdAway only tries to remount the existing partition as RW if allowed.

**Comment by auanasgheps** [comment]
The phone started lagging like hell and I enabled the hosts just few minutes ago, oh god

**Comment by auanasgheps** [comment]
Update: after a couple of days with the webserver properly configured, I can confirm that hangs/lags are still present. 

I get about two severe hangs per day, that last 5 to 10 seconds.

I'll switch to the VPN mode and come back

**Comment by auanasgheps** [comment]
VPN mode seems more "fluid", I didn't get any SystemUI message (with root mode would happen at least twice a day), but today I had a couple of suspicious hangs, but only one foreground app was reported as not responding.

Any thoughts?

I'll turn off AdAway for a couple of days to see how it goes without it.

**Comment by Cebtenzzre** [comment]
I'm curious if your lag is related to high memory usage. I experienced similar symptoms on my Pixel 5a (apps were acting slow and wouldn't stay open in the background) and found in Simple System Monitor that the AdAway webserver was using all of my free memory (>1GB IIRC). It hasn't happened since, otherwise I would open a new issue.

**Comment by auanasgheps** [comment]
> I'm curious if your lag is related to high memory usage. I experienced similar symptoms on my Pixel 5a (apps were acting slow and wouldn't stay open in the background) and found in Simple System Monitor that the AdAway webserver was using all of my free memory (>1GB IIRC). It hasn't happened since, otherwise I would open a new issue.

I haven't checked, but I'm not sure it would be the case: I see the same issue with the Energized Protection module, so bypassing entirely AdAway. I'm sure it's about some hosts that the system doesn't like to be blocked, or simply the stock ROM can't manage well big host file.

**Comment by PerfectSlayer** [comment]
> 

Hopefully it didn't happen again!
Because webserver implementation is really light and I can't see what can produce the issue... But the webserver disable the OOM killer at start. So nothing is preventing it from eating a lot of memory :/

**Comment by auanasgheps** [comment]
This issue is not present anymore in Android 12 for OnePlus. They have rebased OxygenOS on ColorOS, which is terrible, but at least it does not have the problem with host files.

**Comment by PerfectSlayer** [comment]
Glad it finally works fine 👍
