### ISSUE TITLE
Fdroid Apk build size bumped +66% with 5.12 release

### ISSUE THREAD

**Issue by Arnaudv6** [AdAway/AdAway#3174]
Hi and thanks for awesome soft.
5.12 paclage for my arch is 25 Mb, 5.11 was 15Mb.
Nothing in release notes : what happened?

**Comment by androidkotlindev** [comment]
Assuming you downloaded the package from F-Droid, F-Droid compiles the APKs themselves, so the package size can differ a lot depending on how they compile it.

**Comment by Arnaudv6** [comment]
Correct: I downloaded from Fdroid.

**Comment by PerfectSlayer** [comment]
Hi,

You can check the expected size from the GitHub release page: https://github.com/AdAway/AdAway/releases/tag/v5.12.0. It should less than 14MB.

There is definitely something wrong with native parts build:
![image](https://user-images.githubusercontent.com/1766222/164959065-df5fb7b2-cb7c-4ff2-ad6a-5cf3357252e4.png)

But the build script F-Droid uses from my application doesn't seem to changed: https://gitlab.com/fdroid/fdroiddata/-/blob/master/metadata/org.adaway.yml

**Comment by Arnaudv6** [comment]
Thanks for support, and reactivity :+1: 
Yes I confirm: apk from Fdroid with root (Magisk) indeed shows log records all fine.

**Comment by PerfectSlayer** [comment]
Thanks for the feedback.

As the current build is running, I won't release a new build immediately to fix the issue.
I will keep this issue aside for the next version to fix its F-Droid manifest before tagging it on GitHub (as requested by the F-Droid metadata maintainers).

**Comment by PerfectSlayer** [comment]
As a bug fix is coming for the stable version, I tried to push a new fix to F-Droid repo: https://gitlab.com/fdroid/fdroiddata/-/merge_requests/11047.

I hope this one will be approved.

**Comment by PerfectSlayer** [comment]
The PR was approved, I can close the issue. Thanks again for the report!

**Comment by Arnaudv6** [comment]
Thanks for awesome support :+1:
