### ISSUE TITLE
Adding hosts opens Garmin

### ISSUE THREAD

**Issue by dysfunkshun** [AdAway/AdAway#3175]
I'm trying to add additional hosts to AdAway, every attempt by clicking on the add hosts instead opens my Garmin Connect app to add a new course. Is there any other way to add more hosts? Imgur still gets some ads in.

**Comment by PerfectSlayer** [comment]
Hello @dysfunkshun 

Thanks for the report. There is something wrong here, I will have a look at it.

Are you trying to add a host source or a hostname to the block list?
Which version of AdAway are you using?
Does the Garmin Connect app is free and I can I try with an account?

And yes, you can always export your settings, edit them by hand with a text editor and then import them.
But I would prefer fix the issue 😅

**Comment by dysfunkshun** [comment]
I'm trying to add a host source to version 5.12.0. Garmin connect is a free app, you'd prob have to set up an account to get the courses to add page of the app that I'm getting. Thank you for your help!

**Comment by PerfectSlayer** [comment]
I just download the app and setup an account:
![image](https://user-images.githubusercontent.com/1766222/164985265-ff2a40a8-0562-49a6-a962-1338aa0acdad.png)

But I can click the add ("+") button without issue. It open the UI to add a source as expected:
![image](https://user-images.githubusercontent.com/1766222/164985316-b7c4ef5c-6cb3-42bb-9142-c7776fc65267.png)
![image](https://user-images.githubusercontent.com/1766222/164985329-20c134eb-14b3-4138-ae1b-acd8788e4b1d.png)

**Comment by dysfunkshun** [comment]
I see what I was doing wrong as far as adding hosts. I was going into preferences-root based ad blocker and then hitting the host sources, and THAT was bringing me to Garmin. However, clicking on the sources on the home page allows me to add sources, so I thank you very much for your help!!

**Comment by PerfectSlayer** [comment]
You are right, Garmin Connect is an app that declares itself as capable of opening a text file (here the hosts file).
![image](https://user-images.githubusercontent.com/1766222/164990625-258899f4-7702-4791-96dd-d10c6f64e72d.png)

Your feedback is appreciated. I might have done something wrong if you struggled to find how to add a source.
Maybe a rework of this panel is needed 😕 

Would something like that has been clearer? (it might be hard to tell now you know how it really works)
![hosts-sources-screen](https://user-images.githubusercontent.com/1766222/164991152-a30107f9-9b52-4813-8189-a6334186ef07.png)

**Comment by dysfunkshun** [comment]
Oh I dunno if you need to do a rework for one person not paying attention lol! I will say that yes, that does seem a little clearer, but I probably should have tried a few different things before making an issue. Your work is fantastic and I can't thank you enough for making something like this that makes my phone tolerable...well, at least as far as ads go, this phone is a disaster!

**Comment by PerfectSlayer** [comment]
Thanks for your nice comment!

Your issue can be a signal there is something wrong about this part of the UI (I am not a professional Android app developer but rather a backend developer so I am trying hard here to make user friendly screens ^^").

I will keep this edited screen in my idea box and propose it later on the XDA forum for example to gather more feedback.

So, I guess it's time to close the issue :)
