### ISSUE TITLE
ad.doubleclick.net and ... should be removed from hosts.txt

### ISSUE THREAD

**Issue by ace2nutzer** [AdAway/AdAway#3179]
`ad.doubleclick.net, www.googleadservices.com and adservice.google.com` cause high CPU load and logcat spamming on a Galaxy S8 using latest https://adaway.org/hosts.txt.

**Device**
 - using your official hosts.txt (default for mobile phones)
 - Device: Galaxy S8
 - Android version: 9
 - Root version: Magisk v.23.0

**Fix:**
remove
`ad.doubleclick.net`
`www.googleadservices.com`
`adservice.google.com`
from /system/etc/hosts and it fixes high CPU load and battery draining.

Logcat:

`04-25 03:51:31.317 12846 14000 W GoogleTagManager: Exception sending hit: ConnectException
04-25 03:51:31.317 12846 14000 W GoogleTagManager: Failed to connect to www.googleadservices.com/127.0.0.1:443
04-25 03:51:31.318 12846 14000 I System.out: (HTTPLog)-Static: isSBSettingEnabled false
04-25 03:51:31.318 12846 14000 I System.out: (HTTPLog)-Static: isSBSettingEnabled false
04-25 03:51:31.321 12846 14000 W GoogleTagManager: Exception sending hit: ConnectException
04-25 03:51:31.321 12846 14000 W GoogleTagManager: Failed to connect to www.googleadservices.com/127.0.0.1:443
04-25 03:51:31.321 12846 14000 I System.out: (HTTPLog)-Static: isSBSettingEnabled false
04-25 03:51:31.321 12846 14000 I System.out: (HTTPLog)-Static: isSBSettingEnabled false
04-25 03:51:31.324 12846 14000 W GoogleTagManager: Exception sending hit: ConnectException
04-25 03:51:31.324 12846 14000 W GoogleTagManager: Failed to connect to www.googleadservices.com/127.0.0.1:443
04-25 03:51:31.325 12846 14000 I System.out: (HTTPLog)-Static: isSBSettingEnabled false
04-25 03:51:31.325 12846 14000 I System.out: (HTTPLog)-Static: isSBSettingEnabled false
04-25 03:51:31.328 12846 14000 W GoogleTagManager: Exception sending hit: ConnectException
04-25 03:51:31.328 12846 14000 W GoogleTagManager: Failed to connect to ad.doubleclick.net/127.0.0.1:443
04-25 03:51:31.328 12846 14000 I System.out: (HTTPLog)-Static: isSBSettingEnabled false
04-25 03:51:31.328 12846 14000 I System.out: (HTTPLog)-Static: isSBSettingEnabled false
04-25 03:51:31.331 12846 14000 W GoogleTagManager: Exception sending hit: ConnectException
04-25 03:51:31.331 12846 14000 W GoogleTagManager: Failed to connect to ad.doubleclick.net/127.0.0.1:443
04-25 03:51:31.332 12846 14000 I System.out: (HTTPLog)-Static: isSBSettingEnabled false
04-25 03:51:31.332 12846 14000 I System.out: (HTTPLog)-Static: isSBSettingEnabled false
04-25 03:51:31.335 12846 14000 W GoogleTagManager: Exception sending hit: ConnectException
04-25 03:51:31.335 12846 14000 W GoogleTagManager: Failed to connect to www.googleadservices.com/127.0.0.1:443
04-25 03:51:31.335 12846 14000 I System.out: (HTTPLog)-Static: isSBSettingEnabled false
04-25 03:51:31.335 12846 14000 I System.out: (HTTPLog)-Static: isSBSettingEnabled false
04-25 03:51:31.338 12846 14000 W GoogleTagManager: Exception sending hit: ConnectException
04-25 03:51:31.338 12846 14000 W GoogleTagManager: Failed to connect to ad.doubleclick.net/127.0.0.1:443
04-25 03:51:31.339 12846 14000 I System.out: (HTTPLog)-Static: isSBSettingEnabled false
04-25 03:51:31.339 12846 14000 I System.out: (HTTPLog)-Static: isSBSettingEnabled false
04-25 03:51:31.342 12846 14000 W GoogleTagManager: Exception sending hit: ConnectException
04-25 03:51:31.342 12846 14000 W GoogleTagManager: Failed to connect to ad.doubleclick.net/127.0.0.1:443
04-25 03:51:31.342 12846 14000 I System.out: (HTTPLog)-Static: isSBSettingEnabled false
04-25 03:51:31.342 12846 14000 I System.out: (HTTPLog)-Static: isSBSettingEnabled false
04-25 03:51:31.343  3640  3711 D EnterpriseController: netId is 0
04-25 03:51:31.343  3640  3711 E Netd    : getNetworkForDns: getNetId from enterpriseCtrl is netid 0
04-25 03:51:31.343  3640  3711 D DnsProxyListener: DNSDBG::dns addrinfo af 2
04-25 03:51:31.360 12846 14000 W GoogleTagManager: Exception sending hit: ConnectException
04-25 03:51:31.361 12846 14000 W GoogleTagManager: Failed to connect to www.googleadservices.com/127.0.0.1:443
04-25 03:51:31.361 12846 14000 I System.out: (HTTPLog)-Static: isSBSettingEnabled false
04-25 03:51:31.361 12846 14000 I System.out: (HTTPLog)-Static: isSBSettingEnabled false
04-25 03:51:31.364 12846 14000 W GoogleTagManager: Exception sending hit: ConnectException
04-25 03:51:31.364 12846 14000 W GoogleTagManager: Failed to connect to ad.doubleclick.net/127.0.0.1:443
04-25 03:51:31.365 12846 14000 I System.out: (HTTPLog)-Static: isSBSettingEnabled false
04-25 03:51:31.365 12846 14000 I System.out: (HTTPLog)-Static: isSBSettingEnabled false
04-25 03:51:31.368 12846 14000 W GoogleTagManager: Exception sending hit: ConnectException
04-25 03:51:31.368 12846 14000 W GoogleTagManager: Failed to connect to www.googleadservices.com/127.0.0.1:443
04-25 03:51:31.368 12846 14000 I System.out: (HTTPLog)-Static: isSBSettingEnabled false
04-25 03:51:31.368 12846 14000 I System.out: (HTTPLog)-Static: isSBSettingEnabled false
04-25 03:51:31.371 12846 14000 W GoogleTagManager: Exception sending hit: ConnectException
04-25 03:51:31.371 12846 14000 W GoogleTagManager: Failed to connect to ad.doubleclick.net/127.0.0.1:443
04-25 03:51:31.372 12846 14000 I System.out: (HTTPLog)-Static: isSBSettingEnabled false
04-25 03:51:31.372 12846 14000 I System.out: (HTTPLog)-Static: isSBSettingEnabled false
04-25 03:51:31.375 12846 14000 W GoogleTagManager: Exception sending hit: ConnectException
04-25 03:51:31.375 12846 14000 W GoogleTagManager: Failed to connect to www.googleadservices.com/127.0.0.1:443
04-25 03:51:31.375 12846 14000 I System.out: (HTTPLog)-Static: isSBSettingEnabled false
04-25 03:51:31.375 12846 14000 I System.out: (HTTPLog)-Static: isSBSettingEnabled false
04-25 03:51:31.378 12846 14000 W GoogleTagManager: Exception sending hit: ConnectException
04-25 03:51:31.378 12846 14000 W GoogleTagManager: Failed to connect to www.googleadservices.com/127.0.0.1:443
04-25 03:51:31.379 12846 14000 I System.out: (HTTPLog)-Static: isSBSettingEnabled false
04-25 04:40:08.050 14329 14996 W GoogleTagManager: Failed to connect to adservice.google.com/127.0.0.1:443
04-25 04:40:08.119 14329 14996 W GoogleTagManager: Failed to connect to adservice.google.com/127.0.0.1:443
04-25 04:40:08.179 14329 14996 W GoogleTagManager: Failed to connect to adservice.google.com/127.0.0.1:443
04-25 04:40:08.271 14329 14996 W GoogleTagManager: Failed to connect to adservice.google.com/127.0.0.1:443
04-25 04:40:08.383 14329 14996 W GoogleTagManager: Failed to connect to adservice.google.com/127.0.0.1:443
04-25 04:40:08.442 14329 14996 W GoogleTagManager: Failed to connect to adservice.google.com/127.0.0.1:443
04-25 04:40:08.583 14329 14996 W GoogleTagManager: Failed to connect to adservice.google.com/127.0.0.1:443
04-25 04:40:08.645 14329 14996 W GoogleTagManager: Failed to connect to adservice.google.com/127.0.0.1:443
04-25 04:40:08.739 14329 14996 W GoogleTagManager: Failed to connect to adservice.google.com/127.0.0.1:443
04-25 04:40:08.797 14329 14996 W GoogleTagManager: Failed to connect to adservice.google.com/127.0.0.1:443
04-25 04:40:08.887 14329 14996 W GoogleTagManager: Failed to connect to adservice.google.com/127.0.0.1:443
04-25 04:40:08.975 14329 14996 W GoogleTagManager: Failed to connect to adservice.google.com/127.0.0.1:443
04-25 04:40:09.089 14329 14996 W GoogleTagManager: Failed to connect to adservice.google.com/127.0.0.1:443
04-25 04:40:09.149 14329 14996 W GoogleTagManager: Failed to connect to adservice.google.com/127.0.0.1:443
04-25 04:40:09.240 14329 14996 W GoogleTagManager: Failed to connect to adservice.google.com/127.0.0.1:443
04-25 04:40:09.333 14329 14996 W GoogleTagManager: Failed to connect to adservice.google.com/127.0.0.1:443
04-25 04:40:09.422 14329 14996 W GoogleTagManager: Failed to connect to adservice.google.com/127.0.0.1:443
04-25 04:40:09.573 14329 14996 W GoogleTagManager: Failed to connect to adservice.google.com/127.0.0.1:443
04-25 04:40:09.632 14329 14996 W GoogleTagManager: Failed to connect to adservice.google.com/127.0.0.1:443
...`

**Comment by PerfectSlayer** [comment]
Hi,

This issue seems to come from a specific app (related to the GogoleTagManager tag).
It should not expect to have a reliable connection to all google server, or at least, throttle its requests.

The purpose of AdAdway is to block this kind of connection so the domain won't be removed.
Each user can use any hosts sources he/she wants and customize it from by allowing specific domains.
That could be a solution to your application behavior.

**Comment by ace2nutzer** [comment]
Hi,
thanks for clarify this !
As it turned out, the issue only happens with Vanced apps like YouTube & YouTubeMusic.
I'll report the issue to the Vanced-Team since it's painful.
