### ISSUE TITLE
Easy allow blocked domain from lists

### ISSUE THREAD

**Issue by fusionneur** [AdAway/AdAway#3182]
There should be the possibility to long press an entry from the domains blocked by "your lists" which would allow to easily allow that particular domain (thus it will create a new entry in allowed "your lists"). This might be useful when trying to figure out which blocked domain breaks some app functionality.

**Comment by PerfectSlayer** [comment]
Hi @fusionneur 

This option is available from the DNS logs, where you can effectively see which hosts is used by your apps.
Long pressing an item from this list already start the edition item (if not coming from a hosts source).

**Comment by fusionneur** [comment]
I am referring to allowing hosts blocked by hosts sources. Is that currently possible?

**Comment by PerfectSlayer** [comment]
You can allow a blocked domain from one of your hosts source by:

- Either adding it manually from the allowed list (the + button) -- The long way
- Either taping the check "✔️" from the DNS logs (as the hosts was blocked, the block sign "🚫" will become grey and the check sign will become active, creating a new entry in your allowed list) -- The fastest way

Keep in mind blocked hosts does not appears in DNS log using root mode if adblocking is enabled. You must disable adblocking to see block hosts. (blocked and allowed hosts both displayed fine in log using VPN mode even if adblocking is enabled)

**Comment by fusionneur** [comment]
I am currently using root mode. Wouldn't it be much easier for user experience as in my suggestion, to be able to long press any domain in the big list with currently blocked domains and to allow it and thus automatically creating an "allowed" entry (without typing the domain)... or at least allow copy/paste text with the domain name from one list to another

**Comment by PerfectSlayer** [comment]
Long press action is already used to edit item in this list.
If you long press any item you created, it will start edition.

What I could try is to copy the domain is the clip board if the item is not editable for example and display a toast to notify the user.
It would allow to create it faster in any (allowed if you want to enable it, but blocked too if you want to keep it from a source you will remove)

**Comment by fusionneur** [comment]
That sounds fine for a quick workaround i suppose
