### ISSUE TITLE
Unable to copy hosts file on Android 13 Beta 1

### ISSUE THREAD

**Issue by AAGaming00** [AdAway/AdAway#3183]
Attempting to use the root based ad blocker with Magisk (24.3)'s Systemless Hosts results in the following error on Android 13 beta 1 on Pixel 6:

![Screenshot_20220427-230431](https://user-images.githubusercontent.com/42613600/165668417-fa25edaf-b734-4f70-a918-a050aaf7d765.png)

Logcat:
```
04-27 22:59:55.809 I/RootModel(10323): Remounting for RW…
04-27 22:59:55.884 W/ShellUtils(10323): Failed to remount partition /apex/com.android.art as ro: .
04-27 22:59:55.884 W/ShellUtils(10323): Failed to remount partition /apex/com.android.art as ro: .
04-27 22:59:55.884 W/HomeViewModel(10323): Caused by: org.adaway.model.root.CommandException: Failed to remount hosts file partition as read-write.
```

Steps to reproduce:
Install Android 13 beta 1 with Magisk
Add systemless hosts module
Attempt to use AdAway (5.12.0) in root mode
Notice that it fails to setup or if previously installed on an older Android version fails to update the hosts file

**Comment by PerfectSlayer** [comment]
Hi @AAGaming00 

AdAway can't write the hosts file so it tries to remount the partition.
As you are using Magisk with the systemless hosts module, the file should be writable (but it is not).
So there should be an issue with Magisk or the module. 

I haven't tried Android 13 yet but you can check if the hosts file is writable using an adb shell:
```shell
ls -l /system/etc/hosts
```

**Comment by AAGaming00** [comment]
> Hi @AAGaming00
> 
> AdAway can't write the hosts file so it tries to remount the partition. As you are using Magisk with the systemless hosts module, the file should be writable (but it is not). So there should be an issue with Magisk or the module.
> 
> I haven't tried Android 13 yet but you can check if the hosts file is writable using an adb shell:
> 
> ```shell
> ls -l /system/etc/hosts
> ```
```
-rw-r--r-- 1 root root 56 2022-04-27 17:59 /system/etc/hosts
```

**Comment by AAGaming00** [comment]
More of logcat
![Screenshot_20220429-094054](https://user-images.githubusercontent.com/42613600/165956021-316ec169-8179-4374-948c-f0545df13343.png)

**Comment by PerfectSlayer** [comment]
The file seems to have the permissions but libsu (from the Magisk creator) fails to find it as writable.
So it tries to remount the partition (old behavior before Magisk) but it fails (as expected nowadays).

Can you test this dev build: [AdAdaway-dev-220429.zip](https://github.com/AdAway/AdAway/files/8591180/AdAdaway-dev-220429.zip) (it has the same sign key than the GitHub builds, so different from the F-Droid ones)
It uses an updated libsu to latest version but it is not yet released.

**Comment by PerfectSlayer** [comment]
Things might have changed with Android 13 and I don't have a device to test (neither a rooted emulator).

We might need to reach johnwu or its community to get more feedback about it.

**Comment by romhacks** [comment]
I have the same issue on my Pixel 6 running 13b1. Happy to provide any logs or testing that could help

**Comment by AllenChangMusic** [comment]
Can confirm 13b2 still same behavior.

**Comment by KieronQuinn** [comment]
The problem appears to be that 

`System.getProperty("java.home", "/system")`

No longer returns `/system` on Android 13 (as it does on 12, at least on my OP7TP), it now runs `/apex/com.android.art`. 

If I hardcode `ANDROID_SYSTEM_PATH` in `Constants.java` to `/system`, it works fine. 

Now, I presume `java.home` was used for a reason - rather than simply hardcoding `/system`, but perhaps it should be only used on < 13.

**Comment by AllenChangMusic** [comment]
^ or hard code it in Android 13+
Perhaps @PerfectSlayer can assist in updating

**Comment by PerfectSlayer** [comment]
@KieronQuinn That's a good catch!
How did you had the idea to find it?

On my side, I can see I failed at providing useful error... The target file is not logged so I totally missed it.

Here is a build of the current master branch (v6.0.0b) with this fix: 
[AdAway-dev-220513.zip](https://github.com/AdAway/AdAway/files/8684287/AdAway-dev-220513.zip)
Can you test it and report it works?

If it is, I will release a patched build for v5 (a v5.12.1 ?) this weekend.

**Comment by KieronQuinn** [comment]
@PerfectSlayer Yes, that works fine. 

I found it by adding logging to see where it was failing to remount, the location of which `/apex/com.android.art` I'd never even heard of before. After a bit of command poking to see if I could remount that point (I couldn't), I checked to see whether the response had changed since 12, at which point I discovered it was using `/system` on 12. Force use `/system` in 13 and it works.

**Comment by InvokeTheDaemon** [comment]
> @KieronQuinn That's a good catch! How did you had the idea to find it?
> 
> On my side, I can see I failed at providing useful error... The target file is not logged so I totally missed it.
> 
> Here is a build of the current master branch (v6.0.0b) with this fix: [AdAway-dev-220513.zip](https://github.com/AdAway/AdAway/files/8684287/AdAway-dev-220513.zip) Can you test it and report it works?
> 
> If it is, I will release a patched build for v5 (a v5.12.1 ?) this weekend.

This is working on my end as well. No errors when applying the hosts file and I confirmed everything is blocked that should be

**Comment by avtarsingh1122** [comment]
> @KieronQuinn That's a good catch! How did you had the idea to find it?
> 
> On my side, I can see I failed at providing useful error... The target file is not logged so I totally missed it.
> 
> Here is a build of the current master branch (v6.0.0b) with this fix: [AdAway-dev-220513.zip](https://github.com/AdAway/AdAway/files/8684287/AdAway-dev-220513.zip) Can you test it and report it works?
> 
> If it is, I will release a patched build for v5 (a v5.12.1 ?) this weekend.

Had the same issue, just tried this build on Pixel 4a and now it is working perfectly fine. Hosts file updated successfully 🤘🏻

**Comment by PerfectSlayer** [comment]
Thanks for your feedback.
The build is ready, I am waiting from F-Droid to accept a fix that I planed (two weeks ago) the next release.
You can see more details here: #3174

Once F-Droid maintainer approves the fix, I can make the GH release and publish the APK and then, update my backend to distribute the update to users :)

**Comment by PerfectSlayer** [comment]
I just published [the new version that fixes this issue](https://github.com/AdAway/AdAway/releases/tag/v5.12.1).

**Comment by MishaalRahmanGH** [comment]
As @PerfectSlayer already pointed out, ART was made into an APEX module in Android 12.

The current version of the ART module on my Pixel 6 Pro running Android 12L is '311510000'.

The current version of the ART module on my Pixel 6 Pro running Android 13 Beta 2 is '330011000'.

Thus the ART module on the Android 13 betas is newer, obviously. I'd keep an eye out to see if this change appears on 12/12L builds following an ART module update.

**Comment by PerfectSlayer** [comment]
Glad to see you here @MishaalRahmanGH !

If you find incoming changes I should be aware to patch the app, feel free to ping me 😉

**Comment by MishaalRahmanGH** [comment]
![Screenshot_20220806-175128](https://user-images.githubusercontent.com/31252290/183268282-6a86c059-fe2e-461d-8101-41db37a6b5f8.png)

This now affects Android 12 builds with the July 2022 Mainline update, at least it does on my Pixel.
