### ISSUE TITLE
AdAway doesn't seem to block anything on LineageOS 19.1

### ISSUE THREAD

**Issue by pixincreate** [AdAway/AdAway#3191]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

It directly allows blocked links to open on Android 12L LineageOS. It just don't block and replace them with AdAway icon even though I've explicitly opted into. 

### Expected Behavior

It has to block me the access to the websites that I've blocked and should replace the page with AdAway icon by redirecting into 127.0.0.1.

### Steps To Reproduce

1. Install LineageOS 19.1 Official
2. Root with Magisk, enable systemless hosts, reboot
3. Install AdAway.
4. Try to access the website that you've explicitly blocked. 

### Device Configuration

- AdAway version: 5.12.0
- Ad-blocker mode: Root
- Device: Nokia 6.1 Plus (DRG) 
- Android version: LineageOS 19.1 (Android 12L)
- Root version: Magisk 24306

**Comment by PerfectSlayer** [comment]
Hil @pixincreate 

Thanks for the report.

Can you check the content of the hosts file to see if it is well installed? Either using an adb shell or from the app settings.
What are you using to _access the website you've explicited blocked_? Chrome?

**Comment by pixincreate** [comment]
> Can you check the content of the hosts file to see if it is well installed? 
Yea, I checked the systemless hosts file as well as the other one inside `etc` folder (I tried disabling systemless hosts in Magisk to check). Both had the same and we're intact. 

> What are you using to access the website you've explicited blocked? Chrome?

I use Bromite. As of now, I even tried visiting the blocked website with via browser which again gave access to me.


FYI, I reinstalled the app and initially it blocked the website, but after sometime, same lame game.

**Comment by PerfectSlayer** [comment]
> both had the same and we're intact.

Does _intact_ means your `hosts` file is original, only having two lines with localhost declaration?
So AdAway failed to install it?

**Comment by pixincreate** [comment]
> Does intact means your hosts file is original, only having two lines with localhost declaration?

No, what I meant to say was AdAway generated host file was intact. 


> So AdAway failed to install it?

AdAway is behaving normal and shows no sign of issues. However, the issue for me is that it doesn't block Ads even though it claims to be.

**Comment by pixincreate** [comment]
@PerfectSlayer, I tried to grab logs of it. I didn't get any logs related to hosts and the way it's applied. So, I enabled telemetry in the app so that you can find them.

**Comment by PerfectSlayer** [comment]
So you are saying the hosts file is well installed in your system but the ads are not blocked in your browser ?

**Comment by pixincreate** [comment]
Yes. I re-installed the app and it started blocking the ads. So what I did was to check one by one which hosts list is breaking the AdAway as AdAway without my script worked fine.

I believe it's my script that is breaking the AdAway. I legit have no idea about it. The same script used to work on A11.

**Comment by PerfectSlayer** [comment]
> I believe it's my script that is breaking the AdAway. I legit have no idea about it. The same script used to work on A11.

What is your script doing?

Otherwise, you can check you don't have secure dns enabled (from system or browser), or data saver feature enabled (in your browser). That can be the kind of feature that bypass the internal DNS name resolution.

**Comment by pixincreate** [comment]
> What is your script doing?

Inside the app, everything looks and works normal. Most of the websites can be accessed on my phone even though I've explicitly blocked them. 

> check you don't have secure dns enabled

Private DNS is set to `dns.quad9.net` and I've my very own Magisk Module that sets the DNS to quad9 (`9.9.9.9 and 149.112.112.112`)

>  data saver feature enabled

nah! I don't have any such features enabled on my phone. I raised issue after verifying the same on other browsers like `via`, `brave` and `firefox`.

**Comment by PerfectSlayer** [comment]
For AdAway? From the settings, you can enable verbose logging, kill and restart the app.
Now, logs will be added to logcat. You can grab them using an `adb logcat` shell or any logcat application from the store.

**Comment by pixincreate** [comment]
> you can enable verbose logging, kill and restart the app.

Yeah, I've enabled this since the day I found the Ads and websites not being blocked by AdAway. 

> logcat application from the store.

Ok, I'll put up them here separately.

**Comment by pixincreate** [comment]
[logcat-adaway-filtered.txt](https://github.com/AdAway/AdAway/files/8701752/logcat-adaway-filtered.txt)
[logcat-adaway-unfiltered.txt](https://github.com/AdAway/AdAway/files/8701754/logcat-adaway-unfiltered.txt)
