### ISSUE TITLE
Twitter compatibility report

### ISSUE THREAD

**Issue by prempalsingh** [AdAway/AdAway#3205]
### Is there an existing report for this app?

- [X] I have searched the existing issues

### Application Name

Twitter

### Application Version

9.35.1-release.0 (29351000)

### Compatibility issue

Twitter links (https://t.co***) are broken with AdAway enabled.
![image](https://user-images.githubusercontent.com/9432975/169114732-37c7d5f9-8989-436f-b8b8-85c4325ea2da.png)

**Comment by BlackLion17** [comment]
I am having the same problem. Version: 9.42.-release.0

**Comment by PerfectSlayer** [comment]
Hi,

The `t.co` domains is coming from one of the default list: https://pgl.yoyo.org/adservers/serverlist.php?hostformat=hosts&showintro=0&mimetype=plaintext from https://pgl.yoyo.org/adservers/ .

As @BlackLion17 , you can either add it to your _allowed list_ (this is what I personally did) or disable the source.

Can't do more right now about it 😕

**Comment by abosaad11** [comment]
Hello. Could you please keep this issue open.

I'm having the same problem with t.co and Adaway on google Chrome only. Clearing data and cache and clearing the internal chrome DNS doesn't do anything. The problem persists even after stopping Adaway using the button in the middle of the app UI, and of course even after whitelisting t.co.

At first this doesn't seem like an Adaway issue, but more of a Chrome one. However, the Adaway image is visible like Adaway is still blocking t.co. Keep in mind, this is still happening even after stopping the Adaway app, even after clearing Chrome's data and cache. Some blocking of t.co is persistent only in Chrome.

The behavior on other browsers (Firefox, Samsung Browser) is normal and as expected.

**Comment by PerfectSlayer** [comment]
> At first this doesn't seem like an Adaway issue, but more of a Chrome one. However, the Adaway image is visible like Adaway is still blocking t.co. Keep in mind, this is still happening even after stopping the Adaway app, even after clearing Chrome's data and cache. Some blocking of t.co is persistent only in Chrome.

> The behavior on other browsers (Firefox, Samsung Browser) is normal and as expected.

So it looks like to be more an issue about Chrome cache than AdAway isn't it?

**Comment by abosaad11** [comment]
> So it looks like to be more an issue about Chrome cache than AdAway isn't it?

Well what I said in my comment that the issue persists even after clearing Chrome's data and cache.
