### ISSUE TITLE
Request: Specify update time

### ISSUE THREAD

**Issue by dschuermann** [AdAway/AdAway#321]
_Original author: smherge...@gmail.com (September 07, 2012 15:44:20)_

Hi there,
Would it be possible to implement a scheduled update of the AdAway sources?

I ask because I have a mid-range Android phone which occasionally slows down for apps checking for updates in the background, AdAway just being one of them. I'm trying to set up automation so that all of that is done in the background at night, when I'm asleep and not using it.

Regards,
-Steve

_Original issue: http://code.google.com/p/ad-away/issues/detail?id=320_

**Comment by JacktoseIntolerant** [comment]
I don't think you linked the right duplicate. #283 is about a false positive. This is about scheduling updates, which should still be an open request.
Thanks!
