### ISSUE TITLE
Please import russian translation changes

### ISSUE THREAD

**Issue by soredake** [AdAway/AdAway#3266]
I was translating this string to russian:
![изображение](https://user-images.githubusercontent.com/5204968/170833587-e7189be6-3176-4360-a7ae-1bd0e17b7d20.png)
Then some user reverted my change:
![изображение](https://user-images.githubusercontent.com/5204968/170833622-1f6d0179-9ba5-4bf5-a161-58c2c8060a65.png)

I don't know why this user reverted my change, original russian translation for "unmetered" is wrong, "незащищенной" translates back to english as "unprotected". Correct translation will be "нетарифицируемой".

**Comment by PerfectSlayer** [comment]
Hi,

You should be able to declare this translation as issue and discuss with the other translator from the transifex platform.
It might provide you some details why 🤷 

Regards

**Comment by soredake** [comment]
@PerfectSlayer how can i "declare this translation as issue"? I don't see a button for this.

Also i don't get why bot does not import my translation change but import others:
https://github.com/AdAway/AdAway/commit/f94b148165a45687c64bcb58aba52e2721cccae1
https://github.com/AdAway/AdAway/commit/73e82837091c02b07638ce159bac9e7126be84c2

**Comment by PerfectSlayer** [comment]
Please stop using mention in a discussion I am already in.

You have a Issue button on transifex:
![image](https://user-images.githubusercontent.com/1766222/180638918-291440a9-32c2-4779-8ad5-79887bade668.png)
I am not in control of the box. May be ask to transifex support for more details?
