### ISSUE TITLE
AdAway 6.0.1 doesn't detect root when freshly installed

### ISSUE THREAD

**Issue by Dandu32** [AdAway/AdAway#3269]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

It says that it couldn't find the su binary, without ever seemingly checking for it. Magisk never pops up, and the app won't go further unless you use the non root option

### Expected Behavior

It works fine on 6.0.0, and as you probably already know, upgrading to 6.0.1 from an existing rooted setup works just fine. 

### Device Configuration

- AdAway version: 6.0.1
- Ad-blocker mode: root
- Device: Moto G 5G (kiev)
- Android version: 12L API level 32
- Root version: Magisk 24315

**Comment by ipdev99** [comment]
This issue has been reported by a few with different devices.

Steps To Reproduce
Clean install of AdAway v6.0.1 (Root based ad blocking).

Device Configuration
- AdAway version: 6.0.1
- Ad-blocker mode: root
- Device: Google Pixel 5a
  - Lineage 19.1 official nightly.
  - OpenGApps 12L mini (test build)
- Android version: 12L API level 32
- Root version: Magisk v25001 (snapshot builds).

As noted, you can clean install v6.0.0 in root mode.
_Then update from v6.0.0 to v6.0.1 without issue._

Attached logfile(s) and screenshots from both v6.0.1 and v6.0.0 clean install.

---

[601-adaway.log](https://github.com/AdAway/AdAway/files/8905377/601-adaway.log)
[600-adaway.log](https://github.com/AdAway/AdAway/files/8905376/600-adaway.log)

----
![](https://user-images.githubusercontent.com/18606268/173728485-72a75a53-8f64-4cf7-ac50-cd358bf9495e.png)
![Screenshot_20220614-212328_AdAway](https://user-images.githubusercontent.com/18606268/173728488-61560712-1362-496f-927f-e1c88c6eb5fc.png)
![Screenshot_20220614-213100_AdAway](https://user-images.githubusercontent.com/18606268/173728491-abfa7638-8ace-4a53-890a-b640cde28174.png)
![Screenshot_20220614-213105_AdAway](https://user-images.githubusercontent.com/18606268/173728492-d35ae703-7c26-4048-83f4-b173aebf2448.png)
![Screenshot_20220614-213111_Settings](https://user-images.githubusercontent.com/18606268/173728494-43ff2533-fe3f-490c-aad1-ecf835ceed51.png)
![Screenshot_20220614-213119_AdAway](https://user-images.githubusercontent.com/18606268/173728495-dc77ffb5-c262-4ae6-8bb8-c2731cd11982.png)
![Screenshot_20220614-213123_AdAway](https://user-images.githubusercontent.com/18606268/173728496-1960372f-9aca-4f6b-9c70-da299e81a081.png)
![Screenshot_20220614-213130_AdAway](https://user-images.githubusercontent.com/18606268/173728497-4e56e928-2fd8-474f-a7f0-89fe9933be98.png)

**Comment by PerfectSlayer** [comment]
Hi everyone,

Sorry for the trouble, I fixed it already in e8731b259dbebfd61998935bb7000996a24bfe64 but I didn't think it will affect so many people so I didn't release yet. It will only happen for new users that will start using AdAway with the 6.0.1 beta only.

I will release a new beta with the fix this week.
Thanks for the reports!
