### ISSUE TITLE
AdAway YouTube Library

### ISSUE THREAD

**Issue by Raulking868** [AdAway/AdAway#3271]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I have a problem with the application.  If I use AdAway with YouTube root, it no longer saves videos viewed in the library.  if I want to close a video at a certain minute and resume it from where it left off, I can't.  I need to see him 
from the beginning if I can't remember the minute.

### Expected Behavior

I want the error resolved as soon as possible.  I want to be able to sync YouTube video library

### Device Configuration

- AdAway version: 
- Ad-blocker mode: 
- Device: 
- Android version: 
- Root version:

**Comment by MightyPiggie** [comment]
The wat you can fix this is by adding 
s.youtube.com
s2.youtube.com
To your whitelist. Then it will save your watched videos

**Comment by PerfectSlayer** [comment]
@MightyPiggie Are you sure about s2.youtube.com? 
It is the first time I hear about it and even the Google DNS do not resolve it.

**Comment by MightyPiggie** [comment]
> @MightyPiggie Are you sure about s2.youtube.com? It is the first time I hear about it and even the Google DNS do not resolve it.

Ah yeah, it seems you're right. Not sure where I found that I needed to add s2.youtube.com too to the whitelist.

**Comment by MightyPiggie** [comment]
> > @MightyPiggie Are you sure about s2.youtube.com? It is the first time I hear about it and even the Google DNS do not resolve it.
> 
> Ah yeah, it seems you're right. Not sure where I found that I needed to add s2.youtube.com too to the whitelist.

Whoops, I did some more searching and it should be a domain from Google tho. [As seen here](https://github.com/StevenBlack/hosts/issues/960)

**Comment by PerfectSlayer** [comment]
I found this issue too but it's all I could find. Even Google DNS is not aware about is 😐
