### ISSUE TITLE
latest 6.0.1 version can't get root permission

### ISSUE THREAD

**Issue by zhmstar0310** [AdAway/AdAway#3272]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

latest 6.0.1 version can't get root permission(app doesn't ask the permission), so can't work as root mode, but he v6.0.0 works well

### Expected Behavior

app ask and get root permission, then work in root mode

### Steps To Reproduce

start the app, then the issue will be there

### Device Configuration

- AdAway version: 6.0.1
- Ad-blocker mode: root
- Device: lg v50(korean model)
- Android version: 11
- Root version: magisk 24.3

**Comment by laur89** [comment]
Have you tried with latest Magisk release (v25.0)?

**Comment by ipdev99** [comment]
This is a duplicate issue.
Please close this one and move conversation to https://github.com/AdAway/AdAway/issues/3269
