### ISSUE TITLE
Bandwidth savings seem possible via Etag & last-modified headers

### ISSUE THREAD

**Issue by yoshimo** [AdAway/AdAway#3290]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

According to network capture Adaway doesn't send the required headers to avoid re downloading files that haven't changed since the last download. 

### Expected Behavior

If I refresh lists right after I did it last time, I would expect to see in the request both an if-none-match header with the last saved Etag and an if-modified-since header with the timestamp of the last local copy of the file.
If we get a 304 header back, use the stored copy instead of downloading the file again and wasting bandwidth. 

### Device Configuration

- AdAway version: 5.12.1
- Ad-blocker mode: root based
- Device:  Xiaomi 
- Android version: 9
- Root version: yes

**Comment by PerfectSlayer** [comment]
Hi,

I use OkHttp as client with request caching: https://square.github.io/okhttp/recipes/#response-caching-kt-java
But it seems it is not enough. What did you use to capture network on Android?

**Comment by yoshimo** [comment]
https://github.com/emanuele-f/PCAPdroid
