### ISSUE TITLE
Adding network hosts does not work

### ISSUE THREAD

**Issue by BlueDolphin9527** [AdAway/AdAway#3292]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Adding network hosts does not work

### Expected Behavior

After adding network hosts to take effect

### Steps To Reproduce

I first added network hosts, but it didn't work, then I suspected that the bug was caused by spaces, so I downloaded it, kept only one space, and imported it into the local file, but it still didn't work.

### Device Configuration

ROOT ADaway 5.12.1 
Realme GT Neo 3
Android 12
Magisk 24300
Add [Github hosts](https://gitlab.com/ineo6/hosts/-/raw/master/next-hosts Set allow and look for the URL or IP address in it in Android's hosts, none of them can be found.
Please help to see where the error is caused

### Additional context and screenshots

![AD1](https://user-images.githubusercontent.com/62049321/175819198-f37965eb-03a2-438d-a28d-904ff091fbf6.jpg)
![AD2](https://user-images.githubusercontent.com/62049321/175819200-7b22461f-dbf1-402e-837f-a8699cea61b4.jpg)
<img width="554" alt="AD3" src="https://user-images.githubusercontent.com/62049321/175819298-571ed98d-3860-4d7d-be93-e586ef81aa23.png">

**Comment by PerfectSlayer** [comment]
Hi,

First, the hosts file you try to add is a "block" list format, not an "allow" list format.

Then, block list format only allows blocked hosts, not redirection. It is a security feature.

Your source redirect hosts to custom IP instead of localhost so its lines are ignored (per security).

Regards
