### ISSUE TITLE
My app keeps turning gray every time I close it. Android 12.1 and rooter

### ISSUE THREAD

**Issue by fawzynahwi** [AdAway/AdAway#3335]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

First of all, ads are not being blocked
2nd, app turns gray every time I clear it from recent apps

### Expected Behavior

Keep being red and block ads

### Device Configuration

- AdAway version:  5.2.1
- Ad-blocker mode: on
- Device: k20 pro Evolution os
- Android version: 12.1
- Root version: magisk 25.1

### Additional context and screenshots

![Screenshot_20220710-052206_AdAway](https://user-images.githubusercontent.com/52822428/178128910-c12458b2-86ea-4e95-81a0-2edd00232ed9.png)

**Comment by Osga21** [comment]
Have the exact same issue, on the same phone and ROM. Perhaps it's a device specific issue? App has been given unrestricted status on battery manager

**Comment by fawzynahwi** [comment]
The solution turned out is to go to Magisk - settings and scroll to magisk section and click on systemless hosts and reboot. It solved it for me
