### ISSUE TITLE
virus total error 

### ISSUE THREAD

**Issue by milad19s** [AdAway/AdAway#3343]
Please fix this problem 
![Screenshot_۲۰۲۲۰۷۲۲-۱۴۲۵۲۳_Telegram X.png](https://user-images.githubusercontent.com/36108979/180415404-088e4cc3-8f08-4900-8c75-fccab01b8b20.png)

**Comment by PerfectSlayer** [comment]
I don't know where you are getting the APK from.
But there is no issue with this version: https://www.virustotal.com/gui/url/f1c356f9117cb4a67e5e47625ce077693c43a02827ebf527e5172ebe0d222cb5
