### ISSUE TITLE
Can't get DNS logs

### ISSUE THREAD

**Issue by TerDale** [AdAway/AdAway#3357]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Just installed a new Oneplus 8 phone, rooted with Magisk 25, with Evolution X ROM6.6 /Android 12.
AdAware 6.0.3,  used in root mode,  is properly working regarding ads filtering. However, I can't get any log after starting recording in "DNS requests". Tried to find a solution in these issues and elsewhere on the Net, but without luck. Any clue? 

### Expected Behavior

Having log requests displayed once recording started. 

### Steps To Reproduce

1. In AdAware, select "Show DNS requests log"
2. Tap the recording button
3. Switch to a browser or other network-tied app, generate activity 
4. Switch back to AdAware: no logs displayed 

### Device Configuration

- AdAway version: 6.0.3
- Ad-blocker mode: root
- Device: Oneplus 8
- Android version: 12
- Root version: ??

**Comment by ClementTsang** [comment]
If you're still facing this issue (or for anyone coming across this report), just a shot in the dark, do you have a custom DNS set? I had this issue when I forgot I had Cloudflare's 1.1.1.1 DNS set to always be on.

**Comment by TerDale** [comment]
Thanks @ClementTsang! That was also the cause on my side, works properly once custom DNS disabled!

**Comment by asheroto** [comment]
I had this problem too but found this issue and it did indeed resolve the problem.

Perhaps you could add a check for the Global setting `private_dns_specifier` which would help by notifying others that their private DNS setting is set and must be disabled for DNS logging. 😊

Thanks!
