### ISSUE TITLE
Is there way to flash hosts file of adaway via twrp recovery ?

### ISSUE THREAD

**Issue by Rishang** [AdAway/AdAway#3404]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I need to install Magisk and adaway application in order to apply etc/host file to block ads

### Expected Behavior

If i can directly flash zip in twrp recovery i wont to go through part of installing magisk and make work easier, as i need to root only for this part after which i unroot

### Device Configuration

- AdAway version: 
- Ad-blocker mode: 
- Device: 
- Android version: 
- Root version:

**Comment by spider1163** [comment]
You are looking for an entirely different process

Take a look at AdfreeZip

https://forum.xda-developers.com/t/app-4-0-adfreezip-twrp-flashable-hosts-file-generator.3694641/

**Comment by Rishang** [comment]
ok thanks

**Comment by Rishang** [comment]
I think adaway also do same process but via root
