### ISSUE TITLE
Adaway not working only in chrome 

### ISSUE THREAD

**Issue by rafalou38** [AdAway/AdAway#3407]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Adaway does not block adds on the chrome browser for Android.

### Expected Behavior

Adaway should block adds on the chrome browser for Android.

### Steps To Reproduce

1. Enable adaway
2. Open https://www.googleadservices.com/ in chrome, the add server is shown
3. Open https://www.googleadservices.com/ in any other browser (Firefox, duck duck go, curl), the add server is not shown

### Device Configuration

- AdAway version: 6.0.3
- Ad-blocker mode: root
- Device: Xiaomi Poco F3 (aliolith) 
- Android version: 12
- Root version: Magisk 25.2
- Chrome: 107.0.5304.91

### Additional context and screenshots

When I go to https://whatismyipaddress.com/fr/mon-ip I get a different address on chrome to the one I get on ddgo.
It is located in Paris on chrome and close to me on ddgo.
So I guess chrome is using some kind of proxy or vpn, how can I disable it?

**Comment by thebestnom** [comment]
How to debug this??
It's even worse, tried installing chromiun 110 and it just works, meaning it's probably google prebuild somthing

**Comment by thebestnom** [comment]
Intersting, completly uninstalling (using root) chrome and reinstalling from play store fixed that, mind testing for yourself also?
```bash
su -c "pm uninstall --user 0 com.google.chrome"
```

**Comment by rafalou38** [comment]
Thanks that worked, 
In my case, it's `com.android.chrome` and not `com.google.chrome`

**Comment by kullurumanoj** [comment]
I had a same issue and got it solved after completely uninstalling and reinstalling the chrome using SU. Thanks for the workaround

**Comment by PerfectSlayer** [comment]
Thanks for the feedback! You do not seem to be alone with this `Chrome` issue.

**Comment by SharkySquare** [comment]
> ### Is there an existing issue for this?
> * [x]  I have searched the existing issues
> 
> ### Current Behavior
> Adaway does not block adds on the chrome browser for Android.
> 
> ### Expected Behavior
> Adaway should block adds on the chrome browser for Android.
> 
> ### Steps To Reproduce
> 1. Enable adaway
> 2. Open https://www.googleadservices.com/ in chrome, the add server is shown
> 3. Open https://www.googleadservices.com/ in any other browser (Firefox, duck duck go, curl), the add server is not shown
> 
> ### Device Configuration
> * AdAway version: 6.0.3
> * Ad-blocker mode: root
> * Device: Xiaomi Poco F3 (aliolith)
> * Android version: 12
> * Root version: Magisk 25.2
> * Chrome: 107.0.5304.91
> 
> ### Additional context and screenshots
> When I go to https://whatismyipaddress.com/fr/mon-ip I get a different address on chrome to the one I get on ddgo. It is located in Paris on chrome and close to me on ddgo. So I guess chrome is using some kind of proxy or vpn, how can I disable it?

**Comment by SharkySquare** [comment]
https://www.googleadservices.com/ chrome is blocking it.

**Comment by flynesss** [comment]
reinstalling dont help me, but...!
Change DNS settings in android from auto to OpenDNS + change DNS in Chrome to "Current" (sorry idont know how it was in english, in chrome i choose same, not disable and not other dns)
