### ISSUE TITLE
"VPN based ad blocking" is not clickable

### ISSUE THREAD

**Issue by katastrophe92** [AdAway/AdAway#3416]
First time ever I installed the app, downloaded from GitHub. Launched and clicked multiple times on the unrooted option, also forced closed the app and tried again with no luck.
I'm using a unrooted Samsung M12 android 12

**Comment by jmoney97** [comment]
I had the same issue: I already had another VPN enabled and had to manually disable that one then it would let me l click on the VPN based option; ie it wouldn't automatically disable the current VPN and ad the Adaway.

**Comment by eprst** [comment]
Same here. `VPN based ad blocker` is grayed out, even though I removed all other VPNs in Android settings. Tries to install hosts to the system partition and fails.

Adaway 6.0.3
Non rooted stock Android 13
