### ISSUE TITLE
Hulu app unusable 

### ISSUE THREAD

**Issue by dschuermann** [AdAway/AdAway#343]
_Original author: h.severi...@gmail.com (November 15, 2012 03:27:53)_

<b>What steps will reproduce the problem?</b>
1.enable ad away 
2.try to watch a video on Hulu app. 
3 . After a few secs the advertisement will try to play and it will never stop cuz it is unable to connect

<b>What is the expected output? What do you see instead?</b>

<b>Please enable Debug Logging in preferences of AdAway, install aLogcat and</b>
<b>save a logfile while reproducing the problem. The logfile can be attached</b>
<b>to this issue.</b>

<b>What version of AdAway are you using? What Android version? What custom</b>
rom? Latest version. Running cm10 on epic 4g touch. 

<b>Please provide any additional information below.</b>

_Original issue: http://code.google.com/p/ad-away/issues/detail?id=342_

**Comment by ArKay74** [comment]
Why is this closed? Hulu ads are still being blocked which makes it impossible to use the app.
