### ISSUE TITLE
Adaway latest release not available on FDroid

### ISSUE THREAD

**Issue by the100rabh** [AdAway/AdAway#3659]
Adaway latest release not available on FDroid, its still showing Version 6.0.3 (60003)

**Comment by rusty-snake** [comment]
F-Droid delays updates. Being two weeks and more being upstream is not supring.

**Comment by gallegonovato** [comment]
Good afternoon:

It is now available on fdroid. Check out https://f-droid.org/es/packages/org.adaway/

It was a bug of theirs when creating the fdroid versions.

Best regards
