### ISSUE TITLE
logcat shows google analytics access error looping

### ISSUE THREAD

**Issue by dschuermann** [AdAway/AdAway#376]
_Original author: jaclane...@gmail.com (December 31, 2012 06:38:18)_

Latest version of adaway
Google analytics is blocked apparently and in logcat it shows it looping for access every 5 sec. 
Happens on my gingerbread and froyo devices pls add a feature to remove this block in the hosts

_Original issue: http://code.google.com/p/ad-away/issues/detail?id=375_

**Comment by SpaceDax** [comment]
[alogcat.2017-01-12-18-39-11+0100.txt](https://github.com/AdAway/AdAway/files/702479/alogcat.2017-01-12-18-39-11.0100.txt)
Something is wrong and I dont know what :( Please help, here is my logcat .txt file. Thank you!
