### ISSUE TITLE
Strings for source edit screen cannot be translated on Transifex

### ISSUE THREAD

**Issue by Fs00** [AdAway/AdAway#3938]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

UI strings located in https://github.com/AdAway/AdAway/blob/master/app/src/main/res/values/strings_source_edit.xml are not present on Transifex and therefore cannot be translated.

### Expected Behavior

Those strings should be added on Transifex so that people can translate them. Thank you!

**Comment by gallegonovato** [comment]
Good afternoon:

I have to agree with @Fs00.

In the translation page I don't see those strings. And in Adaway they are not translated either.

I add a little more information to the subject.

Adaway version 6.1.1
Where is the problem: If you go to where your host lists are. Click on the + symbol to add a source. A new window opens. And there is where it is untranslated what the partner indicates.
I have Adaway in Spanish and the whole page is missing to be translated. What the partner indicates is in English, which would be https://github.com/AdAway/AdAway/blob/master/app/src/main/res/values/strings_source_edit.xml the strings or words that appear there.

I do not know if there is any place in https://www.transifex.com/free-software-for-android/adaway/ to modify them.

A hug

**Comment by gallegonovato** [comment]
Good evening @PerfectSlayer @Vankog

With your permission, I add a translation to those xda entries. I don't know if I have to edit that file in github. Or are you going to upload those strings for translation, on the web.

It didn't allow me to put everything here, so I uploaded it to xda. The link is https://forum.xda-developers.com/t/app-root-nonroot-official-adaway-v6-1-1.2190753/post-88693501

I hope it will be useful. If you have any questions, feel free to contact me.

Sincerely

Pd: with your permission. I take this opportunity to thank our colleague @Fs00 for the warning. HE RECEIVES MY SINCERE THANKS @Fs00 👍

**Comment by PerfectSlayer** [comment]
Thanks for bringing this issue to my attention 🙏 

 I updated [the Transifex client configuration](https://github.com/AdAway/AdAway/blob/master/.tx/config) but for not the GitHub integration. It turns out Transifex improved their integration and it can now be configured by a repository file.
I just update and push it in 4c0805d55c84973a0679fa6d2096fe160a69821b and I confirm there is a new resource on Transifex website.

Best,
Bruce
