### ISSUE TITLE
click.discord.com is not ad site i cannot login

### ISSUE THREAD

**Issue by ozogorc** [AdAway/AdAway#4063]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Trying authorizing my ip for discord in this site click.discord.com but adaway blocks it

### Expected Behavior

Remove it in hosts file when i update it click.discord.com block get back

### Steps To Reproduce

Just try authorize your ip for new discord login

### Device Configuration

- AdAway version: 6.1.0
- Ad-blocker mode: root
- Device: redmi
- Android version: 13
- Root version: 27.0

**Comment by gladykov** [comment]
You can add it to allowed list
