### ISSUE TITLE
Is this app still being maintained?

### ISSUE THREAD

**Issue by QWIILXEY** [AdAway/AdAway#4069]
asking this because there has been no updates for adaway for a while now

**Comment by GKid94** [comment]
@PerfectSlayer ?

**Comment by GKid94** [comment]
> It is! But I have not had a lot of personal time lately... I still use it on my daily driver and make some dev commit on the side but nothing serious enough to push it to the repo.

Hope it will get updated soon

**Comment by PerfectSlayer** [comment]
Yes, me too... 
There is always a toll to keep the project up to date with the latest libraries and build tools, and target the latest Android features too. The past lack of time makes it even harder to catch all the steps I missed back.
And there is a good PR about material design makeover from external contributors that is very compromising I would like to merge too 👍
