### ISSUE TITLE
Erreur de synchronisation, et d'installation fichier HOST

### ISSUE THREAD

**Issue by Logidroid** [AdAway/AdAway#4072]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Erreur de synchronisation, et d'installation fichier HOST

### Expected Behavior

I expected this to work xD

### Device Configuration

- AdAway version: 6.1.1
- Ad-blocker mode: ROOT
- Device: Google Pixel 6 PRO
- Android version: Android 14
- Root version: Android 14

### Additional context and screenshots

![Screenshot_20240319-145340_AdAway](https://github.com/AdAway/AdAway/assets/58258858/744ebb20-cc5d-4729-ba0b-18da65e44495)
![Screenshot_20240319-145429_AdAway](https://github.com/AdAway/AdAway/assets/58258858/6ca20892-bc5b-49fc-b2d0-f7b61e95128d)

**Comment by LovecraftianGodsKiller** [comment]
You need to add the Magisk Systemless hosts module.

Go into the magisk settings, find the Systemless hosts option, tap on it, then reboot your device
