### ISSUE TITLE
Asterisks in host lists (only for subdomains)

### ISSUE THREAD

**Issue by mtxadmin** [AdAway/AdAway#4086]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

After reading linked issues (#1482, #3348, #3747, #678, and #47) I still don't understand. Does AdAway support asterisks in host lists?

I mean, asterisks for subdomains only. For instance,
0.0.0.0    *.doubleclick.net
0.0.0.0    *.mcs.snssdk.com
0.0.0.0    *.smetrics.lexus.com
0.0.0.0    *.3w9xneegnw91xugij1i3j27a-wpengine.netdna-ssl.com

### Expected Behavior

-

### Steps To Reproduce

-

### Device Configuration

- AdAway version: 
- Ad-blocker mode: 
- Device: 
- Android version: 
- Root version:

**Comment by gladykov** [comment]
https://github.com/AdAway/AdAway/issues/678#issue-115140852

**Comment by gladykov** [comment]
https://github.com/AdAway/AdAway/issues/678#issuecomment-157478372

**Comment by mtxadmin** [comment]
Thanks, it was exhaustive

Ok, I could have guessed that it is standard hosts file and there is no magic at all.
