### ISSUE TITLE
Webserver does not activate on 6.1.2 build

### ISSUE THREAD

**Issue by bdOtopsy63** [AdAway/AdAway#4101]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Webserver button is activate and certificat is installed but webserver is not activate

### Expected Behavior

Webserver button is activate and certificat is installed so webserver should be activate.

### Steps To Reproduce

1 On 6.1.1
2 update to 6.1.2
3 reboot: webserver is not activate and so does not work
4 return to 6.1.1 and it works perfectly
(need erase app and certificate and re install them on proper 6.1.1 version).

### Device Configuration

- AdAway version: 6.1.12
- Ad-blocker mode: root
- Device: redwood
- Android version: 14
- Root version: Magisn 27.1

**Comment by bdOtopsy63** [comment]
Tested on two different devices

**Comment by Waredane** [comment]
Hi,
Same here.

Device Configuration:

    AdAway version: 6.1.2
    Ad-blocker mode: root
    Device: xiaomi redmi note 9 pro
    Android version: 10 RROS 8.7.0
    Root version: Magisk 27 (27000)

**Comment by adrardossa** [comment]
can vouch, same here too.. and i just realized it this for the past 3 days and been looking through. my first thought was due to kernelsu and yet after ive switched over to magisk the issue still persist.

```
AdAway version: 6.1.2
Ad-blocker mode: root
Device: poco f5 pro 5g
Android version: Infinity X 1.1 A14
Root version: KerneSU 1.0.0 
```

**Comment by bober757** [comment]
Same here.

Device Configuration:

```
AdAway version: 6.1.2
Ad-blocker mode: root
Device: OnePlus 7
Android version: LineageOS android14
Root version: Magisk 27 (27000)
```

**Comment by PerfectSlayer** [comment]
Thanks for the report! I just release v6.1.3 to address the issue.
