### ISSUE TITLE
SSL Certificate expired

### ISSUE THREAD

**Issue by masudscloud** [AdAway/AdAway#4130]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

certificate expired 9 days ago. please increase the date/renew.
using latest version, certificate expiration causing errors in browsers

check screenshots, best wishes
![Screenshot_20240922-173516_Settings](https://github.com/user-attachments/assets/d6daf497-eae9-4006-990a-c4e8015a1ae8)
![Screenshot_20240922-173714_Chrome](https://github.com/user-attachments/assets/521e8255-bc00-4864-a8c1-12309e1ab24b)

### Expected Behavior

date expired issue less

### Device Configuration

- AdAway version: 
- Ad-blocker mode: 
- Device: 
- Android version: 
- Root version:

**Comment by sijav** [comment]
+1

**Comment by Clyde6790pGIT** [comment]
+1

**Comment by Clyde6790pGIT** [comment]
I created a certificate; Github won't let me send it here, so here's a link to it; it expires at 2027.
https://github.com/Clyde6790pGIT/Garbage-Dump/blob/main/localhostCA.crt

**Comment by Clyde6790pGIT** [comment]
> I created a certificate; Github won't let me send it here, so here's a link to it; it expires at 2027. https://github.com/Clyde6790pGIT/Garbage-Dump/blob/main/localhostCA.crt

![Screenshot_20241013-141524_Firefox](https://github.com/user-attachments/assets/8d29dc61-53f7-49a9-a9ef-24bc266b2421)
Seems to be working fine, just install it and reboot after.

**Comment by mhggpo** [comment]
> I created a certificate; Github won't let me send it here, so here's a link to it; it expires at 2027. https://github.com/Clyde6790pGIT/Garbage-Dump/blob/main/localhostCA.crt

installed this but not useful for me

**Comment by sixstrings** [comment]
Not secure (Verbindung ist nicht sicher) on my device (Xiaomi Mi 9T, A11) latest Firefox beta.

![Screenshot_2024-10-19-12-56-15-940_org mozilla firefox_beta](https://github.com/user-attachments/assets/92690caa-0a74-4a04-86bd-9b7b370788d0)
![Screenshot_2024-10-19-12-54-47-847_org mozilla firefox_beta](https://github.com/user-attachments/assets/3e4da943-b601-46c0-a484-6d9eb13664f1)

**Comment by rage302** [comment]
> > I created a certificate; Github won't let me send it here, so here's a link to it; it expires at 2027. https://github.com/Clyde6790pGIT/Garbage-Dump/blob/main/localhostCA.crt
> 
> installed this but not useful for me

+1| also no luck with this CRT. But Dev is aware of this problem and a new release is coming (:

**Comment by rage302** [comment]
> @rage302 You got any sources for your claim? I doubt there will be any more development of this app anytime soon.

...yes, I've a source here:
https://xdaforums.com/t/app-root-nonroot-official-adaway-v6-1-3.2190753/post-89766193

**Comment by PerfectSlayer** [comment]
> @rage302 Perfect Slayer said "will issue a patch release as soon as I can." This proves nothing lol. Might be somewhere in 2030 or tomorrow.

I was traveling for professional reasons so I did not had access to the application signing keys. I just get back yesterday and fired up my idea at 4 in the morning (and got welcomed with tons of updates first… from Android Studio, git, JVM, SDK tools 😩 ) but it should not take 6y to release the fix. 

I already update the certificate, its setup and usage but I'm waiting for my test device battery to charge to test it.

**Comment by PerfectSlayer** [comment]
This should be fixed in the [newly released 6.1.4](https://github.com/AdAway/AdAway/releases/tag/v6.1.4).
Don't forget to manually re-install the certificate from the application settings 😉

**Comment by rage302** [comment]
> This should be fixed in the [newly released 6.1.4](https://github.com/AdAway/AdAway/releases/tag/v6.1.4). Don't forget to manually re-install the certificate from the application settings 😉

...thank you very much! Ad replacement is working again like intended 🥳

**Comment by masudscloud** [comment]
Thank you so much @PerfectSlayer <3
And also to you @rage302 ;)
