### ISSUE TITLE
White list google analytics

### ISSUE THREAD

**Issue by dschuermann** [AdAway/AdAway#422]
_Original author: gab...@gabrielcastro.ca (March 20, 2013 18:31:23)_

As an app developer myself I rely on Google analytic to improve the design of my application, but google-analytics.com gets blocked by users who use ad-away. I think it would be great if google-analytics.com was in the white-list when users first install the app because it dose NOT serve ads and helps developers improve user experience. If a user is concerend about privacy they can simply remove it from the list.

_Original issue: http://code.google.com/p/ad-away/issues/detail?id=421_

**Comment by yochananmarqos** [comment]
Holy issue resurrection Batman!

I'm not a developer, however I often beta test apps. I add these to my whitelist:

*analytics.google.com*
*google-analytics*
*crashlytics*

**Comment by davidmegginson** [comment]
Old issue, but we should always failsafe. The default should bw privacy, and users who want to allow Google to monitor their behaviour can opt in my whitelisting it.

For UI affordance, maybe AdAway could have a checkbox "Allow legitimate analytics sites", u checked by default.
