### ISSUE TITLE
[suggestion] Add support for web filtering through regex

### ISSUE THREAD

**Issue by Shohreh** [AdAway/AdAway#497]
Hello

I installed AdAway on my Android smartphone after seeing too many ads slipping through AdBlockPlus.

It appears that both only rely on hosts, which means that embedded images are still displayed. I suggest letting user edit a regex-based filter file à la Privoxy so that even those ads are removed.

Cheers,

**Comment by Nick-White** [comment]
AdBlockPlus is not hosts based (it's a proxy and thus suports regex).
AdAway is hosts file based, so it's impossible to use regex.
