### ISSUE TITLE
Crash on large hosts file

### ISSUE THREAD

**Issue by ysrn** [AdAway/AdAway#516]
The large hosts file from a well-maintained XDA thread (see http://forum.xda-developers.com/showthread.php?t=1916098) crashes Adaway 2.8.1 on my device even when it's the only hosts source. The source is http://adblock.mahakala.is/. The device is a Samsung GT-P7500.

I was going to re-open issue 58, but I don't have access.

**Comment by L-Andrew** [comment]
Same problem with adaway 3.0.1 on Android 5.1.1
Device is Nexus 5, hammerhead, stock and rooted
I've terminated all other processes before starting so the memory should've been enough
