### ISSUE TITLE
Sources cache

### ISSUE THREAD

**Issue by Nick-White** [AdAway/AdAway#549]
Does the apply sources button download the sources every time?
Domain sources are not updated very often, but disabling, enabling, whitelisting and blacklisting are done more frequently.
If so, it would make more sense to cache the sources locally, and update them when refreshing or if daily update activated.

**Comment by 0-kaladin** [comment]
related to #651 as I'd check a local cache and us it if the source was down.

**Comment by Nick-White** [comment]
Yes, only for blacklisting or whitelisting, it doesn't make sense not to use the local sources, even if the remotes are not down.
