### ISSUE TITLE
webserver wont start con android lollipop

### ISSUE THREAD

**Issue by gdelacruz** [AdAway/AdAway#572]
After upgrading to lollipop, webserver won't start anymore. This is the log at the moment of start it

11-24 20:33:58.303 W/PackageManager(936): Failure retrieving resources for org.adaway: Resource ID #0x0
11-24 20:34:00.362 W/tmp-mksh(29136): type=1400 audit(0.0:658): avc: denied { execute_no_trans } for path="/data/app/org.adaway-1/lib/arm/libblank_webserver_exec.so" dev="mmcblk0p28" ino=213011 scontext=u:r:init:s0 tcontext=u:object_r:apk_data_file:s0 tclass=file
11-24 20:34:01.064 W/PackageManager(936): Failure retrieving resources for org.adaway: Resource ID #0x0
11-24 20:34:01.145 W/PackageManager(936): Failure retrieving resources for org.adaway: Resource ID #0x0
11-24 20:34:30.967 E/GoogleConversionReporter(18717):   at org.apache.http.impl.conn.AbstractPooledConnAdapter.open(AbstractPooledConnAdapter.java:119)

**Comment by slartibartfass** [comment]
Works great, webserver keeps running!
