### ISSUE TITLE
Add Flashable ZIP creation

### ISSUE THREAD

**Issue by eladavron** [AdAway/AdAway#573]
Anyone who flashes new builds a lot knows what a pain it is to have to restart again after flashing for whatever reason.
Given that (as I understand it) the hosts file is, well... a file - would it be possible to add an option to the app to create a flashable zip file so that the hosts could be then patched from recovery at the same time as the rom is?
Thanks a bunch!

**Comment by ericcotelnu** [comment]
Check out zip.me in the play store, allows for just this sort of thing.

**Comment by nyuszika7h** [comment]
It would be better to add an option to create an `addon.d` script which persists the host file through ROM upgrades.

**Comment by jawz101** [comment]
Agreed with the addon.d.  Seems like something could be implemented similar to supersu's option to add a script to preserve the host file

**Comment by ericcotelnu** [comment]
That would be great. I've noticed CM has support in recent builds. Using addon.d to save the hosts file.
