### ISSUE TITLE
Host entries flagged as "Does not match" when more than 1 hostname

### ISSUE THREAD

**Issue by kptkill** [AdAway/AdAway#595]
I have a private source of hosts entries that are being flagged as "Does not match" and not being added to the final hosts list.  It would appear as if any entry w/ more than 1 hostname is not being merged.  

For example:
D/AdAway  (24905): Does not match: #IBM [redacted] Project
D/AdAway  (24905): Does not match: ## needs vpn
D/AdAway  (24905): Does not match: ## 10.201.4.10 wc7dev wc7dev.[redacted].ibm.com
D/AdAway  (24905): Does not match: 10.201.4.11 wc7dev wc7dev.[redacted].ibm.com
D/AdAway  (24905): Does not match: 10.201.4.24 70sterling2 70sterling2.[redacted].ibm.com
D/AdAway  (24905): Does not match: 10.201.4.23 70sterling3 70sterling3.[redacted].ibm.com

**Comment by TameOfGroans** [comment]
does your format match the requirements outlined in the project wiki?

**Comment by kptkill** [comment]
The only difference is that there are 2 (or more) host names per IP address on some of the lines.
I have no doubt that the problem is that Adaway is not parsing the additional hostnames, however, the question is, can adaway be updated to accommodate hosts files with more than one host per line.

http://unixhelp.ed.ac.uk/CGI/man-cgi?hosts
notes that the hosts file format is : ip_address hostname aliases

EXAMPLE
	127.0.0.1	localhost
	192.168.1.10	foo.mydomain.org  foo
	192.168.1.13	bar.mydomain.org  bar
	146.82.138.7	master.debian.org      master
	209.237.226.90	www.opensource.org
