### ISSUE TITLE
update white and black list without internet/downloading new host sources

### ISSUE THREAD

**Issue by nutpantz** [AdAway/AdAway#659]
I am using adaway and I have found that I am adding new white list entry's and black list entry's often and each time I update to reflect the changes I have to download the block list source files each time, it would be fantastic if there was a way to update changes without downloading the block list source host files each time.

I mean other than exporting the entire host file and adding that as a black list then disabling the host file download. (Which works but is a pain)

Thank you for the great software.

**Comment by Nick-White** [comment]
I also have the same problem. There are lots of ad sites that "go through" the host lists and I constantly have to log DNS requests, then add to blacklist. But for each one to take effect, I have to rebuild the hosts file (and with every build, it downloads and parses the remote lists).
