### ISSUE TITLE
On DNS Log Item Indicators

### ISSUE THREAD

**Issue by GuardianMajor** [AdAway/AdAway#669]
Can we please add an indicator in the DNS log that identifies the item listed as how they are being handled in the list, for example blocked, whitelist, blacklist, or nothing for allowed or unblocked items.

So for example say we have a bunch of items like:

xyz.com
yza.com
zab.com
abc.com

It would become:

xyz.com [blocked]
yza.com [blacklist]
zab.com [whitelist]
abc.com <- nothing so means its a new item or allowed

**Comment by 0-kaladin** [comment]
not really that simple.  if adaway is applied tcpdump will not show anything being blacklisted.  You only see things that get through and you can add them to your blacklist.  if you disable adaway and run tcp dump then you see everything and will have to add to you whitelist.  what gets hard is for any domain showing in the tcp dump log we'd have to try to match it to one of the lists.  this could get very time consuming if the hosts file is large and like I said if hosts file is applied you'll see no blocked entries showing up anyway.  
I understand what you want and agree it would be nice but would have to be implemented in a way to show this info maybe on request or on a saved tcp dump log.  Not something I'll ever take the time to tackle but I'll mark as an enhancement in case any other dev ever wonders in here.

**Comment by GuardianMajor** [comment]
Well that was my first assumption too that what makes it to the DNS log is what is allowed to go through, meaning it was not blocked as part of the main lists or the blacklist, but the fact is that I have items on the blacklist that are appearing on this list, which means they are not being blocked then?

That's why I wanted the labeling so I can tell if its just an attempt by the system to access but couldn't or that it was not filtered at all, so that's why its there.

**Comment by jawz101** [comment]
So that's good news.  I wish the app stated the TCPDUMP log implicitly means this is any traffic which is not blocked in your Adaway block lists.
