### ISSUE TITLE
On Android 6.0 import/export doesn't prompt when no storage permission

### ISSUE THREAD

**Issue by 0-kaladin** [AdAway/AdAway#670]
With android 6.0, permissions aren't granted on install.  The only permission AdAway needs granted by the user is write external storage.  It doesn't use this permission for its normal functionality since it uses root rights.  However it uses this permission when exporting/importing the lists since it writes to sdcard.  The issue is, if the user doesn't grant this permission, Adaway states that it successfully exported the list even though no file will be on the sdcard.  We need to minimally error when the permission isn't granted and ideally even prompt the user to enable it.
Workaround: if user doesn't see the export file on sdcard, check the permission is actually granted and export again.

**Comment by jsilvermist** [comment]
Just realized this was the problem after trying to figure out if it was exporting in the wrong place such as /data/data or /sdcard/Android/data.
Finally realized this was the issue and it worked after granting storage permission, but it could definitely be more verbose on the issue.
