### ISSUE TITLE
Pictures/photos on facebook

### ISSUE THREAD

**Issue by smilerukss** [AdAway/AdAway#711]
Not sure what's going on, if I disable adblock, all pictures show in news feed.  After I re enable.  I only see a few of them.  This could be on any link going to an external source or something I'm posting.   Are facebook turning the post holders into ads? So it blocks them out? Very odd.   Everything is as it should be on the ad blocker.  :)

**Comment by GreasyDickMcHerpes** [comment]
same issue here, been getting worse for a couple of weeks, today pretty much no images load on facebook, including profile pictures. images load fine with adaway disabled. have tried whitelisting.

**Comment by smilerukss** [comment]
Well yesterday I could see people's photos. Now I can't.  I can't even see
the profile photos.  Take adaway off. And everything is back.  Anyway of
rolling back the list which is downloaded to an early date? This is getting
stupid.

**Comment by smilerukss** [comment]
Ok. Temp fix.

Tick all host files off
Revert to your own host file as in disable
Check Facebook all should work.
Go back to adaway and add host files from bottom up 1 by 1 testing facebook
after each complie.
So all is ok with mobile app and browser on phone.

Try it. Let me know if it works.

**Comment by GreasyDickMcHerpes** [comment]
thanks, if I untick http://hosts-file.net/ad_servers.txt  and leave the rest of them ticked, all facebook images load properly, and so far adverts on every other site I've been on are still blocked.

**Comment by jeffkrebs** [comment]
From:
http://forum.xda-developers.com/showpost.php?p=64961509&postcount=5311

white *fbcdn.net
white fb-promotions.com
white *facebook.com
white fbcdn-creative-a.akamaihd.net

See if that does the trick.
