### ISSUE TITLE
change 127.0.0.1 to 0.0.0.0

### ISSUE THREAD

**Issue by xxlsm** [AdAway/AdAway#732]
Hi,
an Option to redirect to 0.0.0.0 would be nice because 127.0.0.1 is a real IP.

regards

**Comment by Seranok** [comment]
127.0.0.1 acts like an OpenDNS umbrella as it blocks malware and ads.

The F-Droid description of AdAway, is described as:

An ad blocker that uses the hosts file. The hosts file contains a list of mappings between hostnames and IP addresses. When an app requests an ad, that request is directed to 127.0.0.1 which does nothing.

So, an adblocker redirects an app's ad requests to an IP address which produces a blank result, which prevents the ad from being visible.

**Comment by xxlsm** [comment]
Yes you are right but redirecting it to 0.0.0.0 schould reproduce the same effect for sure. The reason why I opened the issue was because of the fact that 127.0.0.1 is a real IP which can be used in order to run services on specific Ports of that IP. Therefore an option for the user to redirect it to 0.0.0.0 would be quite nice.

**Comment by Seranok** [comment]
I agree with custom ip. I think you better check out 
http://forum.xda-developers.com/showthread.php?t=2252747

It is not open source but I believe you can use 
custom ip in it.
It is quite trustful.

**Comment by xxlsm** [comment]
I would rather stay with the open source adaway. Actually I am using the find and replace funktion from sed. Maybe I will work on a patch later.

**Comment by Shadow53** [comment]
AdAway has an option under preferences to change the redirection IP address under the "Hosts File" section.

![screenshot_20160402-113707](https://cloud.githubusercontent.com/assets/10555070/14228355/4de868b4-f8c7-11e5-8b31-fae4cd54516a.png)

Isn't this what you are looking for?

**Comment by mrchief** [comment]
Changing it in the file would help those of us who are using the hosts file directly (like on desktop OSes). 0.0.0.0 is a no-op and is faster as no network traffic is involved. 127.0.0.1 on the other hand does generate network traffic and is slower by comparison.

**Comment by ale5000-git** [comment]
I think it should be checked because actually 0.0.0.0 has many different meanings.
If there is also only one app that may consider it as "all IPv4 addresses on the local machine" it could cause a lot of traffic.

Quote from Wikipedia:
> Uses include:
> 
>     A way to specify "any IPv4 address at all". It is used in this way when configuring servers (i.e. when binding listening sockets). This is known to TCP programmers as INADDR_ANY. (bind(2) binds to addresses, not interfaces.)
>     The address a host claims as its own when it has not yet been assigned an address. Such as when sending the initial DHCPDISCOVER packet when using DHCP.
>     The address a host assigns to itself when address request via DHCP has failed, provided the host's IP stack supports this. This usage has been replaced with the APIPA mechanism in modern operating systems.
>     A way to explicitly specify that the target is unavailable.[1]
> 
> In the context of servers, 0.0.0.0 can mean "all IPv4 addresses on the local machine". If a host has two IP addresses, 192.168.1.1 and 10.1.2.1, and a server running on the host is configured to listen on 0.0.0.0, it will be reachable at both of those IP addresses.

**Comment by ale5000-git** [comment]
To avoid conflict to a "possible" local webserver (different from one of AdAway) it could be used this: 127.0.1.1

**Comment by Shadow53** [comment]
As I understand it to work, 0.0.0.0 only means "all IP addresses" when used as an argument in a server's configuration file. When received as the result of a DNS query (which is essentially what the hosts file does), it should only mean "null" or "not available."

From https://superuser.com/questions/698990/with-dns-what-does-0-0-0-0-stand-for#877957

> Because 0.0.0.0 is not a valid destination address, this is simply an invalid configuration.

> DNS servers, like other regular IP services, need to be addressed by a valid destination IP address, ie. anything but 0.0.0.0 and 255.255.255.255 minus a few reserved ranges. Depending on the actual network configuration, other addresses might be invalid, too, like 192.168.2.0 and 192.168.2.255 on the 192.168.2.0/24 network. Additionally, for name resolution to work, the server has to be reachable.

> There is one valid use for the 0.0.0.0 address though: When listening for connections, it means “listen on all interfaces on this computer”.

So unless an app is performing a DNS request to determine what address/interface to bind a server to (which doesn't make sense), using 0.0.0.0 shouldn't cause issues.

**Comment by ale5000-git** [comment]
In theory yes but an app (maybe badly programmed) resolving an ads hostname to 0.0.0.0 and NOT expecting it to ever be 0.0.0.0 who know how may behave.

**Comment by dviree** [comment]
Any updates

**Comment by PerfectSlayer** [comment]
There is an option to set 0.0.0.0 as the default redirect instead of 127.0.0.1.
The default value won't be changed as it is the default Linux settings.
