### ISSUE TITLE
Colorblind people can not see red on a dark background

### ISSUE THREAD

**Issue by chisli** [AdAway/AdAway#750]
Issue see title. Change app so all people are happy.
tx

**Comment by davidtowson** [comment]
Amen to that! To me, red on black or black on red is black, just all black. And the pale script on white background so popular on the web these days is just as bad - no contrast. We color blind people see only shape and contrast. And so called "high contrast" settings make a lot of content just disappear. I don't know why, but it happens. The stuff is just not there. To me, high contrast themes are absolutely useless.

**Comment by Gitoffthelawn** [comment]
I agree that the new icons do not have enough contrast.

**Comment by lpinner** [comment]
This is an issue for me also. The urls in the help and the section titles in the preferences are unreadable. The red checkboxes are quite hard to distinguish also.

**Comment by PerfectSlayer** [comment]
Hello everyone,

It is good to have this kind of feedback 👍 
I added a white / light theme. Is it better for you? (you can enable it from the top of the setting UI)
Once changed, is there still some part of the UI you can't see or use properly?
