### ISSUE TITLE
[RFE] Blacklist Update Only Function

### ISSUE THREAD

**Issue by GuardianMajor** [AdAway/AdAway#751]
I was wondering if we can add a lighter function that ONLY processes/merges/updates the entries in the blacklist WITHOUT downloading already updated files again from the servers each time you need to add or remove something from the blacklist.

I think this would remove a lot of "data traffic" burden on the devices as well as the servers that deliver the lists and greatly reduce point of failure. There is really no reason why it would need to download everything again EACH TIME it is updated with private entries in the blacklist, so this would make it much quicker and much more efficient overall.

I think honestly that adding this function to the blacklist tab so it can be done straight from there when something is added or removed, would provide added benefit to everyone and improve the stability of the app, thank you in advance.

The logic would works something like this: if has been updated today or check for update = nothing new, update locally only to make changes, else, include the update of all lists along with it.

**Comment by ckuethe** [comment]
+1... I was just about to request this very thing.

**Comment by guest4711** [comment]
I think we need a local copy of the sources for it, as described in #956 . If you remove some hosts from the whitelist, they should be inserted in the hostfile (if omitted by whitelisting) or simply ignoted (if not in any source file). Same for blacklist: If included in any source file, keep it in host. If not, delete it from host file.
So the simpliest way is to recreate the host file from sources (or copies of them, e.g. cache) and applying your lists...

**Comment by patrickdrd** [comment]
+1

**Comment by PerfectSlayer** [comment]
It should be fixed using the http client cache. No more hosts file download :)
Some other aggressive improvements in the futur (developed but not published yet)
