### ISSUE TITLE
permit multiple custom entry in one entry

### ISSUE THREAD

**Issue by irregularisnotrandom** [AdAway/AdAway#755]
Hi

It would be nice if one coukd paste multiple lines to custom blocklist so that one does not need to enter subdomains one by one.

Even better if adaway can find out all theubdomains of a domain and add all if them

Thanks

**Comment by PerfectSlayer** [comment]
Hello @irregularisnotrandom 

There is no way to find / guess all sub domains to block them.
If you have a lot of domain to import, create you own hosts file and add it using file:// protocol.

Regards.
