### ISSUE TITLE
Any problem moving AdAway to external microSD card?

### ISSUE THREAD

**Issue by Gitoffthelawn** [AdAway/AdAway#759]
AdAway's manifest is set to allow the app to be moved to an external microSD card (yea!).

It also has a Broadcast Receiver (`BootReceiver`) for `android.intent.action.BOOT_COMPLETED`

Typically, once an app is moved to external storage, it can't respond to `BOOT_COMPLETED`.

Is any functionality lost when moving AdAway to an external microSD card?

**Comment by PerfectSlayer** [comment]
Hi @Gitoffthelawn 

There was some issues moving the app to the SD card (boot receiver, running binaries, etc…)
With the internal storage becoming bigger and bigger, I blocked this feature.
AdAway is not a big app and can easily run on internal storage :)

Regards.

**Comment by Gitoffthelawn** [comment]
Hi @PerfectSlayer 

Thanks for your note.  I tend to use AdAway on older Android devices that don't have much internal storage, and can really benefit from moving as much as possible to external storage.

So if it's possible and not too hard, I think it's a nice feature to have.

**Comment by PerfectSlayer** [comment]
I would recommend using the old versions which provide better support for older Android devices and root solution (so before the SD card installation was removed). More over, they still work as the new versions (download and apply hosts).
New versions are mainly for compatibility issue with new Android version and root solution 😉
