### ISSUE TITLE
Wrony Chinese version is used in zh-HK region

### ISSUE THREAD

**Issue by mcdull** [AdAway/AdAway#762]
Hong Kong uses Tranditional Chinese which is the same as Taiwan. Or English as second language. But now I got simplified Chinese by default. Would you please fix it? Thanks.

**Comment by Vankog** [comment]
The app should by now have traditional and simplified Chinese translations.

For contributions towards translations, please have a look at the Readme.md of this repository. We updated the guidelines about how to use Transifex (**https://www.transifex.com/free-software-for-android/adaway/**).
