### ISSUE TITLE
Adaway doesn't detect my  as a rooted device.

### ISSUE THREAD

**Issue by didou54** [AdAway/AdAway#778]
I have a rooted Huawey Honor 7 smartphone.
Both CPU-Z & Root Checker v5.9 tell me that the phone is rooted. But Adaway says not when  started up and quits.
I 'm on an Android 6.0 OS. Supersu v2.65 contains the adaway request for su accepted.

I don't anderstand. Is there an issue with a crypted devices ?

**Comment by slockavick** [comment]
I'm on note 4 6.0.1 rooted as well but adaway says device is not rooted 
Any help?

**Comment by didou54** [comment]
Hi.
If you use supersu like me, you have to change the default setting for the application adaway in supersu; set the option «force use» to «root» instead «system».

**Comment by slockavick** [comment]
What solved the issue for me was to delete the app
Download Fdroid and install newest version of app

**Comment by ZJaume** [comment]
It happens the same to me on my Moto G with CyanogenMod 13,  I accept the root permission for the app and then it shows that my Android is not rooted. On CM 12 this didn't happen.

**Comment by Klex167** [comment]
Same here.
Nexus 6P with Stock Android 7.
Rooted with SuperSU 2.78.
Latest version fron Adaway.
It dosen't ask for Root permissions.
It says "No Root found".
Systemless Hosts V2 dosen't change anything.

**Comment by konaya** [comment]
Same here on my OnePlus Three. Note that other apps detect and use SuperSU just fine on my device.

**Comment by ZJaume** [comment]
The problem is now solved for me in version 3.2 .
