### ISSUE TITLE
https://adaway.org/hosts.txt not connecting

### ISSUE THREAD

**Issue by varuniyer** [AdAway/AdAway#780]
It says local and online not available although the others work and adaway.org/hosts.txt loads on my phone browser.

**Comment by 0-kaladin** [comment]
@dschuermann  something with the recent changes?

**Comment by dschuermann** [comment]
Yeah sry, currently moving the server

**Comment by dschuermann** [comment]
Please try again now. DNS should be propagated now

**Comment by Zireael-N** [comment]
@dschuermann, it works if you change the address to https://**www.**adaway.org/hosts.txt. If the `www.` is omitted, it redirects the browser to non-HTTPS version, AdAway doesn't like this behaviour and simply says that the online version is not available.

**Comment by dschuermann** [comment]
does it work again for everyone?

**Comment by 0-kaladin** [comment]
Looking good bud!
