### ISSUE TITLE
AdAway incompatible with newer systemless root

### ISSUE THREAD

**Issue by rmenessec** [AdAway/AdAway#781]
Even after applying the "unofficial" systemless root Zip from [XDA](http://forum.xda-developers.com/showthread.php?t=2190753), AdAway does not work properly with systemless root—which is probably the most popular root method on XDA by this point.

If "Target hosts file" is set to "/system/etc/hosts" (default), AdAway will always fail with a message that it's out of space on /system for a Nexus 5X or 6 running Marshmallow—most devices running Marshmallow, apparently—even though we're working with a symlink on an overlay. If there's a way to prevent the freespace check, I can't find it.

There's one way AdAway can be used with systemless root, but only if:

- "Target hosts file" is set to "Custom"
- "Custom target" is set to "/su/etc/hosts"
- You don't mind responding to a message about "creating a symlink" on every hosts file update (automatic updates break completely)

Please add proper support for symlinking - or at least provide a way to disable freespace and file creation checks. Without systemless root, I have to reflash the entire /system partition every month as the OTAs roll in. (Nexus 6.)

Thanks!

**Comment by clarkcant** [comment]
I don't believe this was solved. I'm experiencing this issue on my Moto X Pure running 7.2.1

_Sent from my Android XT1575 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_
