### ISSUE TITLE
Autostart problem after reboot

### ISSUE THREAD

**Issue by MChelik** [AdAway/AdAway#783]
Dear dschuermann,
When I update and enable AdAway and then restart my phone, AdAway doesn't start automatically. When I open it after restart I see it's disabled.
**Info 1: AdAway can grant su access automatically (it's in SuperSu's whitelist)**
**Info 2: I have htc One M8 with ViperOne 5.0.2 installed on it**
Thank you,
Best wishes

**Comment by DStewartGWA** [comment]
Did you ever find a solution to this? I'm having the same issue with the same phone and rom.

**Comment by MChelik** [comment]
Yeah, my solution was uninstalling ViperOne and installing crDroid. I'm much happier now.
