### ISSUE TITLE
InApp ads 

### ISSUE THREAD

**Issue by bonkichi** [AdAway/AdAway#791]
In App (musixmatch and texra) ads are still visible even after updating the hosts and rebooting

**Comment by tigermick** [comment]
I have the same problem with meteo france application on my nexus 6.
I updated host file in adaway, reboot and ads are still visible.
Why please?

**Comment by Alqaszar** [comment]
In apps are not completely blocked in Marshmallow. E. g. "Hill Climb Racing" still shows apps.

**Comment by jeroen7s** [comment]
Same with the Whisper app and many other apps
