### ISSUE TITLE
missing license of the host list from yoyo.org

### ISSUE THREAD

**Issue by tsekityam** [AdAway/AdAway#792]
According to the license notice at https://pgl.yoyo.org/, Yoyos Hosts file listed in [Wiki](https://github.com/AdAway/AdAway/wiki/HostsSources#adaways-default-hosts-sources) is released in [MCRAE GENERAL PUBLIC LICENSE (version 4.r53)](https://pgl.yoyo.org/license/). I think we should better add the license of the list to the Wiki too

**Comment by dschuermann** [comment]
done
