### ISSUE TITLE
README: Please add installation instructions before build instructions

### ISSUE THREAD

**Issue by guettli** [AdAway/AdAway#804]
Hi,

I guess most people want to install AdAway (I guess 99%) and only very few people want to build it (guess 1%).

Please add installing instructions in the README before the build instructions.

**Comment by sanjay900** [comment]
But your on github... The reason this exists is so we can download the code and build it ourselves.

**Comment by 0-kaladin** [comment]
You can go here http://forum.xda-developers.com/showthread.php?t=2190753 for help installing if none of the other resources here have helped.

**Comment by guettli** [comment]
Ah, I see. You wrote the README for you, not for new comers. All right, then it is best, to start with the details and put the high level few at the bottom.

**Comment by mark-hahn** [comment]
I myself could not find installation instructions *anywhere*.  Not on `https://adaway.org/` or `https://f-droid.org/packages/org.adaway/`.   I also don't have the patience to read the 786 posts from the thread posted above.  

I downloaded the f-droid app and adaway was not listed.  No apps were listsed. I tried adding adaway with the "link" adaway.org and that didn't work.

Can someone please help?
