### ISSUE TITLE
Ads not blocked on timeanddate.com

### ISSUE THREAD

**Issue by Beastador** [AdAway/AdAway#812]
I am using the following hosts:

http://someonewhocares.org/hosts/hosts
http://winhelp2002.mvps.org/hosts.txt
https://adaway.org/hosts.txt
https://pgl.yoyo.org/adservers/serverlist.php?hostformat=hosts&showintro=0&mimetype=plaintext

I added https://hosts-file.net/ad_servers.txt but that didn't help. 

This is what the ads look like http://imgur.com/fKwldSV

The ads are from www.googleadservices.com. I blacklisted that and it didn't do anything

**Comment by sanjay900** [comment]
Odd, they are blocked on my device

**Comment by Beastador** [comment]
Fixed by itself, I think one of the hosts list was updated.
