### ISSUE TITLE
Error messages too unverbose

### ISSUE THREAD

**Issue by brandsjek** [AdAway/AdAway#821]
I have tried to install hosts file, but it failed because I failed to add it to AfWall+. It just spitted out that it failed to apply the hosts file. 

It'd probably be useful if a different error message is shown when no hosts file sources could be found, as I was thinking it was a storage error.

**Comment by sanjay900** [comment]
I agree with this though, many people have had issues with nougat recently which could have been easily fixed with s better error message

**Comment by Gitoffthelawn** [comment]
This is an open-source project.  Anyone can edit the string files and submit a pull request.
