### ISSUE TITLE
Can't access CEX.IO app and website.

### ISSUE THREAD

**Issue by Sgmaster** [AdAway/AdAway#822]
Hello while adaway hosts are applied I can't access https://cex.io neither its app https://play.google.com/store/apps/details?id=io.cex.app.prod
I have tried monitoring and whitelist the IPs that it connects to, but no luck yet...
Please help me with it its really important.
Thank you

**Comment by alete89** [comment]
+1
I confirm same problem

**Comment by Vankog** [comment]
Whitelisting works for me, though.
Have you turned the Whitelisting-feature on in settings? It is off by default.
