### ISSUE TITLE
S-ON/S-OFF on Nexus phone

### ISSUE THREAD

**Issue by abetterfish** [AdAway/AdAway#823]
I am unable to create a symlink on my Nexus 6 with Android N even through a terminal emulator. AdAway says the issues is S-ON/S-OFF. Any idea on a work around?

**Comment by sanjay900** [comment]
What version are you using? Are you on the latest preview build?

**Comment by abetterfish** [comment]
Im using version 3.1.2

**Comment by sanjay900** [comment]
That's why, there's a preview up on xda

**Comment by sanjay900** [comment]
http://forum.xda-developers.com/showthread.php?t=2190753

**Comment by abetterfish** [comment]
D

**Comment by sanjay900** [comment]
To clear up the confusion, i created a pull request that should add a bit more info about preview builds to the readme.
