### ISSUE TITLE
Adaway fails to apply Hosts changes after upgrade to CM 14.1

### ISSUE THREAD

**Issue by 4oo4** [AdAway/AdAway#824]
I just upgraded from CM 13 to 14.1, and since then Adaway is unable to apply hosts changes. It downloads the lists OK but then fails when it gets to the step where it applies the changes.

From what I can tell, it seems to be a problem with getting root access, I remember before that just opening the app would have the status bar icon that indicated root access, but now I'm only seeing that icon when it tries to merge/apply the hosts, where it flashes briefly and then throws up an error (Failed to copy hosts file). My other root apps still work fine except Adaway.

I turned on debug logging but haven't been able to find the logfile. If someone can tell me where that's at I can provide that.

Not sure if this is a bug with the early version of CM 14.1 or something in Android 7.x that breaks Adaway.

**Comment by willianrodrigues** [comment]
Same behavior here. CM14.1

**Comment by gitgruba** [comment]
Same trouble LGG5 CM 14

**Comment by aes512** [comment]
The fix should be pretty simple, the issue is explained in this article:

https://plus.google.com/+Chainfire/posts/dGPQytapwe3

If I knew Java better, I would attempt a pull request. I "think" that this is the code that needs to be updated:

https://github.com/AdAway/AdAway/blob/68c8c08aaca202d909228a193ac7c2c57496236c/libraries/RootCommands/src/main/java/org/sufficientlysecure/rootcommands/Remounter.java

**Comment by 0-kaladin** [comment]
@sanjay900 this something you could look at?

**Comment by sanjay900** [comment]
I'll look into it when I can, been busy dealing with the quake here in nz

**Comment by sanjay900** [comment]
@aes512 that fix was added in a while ago

**Comment by sanjay900** [comment]
I just installed cm 14.1... I have no problems using Adaway. Are you using the latest preview of adaway?

**Comment by sanjay900** [comment]
@aes512 What version of adaway are you using?

**Comment by Hund** [comment]
I have the same issue and I'm using the latest available version on F-Droid.

**Comment by sanjay900** [comment]
Theres a preview build up on XDA. Use that, it is patched for Nougat.
http://forum.xda-developers.com/showthread.php?t=2190753

**Comment by sanjay900** [comment]
This build works perfectly on both CM 14.1 and stock.

**Comment by Hund** [comment]
That works. Thanks. :)

**Comment by sanjay900** [comment]
I put in a pull request to update the readme to reflect these builds are available, which should clear up the confusion a little.

**Comment by Ardakilic** [comment]
I can confirm the preview build at xda-developers works on stock CM 14.01 with OnePlus 2. Thanks!

**Comment by 4oo4** [comment]
Forgot to update that the version on XDA Labs also fixed this for me (using Nexus 5x). Thanks!
