### ISSUE TITLE
failed to copy hosts file（复制host文件失败）

### ISSUE THREAD

**Issue by DanteAndroid** [AdAway/AdAway#826]
I'm using adaway中国版，the download process is OK, but at last it says as the title. 

OS: Android 7.1.1
Device: Nexus 5x

**Comment by sanjay900** [comment]
You using the latest preview? http://forum.xda-developers.com/showthread.php?t=2190753

**Comment by DanteAndroid** [comment]
It's adaway中国版1.3.4（8）

**Comment by sanjay900** [comment]
Wow, that's a very old station] version of adaway. Please get the version from XDA.

**Comment by DanteAndroid** [comment]
It's Chinese version, I don't think it's so old cause updated in March this year. Still, I'll try the newest preview version, thx.

**Comment by DanteAndroid** [comment]
It worked 👍
