### ISSUE TITLE
Latest translations update broke build

### ISSUE THREAD

**Issue by 0-kaladin** [AdAway/AdAway#828]
@dschuermann 
`ad-away/AdAway/build/intermediates/res/merged/debug/values-sr/values-sr.xml:40: error: Apostrophe not preceded by \ (in Poveznicu nije moguće stvoriti.\n Ovo uglavnom onemogućuje \\'opcija\\' zvana S-ON na HTC telefonima!\n\n Moguće rešenje: pokrenite telefon u recovery režimu i kreirajte poveznicu komandom \\'ln -s /data/data/hosts /system/etc/hosts\\'.\n\n Ako ovo nije moguće, potražite na internetu da li postoji S-OFF način za vaš model telefona.)`

not sure how to fix this on the transifex side...

**Comment by dschuermann** [comment]
thanks for reporting! fixed!
