### ISSUE TITLE
Only blocking some ads (v3.2 release)

### ISSUE THREAD

**Issue by Aelfwin1996** [AdAway/AdAway#831]
Hello. Just wanted to report that I am seeing ads (e.g. watchseries websites that are full of ads, pop-ups, etc.) on cm-14.1 with v3.2 that used to be blocked on cm-13 with v3.1.2
I have gone through everything on the FAQ but it didn't help. Even manually deleted the hosts file and then getting AdAway to apply the new one fails to block them all. Only a few website ads and pop-ups and all in-app ads are blocked, otherwise, I get most of the annoying pop-up ads on the example website.

Note: I have noticed v3.2 does not have one of the host files v3.1.2 had, namely, winhelp one. Could that be the problem? Is there a reason it was removed?

**Comment by sjwdeplorable** [comment]
Can confirm. Im getting ads on the game Pixel Racer.

**Comment by Aelfwin1996** [comment]
with the latest updated hosts files, it is getting slightly better, but I still get a few annoying pop-up ones...

**Comment by Aelfwin1996** [comment]
@sanjay900 @0-kaladin I'd like to hear your input on this issue. Do you think it is related to the now "obsolete" winhelp host file? Or would it be something else to look into?

**Comment by dschuermann** [comment]
I removed winhelp due to security concerns. It is not available via SSL. But you can still re-add it in your installation.

**Comment by Aelfwin1996** [comment]
thank you for your clarification on that. Still leaves me wondering if that is the cause for some ads not being blocked or if something else is at fault...

**Comment by Aelfwin1996** [comment]
could be an issue with the root privileges. although i truly don't know
I am closing this issue since I have added host files (I think it is from Steven Black) that now block the ads that were appearing. I dont know if it is on the FAQ, but it should be told that IPV6 (which I did not have active) should be tried if ads are still visible (helped for some ads in my case).
