### ISSUE TITLE
No binary SU found - root required

### ISSUE THREAD

**Issue by Razorphyn** [AdAway/AdAway#835]
I have done a full wipe of my nexus 5x, updated it to the latest 6.0.1 version and installed SuperSU 2.78(from the zip through twrp). 

However when I open AdAway (the _60 version) it says that no SU binary has been found and the only option is to exit, no log is registered in the superSU app. 

This is the only app that gives me problem, is there any solution? 

PS Root Check states that binary is located in **/su/bin/su**, ADB Root is enabled and Selinux is "Enforcing"

**Comment by Aelfwin1996** [comment]
I sometimes had to delete the root binary files (under xbin and bin I believe?) that come integrated with cyanogen. Then flash the superSU zip and then it worked.

**Comment by Razorphyn** [comment]
@Aelfwin1996 The software is the official one, not a ROM, the only think I have done is installing Elementalx kernel and installing busybox in xbin

**Comment by Aelfwin1996** [comment]
oh ok sorry. well, unless the kernel or busybox create root files before superSU, I can't help much. Have you tried the new v3.2 Adaway stable release?

**Comment by Razorphyn** [comment]
Yes, same problem, the first thing I have installed has been superSU and then the other apps, however thank you!

**Comment by Razorphyn** [comment]
Found the solution!
Source: http://forum.xda-developers.com/showpost.php?p=69328864&postcount=7289

1. Boot into TWRP
2. Mount system partition (do NOT check the "mount read only" box).
3. Open the terminal and execute the following:
4. Code:
    `ln -s /su/bin/su /system/bin/su`
5. Reboot

**Comment by Aelfwin1996** [comment]
don't forget to mark the issue as closed :)

**Comment by Razorphyn** [comment]
>close

**Comment by Razorphyn** [comment]
close #835

**Comment by 0-kaladin** [comment]
@sanjay900 maybe we should look for su in /su/bin

**Comment by sanjay900** [comment]
That shouldn't be hard, ill fix it when i get home
