### ISSUE TITLE
Syntax for lists that contain *allow* items

### ISSUE THREAD

**Issue by Gitoffthelawn** [AdAway/AdAway#838]
The [list syntax page in the Wiki](https://github.com/AdAway/AdAway/wiki/HostsSyntax) does not include the syntax for creating a list that contains both *allow* and *block* items (or only *allow* items).

Can you provide an example of this?

Do *allow* hosts always override *block* hosts (in other lists)?

**Comment by PerfectSlayer** [comment]
Allowed hosts will prevent blocked hosts to be added to the `hosts` file.
So you will never see allowed hosts directive in `hosts` file ;)
