### ISSUE TITLE
Mercari not working with AdAway

### ISSUE THREAD

**Issue by mrboard** [AdAway/AdAway#840]
Hello, could someone please help me figure out what I need to add to my whitelist in order for Mercari to work properly. It mostly works, but help center doesn't and certain postings don't work.

**Comment by JORGETECH** [comment]
You can use the TCPDump option to create a log of the ad domains and investigate which ones are.

**Comment by mrboard** [comment]
So, I just tried that... And I added *.*.akamaitechnologies.com and *.*.amazonaws.com to the white list and it didn't fix anything... Is there any way you could help me figure out how to do this properly???
