### ISSUE TITLE
Material Design App Icon

### ISSUE THREAD

**Issue by Lokesh-Krishna** [AdAway/AdAway#841]
Are there any plans to update the app icon to adhere with the Material Design guidelines?
And maybe add a round icon as well to support the Pixel Launcher?

**Comment by 0-kaladin** [comment]
How does the current not adhere to material design guidelines? Also round icon support is in version 3.2.

**Comment by Lokesh-Krishna** [comment]
I felt like the color palette was off. I'm no designer though so I'm sorry if my judgement on that was wrong.
I've seen the icon in various icon packs and the color tends to be a different shade in the Material Design icon packs.

**Comment by 0-kaladin** [comment]
Nope. It's one of the colors. No problem.
