### ISSUE TITLE
Launching AdAway on a Systemless root doesn't provide to option to use it with Systemless logic

### ISSUE THREAD

**Issue by julianxhokaxhiu** [AdAway/AdAway#845]
Hi,

I found an interesting issue. I saw that you now support Systemless root starting from v3.2. Although when I try to open the app I got only this error message, and no other possibility is given to go into the Preferences, and setting the checkbox.

Either allow the user to enable that checkbox, or preferred, auto-check ( and use ) the Systemless support, when no su binary is found.

Thank you and best regards,
Julian

![photo_2016-12-24_13-27-10](https://cloud.githubusercontent.com/assets/1237070/21466982/d31838de-c9dc-11e6-8f1c-c2aa3b6b688c.jpg)

**Comment by tonyp** [comment]
How did you use your device? Are you sure you granted root to AdAway? For me it works perfectly with 3.2 using systemless SuperSU.

**Comment by julianxhokaxhiu** [comment]
isn't this mented to be used without root now?

**Comment by BigBugHmb** [comment]
Nope… SYSTEMless root isn't rootless system… 😆.
That's two different things. 😉

Julian Xhokaxhiu <notifications@github.com> schrieb am Di., 27. Dez. 2016,
11:59:

**Comment by ShapeShifter499** [comment]
I'm having this issue with the Magisk root method.  I use Magisk hide so I can pass SafetyNet while using root.

**Comment by ShapeShifter499** [comment]
I submitted a possible fix for my issue  https://github.com/AdAway/AdAway/pull/875
