### ISSUE TITLE
a lot of mobile ad networks and analytics for consideration

### ISSUE THREAD

**Issue by jawz101** [AdAway/AdAway#850]
Taken from DNS logs.  Probably 95% of these aren't covered by any public blacklist because no one monitors mobile traffic much.
[adaway-export.txt](https://github.com/AdAway/AdAway/files/679830/adaway-export.txt)

**Comment by callyama** [comment]
Yikes - Can you separate the domains by line per chance?

**Comment by jawz101** [comment]
look at the pull request.  it's cleaned up

**Comment by callyama** [comment]
awesome! hmm I can't just add the link to the raw text to AdAway and it function though it seems. Tried this: https://raw.githubusercontent.com/jawz101/adaway.github.io/639811f20e63f0885c163f9d54c035b63d31e406/hosts.txt

Also - how did you observe these domains? Would they happen to include how YouTube & Instagram sneak ads into their apps somehow?

**Comment by jawz101** [comment]
Adaway lets you log DNS requests but mainly I use NetGuard to find specifically Android ad and analytic services.

Adaway is good for generic ad blocking but the normal blocklists out there are collected from computer users surfing the net.  There's a ton of mobile-only ad companies out there but no one has thought about them.

I'll send a screenshot of what I did for a better explanation of where they come from. It's really not that difficult at all :)  I just wish someone would do it.

**Comment by jawz101** [comment]
![Uploading Screenshot_2017-03-08-21-13-40.png…]()

**Comment by jawz101** [comment]
Here are some screenshots of running a game AdVenture Capitalist
https://play.google.com/store/apps/details?id=com.kongregate.mobile.adventurecapitalist.google
Using [NetGuard](https://github.com/M66B/NetGuard) just lets me see stuff that game is doing specifically
Another app might be [Net Monitor](https://f-droid.org/repository/browse/?fdfilter=network&fdid=org.secuso.privacyfriendlynetmonitor&fdpage=3)
or you can use AdAway's log DNS function but it will log all DNS requests on your phone and I'm not concerned with browser DNS traffic, for example.

Anyways, I show connections to all sorts of obvious Ad and analytic services.  Namely tapjoy and supersonicads (a quick google search shows that ssacdn is a supersonic ads delivery domain).  Pretty much any domain name not sounding like it comes from the developer's company is questionable and I see them in a lot of apps (crashlytics, adjust.com, segment.com, applovin, vungle, tapjoy, etc.)  If an app shows connections to graph.facebook.com yet has no apparent Facebook functionality I block it in NetGuard for that specific app, for another example, even though graph.facebook.com is probably needed for the actual Facbook apps.

Anyways, this takes little effort to figure out.  Plus, I've seen a lot of these domain names for quite some time now.  I just wanted to contribute them somewhere.

![screenshot_2017-03-08-21-13-45](https://cloud.githubusercontent.com/assets/14151703/23734457/ce0764c6-0444-11e7-9f17-4aa1ddaf124a.png)
![screenshot_2017-03-08-21-13-40](https://cloud.githubusercontent.com/assets/14151703/23734462/d31f023e-0444-11e7-9176-7cb92d2de06f.png)

**Comment by jawz101** [comment]
sorry about the line thing.  I think regular notepad must not like the EOL characters of Notepad++.  I'll fix that but I'm working on reorganizing my commit on the actual pull request.
