### ISSUE TITLE
Problem with new update

### ISSUE THREAD

**Issue by novembernebel** [AdAway/AdAway#851]
Hello,
Since the hostfiles update during the night between the 5th and the 6th of january, I can't access the Playstore.
When I set the original hostfiles, it works angain.
Sorry if this is not the place for this report...
Good day to all!

**Comment by udpPigeons** [comment]
What hosts sources are you using? Have you tried deselecting them one-by-one until finding which one is causing the problem?

**Comment by novembernebel** [comment]
I have :
- winhelp (last update december 11th 2016)
- adaway.org (last update nov. 28th 2016)
- host-file.net (last update jan. 6th 2017)
- pgl.yoyo.org (last update dec. 22th 2016)

Is it too much?

**Comment by BigBugHmb** [comment]
No, but you must deselecting them one-by-one until finding which one is
causing the problem...

novembernebel <notifications@github.com> schrieb am Fr., 6. Jan. 2017,
12:25:

**Comment by novembernebel** [comment]
Thank you for your advice! I tryed them one by one. The problem seems to be in the winhelp file.
Thank you very much, it works again!

**Comment by novembernebel** [comment]
Nevermind, after another reboot, the problem still occurs.
With all the lists... it's very strange !

**Comment by udpPigeons** [comment]
Are you still having a problem?

If so, have you tried disabling ad blocking, rebooting, and re-enabling the lists one-by-one again (or just the WinHelp list)?

**Comment by novembernebel** [comment]
I solved it yesterday.
I had to uninstall Adaway, reboot the device, clean cache with SDMaid, then reinstall Adaway and apply it.
Then I rebooted one more time, and it works fine now!
I think the I can close the issue.
