### ISSUE TITLE
Office365 Clients are blocked

### ISSUE THREAD

**Issue by danishabdullah** [AdAway/AdAway#852]
#### Steps to reproduce this issue
1. Install office 365 desktop apps
2. Activate the spy blocker hostfile
3. Try to log in to activate and use your licensed product

#### Expected Behaviour
Tell me what should happen
You should be able to sign into your office 365 desktop apps and keep them working

#### Actual Behaviour
Tell me what happens instead
You cannot sign in and access the configuration

#### Configuration
```0.0.0.0 officeclient.microsoft.com```

#### Fix
```# 0.0.0.0 officeclient.microsoft.com```

**Country** : Germany

**Operating system** : Windows 10 Pro 64 bit

**Winver** : Version 1607 OS Build 14393.0

**Comment by udpPigeons** [comment]
AdAway is an Android app. Are you posting this in the right place? I see you already posted this to WindowsSpyBlocker.

**Comment by danishabdullah** [comment]
my bad.
