### ISSUE TITLE
Taboola ads not being blocked

### ISSUE THREAD

**Issue by ploder424** [AdAway/AdAway#853]
Having trouble with Taboola ads 'from the web' and 'sponsored links by Taboola' not being blocked by adaway e.g at the bottom of Gamefaqs.com . My current hosts file is: https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts.

**Comment by udpPigeons** [comment]
Can you provide an image as an example and a URL of the page that is showing the ads?

**Comment by ploder424** [comment]
Screenshot: https://s30.postimg.org/j4ngdlyo1/Screenshot_2017_01_13_14_07_23.png
URL: http://www.gamefaqs.com/

**Comment by Kronopt** [comment]
I've also been seeing ads from taboola recently while browsing news sites.
I don't have specific examples though

**Comment by udpPigeons** [comment]
Is that the only host source you're using, @ploder424 (https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts)?

**Comment by ploder424** [comment]
Yes, that is the only host source I am using. It is supposed to ne a consolidated list.

**Comment by DarthKeizer** [comment]
Can confirm taboola is being a pain 👎

**Comment by Beastador** [comment]
Taboola is still an issue 😥 http://imgur.com/oBoqGPT

**Comment by kevin1979** [comment]
Taboola is a major eyesore and slows loading to a crawl. Hope this can be fixed. Also infolinks doesn't get blocked, but Taboola is far more prevalent.

**Comment by dutch55** [comment]
Explicitly adding a blacklist entry for taboola.com does not stop ads either. One site you might check is www.lucianne.com

**Comment by SMed79** [comment]
@dutch55 You issue is not related to taboola, the ads are pushed from the first party server via blob script an websocket requests (can't be blocked by DNS filtering app) also pushed from revolving adservers.

firefox http://i.imgur.com/jQTzXvV.png 
chrome http://i.imgur.com/Q0NJMtH.png

First try to block this host "`a.gerasopa.com`" if does not work :-/

Install an advenced filtering app [**Adblock Browser**](https://adblockbrowser.org/), [Adblock Plus Samsung Internet](https://play.google.com/store/apps/details?id=org.adblockplus.adblockplussbrowser), [AdBlock](https://chrome.google.com/webstore/detail/adblock/gighmmpiobklfepjocnamgkkbiglido), [Adguard](https://play.google.com/store/apps/details?id=com.adguard.android.contentblocker) ...

then you need to add these filters https://forums.lanik.us/viewtopic.php?f=62&t=37043

For **taboola**  ==> https://pastebin.com/raw/1bv34xET
For **outbrain**  ==> https://pastebin.com/raw/6ZC6JEkz
