### ISSUE TITLE
Steve black list not working

### ISSUE THREAD

**Issue by andersj81** [AdAway/AdAway#859]
I get local: not available online: not available when added https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts

**Comment by Aelfwin1996** [comment]
Have you tried accessing directly one of the domains it blocks? Adaway doesn't report whether it has been updated but definitely applies the hosts in my case (and block the websites/ads that are listed on that list). Check when it is downloading if Steven Black hosts appears.

**Comment by jawz101** [comment]
It hasn't worked ever.  I don't know why but it seems like lists hosted on github don't seem to process.

Test by unchecking all other lists.  Then disable ad blocking button to revert to a blank hosts file.  Now add only the Steven Black hosts file and download it.  Click the view hosts file menu item.  Still left with a blank hosts file

**Comment by jawz101** [comment]
If you look on his list's readme a mirror is at
http://sbc.io/hosts/hosts
Which does work.  I'm pretty sure it's any list hosted on github


A few other samples

https://raw.githubusercontent.com/michaeltrimm/hosts-blocking/master/_hosts.txt

https://raw.githubusercontent.com/lewisje/jansal/master/adblock/hosts

https://raw.githubusercontent.com/FadeMind/hosts.extras/master/UncheckyAds/hosts

https://raw.githubusercontent.com/mozillahispano/nauscopio-filtros/master/hosts

https://raw.githubusercontent.com/FadeMind/hosts.extras/master/add.2o7Net/hosts
