### ISSUE TITLE
Virus Total Analysis for Adaway. 3.1.2.apk

### ISSUE THREAD

**Issue by Bogla** [AdAway/AdAway#865]
APK Downloaded from:  https://www.androidfilehost.com/?fid=817550096634744719

https://www.virustotal.com/en/file/3bdc271253e7cf635076ce5174db0fcf1444ae495f1cd66850f765e411e5080b/analysis/1487731191/

APK Downloaded from: http://www.adaway.net/adaway-apk-free-download/ and 

https://www.virustotal.com/en/file/aef718d2fb6e0ffbdac186e181d739ab308138a1f48205e5dfab96d36b5d46c6/analysis/

Antivirus 	            Result 	                                                                           Update
AegisLab 	         Troj.Gen!c 	                                                                  20170221
Symantec 	         Trojan.Gen.8 	                                                                  20170221
Tencent 	         a.gray.adaway 	                                                                  20170222
Trustlook 	         Android.PUA.Riskware 	                                                  20170222
WhiteArmor 	Android-PUA.SN-Sure.4045406139523840.[Riskware]       20170215

**Comment by KoolieAid** [comment]
Download it from here
https://f-droid.org/repository/browse/?fdid=org.adaway
Also, the official site is adaway.org not adaway.net

**Comment by superlex** [comment]
Hi,
I downloaded AdAway from f-droid:
https://f-droid.org/repo/org.adaway_60.apk
SHA256: d1b2b199f9f4839a151ac54e41a545cf645d8e0d183b5355525cfd1d1903487e

This is the result:
https://www.virustotal.com/it/file/d1b2b199f9f4839a151ac54e41a545cf645d8e0d183b5355525cfd1d1903487e/analysis/1501035513/

Currently, 7 / 58 antivirus detect it as malware.
