### ISSUE TITLE
Translation Participation for AdAway

### ISSUE THREAD

**Issue by roshanravan** [AdAway/AdAway#867]
i just finished translating AdAway for new Language "Persian/Farsi" at https://www.transifex.com/dominikschuermann/adaway/ i am not sure if i have done it in correct place or not cause there are many AdAway versions/builds (official, xda, modded, material design...) i hope new language would be added in future releases.
thanks

**Comment by GeoZac** [comment]
Thats for official version and will be merged for next update

**Comment by Vankog** [comment]
@roshanravan 
Thanks for the effort!
It was indeed the right place. 
We updated the Readme to give more guidance for translators.
