### ISSUE TITLE
No ads are being block no matter what.

### ISSUE THREAD

**Issue by HeadphoneMC** [AdAway/AdAway#868]
Okay well first of youtube app ads arnt block second i go on a select few sites on my mobile device (nivida shield tablet k1 running android 7) and those site of course have ads and none get block on google chrome EVEN with data saver off....so what the heck am i doing wrong. the site i use are as listed but be warned two and brony and furry related but i dont want ads there so i need host code or something.

deviantart.com
furaffinity.net
derpibooru.org
fimfiction.net
emuparadise

No ads get blocked at all on them why? I have followed all trouble shooting tips and tricks and nothing.

**Comment by SirUltimateBass** [comment]
I'm assuming that you're rooted, so download AdAway from this link: https://f-droid.org/repo/org.adaway_60.apk Grant it root access and when it shows "Newer hosts file available " click on it and download it. After that, restart your phone and Chrome's ads will be blocked.

**Comment by HeadphoneMC** [comment]
i have tried that but to know avail maybe im doing it wrong but i can try till i get is or ad all listed hosts and see where that goes.

**Comment by guest4711** [comment]
If you use mobile data make sure your APN settings do not include any proxy...
