### ISSUE TITLE
Wildcards in Blacklist Not Available 

### ISSUE THREAD

**Issue by davedavis** [AdAway/AdAway#869]
Is there a reason why Wildcards aren't available in Blacklists but are in whitelists? 

Need to block entire root domains (and TLDs like xyz and gdn) instead of having to supply thousands of variations of FQDNs. Regex doesn't work either. 

Before investigating and submitting a PR, is there a reason for this?

**Comment by weedy** [comment]
black list entries go straight into the host file. a linux hostfile doesn't allow wildcards

**Comment by davedavis** [comment]
Ahh, that makes sense. Appreciate the input.
