### ISSUE TITLE
Reporting symlink missing but hosts file IS up to date

### ISSUE THREAD

**Issue by srothkin** [AdAway/AdAway#872]
Every so often it reports in the status bar or app (as shown in attached screen shot) that symlink is missing. It is configured for custom hosts file /su/etc/hosts. 

I did cmp -l /etc/hosts /su/etc/hosts and it reported the files are identical. Furthermore they look up to date (proved by adding a google host to whitelist, updating, and seeing that it got removed from the hosts file). Also both files show the identical modification date/time which is current.

However, ls -lL doesn't show a link. I'm guessing that's related to how the link is done through TWRP (since I presume Adaway isn't explicitly updating BOTH files).

This is on a Nexus 6 rooted with Feb 5, 2017 stock Android 7.1.1 and running AdAway_systemless_hosts_v2.zip in TWRP after rooting.

I would like to see either that this error message goes away OR that it automatically reapplies the symlink without user intervention.

![screenshot_20170311-075756](https://cloud.githubusercontent.com/assets/159869/23833633/df64a030-071e-11e7-81f6-9d817ddfc067.png)
![screenshot_20170311-080042](https://cloud.githubusercontent.com/assets/159869/23833637/df69afda-071e-11e7-8aab-2651ea42a281.png)
![screenshot_20170311-080138](https://cloud.githubusercontent.com/assets/159869/23833634/df677080-071e-11e7-9a45-2364e1b80aec.png)
![screenshot_20170311-080206](https://cloud.githubusercontent.com/assets/159869/23833635/df67dc96-071e-11e7-8c7f-747f05397672.png)
![screenshot_20170311-080211](https://cloud.githubusercontent.com/assets/159869/23833636/df68adec-071e-11e7-8abd-1c64062b2ca4.png)
![screenshot_20170311-080627](https://cloud.githubusercontent.com/assets/159869/23833638/df6a0890-071e-11e7-96c2-15cbaf4093d2.png)

**Comment by GuardianMajor** [comment]
I am facing the same issue, came here to see if anyone had this problem and see that you do as well. Sad part is that I have TWO identical Nexus 6 running the SAME 7.1.1 and the SAME AdAway and everything was configured identically and yet one throws this error and you say yes, it seems to be fine until next reboot where it comes back and says the problem. But the other one, persists across reboots with no issues and always honors the symlink. For the life of me, I can not figure out why. Hoping people here have some insight on how to resolve this.
