### ISSUE TITLE
Doesn't block ads in Redmi Note 3 SD (Marshmallow)

### ISSUE THREAD

**Issue by NewRaGu** [AdAway/AdAway#877]
I have managed to apply hosts using Adaway app. But surprisingly In app ads are not being blocked. It didn't block any in app ad. Kindly let me know why?

**Comment by NewRaGu** [comment]
Is there anyone listening to my complaint?

**Comment by Kronopt** [comment]
Can you give more information about your system configuration?
Like root and adaway host sources?

Also myself and others have noticed some ad providers not being blocked by adaway default host sources, like taboola ads. That might be it

**Comment by NewRaGu** [comment]
Root- SuperSU

Host Sources:
1) http://winhelp2002.mvps.org/hosts.txt
2) https://adaway.org/hosts.txt
3) https://hosts-file.net/ad_servers.txt
4) https://pgl.yoyo.org/adservers/serverlist.php?hostformat=hosts&showintro=0&mimetype=plaintext

My device: Redmi Note 3 Snapdragon
Android version : 6.0.1
Security Patch: 01 feb 2017

Adaway shows Enabled

**Comment by sharath-psh** [comment]
Same device and configurations here and can confirm that some ads are not being blocked

**Comment by NewRaGu** [comment]
@sharath-psh, It doesn't block 95 % of the In-app ads.

**Comment by Kronopt** [comment]
I would recommend you take a look at the Help/Problems tab inside the adaway app.
I'm sure it's just some domain that is not included in any of your host sources.

**Comment by NewRaGu** [comment]
Tried Log DNS Requests. And blacklisted a few links and it helped but Adaway should do it work. One more thing is that I can't find exported adaway-export file in sdcard.

**Comment by guest4711** [comment]
To get the lists exported you have to grant storage permissions to AdAway
