### ISSUE TITLE
Unable to block ads and fullscreen ads in some apps

### ISSUE THREAD

**Issue by abhijitvalluri** [AdAway/AdAway#878]
There is this app called [Puzzlerama ](https://play.google.com/store/apps/details?id=com.leodesol.games.puzzlecollection&hl=en)where I just cannot block ads no matter how hard I try,

And another app where full screen ads pop up every now and then: [Roll the ball](https://play.google.com/store/apps/details?id=com.bitmango.rolltheballunrollme&hl=en)

Am I doing something wrong? Or are these apps using some clever techniques to circumvent ad blocking? I am running on Android 7.1.1 by the way.

I can at least confirm that ads are getting blocked on websites in Chrome, although I had to install a more comprehensive hosts file. The default hosts file left out many ad providers causing ads to not be blocked on many websites. This is the first time I found AdAway's default hosts insufficient.

**Comment by guest4711** [comment]
As always: Please use the DNS-log feature of AdAway to find out which hosts you should blacklist...
