### ISSUE TITLE
TrueCaller blocking AdAway ad blocking

### ISSUE THREAD

**Issue by terenzif** [AdAway/AdAway#880]
After some time trying to figure out why adaway stopped blocking ads, i found TrueCaller reported between adware apps. I knew this app could present unwanted ads, but I didn't expect it was able to completely block adaway.
I figured it out when i removed it, and adaway returned to work fine.
I don't how it does this, but developers should find a way to circumvent it
Cheers
FT

**Comment by Itsnothectic** [comment]
Its probably installing its own DNS resolver and cache for the system. I wouldnt really wanna continue using an app that not only shares your contacts list but also disables hosts files.
