### ISSUE TITLE
Could you please add these lines in the host file?

### ISSUE THREAD

**Issue by sandirickyroy** [AdAway/AdAway#886]
This lines help to block ads in various apks.
Ads are now blocked in these apps(Personally tested):- Mcent Browser App, True Messenger App, iReff App, Some of the TouchPal theme app.
[Host For Adblock modded by Ad Deimator.txt](https://github.com/AdAway/AdAway/files/941205/Host.For.Adblock.modded.by.Ad.Deimator.txt)

**Comment by SMed79** [comment]
So you want to block the mobile version of youtube `m.youtube.com`, google india `www.google.co.in` and taboola `api.taboola.com` which is a platform for content recommendation?

Are you sure?
