### ISSUE TITLE
Adaway blocks Facebook messenger connection

### ISSUE THREAD

**Issue by cr4ck3dn** [AdAway/AdAway#890]
Hello!
From last week adaway blocks Facebook messenger application connection, in messenger it's " waiting for network " if I disable adaway and restart devices all works ok!
I verified in 2 devices Huawei G525 and Allview viper L ( Gionee elife 3 ) and I have this problem.
How I can fix this , to work messenger I need to disable adaway :(
Thanks and sorry for my English.

**Comment by SMed79** [comment]
Hi, 
uncheck **Hosts sources** one by one to check which **hosts** file is causing the issue then report the problem to the maintainer.

**Comment by cr4ck3dn** [comment]
Problem solved!!
In block list was portal.fb.com and fbcdn.xxx servers, I added to white list and now it's working! :) 
Thanks.

**Comment by SMed79** [comment]
Blocked by which list ?

**Comment by cr4ck3dn** [comment]
My personal list.
