### ISSUE TITLE
KingRoot says AdAway is a security risk

### ISSUE THREAD

**Issue by rraallvv** [AdAway/AdAway#902]
![screenshot_2017-05-31-13-42-48](https://cloud.githubusercontent.com/assets/1840524/26646043/2d9b164e-4608-11e7-97a8-27ede404f0d5.png)

I downloaded org.adaway_60.apk from f-droid as pointed out in adaway.org, it seems for some reason KingRoot has blacklisted AdAway.

Is there another app to admin root privileges that I can use instead of KingRoot?

Is there another way to give root privileges to AdAway?

**Comment by SMed79** [comment]
> KingRoot says AdAway is a security risk

False positive :-1:  ...

> Is there another way to give root privileges to AdAway?

Did you try to click the greyed **CONTINUE** button?

> Is there another app to admin root privileges that I can use instead of KingRoot?

Search on google "How to Replace Kingroot with SuperSU".

**Comment by alamo18** [comment]
Yeah but why do you even use kingroot move to supersu or smth

_Sent from my Xiaomi Redmi Note 4 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by rraallvv** [comment]
@SMed79 I tried that button but it doesn't do anything, it should be labeled DISMISS rather than CONTINUE.

@alamo18 I'm moving to supersu then.

**Comment by fadlibalam86** [comment]
Try replace kingUser first, Raed this [Replace KingUser KingRoot with SuperSU](http://www.infonewtechnologies.net/replace-kinguser-kingroot-with-supersu/). If you haven't rooted your device, [root your device using KingRoot](http://www.infonewtechnologies.net/root-any-android-device-using-kingroot/) first.
