### ISSUE TITLE
Can You help me block these disgusting ads using host only .

### ISSUE THREAD

**Issue by anasshm** [AdAway/AdAway#903]
look at this image http://imgur.com/a/XNDiZ .
this is the website . 
http://biqle.ru/video/name.

**Comment by SMed79** [comment]
Ads pushed from the first party domain `blob` and `websocket` can't be blocked by DNS filtering app.
More than that they use a revolving adservers 

Adblock Browser, Adblock Plus Samsung Internet, AdBlock, Adguard or uBo which has more advanced filtering options.

FYI, ads on biqle.ru are blocked by **RU AdList** https://hg.adblockplus.org/ruadlist/log?rev=biqle.ru

**Comment by anasshm** [comment]
I have Adblock samsung internet but i don't know how to use it to block those ads .

**Comment by anasshm** [comment]
i just downloaded adguard and addedm my own filters that were working for me on my computer ussing adblock plus , but they didn't work

**Comment by anasshm** [comment]
Found a Solution : 
if you are using Android add those filters to adguard user lists , and if you are using a computer you can add them to your own filters in adblock plus .

||peremoga.xyz^$popup,third-party

||traffic-media.co^$third-party

|http://$xmlhttprequest,script,third-party,domain=daxab.com

|https://$xmlhttprequest,script,third-party,domain=daxab.com

**Comment by SMed79** [comment]
Not sure because the filters you posted are only for the daxab.com video player not biqle.ru !!
... also your filters will block the scripts loaded from crazycloud.ru too which will also block the video :-/

correction:
```
|blob:$domain=biqle.ru
$websocket,domain=biqle.ru
$xmlhttprequest,stylesheet,popup,script,third-party,domain=biqle.ru|daxab.com
@@||crazycloud.ru^$script,domain=daxab.com
```
