### ISSUE TITLE
carrier can push ads

### ISSUE THREAD

**Issue by bonnouji** [AdAway/AdAway#906]
Phone: redmi 3
ROM / Android version: Resurection Remix 5.8.3 / Nougat 7.1
Root (yes/no):yes
Xposed, or any other modifications:  Magisk installed, systemless host enabled

issue: installed adaway and applied the filter setting but sometimes ads still present on chrome. after i turn on wifi and not using carrier data the ads is gone, but when i using data again, the ads appeared again

**Comment by SMed79** [comment]
Did you test if the ads are still present in [Firefox](https://play.google.com/store/apps/details?id=org.mozilla.firefox) too or disable the [data saving](https://support.google.com/chrome/answer/2392284?co=GENIE.Platform%3DAndroid&) in chrome ?

**Comment by bonnouji** [comment]
yes, the ads is still present in firefox as well. I have disabled the data option in chrome as well

**Comment by SMed79** [comment]
**FAQ** > Ads are not blocked when on mobile data connection!
> AdAway will not work reliable when on Mobile Networks like 3G. You can deactivate that proxy by going to your selected APN (On Android 4: Wireless and networks -> More… -> Mobile Networks -> Access Point Names) and remove the value in the proxy field.

Source:  https://adaway.org/

**Comment by bonnouji** [comment]
welp, my fault for not reading the FAQ. Thanks for your answer.
