### ISSUE TITLE
hosts-file.net broken https

### ISSUE THREAD

**Issue by Jusix** [AdAway/AdAway#907]
One of the Hosts file "https://hosts-file.net/ad_servers.txt" isn't reachable through https anymore so a lot of annoying ads don't get blocked.

**Comment by SMed79** [comment]
The `http:` version works fine http://hosts-file.net/ad_servers.txt

**Comment by Jusix** [comment]
Yes I know, but thats very risky. Because anyone could push a modified .txt to you when using a wifi which would route your phones DNS requests to anywhere he wants...

**Comment by SMed79** [comment]
The [https](https://hosts-file.net/ad_servers.txt)` version works again.
