### ISSUE TITLE
Copying of hosts file failed

### ISSUE THREAD

**Issue by thany** [AdAway/AdAway#913]
I'm getting this message consistently on my phone. It's a Galaxy S7 (SM-G930F), updated to Android 7.0, and rooted. Root is definitely working, and Adaway has been granted root permission.

Not sure if this helps, but I'm on kernel version 3.18.14-11104523. I'm downloading block files via wi-fi (working fine) and most importantly: on this exact phone it used to work fine back when it was running Android 6.0.

**Comment by JonnyTech** [comment]
In preferences, what is target hosts file set to?

**Comment by thany** [comment]
It's set to `/system/etc/hosts`

But! I found a possible solution. I haven't been able to test this thoroughly. I'm using Magisk as my root management thing, and it has an option "systemless hosts". I enabled that, and now Adaway appears to be working. No errors at least.

I say "appears", because no errors doesn't always mean that it works perfectly ;)
I haven't encountered any ads yet, so maybe we're good.

Perhaps add this to some documentation? I'm not 100% sure what "systemless hosts" means, but if it fixes things, might as well mention it.

**Comment by mhrussell1** [comment]
I am having the same problem on Oreo 8.1 on the stock ROM with pico OpenGApps on Nexus 5X.  I am using the latest SuperSU beta and Franco kernel r49.  Everything was working fine with a similar setup back on Nougat 7.1.2 with SAOSP custom ROM.  Error message is "Copying hosts file failed."  Should I see the mods in /system/etc/hosts or should I look somewhere else?

**Comment by mhrussell1** [comment]
Not sure what I did but I did the apk download from F-droid on my phone and after installation, my hosts update worked.

**Comment by manish9213** [comment]
Dude I had the same problem, Just download the latest version from f-droid no previous versions will work......

**Comment by heubergen** [comment]
Thx @oblivion2k, you saved my day! Maybe the devs should add this wonderful tip to the error message they show! I have an Xiaomi Mix 2S.

**Comment by oblivion2k** [comment]
@Vankog good suggestion by @heubergen, I believe most people are being suggested to most from SuperSU to Magisk now for more features and an easier updating experience, so this issue will occur more frequently.

**Comment by regulator-g** [comment]
STILL AN ISSUE

**Comment by PerfectSlayer** [comment]
@regulator-g Could you at least provide anything requested in the bug report issue template?

**Comment by regulator-g** [comment]
@PerfectSlayer I've opened a new issue with the proper bug report filled out
https://github.com/AdAway/AdAway/issues/1477

**Comment by DavidUniUlm** [comment]
At first it didn't work for me either even after enabling systemless hosts in settings.
Just restarted the phone and everything worked as expected :)
