### ISSUE TITLE
AdAway does not process any sources hosted on GitHub

### ISSUE THREAD

**Issue by CaptainFrosty** [AdAway/AdAway#917]
This is a pretty serious problem that has been brought up in the past. I've tried both forms of GitHub URLS, to no avail. I have tested and Hosts file will not include anything drawn directly from a GitHub URL.

![screenshot_2017-07-21-20-43-57](https://user-images.githubusercontent.com/8523498/28486974-71063a96-6e56-11e7-9280-7f858ce2142f.png)

![screenshot_2017-07-21-20-44-06](https://user-images.githubusercontent.com/8523498/28486977-796998fe-6e56-11e7-99c7-4e909351e1e7.png)

**Comment by guest4711** [comment]
Just tested with https://raw.githubusercontent.com/StevenBlack/hosts/master/alternates/social/hosts as only source.
The source is downloaded, analyzed and a hostfile created. But in the list of sources it is displayed as "not available" (local and remote).

**Comment by onabi** [comment]
Having the same problem here.
