### ISSUE TITLE
Request to block URLs

### ISSUE THREAD

**Issue by maxim-sm** [AdAway/AdAway#922]
Hi,

The following URLs are responsible for serving ads in Terrarium TV.
They can be blocked without breaking the app functionality,

ads.aerserv.com
ads.avocarrot.com
ads30.adcolony.com
adc3-launch.adcolony.com
events3alt.adcolony.com
wd.adcolony.com
events3alt.adcolony.com
adserver.unityads.unity3d.com
d.applvn.com
app.appsflyer.com
config.unityads.unity3d.com
a.applvn.com
admin.appnext.com
auction.unityads.unity3d.com
rt.applovin.com
live.chartboost.com
v2.chartboost.com
rt.applvn.com
webview.unityads.unity3d.com

Thanks

**Comment by SMed79** [comment]
fyi @mitchellkrogza @StevenBlack @yous

**Comment by mitchellkrogza** [comment]
Thanks @drtrotusk will add these in my next commit.

**Comment by mitchellkrogza** [comment]
Added in > https://github.com/mitchellkrogza/Badd-Boyz-Hosts/commit/44334291fae0c9e2a0b2106b42ffdbc02ba32098 👍  Thanks @drtrotusk and @SMed79
