### ISSUE TITLE
Add limited support for non-root mode

### ISSUE THREAD

**Issue by ccaapton** [AdAway/AdAway#932]
Hi, I've enjoyed AdAway on my previous rooted-phone, now I changed to a new one that is not root-able at the moment.

Still, I would like to use adway as a hosts-file aggregator, and use the final hosts.txt somewhere else, like in termux, or even on my linux pc. I have quite a long list of customized whitelist and blacklist, so switching away from adaway would cost time.

Could you add such a function for the non-root user, to export the aggregate hosts file?

**Comment by superlex** [comment]
Good idea. For example we can install hosts file via twrp, without root.
AdAway should create hosts file and save it in user data, then ask for root: if granted, mount system r-w, install hosts file, remount system only r.

**Comment by PerfectSlayer** [comment]
Hello,

The version 5, currently in beta, support a non-root mode feature.

Regards
