### ISSUE TITLE
you killed seasonvar.ru 

### ISSUE THREAD

**Issue by pvlb** [AdAway/AdAway#934]
In hosts file line "0.0.0.0 seasonvar.ru" blocks online cinema seasonvar.ru! It's better to remove advertising on the site like it does adblockplus/agruard... Fix it!

**Comment by SMed79** [comment]
Report the `seasonvar.ru` issue at https://github.com/StevenBlack/hosts/issues

(fyi @StevenBlack)

**Comment by StevenBlack** [comment]
Thank you @SMed79.

@mitchellkrogza Mitchell, can you please 👍  or 👎  the inclusion of seasonvar.ru in our data?   Dankie!

**Comment by mitchellkrogza** [comment]
I'll have a look in the morning, off for the night :+1:

**Comment by mitchellkrogza** [comment]
@StevenBlack @pvlb seasobvar.ru removed in latest commit > https://github.com/mitchellkrogza/Badd-Boyz-Hosts/commit/a0181c421143c5cf29aa2b4c819a40ce0ad56408

This is a false positive for a Hosts file but seasonvar.ru will remain on my Nginx and Apache bad referrers projects as I pick up constant fake referrer traffic from them on my sites. 

So in the latest commit seasonvar.ru has been removed and only their ad-servers are blocked now with.

serving.adbetclickin.pink
creatives.adbetclickin.pink
adbetclickin.pink

**Comment by SMed79** [comment]
@mitchellkrogza 
>  in the latest commit seasonvar.ru has been removed and only their ad-servers are blocked

missed adservers 
```
franecki.net
pipki.r.acdnpro.com
```
==> `http://seasonvar.ru/serial-16594-Doma_na_derev_yah-6-season.html`

**Comment by mitchellkrogza** [comment]
Thank you @SMed79 will add in next build. Current build in progress removing Dead Domains then I will add these and set off a new build. 👍
