### ISSUE TITLE
all mobile browsers suddenly keep loading blocked requests till timeout

### ISSUE THREAD

**Issue by Vankog** [AdAway/AdAway#938]
For a few days now I have this strange behaviour.
I realized it, because some websites started loading forever till finally a timeout kicked in (about a minute or more, even).

For some websites with poor async fetching, this means that nearly the whole content is blocked from loading until the timeout of the blocked requests kicks in. e.g. https://www.googlewatchblog.de/2017/09/google-play-store-aktion-46/
Depending on how much is blocked, this site loads several stages of the content only after one timeout kicks in and the next blocked request starts loading till this timeout kicks in and so on.

I tried several lists, blacklisting and whitelisting, and options (toggling redirects, whitelisting, webserver...)  and finally came to the conclusion that all blocked requests, no matter from what list, are blocking the loading.
If I add all blocked requests to the whitelist everything loads fine, do I remove even one from the whitelist, the site loads again till nirvana.
I tried it with Chrome stable, WebView, Firefox. All behave the same.
It's the same for my Wifi and on mobile data.

What has changed during the last few days to have such a dramatic impact? I did not change any Adaway-related stuff. Only the daily automatic host-file updates are active for:
- adaway.org
- malwaredomainlist.com
- winhelp2002.mvps.org
- pgl.yoyo.org ad servers
- hosts-file.net ad servers

But as I said, it does not matter where the blocks come from. All have this issue suddenly.

**Comment by Vankog** [comment]
Oh boy. It seems it a crazy conflict with AFWall+. I deactivated and reapplied the firewall rules and suddenly it works again.
Has anyone experience with AFWall+ and AdAway? Any suggested configurations to prevent such conflicts?

**Comment by Kronopt** [comment]
I have a similar issue, but I found out earlier this year that I could just turn the wifi/data off and on again and the website would finish loading (albeit sometimes with missing images). Turning the screen off for a couple of minutes would also force the website to finish loading.

I had already realized that it had something to do with AdAway, as everything would load fine when the default (blank) hosts file was restored.

I didn't, however, thought it had anything to do with AFWall+...
You fix doesn't work on my phone though.

**Comment by Vankog** [comment]
Yeah, turning data off practically forces a timeout, because the system knows it can't retrieve anything.

Have you tried turning the AFWall+ firewall off completely?
I also disabled the webserver in AdAware just to be sure.

**Comment by Kronopt** [comment]
Turning AFWall+ off while having AdAway enabled seems to work, but when I turn it on again it no longer works.
I also do not have the AdAway webserver turned on.

It doesn't bother me that much, but if I eventually find out what's going on I'll post my fix here.
Thanks though

**Comment by Vankog** [comment]
What are your AFWall+ settings (IP6, startup behaviour etc.)? And do you use blacklist or whitelist? 

For me it is blacklist.
I enabled IP6, enabled incoming traffic, disabled startup init.d, no delay. I also tried different combinations of binaries: system or build-in. But this does not seemed to had any effect for me.

**Comment by Kronopt** [comment]
IPv6 support: Changing between enabled and disabled changes nothing (regarding this issue)
Startup behaviour: "normal I guess, no experimental features enabled
Block mode: black list
