### ISSUE TITLE
Cant whitelist by app

### ISSUE THREAD

**Issue by ghost** [AdAway/AdAway#940]
cant whitelist a complete app, similar to adguard.

**Comment by guest4711** [comment]
Because AdAway maintains the hostfile whitelisting per app is not possible. The hostfile is a global table for translations of hostnames into ip addresses.

**Comment by guest4711** [comment]
DNS66 (Block ads/hosts via DNS) - https://f-droid.org/app/org.jak_linux.dns66 - may be a nice alternative solution for you.

**Comment by PerfectSlayer** [comment]
Hi,

This feature is available in the current V5 beta if you use the VPN ad-blocking method.

Regards
