### ISSUE TITLE
Whitelist not working for specific domain

### ISSUE THREAD

**Issue by heatl0rd** [AdAway/AdAway#943]
- attempted to visit 'https://www.hotslogs.com/Sitewide/HeroDetails?Hero=Malthael
- returned ad block warning.
 -entered 'www.hotslogs.com*' as whitelisted address
- opened Firefox
- entered url again but failed.
-navigated to homepage of domain (www.hotslogs.com) and works but every other does not.
- restarted and still unsuccessful.
- disabled adaway and immediately website is fully functional.

Seeking advice yo resolve.

**Comment by heatl0rd** [comment]
Also confirming that I have tried to use the DNS logger but strangely each time I attempt to access the url, unique DNS attempts are made.

I am not talking about dynamic.Static.Com but each DNS log has a unique domain, I am unable to whitelist them all to fix the issue.

**Comment by PerfectSlayer** [comment]
Hello @heatl0rd 

Just remove the `*` to add `www.hotslogs.com` to the whitelist and it should works fine.
Only domain name must match, not the URL.

Regards
