### ISSUE TITLE
Not working on youtube apps

### ISSUE THREAD

**Issue by Thanaro** [AdAway/AdAway#945]
As I say Adaway dosn't work on YT apps anymore. For months i'd no adds, no pub when i was on YT but now i get it on every single vidéo.
What the matter ?
Anyway thx a lot for your hard work

**Comment by Vankog** [comment]
AdAway is only as good as its configuration and it can only block hosts.
Some apps serve ads via other means or by serving ads and content from the same host.
We cannot fix this unfortunately. You’ll need other, probably more active blockers for this.
