### ISSUE TITLE
features and bugs

### ISSUE THREAD

**Issue by patrickdrd** [AdAway/AdAway#950]
feature request: I would like to have the option to export my sources too (as is with lists),

bug: when I export my lists, the redirect is shown as 127.0.0.1,
although I have selected in the setting that I would prefer to use 0.0.0.0

also, why do I have to download all my sources when I only want to apply an entry in my list?
there should be an option to apply without downloading 

post is in xda too:
https://forum.xda-developers.com/showpost.php?p=74041983&postcount=9946

**Comment by PerfectSlayer** [comment]
Hosts sources are now backed up! 🎉  
Check PR #1189 for mote details.
