### ISSUE TITLE
New ad site not included un latest hosts

### ISSUE THREAD

**Issue by ectatomma** [AdAway/AdAway#952]
Hi, could you please include ads.eltiempo.co into the hosts file? I started to see ads from that server, then I added it to my blacklist and ads gone. Other people could benefit.

**Comment by ectatomma** [comment]
Sorry, duplicate entry by mistake

**Comment by SMed79** [comment]
AdAway hosts file is deprecated.
Report to 
- **hpHosts** [support @ it-mate.co.uk](http://mysteryfcm.co.uk/?mode=Contact)
- [Yoyos Hosts file](https://github.com/yous/YousList/issues)
- [The Ultimate Hosts Blacklist](https://github.com/mitchellkrogza/Ultimate.Hosts.Blacklist)
