### ISSUE TITLE
New ad site

### ISSUE THREAD

**Issue by ectatomma** [AdAway/AdAway#953]
Hi, could you please include ads.eltiempo.co into the hosts file? I started to see ads from that server, then I added it to my blacklist and ads gone. Other people could benefit.

**Comment by SMed79** [comment]
duplicated https://github.com/AdAway/AdAway/issues/953

**Comment by ectatomma** [comment]
Sorry, submitted twice the same issue by mistake. I just closed the duplicated issue (#952).

**Comment by SMed79** [comment]
AdAway hosts file is deprecated.
Report to 
- **hpHosts** [support @ it-mate.co.uk](http://mysteryfcm.co.uk/?mode=Contact)
- [Yoyos Hosts file](https://github.com/yous/YousList/issues)
- [The Ultimate Hosts Blacklist](https://github.com/mitchellkrogza/Ultimate.Hosts.Blacklist)
