### ISSUE TITLE
Export lists not working

### ISSUE THREAD

**Issue by pkramerruiz** [AdAway/AdAway#955]
Hi I'm on OnePlus One with LineageOS latest nightly (14.1-20171009), that's Android 7.1.2 (rooted with SuperSU) using AdAway 3.2 (60).
When trying to export my (white)lists it says they're all exported to a file named adaway-export on my SD, but there is no such file. Also not in /android/org.adaway/files nor elsewhere on the phone.

What can I do?
Thank you

**Comment by pkramerruiz** [comment]
Edit: It doesn't matter if blocking is disabled or enabled.

**Comment by guest4711** [comment]
See #904   Did you give AdAway storage permissions?

**Comment by pkramerruiz** [comment]
Thank you! Never got asked. Enabled in Phone settings ➡️Apps➡️ AdAway ➡️ Permissions, and now it works.
