### ISSUE TITLE
Local Cache of Remote Hosts Files

### ISSUE THREAD

**Issue by nathanmuccino** [AdAway/AdAway#956]
Any plan on implementing a local cache of remote hosts files so that in case there is a situation where a web address can't be reached it simply prompts the user if they would instead like to use the latest downloaded hosts file from that particular source that now can't be reached? This would prevent the content of that source from not being included all together. Either way, thank you for keeping this application alive and up to date! I'm sure it is a lot of work with Android changing so frequently. Currently running it on 7.1.2 Nougat and loving it!

**Comment by guest4711** [comment]
To allow an automated run it should not ask but (perhaps optionaly) use the old file (as 'AdAway' does if there is no update for this file).

**Comment by patrickdrd** [comment]
+1

**Comment by PerfectSlayer** [comment]
Interesting idea. But if you introduce a cache, the main issue is to know when invalidate it.
As @guest4711 said, you can't require user interaction during automatic update, so the app will use the cache if hosts source can't be reached and user won't know some hosts file are not updated.

We need to define a time validity (1 week for example) after which the cache is no more valid and failing to reach hosts source will raise an error.
Moreover, adding a cache means to handle low storage left issue (clearing cache when system requires it, dealing with cache clear, etc…).

I might have a look at it for future issue.

**Comment by PerfectSlayer** [comment]
It was implemented few releases ago.
