### ISSUE TITLE
AdAway slows down page loading 

### ISSUE THREAD

**Issue by KopiasCsaba** [AdAway/AdAway#960]
Hello!

Thanks for this wonderful app!

But i've found recently (using it for a long time) that after a while pages just simpl not loading, or loading very slowly. It is the same with any website when it happens.

I'm on a one plus one without bloatware (so it is not because of being low on resources), using lineage os 14.

Let me know how can i help you debugging this!

Thanks!

**Comment by guest4711** [comment]
1. Did you try to enable the integrated webserver? For me it helps... 
2. Also helpful for me was clearing the cache of the browser

**Comment by DJCrashdummy** [comment]
this also may depend on how big your host-file is... so the additional information which (and especially if some additional) hosts-files you have you enabled may help.

**Comment by Vankog** [comment]
Have you any further network-restricting apps?
I had such issues in combination with AFWall for example.

**Comment by KopiasCsaba** [comment]
guest4711 answer was solved for me! (I needed to start the webserver.) Thank you!

**Comment by guest4711** [comment]
Glad it worked for you, too.
