### ISSUE TITLE
Adaway doesn't work because of not working host lookup

### ISSUE THREAD

**Issue by hydra44** [AdAway/AdAway#971]
Hi all,

AdAway does not block any Ads. Although my device is rooted and I keep the files up-to-date.
Since I'm running Andropid 7.1.1 I had to implement the "linking" fix as described in the AdAway help.

Now I can see that al lot of hosts are listed in /data/data/hosts and also (as it is a link now) in /system/etc/hosts.
I set AdAway to look at /data/data/hosts and also added some additional site to the blacklist.

However, take a random URL from those and execute nslookup.
As user root the name resolves to 127.0.0.1 ... but as a standard user it resolves to its real address.

So this looks like the reason why the app is not working.
Now ... any ideas to fix this ?
Could this be a SeLinux thing ?

**Comment by guest4711** [comment]
NSLookup should ignore the system host file at all. It is used to have an userinterface to ask a DomainNameServer.

So nslookup is not a good tool for testing your host file...

**Comment by hydra44** [comment]
Sounds plausible ... but why does a nslookup as root give me 127.0.0.1 ?
When I do the same as user u0_143 I get the real IP of the host ?

Is nslookup was completely unaffected by AdAway or the hosts file I'd expect the output would be the same rather than different

**Comment by hydra44** [comment]
Well after I encountered a few more troubles with my stock Android I trashed it and went on LineageOS 14.1. So the following observations might only work in LinOS but I'm quite certain apply for Android 7.x as well...

You'll (most probably) need the development Version of AdAway to make this work and a TWRP !

So the "hosts" file is the magic item. But I found out that even if you place it in /data/data (and create a link to /system/etc/hosts) it remains unreadable !
Just try for yourself. Open a shell and try to read from /data/data/hosts ... as a non "root" user you'll get a "permission denied".
So even when the app/user ties to lookup a host in hosts-file it'll fail.

I created my hosts file in /su/etc and gave it 644 permissions.
Now you need the development version of AdAway and let it point to the custom hosts file.

Still nslookup doesn't work correctly (as described above) but it seem to work for my apps.

**Comment by Vankog** [comment]
I am a bit confused. You say changing the permission actually resolved your problem? (besides nslookup)
What was your prior permission? 
644 should be correct. That's what my hosts file got set to.

**Comment by hydra44** [comment]
It's not  the permission. 
My /data/data/hosts file is world-readable but you cant "cat" it as non-root
It seem that in general any files in /data and /system are not readable by any "normal" user.
That's why you need to create a "hosts" file outside these realms to make it work.
I just choose /su/etc/ ... but any other might work as well. The only thing you need to make sure is to create a link in /system/etc that points to your hosts file. (ln -s /su/etc/hosts /system/etc/hosts)

Ping resolves my test-hosts to 127.0.0.1 ... so
