### ISSUE TITLE
Adaway not blocking any ads

### ISSUE THREAD

**Issue by sudharsannr** [AdAway/AdAway#977]
I have checked the [wiki](https://github.com/AdAway/AdAway/wiki/Solutions#adaway-is-enabled-but-all-ads-are-getting-through) and thus posting this issue.

Newbie here. I have a rooted HTC One M7 with recent installation of adaway 3.2. The preferences are all checked. Hosts are downloaded properly but the ads are not blocked. Proof that hosts are merged:
```
> adb shell
shell@m7:/ $ ls -l /sys
sys/    system/
shell@m7:/ $ ls -l /system/etc/hosts
lrwxrwxrwx root     root              2016-11-06 08:42 hosts -> /data/data/hosts
shell@m7:/ $ ls -l /data/data/hosts
-rw-r--r-- root     root      5167845 2017-12-24 12:28 hosts
shell@m7:/ $
```

Using wifi. Checked the mobile access point settings and it doesn't have the proxy details.
Using firefox latest version testing [this](https://ads-blocker.com/testing/) one with ads.
Super su shell logs looks like this:
```
echo Started
Started
ls /su/bin/su 2>&1

echo F*D^W@#FGF 0 $?
/su/bin/su: No such file or directory
F*D^W@#FGF 0 1
mount | grep /system/etc/hosts 2>&1

echo F*D^W@#FGF 1 $?
echo F*D^W@#FGF 1 1

exit 0

echo Started
Started
id 2>&1

echo F*D^W@#FGF 0 $?
uid=0(root) gid=0(root) context=u:r:init:s0
F*D^W@#FGF 0 0

exit 0

echo Started
Started
/data/app/org.adaway-1/lib/arm/libblank_webserver_exec.so > /dev/null 2>&1 & 2>&1

echo F*D^W@#FGF 0 $?
F*D^W@#FGF 0 0

exit 0
```

Can anyone help me on why ads aren't blocked on adaway?

**Comment by Vankog** [comment]
Is your SELinux mode on permissive?

**Comment by JonnyTech** [comment]
Did you reboot after adding to hosts file?

**Comment by sudharsannr** [comment]
@Vankog SELinux was enforcing. Set permissive
[This was result](https://dl2.pushbulletusercontent.com/7AWpLlelbMwVQInCnQHgFUYiyrOl0Pjs/Screenshot_2017-12-24-17-40-53.png)
;rebooted and the state was lost. Working on installing the init script. Will get back to you on this.
@JonnyTech Rebooted several times with no avail.

Closing this as the solution is to set the SELinux mode to permissive.
