### ISSUE TITLE
Adaway stuck, black window with a red bar with the "Adaway" title

### ISSUE THREAD

**Issue by SkoDave** [AdAway/AdAway#979]
I have a Redmi 4 pro/prime with MIUI 8.5.4.0 and Magisk 15 installed, some days ago to update Magisk from version 14 to version 15 my device went in bootloop, I managed to restore it flashing the MIUI and re-flashing Magisk 15, after that adaway stopped working. It starts and either stucks in a black window with a red titlebar or a full black window. I have tried the beta version too but I still have that problem. 

Magisk has the "hosts system less option" enabled.

**Comment by guest4711** [comment]
Give AdAway the storage permission in settings -- apps -- AdAway -- permissions.

**Comment by SkoDave** [comment]
Thank you but sadly still doesn't work

**Comment by MarcinSzq** [comment]
Same with few latest builds of xiaomi.eu - miui 9 based on china dev -  for natrium.
Log attached below:
[adaway_miui9_xiaomi_eu.txt](https://github.com/AdAway/AdAway/files/1594054/adaway_miui9_xiaomi_eu.txt)

**Comment by inprealpha** [comment]
Can confirm this happens to me too on latest MIUI global beta.

**Comment by Cannon94** [comment]
Same problem with the lastest xiaomi.eu on xiaomi redmi note 4

**Comment by Tabayesco** [comment]
Same on my HTC U11 with latest firmware 1.27.400.21 on Android 7.0 (Indian market device).

**Comment by Threefifty** [comment]
Same rom with Magisk 14.0 installed no issue. Updated Magisk to 15.2 and this issue occurs.

**Comment by pec0ra** [comment]
This issue is due to the RootCommands library being deprecated. Newer versions of Magisk (15+) don't recognize the root request done by AdAway.

I have created a pull request #983 which fixes this by forcing a root request at startup in a way that Magisk recognizes. Once the user has granted root access to AdAway, the rest of the RootCommands library's functionalities work.
This is not the most beautiful way to do this (we should replace RootCommands completely) but it is a good temporary solution.

**Comment by SkoDave** [comment]
Hi, ty for the fix, sorry but I don't know how this works, can we already use this fix in some way or we must  wait for a new apk?

**Comment by pec0ra** [comment]
The best way is to wait for a new official release.
If you can't wait, you can give a try at [my fork](https://github.com/pec0ra/AdAway/releases). There's no guaranty that it will work though since I have also updated some libraries.

**Comment by guest4711** [comment]
For me the version 3.2  from f-droid - AdAway (Block advertisements) - https://f-droid.org/app/org.adaway - runs fine with magisk 15.2

**Comment by SkoDave** [comment]
I tried the fork but sadly doesn't work for me, thank you anyway! (Magisk 15.2 now)

**Comment by belidzs** [comment]
I can also confirm that the F-Droid version works while the one from XDA Labs doesn't. Weird.

**Comment by SkoDave** [comment]
No luck for me also with the F-Droid version, same problem.

**Comment by amzukk1** [comment]
I also had same problems with latest MIUI beta. You need to enable systemless hosts in MagiskManager (settings) and then install Adaway from fork. It worked for me on MIUI after systemless hosts enabling. Hope it helps. Thank You the development team for the quick support.

**Comment by SkoDave** [comment]
Thank you amzukk1, now it worked, but this is strange because I had systemless hosts enabled (because I was using the unified hosts adblock since adaway stopped to work) but it did not work, now I just reinstalled adaway 3.3 (the fork) and now it is ok...

**Comment by dzyla** [comment]
The same here, Mi5, MiUI 9. Waiting for the newer version of this great program

**Comment by imarindam** [comment]
Same problem with Miui 9 on redmi note 4. Tried Magisk 15.2, 15.3, 15.4 beta none of them works with f-droid or xda version of adaway. However thefork version mentioned by pec0ra can prompt forroot request but I am not sure it is blocking any ads, local webserver is also not working in this version. Please fix this issue, we need adaway so muck. Thank you.

**Comment by Mrvu182hp** [comment]
Uninstall magisk use magisk uninstall from xda and install SuperSU install hots complete reinstall magisk fix on device miui 9

**Comment by ale5000-git** [comment]
Hi,
could someone tag version 3.3 please?

**Comment by PerfectSlayer** [comment]
It was fixed in the last beta.
It should be available soon™️ in F-Droid market 😉

**Comment by ale5000-git** [comment]
Hi, you have closed the milestone but the tag isn't created.
Without the tag there will never be a new version on F-Droid.

**Comment by g3n35i5** [comment]
After the problem was fixed at that time, it occurs again to me now.

Specs:
Xiaomi Mi8 running MIUI 10.3 (xiaomi.eu), v9.1.24
AdAway v. 3.3
Root: Magisk v18.0

![screenshot_2019-01-28-09-51-17-201_org adaway](https://user-images.githubusercontent.com/17593457/51824486-b23ff500-22e2-11e9-86a6-dcb1986a0afd.png)
