### ISSUE TITLE
Not work in nougat

### ISSUE THREAD

**Issue by jealno** [AdAway/AdAway#986]
Im using AdAway v3.2 from official website (adaway.org) but i still got blank screen when i opened the app

Detail:
Redmi 4A
ROM Global Beta 7.12.28 (Based on 7.1.2)
Root using Magisk v15.2 (Enabled option Systemless hosts) 
AdAway 3.2

Screenshot:
https://drive.google.com/file/d/155qxpii2-5EoIGhHqNF71oUaadZQoifP/view?usp=drivesdk

Logcat:
I/Timeline( 2362): Timeline: Activity_launch_request time:161430 intent:Intent { act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=org.adaway/.ui.BaseActivity bnds=[296,756][418,878] (has extras) }
I/ActivityManager( 1446): START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=org.adaway/.ui.BaseActivity bnds=[296,756][418,878] (has extras)} from uid 10027 on display 0
D/Boost   ( 1446): hostingType=activity, hostingName=org.adaway/.ui.BaseActivity, callerPackage=com.miui.home, isSystem=true, isBoostNeeded=false.
I/ActivityManager( 1446): Start proc 8129:org.adaway/u0a232 for activity org.adaway/.ui.BaseActivity caller=com.miui.home
I/WtProcessController( 2576): MOVE TO FOREGROUND: org.adaway 10232
I/StatusController( 2576): Last foreground:com.miui.home uid:10027 Current foreground:org.adaway uid:10232
I/WtProcessController( 2576): FOREGROUND INFO: name=org.adaway uid=10232 pid=8129 TaskId:1447
D/AccessibilityManager( 8129): current package=org.adaway, accessibility manager mIsFinalEnabled=false, mOptimizeEnabled=true, mIsUiAutomationEnabled=false, mIsInterestedPackage=false
W/ActivityManager( 1446): Activity pause timeout for ActivityRecord{8e31db7 u0 org.adaway/.ui.BaseActivity t1447}
I/StatusController( 2576): Last foreground:org.adaway uid:10232 Current foreground:com.miui.home uid:10027
W/ActivityManager( 1446): Activity stop timeout for ActivityRecord{8e31db7 u0 org.adaway/.ui.BaseActivity t1447}
W/MiuiGallery2_ExifUtil( 9954): invalid exif format com.miui.gallery3d.exif.ExifInvalidFormatException: Invalid JPEG format, /storage/emulated/0/DCIM/Screenshots/Screenshot_2018-01-10-23-05-43-389_org.adaway.png
D/Cal:D:MiPushManager(11688): shouldInit(): 8129:11688, com.android.calendar:org.adaway
D/Cal:D:MiPushManager(11735): shouldInit(): 8129:11735, com.android.calendar:org.adaway

**Comment by guest4711** [comment]
It works in Nougat for me. But it seems that on new installation with magisk 15.2 it does not get root privileges... There is an unofficial firk addressing this - see the XDA thread.

**Comment by jealno** [comment]
Thanks mate. Its working now using pec0ra fork
