### ISSUE TITLE
feature requests

### ISSUE THREAD

**Issue by patrickdrd** [AdAway/AdAway#990]
hello,
I think the following should be considered for a new version of the app:

option to:
1) backup hosts file (like hostsman app for windows does)
2) update our hosts file every week automatically
3) export hosts sources
4) apply blacklist and whitelist without downloading hosts sources

regards

edit: I've got another issue: integrated webserver gets stopped (e.g. after reboot) and
 I cannot figure out why

**Comment by Sadi58** [comment]
Can I also add a simple option to choose **0.0.0.0** instead of **127.0.0.1** which works equally well and results in a smaller file?

**Comment by PerfectSlayer** [comment]
Export / import hosts sources are also requested here: https://github.com/AdAway/AdAway/issues/999

**Comment by Shadowghost** [comment]
Any reason we use 127.0.0.1 over 0.0.0.0? Regarding the README.md of StevenBlack and my own knowledge using 0.0.0.0 is empirically faster, possibly because there's no wait for a timeout resolution.

**Comment by PerfectSlayer** [comment]
Hosts sources are now backed up! 🎉  
Check PR #1189 for mote details.
