### ISSUE TITLE
hp.com

### ISSUE THREAD

**Issue by Dodgexander** [AdAway/AdAway#996]
For some reason I just can't get this website working with adaway.

I've tried tracing hosts and have multiple hp.com entries but the website doesn't let you enter certain pages such as opening the details of a product.

Is there anything I can whitelist that could be causing this?

**Comment by Dodgexander** [comment]
If I open the linked pages in a new window they work, just doesn't work simply tapping on the link

**Comment by Mattwmaster58** [comment]
> If I open the linked pages in a new window they work, just doesn't work simply tapping on the link
That would suggest it's not a problem with AdAway. Might be your browser

**Comment by Dodgexander** [comment]
Thanks for your help!

I just tested it again and the website now seems to work fine when accessed
directly at hp.com

When I visit the website via a referral link however it doesn't work.

I tried the same on my desktop using Chrome rather than chrome on android
and it doesn't have this problem.

Narrowed it down watching hosts as I loaded the page and adding different
ones to the whitelist.

Process of elimination seems to have narrowed it down to taobao.com so I
added an exception to the whitelist *taobao.com* and it worked.

So the referral link must be sending requests back there each time, anyway
I think its resolved, hopefully if someone else has this issue or a similar
one with referrals, it will help!

**Comment by Dodgexander** [comment]
Well, thought it was solved but it isn't.  There is something that adaway is doing to hp.com both non-referral that stops certain aspects of the page from working.

Without adaway enabled these problems don't exist, even with hp.com whitelisted.

I have tested now with chrome, brave and firefox on Android 7.

**Comment by Mattwmaster58** [comment]
Monitor DNS requests in adaway. It's probably some CDN that adaway is
blocking

**Comment by Dodgexander** [comment]
Yeah I have been monitoring DNS requests and adding all to the whitelist
but it doesn't help.

I think something is just broken with their website as I've noticed it
happens sometimes now even without adaway.

I guess just another reason to not buy HP!

**Comment by PerfectSlayer** [comment]
Okay, if it comes from their website, AdAdaway can't do anything for you.
I close this issue 😉
