### ISSUE TITLE
[Feature request] Import hosts sources in a conveinient format

### ISSUE THREAD

**Issue by radamar** [AdAway/AdAway#999]
I have a huge list of hosts sources i want to add to AdAway hosts sources. I took these from uBlock Origin's host sources. I didn't want to manually type out all URLs so I had to recompile the whole app from source to add the list because the default hosts sources are hard coded into the application. I reckon it would be better if we could use an external file to import hosts sources into the app, possibly in JSON or String array type formats. Again, thanks for all the work, I enjoy this app, makes browsing the web a whole lot more efficient on the small screen of a phone.

Cheers,
amar

**Comment by PerfectSlayer** [comment]
ASCII file with one host per line could be a simple format to import/export hosts source.
How many hosts sources do you have? (dozens, hundreds, more?)

**Comment by radamar** [comment]
See Pull Request #1001

I would like the option to import Hosts sources as a text file, the solution you described works too. The point is to give user more control over what he wants to do with the app, manually typing down links is a very tedious job. But, how about unicode-8 instead of ASCII? 

I have 55 hosts sources, AdAway and uBlock Origin combined sources combined. I stick with stuff that is being maintained. Earlier i used to manually gather lists and concatenate them. But links break, and it takes upkeep.
So, i thought it's a great idea to tap into a 'list' already being updated and curated by someone else, it's good for AdAway too, to have support for one of the most popular desktop adblocker's lists. The end hosts file is about 4MB in size(with  55 lists applied), devices can handle much more than that.

Cheers

**Comment by RichyHBM** [comment]
+1 Having a way to import multiple host file sources would make adaway so much more usable, not to mention making it easier to keep your phones hosts file up to date with your other devices.

Using the json format defined by unlock seems like a good idea

**Comment by diamondjohndroid** [comment]
I use a boot script to import/confirm my host sources are loaded, which also auto re-establishes them in any new ROM I flash, on first boot of enabling my boot scripts. ie a bash script can also do this job today

**Comment by RichyHBM** [comment]
@PerfectSlayer @Vankog Are there any updates on this issue? Being able to import the list of hosts to use from a text file or some other format would be really useful

**Comment by PerfectSlayer** [comment]
Hosts sources are now backed up! 🎉  
Check PR #1189 for mote details.
